### ISSUE TITLE
ISO isnt bootable

### ISSUE THREAD

**Issue by RevertedClock** [holoiso-eol/holoiso#1]
Trying to boot the iso but it doesnt work. only gives the EFI shell :(

**Comment by silentgameplays** [comment]
Wrote the USB in both DD and ISO formats in DD it gives a Steam OS option to log in on boot and then freezes at 
:: Triggering uevents...

**Comment by abhitrueprogrammer** [comment]
> Trying to boot the iso but it doesnt work. only gives the EFI shell :(

Doesn't work in virtualbox too.

**Comment by theVakhovskeIsTaken** [comment]
For some reason, writing thru rufus/dd doesn't work. However, flashing it with BalenaEtcher works fine

**Comment by theVakhovskeIsTaken** [comment]
#2

**Comment by carrierfry** [comment]
> > Trying to boot the iso but it doesnt work. only gives the EFI shell :(
> 
> Doesn't work in virtualbox too.

Same Story with Hyper-V
