### ISSUE TITLE
AMD RZ608(MT7921K) wifi card no driver supported

### ISSUE THREAD

**Issue by leogcry22** [holoiso-eol/holoiso#10]
Try boot and install on my ONEXPLAYER mini AMD R7-5800U version, but stuck on connecting wifi with no device found

**Comment by theVakhovskeIsTaken** [comment]
Apparently, your WiFi card isn't supported by linux-firmware and Neptune kernel. Does WiFi work on stock Arch Linux? If yes, then tether wifi from your phone, and install core/linux by invoking `sudo pacman -S core/linux`

**Comment by leogcry22** [comment]
> Apparently, your WiFi card isn't supported by linux-firmware and Neptune kernel. Does WiFi work on stock Arch Linux? If yes, then tether wifi from your phone, and install core/linux by invoking `sudo pacman -S core/linux`

I can comfirm this wifi card is working well on latest stock Arch with kernel 5.17.5

**Comment by theVakhovskeIsTaken** [comment]
> > Apparently, your WiFi card isn't supported by linux-firmware and Neptune kernel. Does WiFi work on stock Arch Linux? If yes, then tether wifi from your phone, and install core/linux by invoking `sudo pacman -S core/linux`
> 
> I can comfirm this wifi card is working well on latest stock Arch with kernel 5.17.5

If it works on stock Arch Linux kernel, then just `sudo pacman -S core/linux core/linux-headers`

**Comment by leogcry22** [comment]
> > > Apparently, your WiFi card isn't supported by linux-firmware and Neptune kernel. Does WiFi work on stock Arch Linux? If yes, then tether wifi from your phone, and install core/linux by invoking `sudo pacman -S core/linux`
> > 
> > 
> > I can comfirm this wifi card is working well on latest stock Arch with kernel 5.17.5
> 
> If it works on stock Arch Linux kernel, then just `sudo pacman -S core/linux core/linux-headers`

I can't connect network in ISO due to lack of kernel driver and I don't have an ethernet adapter for my console too, maybe I should wait for the next release with latest kernel?

**Comment by theVakhovskeIsTaken** [comment]
> > > > Apparently, your WiFi card isn't supported by linux-firmware and Neptune kernel. Does WiFi work on stock Arch Linux? If yes, then tether wifi from your phone, and install core/linux by invoking `sudo pacman -S core/linux`
> > > 
> > > 
> > > I can comfirm this wifi card is working well on latest stock Arch with kernel 5.17.5
> > 
> > If it works on stock Arch Linux kernel, then just `sudo pacman -S core/linux core/linux-headers`
> 
> I can't connect network in ISO due to lack of kernel driver and I don't have an ethernet adapter for my console too, maybe I should wait for the next release with latest kernel?

This release has option to boot with Arch Linux kernel. However, `holoinstall` will still install Steam Deck kernel only, you might want to chroot into your installation, and install `core/linux` from there.
