### ISSUE TITLE
Aarch64 Support 

### ISSUE THREAD

**Issue by officialmelon** [holoiso-eol/holoiso#100]
Box64 + Box86 You can run Steam Games On arm64 devices At 90% Speed If you could somehow add this into the Installer And Package manager you Could boot Steam/Games On Arm64 : https://github.com/ptitSeb/box64
https://github.com/ptitSeb/box86

Since the Nintendo switch has A UEFI Implementation
https://github.com/imbushuo/NintendoSwitchPkg

But no USB + touch support So if you could make A arm64 version of this Arm64 devices such as Raspberry Pi Banana pi Nintendo Switch NVIDIA Tegra x1  so could you?

**Comment by BoofOof32** [comment]
That's kind of big ask for this project. it's not a bad idea, but it would require a fair bit of work.

**Comment by FayeSpica** [comment]
It is possible run on AYN Odin Qualcomm Snapdragon 845?

**Comment by theVakhovskeIsTaken** [comment]
> Box64 + Box86 You can run Steam Games On arm64 devices At 90% Speed If you could somehow add this into the Installer And Package manager you Could boot Steam/Games On Arm64 : https://github.com/ptitSeb/box64
> https://github.com/ptitSeb/box86
> 
> Since the Nintendo switch has A UEFI Implementation
> https://github.com/imbushuo/NintendoSwitchPkg
> 
> But no USB + touch support So if you could make A arm64 version of this Arm64 devices such as Raspberry Pi Banana pi Nintendo Switch NVIDIA Tegra x1  so could you?

What? Box** translates userspace apps only, and doesn't touch kernel/highlevel stuff, so this is IMPOSSIBLE.
