### ISSUE TITLE
Doesn't start on Aya Neo 2021 Pro after installation

### ISSUE THREAD

**Issue by Furaihai** [holoiso-eol/holoiso#102]
I get to the message saying installation complete but then when I reboot no boot device is found and it looks like a dead installation. Any idea what the issue here could be?

**Comment by FayeSpica** [comment]
Clone and build newest iso.
Latest release efi not mount

**Comment by theVakhovskeIsTaken** [comment]
> Clone and build newest iso.
> Latest release efi not mount

Latest ISO mounts EFI perfectly.
