### ISSUE TITLE
add a newer gamescope for nvidia new open source driver

### ISSUE THREAD

**Issue by ryzendew** [holoiso-eol/holoiso#103]
https://www.gamingonlinux.com/2022/05/nvidia-releases-open-source-linux-gpu-kernel-modules-beta-driver-5154304-out/

nvidia has gamescope support now but it requires a newer build to work

**Comment by theVakhovskeIsTaken** [comment]
1. Those are kernel modules, rather than the drivers itself, the actual drivers are in userspace
2. There is no reports that gamescope works on NV, and i can't test that either

**Comment by ryzendew** [comment]
No reports … where have you been lol they legit added support in those drivers and this is the most talked about thing for today and last night … might wanna do some research a simple google or even read the article https://twitter.com/Plagman2/status/1524480478408953856 even the dev of gamescope tweeted this out and you just close it without even checking do better.

**Comment by BoofOof32** [comment]
> 1. Those are kernel modules, rather than the drivers itself, the actual drivers are in userspace
> 
>     2. There is no reports that gamescope works on NV, and i can't test that either

I think he was referring to the Beta 515 driver for Nvidia cards, rather than the the kernel modules. Gamescope does actually work on the beta driver
