### ISSUE TITLE
No (or little) HW acceleration VEGA56

### ISSUE THREAD

**Issue by vpisciot** [holoiso-eol/holoiso#106]
[vince@demios-steam ~]$ ginfo
direct rendering: Yes
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 3.45, 5.13.0-valve10.1-1-neptune-dri-02144-g7fffaf925dfb)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.0-devel (git-74a3f4e63a)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

vainfo: Driver version: Mesa Gallium driver 
vdpauinfo: Information string: G3DVL VDPAU

**Comment by theVakhovskeIsTaken** [comment]
> [vince@demios-steam ~]$ ginfo
> direct rendering: Yes
> OpenGL vendor string: AMD
> OpenGL renderer string: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 3.45, 5.13.0-valve10.1-1-neptune-dri-02144-g7fffaf925dfb)
> OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> OpenGL core profile shading language version string: 4.60
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> OpenGL shading language version string: 4.60
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.0-devel (git-74a3f4e63a)
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> OpenGL ES profile extensions:
> 
> vainfo: Driver version: Mesa Gallium driver 
> vdpauinfo: Information string: G3DVL VDPAU
> 
> 

Define "little" acceleration?

**Comment by Audrey8989** [comment]
> > [vince@demios-steam ~]$ ginfo
> > direct rendering: Yes
> > OpenGL vendor string: AMD
> > OpenGL renderer string: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 3.45, 5.13.0-valve10.1-1-neptune-dri-02144-g7fffaf925dfb)
> > OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> > OpenGL core profile shading language version string: 4.60
> > OpenGL core profile context flags: (none)
> > OpenGL core profile profile mask: core profile
> > OpenGL core profile extensions:
> > OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> > OpenGL shading language version string: 4.60
> > OpenGL context flags: (none)
> > OpenGL profile mask: compatibility profile
> > OpenGL extensions:
> > OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.0-devel (git-74a3f4e63a)
> > OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> > OpenGL ES profile extensions:
> > vainfo: Driver version: Mesa Gallium driver
> > vdpauinfo: Information string: G3DVL VDPAU
> 
> Define "little" acceleration?

thanks

**Comment by ByteSz** [comment]
Pretty sure this issue is stemming from another issue mentioned here right now #94, where the OS is system wide limiting the TDP due to some changes on config file contents

**Comment by vpisciot** [comment]
little acceleratiom, i tested :Control" which normally runs well with 
medium-low settings on the vega56 and i was getting about 8FPS

On 2022-05-12 18:14, Adam Jafarov wrote:

>> ***@***.*** ~]$ ginfo
>> direct rendering: Yes
>> OpenGL vendor string: AMD
>> OpenGL renderer string: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 
>> 3.45, 5.13.0-valve10.1-1-neptune-dri-02144-g7fffaf925dfb)
>> OpenGL core profile version string: 4.6 (Core Profile) Mesa 
>> 22.0.0-devel (git-74a3f4e63a)
>> OpenGL core profile shading language version string: 4.60
>> OpenGL core profile context flags: (none)
>> OpenGL core profile profile mask: core profile
>> OpenGL core profile extensions:
>> OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.0-devel 
>> (git-74a3f4e63a)
>> OpenGL shading language version string: 4.60
>> OpenGL context flags: (none)
>> OpenGL profile mask: compatibility profile
>> OpenGL extensions:
>> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.0-devel 
>> (git-74a3f4e63a)
>> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 
>> 3.20
>> OpenGL ES profile extensions:
>> 
>> vainfo: Driver version: Mesa Gallium driver
>> vdpauinfo: Information string: G3DVL VDPAU
> 
> Define "little" acceleration?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/theVakhovskeIsTaken/holoiso/issues/106#issuecomment-1124671841
[2]

**Comment by vpisciot** [comment]
> > > [vince@demios-steam ~]$ ginfo
> > > direct rendering: Yes
> > > OpenGL vendor string: AMD
> > > OpenGL renderer string: AMD Radeon RX Vega (vega10, LLVM 13.0.0, DRM 3.45, 5.13.0-valve10.1-1-neptune-dri-02144-g7fffaf925dfb)
> > > OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> > > OpenGL core profile shading language version string: 4.60
> > > OpenGL core profile context flags: (none)
> > > OpenGL core profile profile mask: core profile
> > > OpenGL core profile extensions:
> > > OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.0-devel (git-74a3f4e63a)
> > > OpenGL shading language version string: 4.60
> > > OpenGL context flags: (none)
> > > OpenGL profile mask: compatibility profile
> > > OpenGL extensions:
> > > OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.0.0-devel (git-74a3f4e63a)
> > > OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> > > OpenGL ES profile extensions:
> > > vainfo: Driver version: Mesa Gallium driver
> > > vdpauinfo: Information string: G3DVL VDPAU
> > 
> > 
> > Define "little" acceleration?
> 
> thanks

ok - i have done some more testing/tweaking looks like I am getting the best I can ~ 30fps. so the problem was on my end - thanks for a very cool distro/re-package much appreciated
