### ISSUE TITLE
Broadcom-wl wifi drivers

### ISSUE THREAD

**Issue by jandrokt** [holoiso-eol/holoiso#107]
Some wifi cards such as the BCM4360 do not work with the b43 wifi driver and need the broadcom-wl driver instead (https://wiki.archlinux.org/title/broadcom_wireless#broadcom-wl). Is it possible to get this driver working? I've tried fiddling around with it a bit with not much success, so any help would be highly appreciated

**Comment by odysseywestra** [comment]
Did you try the dkms version? That the agnostic version and should work with any kernel.

**Comment by jandrokt** [comment]
> Did you try the dkms version? That the agnostic version and should work with any kernel.

I just tried it out and it worked! Thank you so much
