### ISSUE TITLE
Requires Hostname during installation

### ISSUE THREAD

**Issue by nik-varad** [holoiso-eol/holoiso#108]
I am attempting to install holoiso on a laptop before I try it on my onexplayer, whenever I initiate the install, after selecting which version I want (barebones or the full experience) and after selecting the drive I want it installed, the install stops and asks for a hostname, cant find anyone that mentions this in other forums. 

Also the drive that I am installing on is partitioned would that create an issue?

**Comment by Techwizz-somboo** [comment]
You type in a hostname then press enter. For example, you chould just enter `steamos`
