### ISSUE TITLE
Getting "SSL certificate is not valid" everytime I try to install.

### ISSUE THREAD

**Issue by Scurry8609** [holoiso-eol/holoiso#109]
Hello, when I go to install I keep getting these errors and the install fails, none of the packages install because of this
![PXL_20220512_224745838](https://user-images.githubusercontent.com/105464516/168180232-81343287-db6f-4e71-852f-03f62bdf2045.jpg)
Thank you for the help
Update: I have tried 2 of the releases so far and I still keep getting these errors. Any help is appreciated.

**Comment by smounives** [comment]
I have the same issue.

**Comment by pants4hire** [comment]
I had this issue on my Aya Neo 2021... I was trying to install the OS before running any other OS on the device.  Basically, the hardware clock was not correct and the OS thought the certs are not valid yet because the clock was in the past.  I connected to the internet and ran the following to correct the clock, it worked after that.

```
# timedatectl set-ntp true
# hwclock --systohc
```

**Comment by Scurry8609** [comment]
Ahhh good point, I noticed the clock in the bios of my mini PC was way off.
Thanks for the idea

**Comment by cdomin1** [comment]
> I had this issue on my Aya Neo 2021... I was trying to install the OS before running any other OS on the device. Basically, the hardware clock was not correct and the OS thought the certs are not valid yet because the clock was in the past. I connected to the internet and ran the following to correct the clock, it worked after that.
> 
> ```
> # timedatectl set-ntp true
> # hwclock --systohc
> ```

Where can you correct this? At the installer command prompt? I was also having issues trying to install this on my Aya Neo Pro

**Comment by pants4hire** [comment]
> > I had this issue on my Aya Neo 2021... I was trying to install the OS before running any other OS on the device. Basically, the hardware clock was not correct and the OS thought the certs are not valid yet because the clock was in the past. I connected to the internet and ran the following to correct the clock, it worked after that.
> > ```
> > # timedatectl set-ntp true
> > # hwclock --systohc
> > ```
> 
> Where can you correct this? At the installer command prompt? I was also having issues trying to install this on my Aya Neo Pro

Yeah.  When you boot to the command prompt on the installer, connect to wifi if you need to, then run those commands.  Basically, you are connecting to an NTP server to sync time and then setting your computer's hardware clock to the correct time.  It's the same as commands referenced in the [Arch Linux install guide](https://wiki.archlinux.org/title/Installation_guide).

**Comment by pants4hire** [comment]
Submitted a change to correct this in the installer. #131
