### ISSUE TITLE
OneXPlayer Mini (AMD 5800u) bugs and issues

### ISSUE THREAD

**Issue by TheShiv14** [holoiso-eol/holoiso#110]
I have compiled a list of bugs, and potential uses with Holoiso for the OneXPlayer Mini (AMD version).

This is all coming from the semi latest version of Holoiso (Summertime stable 1). They go as followed:

• The most known one is that the Steam Deck UI is flipped 180° and there's noway to change it as of now. (You can fix the rotation in the Desktop UI). I've given my output to @Ruineka in the OXP discord.

• Wi-Fi initially doesn't work, but if you use the guide for wifi found on the Aya Neo subreddit, it'll work. https://www.reddit.com/r/ayaneo/comments/uku3uh/guide_to_installing_holoiso_unofficial_steamos_30/?utm_medium=android_app&utm_source=share

•  Sleep function is wonky. It's unusable in the Deck UI, and for the desktop mode it works, however it screws up the WiFi from point #2.

• Keyboard button on the OXPM is unusable outside of switching from mosue mode and gamepad mode.

• Orange button functions as a home button on desktop mode. Deck UI it does nothing. Wishful thinking that it becomes a menu button.

• Triggers and L3 in the keyboard section of Deck UI doesn't work. They're supposed to function as shift and search for the triggers and L3 is supposed to be caps lock and neither of them function.

Outside of this, I'm pleased of the OS and @theVakhovskeIsTaken has done a tremendous job at the OS. And I know he's hard at work oh the issues with other devices as well so if there's any more issues I'll let the team know.

**Comment by bowes332frank** [comment]
Take a look at this:https://github.com/ShadowBlip/aya-neo-fixes

**Comment by TheShiv14** [comment]
> 

But would it work with the OXP Mini?

**Comment by theVakhovskeIsTaken** [comment]
RZ608 should be fixed as https://github.com/theVakhovskeIsTaken/valve_linux_neptune/commit/a996fe00180a1ca975a23f92be7a5d503d7b2a3b
