### ISSUE TITLE
SteamOS / Holo archiso on FreeBSD virtualized with bhyve : jupiter controller firmware update service failed. 

### ISSUE THREAD

**Issue by Marietto2008** [holoiso-eol/holoiso#112]
Hello to everyone,

I'm downloaded and installed SteamOS / Holoiso in bhyve (hypervisor for FreeBSD),using the following parameters :

Code:

```
bhyve -S -c 2 -m 4G -w -H \
-s 0,hostbridge \
-s 1,ahci-cd,/mnt/$vmdisk'p2'/bhyve/iso/Linux/SteamOS_Holo-20220510_0636_amdgpu-x86_64.iso \
-s 2,ahci-hd,/mnt/$vmdisk1'p2'/bhyve/img/Linux/SteamOS.img \
-s 7:0,passthru,2/0/0,rom=TU102.rom \
-s 7:1,passthru,2/0/1 \
-s 7:2,passthru,2/0/2 \
-s 7:3,passthru,2/0/3 \
-s 8:,virtio-net,tap20 \
-s 29,fbuf,tcp=0.0.0.0:5920,w=1440,h=900 \
-s 30,xhci,tablet \
-s 31,lpc \
-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
vm20 < /dev/null & sleep 2 && vncviewer 0:20
```

and yes,it booted and its going to be installed :

![Screenshot_2022-05-13_11-02-41](https://user-images.githubusercontent.com/755339/168255318-021e4c8a-5f8c-421f-a028-3d56eec8b221.jpg)

![Screenshot_2022-05-13_11-22-18](https://user-images.githubusercontent.com/755339/168255323-916e2b93-96f9-415b-817c-72b4816410d0.jpg)

But when I've rebooted this error freezed the VM : 

![SScreenshot_2022-05-13_12-10-18](https://user-images.githubusercontent.com/755339/168262523-e4e35bc2-686c-44d9-8b98-9d6e00eeb017.jpg)

**Comment by Illegalopcode** [comment]
disregard

**Comment by theVakhovskeIsTaken** [comment]
You need GPU acceleration to make SteamOS session work.
Else, switch to tty2, login and type `steamos-session-select`

**Comment by Stajor46** [comment]
пожалуйста распишите как решить эту ошибку!
в tty2 логин и пароль  не проходит

**Comment by Stajor46** [comment]
CPU razen 3600 GPU RX570
