### ISSUE TITLE
Gamescope is forces some games to use 1360x768 resolution

### ISSUE THREAD

**Issue by Sunderland93** [holoiso-eol/holoiso#114]
Hi. When running Rise of the Tomb Raider or any Feral games, gamescope is forced to 1360x768 game resolution on FullHD display. In game's display settings is only 1360x768 and 1280x720 resolutions available. How can I force Gamescope to run game on a native display resolution?

**Comment by theVakhovskeIsTaken** [comment]
I'd honestly recommend you to leave it like this and use FSR to upscale.

But, you can edit /usr/bin/gamescope-session to align with your resolution

**Comment by Sunderland93** [comment]
Ok, I will try. How can enable FSR options? I'm using Xbox360 gamepad, and there is no button to exec `...` menu

**Comment by theVakhovskeIsTaken** [comment]
> Ok, I will try. How can enable FSR options? I'm using Xbox360 gamepad, and there is no button to exec `...` menu

Home+A and then open battery menu
