### ISSUE TITLE
current kernel from steam is lacking some modern improvements in later kernels, IE b160 gyro, amd/mediatek wifi/bt module drivers

### ISSUE THREAD

**Issue by slaminger** [holoiso-eol/holoiso#115]
RZ608 wifi module is currently not supported, but works on the 5.17 ubuntu kernel out of box, also bosch b160 is not working, but works Ubuntu 22.04, we need an updated kernel, or to add support for these into the current kernel, this will enable all features to work on the aya neo handheld devices, currently most things do work, but no wifi or gyro.

**Comment by nachfuellbar** [comment]
Don't want to discourage you but this won't be happening in here.
Just read the project description:

"This project attempts to bring the Steam Deck's Holo OS into a generic, installable format, and provide a close-to-official SteamOS experience."

You'll propably experiance more problems than missing kernel drivers with a vanilla installation until Steam releases Steam OS 3 for devices other than the steam deck.

You could always add third party repos or use AUR though.

**Comment by slaminger** [comment]
> Don't want to discourage you but this won't be happening in here. Just read the project description:
> 
> "This project attempts to bring the Steam Deck's Holo OS into a generic, installable format, and provide a close-to-official SteamOS experience."
> 
> You'll propably experiance more problems than missing kernel drivers with a vanilla installation until Steam releases Steam OS 3 for devices other than the steam deck.
> 
> You could always add third party repos or use AUR though.

I dunno if that is true, numerous devices use the goodix screen in this device, and the bosch gyro is also not exclusive to this device. my use case is focused on one device, this is true, but gpd and several other makers use these components in their devices as well, including lenovo. the wifi/bt is already fixed in the 5.17 kernel. Generally speaking, adding deps or modules to the kernel for devices won't negatively impact others not using said modules.

In my custom build I went up to 5.17.7 kernel and used a custom fix which required unloading the goodix module, but I've got things up and running minus the gyro. I was more offering my help than I was expecting the author to do all the work.

**Comment by nachfuellbar** [comment]
Sorry then i misunderstood you
Just wanted to say - this project is focused on building everything from Steams packages. If you consider this, it's unlikely the author will  add another kernel from the default. Especially since he would need to add other repos to this.
In issue https://github.com/theVakhovskeIsTaken/holoiso/issues/111 he denied a similar request for another package.

I think you best chance would be to provide a custom mirror with your alternative kernel and ask if he could mention this in his README file.

**Comment by slaminger** [comment]
I see what you are saying, that's an additional application that's end user
addable, what I'm asking isn't a new kernel, it's loading some modules into
the current kernel and rebuilding it.

**Comment by theVakhovskeIsTaken** [comment]
> Sorry then i misunderstood you
> Just wanted to say - this project is focused on building everything from Steams packages. If you consider this, it's unlikely the author will  add another kernel from the default. Especially since he would need to add other repos to this.
> In issue https://github.com/theVakhovskeIsTaken/holoiso/issues/111 he denied a similar request for another package.
> 
> I think you best chance would be to provide a custom mirror with your alternative kernel and ask if he could mention this in his README file.

HoloISO uses `linux-neptune-dri` now, which is forked Steam Deck kernel with few fixes to iron out for most devices https://github.com/thevakhovskeistaken/valve_linux_neptune

**Comment by theVakhovskeIsTaken** [comment]
RZ608 should be fixed as https://github.com/theVakhovskeIsTaken/valve_linux_neptune/commit/a996fe00180a1ca975a23f92be7a5d503d7b2a3b
