### ISSUE TITLE
Packages jupiter-hw-support and steamos-customizations-jupiter are not installed by default

### ISSUE THREAD

**Issue by pastaq** [holoiso-eol/holoiso#116]
The packages ```jupiter-hw-support``` and ```steamos-customizations-jupiter``` are not included in the linux-neptune install. This leads to journalctl spamming the following:
```
May 12 19:25:32 testos sudo[1243]:    gamer : TTY=tty2 ; PWD=/home/gamer ; USER=root ; COMMAND=/usr/bin/python /usr/lib/hwsupport/power-button-handler.py
May 12 19:25:32 testos sudo[1243]: pam_unix(sudo:session): session opened for user root(uid=0) by gamer(uid=1000)
May 12 19:25:32 testos sudo[1243]: pam_unix(sudo:session): session closed for user root
May 12 19:25:32 testos sudo[1261]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
May 12 19:25:32 testos sudo[1261]:    gamer : TTY=tty2 ; PWD=/home/gamer ; USER=root ; COMMAND=/usr/bin/python /usr/lib/hwsupport/power-button-handler.py
May 12 19:25:32 testos sudo[1261]: pam_unix(sudo:session): session opened for user root(uid=0) by gamer(uid=1000)
May 12 19:25:32 testos sudo[1261]: pam_unix(sudo:session): session closed for user root
May 12 19:25:32 testos sudo[1276]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
May 12 19:25:32 testos sudo[1276]:    gamer : TTY=tty2 ; PWD=/home/gamer ; USER=root ; COMMAND=/usr/bin/python /usr/lib/hwsupport/power-button-handler.py
May 12 19:25:32 testos sudo[1276]: pam_unix(sudo:session): session opened for user root(uid=0) by gamer(uid=1000)
May 12 19:25:33 testos sudo[1276]: pam_unix(sudo:session): session closed for user root
May 12 19:25:33 testos sudo[1291]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.

```
This spam makes troubleshooting other errors quite difficult and will result in the following features not being available:
- Short press to suspend, Long press to shutdown on power button.
- Formatting SD cards as steam libraries.
- Changing hostname via gamepadui
- Seeing OS update notification via gamepadui
And more!

resolving the issue is as simple as installing the packages
```yay -S jupiter-hw-support steamos-customizations-jupiter```

**Comment by theVakhovskeIsTaken** [comment]
It's probably problem with your install, since jupiter-hw-support is main dependency to be installed, because DeckUI calls BIOS updating service to pass OOBE.

steamos-customizations-jupiter tend to break my wifi on RTL8822CE (which is probably because its the same one as Steam Deck)

**Comment by theVakhovskeIsTaken** [comment]
EDIT: just noticed that `whatever-customizations-jupiter` has its source code published, i can remove NetworkManager and Dracut bullshit, and ship it as `steamos-customizations-holoiso` package

**Comment by cat-master21** [comment]
Also I too can confirm with latest iso that both packages are not installed by default.

**Comment by cat-master21** [comment]
And also this may be why:
![Screenshot from 2022-05-13 19-36-07](https://user-images.githubusercontent.com/96554164/168407764-97b5b217-2bad-4c5a-ae67-ba533523c9ee.png)
