### ISSUE TITLE
Feature Request: Custom Key Mapping for HoloIso Steam UI (Physical/ Laptop Keyboards)

### ISSUE THREAD

**Issue by deannielsen2** [holoiso-eol/holoiso#118]
I may have overlooked something when I installed Holo on my Matebook D but the OS UI is designed for specific Keys (that are not present on any basic physical keyboards). Is there a way to include in an update or manually enable the ability to assign various Function Keys to perform certain tasks such as Super (Windows) for Steam Menu, ect?...

P.S. Holo is working flawlessly on my Matebook D with the only issue being the Resolution Scaling is often Hit and Miss

**Comment by pastaq** [comment]
ctrl+1 settings menu, ctrl+2 quick access menu

**Comment by nixigaj** [comment]
> ctrl+1 settings menu, ctrl+2 quick access menu

I tried this, but it does not seem to work. Could it be the game intercepting my inputs?

**Comment by pastaq** [comment]
> > ctrl+1 settings menu, ctrl+2 quick access menu
> 
> I tried this, but it does not seem to work. Could it be the game intercepting my inputs?

Possible, you can also try steam/home + a buttons on a controller or shift+tab on a keyboard before Ctrl+2 since the game is likely taking input priority.

**Comment by rileydb07** [comment]
Would also like to know if this is a thing!

**Comment by pastaq** [comment]
What keys are you trying to emulate and on what device? There are ways to do things like this but it's not that straightforward.

**Comment by rileydb07** [comment]
> What keys are you trying to emulate and on what device? There are ways to do things like this but it's not that straightforward.

i want something like super as the steam key or etc

**Comment by pastaq** [comment]
What device are you on?

**Comment by rileydb07** [comment]
> What device are you on?


laptop

**Comment by pastaq** [comment]
Dang, alright. If you can code you can make a custom python-evdev script to emulate a controller and capture that key. If you'd like an example of this working, take a look at my project HandyGCCS. It's a lot of work though.
