### ISSUE TITLE
Options menu is zoomed in (DPI scaling issue?)

### ISSUE THREAD

**Issue by nex86** [holoiso-eol/holoiso#119]
I installed holo on my Asrock X300 Mini PC that is plugged in a 4K samsung TV.
When I press ESC to enter the options menu, its completely zoomed in and the only entries I see are "Home" and "Library" the rest is outside of the screen.
is there a way to fix this?

KDE Global Scale is set to 100%.

**Comment by theVakhovskeIsTaken** [comment]
Press ESC, go to settings, enable developer settings and disable OpenGL compositor
