### ISSUE TITLE
RZ608 testers required

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [holoiso-eol/holoiso#120]
To test this thing just install ISO, or update your kernel by doing `sudo pacman -Sy linux-neptune-dri`

**Comment by slaminger** [comment]
i will test it now

**Comment by forrestlay** [comment]
I've updated my Aya Neo 2021 to `linux-neptune-dri-5.13.0.valve14.1.20220514.2031-2`, and wifi still does not work. Running `lscpi -k` shows that the `Network controller: MEDIATEK Corp. MT7921...` has no `Kernel driver in use` listed.

**Comment by Frostyman758** [comment]
You need to install the Linux-neptune-dri-headers package. Updating broke Nvidia drivers until I did that.

**Comment by theVakhovskeIsTaken** [comment]
> I've updated my Aya Neo 2021 to `linux-neptune-dri-5.13.0.valve14.1.20220514.2031-2`, and wifi still does not work. Running `lscpi -k` shows that the `Network controller: MEDIATEK Corp. MT7921...` has no `Kernel driver in use` listed.

Can you run `modprobe mt76` or `modprobe mt7921` and see if that works

**Comment by forrestlay** [comment]
`modprobe mt76` didn't enable wifi, and `modprobe mt7921` resulted in `FATAL: Module mt7921 not found in directory /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb`. Headers package is also updated.

**Comment by theVakhovskeIsTaken** [comment]
> `modprobe mt76` didn't enable wifi, and `modprobe mt7921` resulted in `FATAL: Module mt7921 not found in directory /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb`. Headers package is also updated.

This is cool. Apparently i'll need to backport entire driver from 5.17.

Stay tuned ig?

**Comment by slaminger** [comment]
> > `modprobe mt76` didn't enable wifi, and `modprobe mt7921` resulted in `FATAL: Module mt7921 not found in directory /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb`. Headers package is also updated.
> 
> This is cool. Apparently i'll need to backport entire driver from 5.17.
> 
> Stay tuned ig?

It's not in 5.13 yet, so yeah you will need to backport it from a later kernel.

**Comment by tgienger** [comment]
I have this on my mobo as well, so I can test when there's something to test

**Comment by pastaq** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/245
