### ISSUE TITLE
Installer fails to install anything when initiating holoinstall on Aya Neo Pro 2021

### ISSUE THREAD

**Issue by cdomin1** [holoiso-eol/holoiso#121]
Bought a brand new M.2 SSD to install the HoloISO Full steam deck OS on my Aya Neo Pro 2021, but if fails to install every step within the main installation process. So far it only creates the partitions needed for install and asks me to create the credentials/root passwords etc. After 6 tries I gave up. :( 

Any ideas on what could be going on?

**Comment by cdomin1** [comment]
This is what is happening during installation of all the isos I’ve tried:
![D748B610-C44C-4EDF-9C31-FA3D00F30E9B](https://user-images.githubusercontent.com/105389333/168456128-e6bcad3a-c142-4848-af58-b982a37976de.jpeg)

**Comment by theVakhovskeIsTaken** [comment]
Interesting... Looks like SSL certificates are expired for those installations.
