### ISSUE TITLE
unable to boot after restarting PC.

### ISSUE THREAD

**Issue by 0Synergy** [holoiso-eol/holoiso#122]
As stated in title, restarted PC after installing black screen with 
Starting version 250.3-1-arch
[FAILED] Failed to start Jupiter BIOS Update Service.
[FAILED] Failed to start Jupiter Controller Firmware Update Service.

Cant do anything on this screen at all.

**Comment by bowes332frank** [comment]
Do you do `sudo pacman-Syyu` on KDE Desktop like I did?
Well, that's the problem.

**Comment by 0Synergy** [comment]
> Do you do `sudo pacman-Syyu` on KDE Desktop like I did? Well, that's the problem.

I did do yay -Syu does that count?

**Comment by theVakhovskeIsTaken** [comment]
> Do you do `sudo pacman-Syyu` on KDE Desktop like I did?
> Well, that's the problem.

That's exactly what you shouldn't have done.

steamos-update already takes care of it

**Comment by 0Synergy** [comment]
> > Do you do `sudo pacman-Syyu` on KDE Desktop like I did?
> > Well, that's the problem.
> 
> That's exactly what you shouldn't have done.
> 
> steamos-update already takes care of it

Ah is that listed anywhere? I feel dumb, I'm not used to fancy automatic updates lol. Well time to reinstall.

**Comment by Illegalopcode** [comment]
You can run pacman -Syyu but you need these switches included
Pacman -Syyu --ignore=linux-firmware --ignore=grub --ignore=linux or just use steamos-update

because upgrading any of them will bork your system. And it is also what steamos-update does.

**Comment by Basement561** [comment]
Same issue, neither steamos-update nor pacm…inux work. Fresh install, latest version, Ryzen 5700G / RX 6600. gamescope-session doesn't work either. steam -gamepadui gets stuck after selecting network.

**Comment by kupokev** [comment]
I simply played Civilization VI for a bit and then did a shutdown to make sure my laptop didn't do something weird falling alseep. Thought to myself, "I better boot back up and check if my WIFI works since I was using a wired connection.". I received the same error as the reporting user did.

**Comment by theVakhovskeIsTaken** [comment]
> As stated in title, restarted PC after installing black screen with 
> Starting version 250.3-1-arch
> [FAILED] Failed to start Jupiter BIOS Update Service.
> [FAILED] Failed to start Jupiter Controller Firmware Update Service.
> 
> Cant do anything on this screen at all.

I'm DEEPLY sorry about being that late, what's your PC specs?

**Comment by Illegalopcode** [comment]
> I simply played Civilization VI for a bit and then did a shutdown to make sure my laptop didn't do something weird falling alseep. Thought to myself, "I better boot back up and check if my WIFI works since I was using a wired connection.". I received the same error as the reporting user did.

Well, something had to change from the first boot. Did you install any system software(i.e. drivers) and it asked to switch kernels?  I have had it bork on me editing grub configs.

**Comment by ayamasasaki** [comment]
I have the same problem, and I can't resolve them, I try to do on the Virtual Machine to test how is it the HoloISO and when I run it I have the same problem with the `jupiter`, I try to update the package or change somthing urong with this: `yay -S jupiter-hw-support steamos-customizations-jupiter` , `yay -S jupiter-hw-support steamos-customizations-jupiter` or `sudo pacman-Syyu` . The installations is very well, I know that because I don't have errors or bugs or other, just this bullyshit error.

**Comment by kupokev** [comment]
I pondered on this a bit and I did change 1 thing. I installed the NVidia drivers. That was the only change to the system besides installing the 2 games I played.

**Comment by Illegalopcode** [comment]
> I have the same problem, and I can't resolve them, I try to do on the Virtual Machine to test how is it the HoloISO and when I run it I have the same problem with the `jupiter`, I try to update the package or change somthing urong with this: `yay -S jupiter-hw-support steamos-customizations-jupiter` , `yay -S jupiter-hw-support steamos-customizations-jupiter` or `sudo pacman-Syyu` . The installations is very well, I know that because I don't have errors or bugs or other, just this bullyshit error.

Everyone gets this error it is not important. You are not running the os on a steam deck and do not have the controllers to update.

**Comment by ayamasasaki** [comment]
oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?

**Comment by Illegalopcode** [comment]
> I pondered on this a bit and I did change 1 thing. I installed the NVidia drivers. That was the only change to the system besides installing the 2 games I played.

This ISO does not support Nvidia. This ISO is as close to steam's implementation as possible. So an AMD CPU and GPU are all that are supported after that your mileage may vary. You can try [WinesapOS](https://github.com/LukeShortCloud/winesapOS#winesapos) it is another steamOS 3.0 variant that has Nvidia and Intel support.

**Comment by Illegalopcode** [comment]
> oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?

Is the resolution off in Gamescope?

**Comment by BogdanSasaki** [comment]
no, just when I try to log in on gamescope I get those `jupiter `errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card

**Comment by ayamasasaki** [comment]
> > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> 
> Is the resolution off in Gamescope?


no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card

**Comment by theVakhovskeIsTaken** [comment]
> > > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> > 
> > Is the resolution off in Gamescope?
> 
> 
> no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card
> 
> 

Can you exit to KDE desktop and run `gamescope-session` in terminal?

**Comment by ayamasasaki** [comment]
> > > > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> > > 
> > > 
> > > Is the resolution off in Gamescope?
> > 
> > 
> > no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card
> 
> Can you exit to KDE desktop and run `gamescope-session` in terminal?

i try this and i have same problem

**Comment by theVakhovskeIsTaken** [comment]
> > > > > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> > > > 
> > > > 
> > > > Is the resolution off in Gamescope?
> > > 
> > > 
> > > no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card
> > 
> > Can you exit to KDE desktop and run `gamescope-session` in terminal?
> 
> i try this and i have same problem

What same problem? You need to go to Plasma desktop, open Konsole and type `gamescope-session` in

**Comment by BogdanSasaki** [comment]
I did this and he won't let me, he restarts and then takes me to the login session

**Comment by ayamasasaki** [comment]
> I did this and he won't let me, he restarts and then takes me to the login session


I did this and he won't let me, he restarts and then takes me to the login session

**Comment by Illegalopcode** [comment]
> 

Your GPU may not be supported

> > > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> > 
> > 
> > Is the resolution off in Gamescope?
> 
> no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card

Make sure [mesa-vdpau](https://archlinux.org/packages/?name=mesa-vdpau) is installed. I am not sure if that is the issue.

**Comment by ayamasasaki** [comment]
> > 
> 
> Your GPU may not be supported
> 
> > > > oh, I see. I understand now But what can I do to use the SteamDeck gamescope? When I try to start on a gamescope my computer automated goes back to the login session and does nothing, how can I enter the gamescope mode?
> > > 
> > > 
> > > Is the resolution off in Gamescope?
> > 
> > 
> > no, just when I try to log in on gamescope I get those jupiter errors and after that, it gives me back in the login session, only in KDE display do I have access, but in gamescope no, does it have any problem with the specifications? I have an intel i5 gn3 and AMD R7 370 series video card
> 
> Make sure [mesa-vdpau](https://archlinux.org/packages/?name=mesa-vdpau) is installed. I am not sure if that is the issue.

I also wondered if he might have this problem or not and he says it is and is running on the newest version

**Comment by Illegalopcode** [comment]
> 

Ok well, it is a southern island card. run this and post the output. lspci -k

**Comment by ayamasasaki** [comment]
okey

**Comment by ayamasasaki** [comment]
> > 
> 
> Ok well, it is a southern island card. run this and post the output. lspci -k

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: ivb_uncore
        Kernel modules: ie31200_edac
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
        Kernel driver in use: pcieport
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: mei_me
        Kernel modules: mei_me
00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: ehci-pci
00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device d798
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
        Kernel driver in use: pcieport
00:1c.1 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 (rev c4)
        Kernel driver in use: pcieport
00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: ehci-pci
00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev a4)
00:1f.0 ISA bridge: Intel Corporation B75 Express Chipset LPC Controller (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: lpc_ich
        Kernel modules: lpc_ich
00:1f.2 SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: ahci
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: i801_smbus
        Kernel modules: i2c_i801
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Curacao PRO [Radeon R7 370 / R9 270/370 OEM] (rev 81)
        Subsystem: PC Partner Limited / Sapphire Technology NITRO Radeon R7 370
        Kernel driver in use: radeon
        Kernel modules: radeon, amdgpu
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series]
        Subsystem: PC Partner Limited / Sapphire Technology Device aab0
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7798
        Kernel driver in use: r8169
        Kernel modules: r8169

**Comment by ayamasasaki** [comment]
sorry for the delay, the power went out and I waited until now to recover.

**Comment by ayamasasaki** [comment]
how can I made run on my pc?

**Comment by RIJOSROBERTO** [comment]
Noob here at all of this but will it wor
![20220815_185310](https://user-images.githubusercontent.com/6422024/184758508-427a163b-da5d-4651-9837-4cd347910e54.jpg)
k on these specs ?

**Comment by RIJOSROBERTO** [comment]
It goes to the desktop then i press the install icom sda , passwords , then amd the after its done it tells me to reboot when i reboot it gives me this massege to add a bootable device

**Comment by RIJOSROBERTO** [comment]
![20220815_202748](https://user-images.githubusercontent.com/6422024/184758681-f500d876-caa4-4788-99e4-6c34a4d56347.jpg)
