### ISSUE TITLE
infinite log in screen

### ISSUE THREAD

**Issue by Xalderin** [holoiso-eol/holoiso#124]
When booting up, I get to the Verifying Installation screen.  And then I get to the Log in screen, where you can also choose SteamOS (gamescope) (wayland) or Plasma (x11).  I type in the password, and then it sends me back to verifying installation and starts this process over again.  I can't get through this, unless I select Plasma (x11), but then I can only use the desktop and the "gaming mode" doesn't work at all.  Any fixes to this, or has anyone else encountered this?

**Comment by Illegalopcode** [comment]
What are you installing it on?

**Comment by Xalderin** [comment]
> What are you installing it on?

Desktop.  It's got a AMD CPU and GPU, so I didn't think I'd have issues.  (Had it working at one point, but gamescope didn't work at all, and I had no idea what "steam button" was.  So reinstalled and I've been having issues since.)

**Comment by Illegalopcode** [comment]
Try switching tty ( CTRL+ALT+F4(any F-key other than F1,F2) and running "steamos-session-select plasma-persistent".  By the way, is it an RDNA2-based card?

**Comment by Xalderin** [comment]
> Try switching tty ( CTRL+ALT+F4(any F-key other than F1,F2) and running "steamos-session-select plasma-persistent". By the way, is it an RDNA2-based card?

Yea.  I'm using a R5 5600 with a RX 6400.
and I'll try that out.

**Comment by FayeSpica** [comment]
R5 2600X + 6700XT has no issue

**Comment by Xalderin** [comment]
> Try switching tty ( CTRL+ALT+F4(any F-key other than F1,F2) and running "steamos-session-select plasma-persistent". By the way, is it an RDNA2-based card?

I'm curious on if maybe I'm messing something up in the installation itself.
When I'm installing it, I press 2 for deskperience.  After that, I press 1 when it asks for which modules of the 24 to install (hoping it's the default.)  And then I press 1 for the default "version" of the 3 you can choose from.
Is there anything I'm missing from this, or is this mostly right?

**Comment by theVakhovskeIsTaken** [comment]
> > Try switching tty ( CTRL+ALT+F4(any F-key other than F1,F2) and running "steamos-session-select plasma-persistent". By the way, is it an RDNA2-based card?
> 
> Yea.  I'm using a R5 5600 with a RX 6400.
> and I'll try that out.

6400/6500XT are a new family of cards, which aren't supported by valve's `linux-firmware` you'd need to wait a bit for it to be supported.
