### ISSUE TITLE
Can't even use it. Just a grey screen

### ISSUE THREAD

**Issue by AHandheldFan** [holoiso-eol/holoiso#125]
I wasn't initially going to install this because 1. a brand new distro especially based on Arch, and especially done by true amateurs, is a recipe for instability and 2. because I had to wipe my entire SSD to do so...but after reading the issues section and seeing that it has been working on AMD GPU's. I thought I would give it a try anyway....and what a mistake that was. 
It boots and says verifying steam installation...but then there is a black bar at the very top and below that the rest of the screen is grey and it just hangs there. All it lets me do is use Function+Escape key to shut down the PC. Won't let me do anything else. And I do have a lot of experience with pure Arch...btw. I would use startx, etc...but I can only shut down the PC from that grey screen. Literally every other Arch based distro works.
-Flashed using Etcher.
-RX6900XT.
-R9 5900X.

How do I fix so that I can actually use it?

**Comment by mjkl-gh** [comment]
> How do I fix so that I can actually use it?

I'm not in any way affiliated with this project. But I would start by asking politely. Your message is full of frustration and disdain. A little bit of kindness goes a long way. The devs didn't put a gun to your head and force you to install it.

If it doesn't work, maybe wait for Valve to release SteamOS 3, as promised. Eventually...

**Comment by AHandheldFan** [comment]
Your reply just pissed me off even more. I was waiting for someone to reply with a potential fix...and your reply was anything but.
Of course I'm frustrated. ALL indicators written on the Git page suggested it would work on my hardware, and although no one forced me to install it, the fact I did and it doesn't work AND I lost my entire SSD content to do so...well of course I'm frustrated. So next time, unless you or anyone has a potential solution, then gfy.

**Comment by theVakhovskeIsTaken** [comment]
1. Stop being rude asf and let's try to debug what's happening
2. It's your fault for using your primary SSD to install this
3. Exit to desktop mode and run `gamescope-session` in konsole, do you have any errors doing that?

**Comment by AHandheldFan** [comment]
> 1. Stop being rude asf and let's try to debug what's happening
> 2. It's your fault for using your primary SSD to install this
> 3. Exit to desktop mode and run `gamescope-session` in konsole, do you have any errors doing that?

1. Ok
2. Haha 🤣 I've only got the one SSD bruh.
 3. I cannot exit to desktop mode. That's the thing. I did mention all I can do is shut down the PC from the grey screen

**Comment by AHandheldFan** [comment]
I got it to work finally. But I have to select the initram fallback grub option.
Not ideal.

**Comment by Illegalopcode** [comment]
I have almost the same setup. And had the same issue. I can tell you I have not got gamescope to display @ my monitor resolution. But you can switch to desktop mode and it works. Just don't run pacman -Syyu or yay -Syyu or any variant thereof it will bork the system. To switch CTRL+ALT+F4 then log in as root and run " steamos-session-select plasma-persistent" which should get you a working system. good luck

**Comment by AHandheldFan** [comment]
> I have almost the same setup. And had the same issue. I can tell you I have not got gamescope to display @ my monitor resolution. But you can switch to desktop mode and it works. Just don't run pacman -Syyu or yay -Syyu or any variant thereof it will bork the system. To switch CTRL+ALT+F4 then log in as root and run " steamos-session-select plasma-persistent" which should get you a working system. good luck

Thanks. It works. But if I can't run a system upgrade with the downgrade flag enabled (and therefore can't update the system) is there a point to running the distro?

**Comment by Illegalopcode** [comment]
> Author

I have not tried with the downgrade flag enabled. Well, when you run some games you will find out. This is very early in the life of this platform. These things will get sorted. I can say that this has been the best Linux gaming experience I have had. And I have run many flavors looking for the best gaming experience. Your mileage may vary.

**Comment by johnweland** [comment]
So. I stumbled upon this while face the same (or similar). After fiddling for a bit it looks like the screen is super zoomed in. After mashing some keys  Idid get "sign in" to popup but its in the lower left hand of the screen mostly off screen making me think that the screen is exploded out. I'll post back here as I figure out more. 

[updated]
in the initial install  I get prompted to resolve dependencies for initramfs, my options are Repository Core 1) mkinitcpio, repository extra 2) booster, 3) dracut; with the default being 1. (choosing option 1 as its the default)

When it begins to download the packages; it says there are 146 packages to install. after the first 5 it throws a couple of 404 errors and then gives up trying the rest of the packages. BUT still proceeds through setup as if everything is peachy. Asks to set a root password and a user/password, fails to create some directories in the user home, prompts for reboot and ends up rebooting and jumping in to SteamOS where you can configure language and timezone, reboots, then grey screen.

[updated]
after a 3rd install and waiting about 30-60s between choosing each option everything seems to install. Things seem to work.

**Comment by awdsagg** [comment]
try to get into desktop by using `steamos-session-select plasma-persistent` after getting into recovery mode from advanced options then go into konsole and type `sudo pacman -S gamescope` to go ahead and install gamescope

to switch back just type `steamos-session-select gamescope`
