### ISSUE TITLE
Support Legacy (Non-EFI) Systems

### ISSUE THREAD

**Issue by JongWasTaken** [holoiso-eol/holoiso#127]
Currently it seems only EFI systems are supported.
I have an older HTPC that i wanted to install this onto, but unfortunately it does not support EFI.
I tried using the syslinux configuration in the repo, until i realized that they are the default arch ones.
The boot sector of the iso file seems to be empty as well.

Are legacy systems not supported or is it planned?

**Comment by jomwells** [comment]
If you would like to achieve this yourself, build the .iso for yourself from within an arch environment (e.g. VM)
(guessed via following the build instructions on this repo and using [this ](https://github.com/archlinux/archiso/blob/master/docs/README.profile.rst) as a guide)

```
pacman -Sy archiso
git clone https://github.com/bhaiest/holoiso/
```

edit holosio/profiledef.sh (line 11)
from:
`bootmodes=('uefi-x64.systemd-boot.esp' 'uefi-x64.systemd-boot.eltorito')`
to:
`bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito')`
then run the following
`sudo mkarchiso -v holoiso`

this will produce a new .iso file in the out/ directory which you may flash as before.

I cannot guarantee this is a full solution and wont face any other issues, as I am brand new to archiso and have not actually tried to install SteamOS (yet) using this method, but I have confirmed that I **am** able to boot into the installer on an old legacy/non-UEFI capable PC.

**Comment by ghost** [comment]
This will only allow the installer to be bootable. The install script itself is hardcoded to uefi and thus has to be modified as well to install grub in legacy mode.

**Comment by ghost** [comment]
can confirm it would only allow the installer to be bootable, i bypassed the uefi requirement with ventoy and while the installer liveusb worked, after installation completed my laptop says "Operating System Not Found"
