### ISSUE TITLE
resolution overscan

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#129]
rx570 - dvi connection - 1920x1080 monitor

after installing the ui is overscanned like 2560x1440 or something like this
is there a way to change the default resolution?

**Comment by Illegalopcode** [comment]
I have not been able to get the resolution to match my screen. But I don't use Deck UI so it does not matter to me.  In desktop mode, it works great if you stay away from system updates. switch tty and run "steamos-session- select plasma-persistent" 
rx570 is not RDN2 it may give you issues.

**Comment by ghost** [comment]
Well, as I use ARCH as my main daily system I tinkered a bit and got to the regular kde interface. I was after testing EAC support for Ghost Recon Wildlands - but unfortunately I still don't get it to work.
A friend of mine got it to work a couple of years ago back when the Predator mission was a thing - but even after copy all the stuff like matching package versions and configs for some reason I can't get it to work correctly.
As for other games I play on a regular basis like Hitman3, Arma3, GTAvOnline it came a long way and runs fine on my system - others like Breakpoint or The Crew 2 refuse to even start for some reason.
I guess it's the best I can get for now - and aside from a few games and a bit of performance at least most runs at least fine.
I can only hope that thanks to valve the linux eco gets quite a push both for software as well as hardware. Maybe we'll see RISC-V in about 10 years or so ... it's quite an interesting time right now.

**Comment by Illegalopcode** [comment]
Did you try turning off OpenGL compositor in Developer settings?

**Comment by ghost** [comment]
I read that quite some time - but I haven't found that option. Can you tell me where to find it?
The issue is: I only see the upper left corner of the overscanned image. So anything on the right - like the language or timezone is out of view. It's like setting the resolution to something like 2560x1440 and only have a 1920x1080 viewport on it pinned to the upper left corner. So if this setting is anywhere to be found which requires the right side of screen - that'll be quite challenging.

**Comment by jazzcat007** [comment]
If the UI is too large to see the 'Settings' menu, you can click on the globe icon near the clock at the top of the screen. This will get you into the settings menu. You'll find 'Enable Developer Mode' on the 'System' tab. Once enabled you'll see a new 'Developer' tab at the bottom.

**Comment by jazzcat007** [comment]
I had to edit /usr/bin/gamescope-session, and change "-W 1280 -H 800" to "-W 1920 -H 1080" as well.
