### ISSUE TITLE
Optimization screen

### ISSUE THREAD

**Issue by rbrugnolli** [holoiso-eol/holoiso#13]
Hello.
I installed it on my PC and the only problem I had was that the game optimization screen, the one with the mangohud arrow and the GPU optimizations is not showing up.
I go into the option I can hear the navigation sounds of it, but it doesn't show on the screen.
Did I miss some configuration.

**Comment by ByteSz** [comment]
Passing on some information I read, go into the settings screen in the gamepadui and enable developer settings. Then go to the developer settings tab, and disable the OpenGL composer. This should allow both the Steam menu and the quick access menu to show up.

**Comment by rbrugnolli** [comment]
Worked, thank you.
