### ISSUE TITLE
Hardware TDP Not Detected, Only 15 Watts For GPU

### ISSUE THREAD

**Issue by ByteSz** [holoiso-eol/holoiso#133]
As the title says, SteamOS now has different configurations for per game performance profiles, this means there are new config files for the sessions in place. These by default also limit the GPU to 15 watts no matter what system you are on.

This was an issue for a while, where the only way to disable was to change the launch parameters for Steam from "-steamos3" to "-steamos", but you would lose the battery and quick access menus, as well as the ability to switch to desktop.

A user in a different issue finally found a solution, and potentially this could be used with some extra tools during install to fix this issue globally.

_Fix posted by @sysdba1977 in https://github.com/theVakhovskeIsTaken/holoiso/issues/94#issuecomment-1128522581_

**Comment by pastaq** [comment]
The issue is likely the polkit config from deck for the power1_cap feature of the GPU. removing that will probably stop the deckui from changing your TDP.

**Comment by pastaq** [comment]
So specifically, the file ```/usr/bin/steamos-polkit-helpers/steamos-priv-write``` enables access to a bunch of stuff that should be root only in most situations. It is part of the ```jupiter-hw-support``` package. Removing that package with ```yay -R jupiter-hw-support``` and a reboot will probably solve all these problems and should IMO be removed by default as the deckui has a lot of hard coded automations that mess with these files, as you can see.
