### ISSUE TITLE
Won't load login screen Unless no Username or login passwords given in setup process

### ISSUE THREAD

**Issue by ArtieJames99** [holoiso-eol/holoiso#134]
I've been trying for a while to get this to work; I'm thinking it's probably just my computer hardware but I thought it worth checking out.
I've been trying to create the disk from the Iso file and the process of creating the USB boot drive goes fine. when I try to boot into the Drive, however, It gives the "Failed to Start Jupiter Controller Firmware Update service" and then goes to a black screen. I try to go into TTY2 and log in, and no matter what I put in it doesn't let me log in and do the commands. 
I redid the process without putting in the root Password, Username, and User password. When I gave the command "reboot", it still gave the error "Failed to Start Jupiter Controller Firmware Update service" but it went into the login screen, but I had no way of logging in because I didn't set it up properly. 

Does anyone have any solutions for getting this to work properly? 
I'm fairly new to all of this, but I have had a little experience with Linux, mainly Ubuntu-based, but I was hoping to try to learn how to do this.

**Comment by nyannoying1337** [comment]
i have the same issue but i can see the mouse cursor at the blackscreen

**Comment by ghost** [comment]
I would suggest to first try to set up a regular arch build following the guide on the arch wiki to see if you can get arch to work on your systems at all in the first place.
Next question: What type of hardware do you have? CPU? GPU?
Remember: This is based on the official recovery image for the deck - so it may only support amd cpus and amd gpus - if you have an intel gpu this may can cause issues - if you have an nvidia gpu - well, that's currently not supported.
Also: You HAVE to give at least a root password. If you don't give any password for root the account is disabled and you can't log into it. That's basic linux security. As for user account ... well, I'm not sure what the script does when none is given - but it mostly will result in some funky issue - better to give at least some dummy data easy to type.

**Comment by nyannoying1337** [comment]
> I would suggest to first try to set up a regular arch build following the guide on the arch wiki to see if you can get arch to work on your systems at all in the first place.
> Next question: What type of hardware do you have? CPU? GPU?
> Remember: This is based on the official recovery image for the deck - so it may only support amd cpus and amd gpus - if you have an intel gpu this may can cause issues - if you have an nvidia gpu - well, that's currently not supported.
> Also: You HAVE to give at least a root password. If you don't give any password for root the account is disabled and you can't log into it. That's basic linux security. As for user account ... well, I'm not sure what the script does when none is given - but it mostly will result in some funky issue - better to give at least some dummy data easy to type.

At least on my end i would like to point out that older ISOs worked just fine for me. the most recent one seems to be not working on my end. i5-10400f, GTX 1050Ti

**Comment by ArtieJames99** [comment]
I’ve got a intel I5 and intel Iris integrated graphics. That’s probably why I’m having these issues. I thought I’d give it a try because it’s an old 2014 Mac mini and I’ve seen others get this working on other macs, but those were probably before apple switched to intel. I’ll try to boot regular arch Linux just to get a feel for it. I guess I’ll just have to wait till I can get my Hands on a steam deck to actually try this out.
Also before this one none of the iso files worked. I’ve tried just about every one, but that’s probably because it’s intel.

**Comment by ghost** [comment]
> i5-10400f, GTX 1050Ti

That's mostly the root cause. I'm not sure about the CPU - but the nVid GPU currently is not supported. It's marked in the FAQ.

> I’ve got a intel I5 and intel Iris integrated graphics. That’s probably why I’m having these issues.

Very likely.

**Comment by Illegalopcode** [comment]
Failed to Start Jupiter Controller Firmware Update service this happens because you are not running it on a steam deck. Not related. user names need to be lower case or you will get a lock-up. Why? I have no clue. I have not leaned into that issue.

**Comment by ArtieJames99** [comment]
Thank you, I was able to get the desktop mode working when I set the username as all lowercase. The Deck UI still doesn’t work when I try to sign in, but that’s probably because I’m using intel. Other than that it looks, and seams to run decently. The username change solved most of my problems.

**Comment by ghost** [comment]
Never gave it any thought about using anything else than all lower case letters - as it's common on linux anyway - but this could be related to an issue more upstream.
