### ISSUE TITLE
Error "failed retrieving file"

### ISSUE THREAD

**Issue by F0R3V3R50F7** [holoiso-eol/holoiso#135]
There seems to be issues when downloading packages, I've tried this ISO three times and have not been able to get it working. My issue has been closed once and it's not been resolved. ![IMG_20220518_131521.jpg](https://user-images.githubusercontent.com/30199830/169037730-75e34dee-8070-4eb8-a6d9-24f2fd77876a.jpg)

**Comment by BobDev32** [comment]
I had same thing I run 
`pacman -Sy archlinux-keyring`
`pacman -Su`

That said, I think the latest release has added same thing as a fix, so try it out.
