### ISSUE TITLE
Failed retrieving file 'holoiso.db' error during holoinstall

### ISSUE THREAD

**Issue by irfanhakim-as** [holoiso-eol/holoiso#136]
ISO used: [Holo ISO: Boop (Stable)](https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220507.0729)
To reproduce:
- Flash ISO to USB (FAT32) using BalenaEtcher
- Boot into USB UEFI
- Choose the `core/linux` option
- Connect to the internet using `iwctl`
- Verify that you're connected to the internet by pinging to the internet with no packet loss eg. `ping google.com`
- Run `holoinstall`
- Choose option 2 (deckperience)
- Select the correct disk to install on
- Installation process will then proceed, when repos/databases are being updated, `holoiso.db` will fail to download
- Installation will complete after adding a hostname, username, and password
- Reboot and the disk where holoiso was 'installed' will be unbootable

Full error:
```sh
error: failed retrieving file 'holoiso.db' from dl.thevakhovske.cf : Could not resolve host: dl.thevakhovske.cf
warning: too many errors from dl.thevakhovske.cf, skipping for the remainder of this transaction
==> ERROR: Failed to install packages to new root
```

Someone seems to have the same error of failing to retrieve a file, but a totally different file and for different reason (Operation too slow, instead of Could not resolve host). Referring to #135. Help or advise would be much appreciated.

Edit:
The same issue has apparently been reported before #70. Reason being the (freenom) domain (dl.thevakhovske.cf) was down. Don't know how this could be fixed or worked around on my end other than wait for the domain to be back up.

**Comment by irfanhakim-as** [comment]
Update:
Solved (this error at least) by updating `pacman.conf` before running `holoinstall`. Do so by running the following.
```sh
sudo curl https://raw.githubusercontent.com/theVakhovskeIsTaken/holoiso/3.0/airootfs/etc/pacman.conf -o /etc/pacman.conf
```

Found this thanks to @sharicov from #72. This solves the error that was issued. However after a reboot post-installation, despite reaching the login screen this time, I was able to fill my password but couldn't for the life of me, submit it. Pressing <kbd>Enter</kbd> and what other equivalent I could think of did nothing. I also noticed that the Session dropdown available at the top left of the login screen was empty, revealing the list also showed nothing I could select from. I was able to get into the Terminal from the login screen though and login to my user just fine but that's about it.

The only other error I managed to notice during the quick installation was the absence of certain locales. We weren't presented to select any during installation so it might not mean a thing. I might give up for now, unless I get any advice I could proceed with. Thank you!

**Comment by JoshDoesStuff** [comment]
Use the new update, holoiso Summertime

**Comment by irfanhakim-as** [comment]
I've been happily using [ISO Update 3.1](https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/isoupd3_stable) for some time now. The installation process was a breeze, and the system itself is relatively if not perfectly stable on my Ryzen 5 5600G system. Thanks!
