### ISSUE TITLE
install via SSH - root SSH password?

### ISSUE THREAD

**Issue by nathlx** [holoiso-eol/holoiso#137]
I am trying to install on my Aya Neo, but it doesn't have a keyboard and I dont have a USB one to hand. 
Could I SSH in and then run the installer? What is the default root SSH password?

**Comment by ghost** [comment]
As it's based on arch, the answer is: NONE - there's no default password set on the install files - hence you can't ssh into without first setting a password.

**Comment by nathlx** [comment]
ah, damn, ok. that would be a neat thing to set going forwards. 
I guess ill run the install with the SSD in my laptop and swap it after it copies the files to the SSD. Hopefully it will boot!
