### ISSUE TITLE
4K TV Issue

### ISSUE THREAD

**Issue by aaronson2012** [holoiso-eol/holoiso#138]
Some UI Elements appear too large/zoomed in on my display in gaming mode. Sometimes when I boot into gaming mode the UI is normal size (except when I press the home button on my controller) and sometimes the entire UI is too large/zoomed in. I am using a 4K Samsung TV. I am using a AMD GPU. Please see screenshot.

[https://anonfiles.com/59V4A9h9y5/IMG_20220518_081304_jpg](url)

**Comment by Mar2ck** [comment]
Disable OpenGL compositor in the Dev settings

**Comment by aaronson2012** [comment]
> Disable OpenGL compositor in the Dev settings

Hey thanks for the reply, can you briefly walk me through how to do that? I see the compositor settings for kde but i imagine that only applies to kde.

Thanks! :)

**Comment by aaronson2012** [comment]
Never mind, I figured it out. I'll report back in a minute to tell you if it worked

**Comment by aaronson2012** [comment]
Wow it worked! Thanks for the tip!!!

**Comment by deftdawg** [comment]
@aaronson2012 if it worked why don't you close the issue? 😉
