### ISSUE TITLE
Collaboration with winesapOS

### ISSUE THREAD

**Issue by LukeShortCloud** [holoiso-eol/holoiso#139]
Hey @theVakhovskeIsTaken , I recently came across your [Reddit post](https://www.reddit.com/r/SteamOS/comments/u3jcek/finally_got_everything_working_on_winesapos/) showing you taking [winesapOS](https://github.com/LukeShortCloud/winesapOS) for a spin. That's awesome! Hopefully that helped you reach the finish line for HoloISO. I would love to collaborate on our two projects since we share a similar goal of spreading SteamOS to the masses. For example, for winesapOS, I have created AUR packages for [mesa-steamos](https://aur.archlinux.org/packages/mesa-steamos) and [lib32-mesa-steamos](https://aur.archlinux.org/packages/lib32-mesa-steamos) that re-enable support for Intel and NVIDIA graphics drivers. We also have goals of supporting an ISO installer of our own. Let me know what you think and if there are any areas where I can help!

**Comment by theVakhovskeIsTaken** [comment]
Hey there, Luke! Thanks for replying late, i might consider doing that in future, but now i'm focused in getting everything to a good shape.

Just compiled those MESA packages, and they don't differ with those from jupiter/jupiter-main branches. Same Vangogh/AMD-locked MESA with RADV only support

**Comment by LukeShortCloud** [comment]
I completely understand. I am one message away if you need anything!

For the SteamOS AUR packages, the source code is the same but how it is built is very different. One of the biggest changes is enabling more OpenGL drivers. Intel, NVIDIA, and VMware virtual drivers are fully enabled now. Here is a full change log:  https://aur.archlinux.org/cgit/aur.git/log/?h=mesa-steamos . If you have any suggestions on how to improve those packages, I am open to feedback!

**Comment by theVakhovskeIsTaken** [comment]
> I completely understand. I am one message away if you need anything!
> 
> For the SteamOS AUR packages, the source code is the same but how it is built is very different. One of the biggest changes is enabling more OpenGL drivers. Intel, NVIDIA, and VMware virtual drivers are fully enabled now. Here is a full change log: https://aur.archlinux.org/cgit/aur.git/log/?h=mesa-steamos . If you have any suggestions on how to improve those packages, I am open to feedback!

Ah-ha...I see, i'll try to upload my master branch gamescope PKGBUILD today onto my repositories, and try to push your MESA/Multilib MESA to see if that's gonna be fine with it

**Comment by LukeShortCloud** [comment]
I wanted to continue a conversation from here: https://github.com/theVakhovskeIsTaken/holoiso/issues/241

> > This has been added as part of the latest HoloISO update: https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1 . I created a fork of the Mesa drivers from SteamOS and re-enabled support for all upstream drivers. These packages are all up on the AUR.
> > 
> > * https://aur.archlinux.org/packages/mesa-steamos
> > * https://aur.archlinux.org/packages/lib32-mesa-steamos
> > 
> > We have been using this for a while in my [winesapOS](https://github.com/LukeShortCloud/winesapOS) project. Let us know if you run into issues using it!
> 
> Got reverted btw :P DRI/RADV was still old, so that was pointless to use, nevertheless, thanks

I actually looked into updating Mesa and a few other packages today from SteamOS but Valve hasn't released a new source package since the launch of the Steam Deck. That's a blocker for us being able to update it.

Also important to note: SteamOS uses a separate package for RADV. With mesa-steamos, we bundle it.

Does HoloISO do anything special for handling Mesa? In winesapOS, the official SteamOS Mesa did not work well (if at all) for non-AMD graphics devices. Most devices defaulted to lavapipe software rendering. We first switched to Mesa from Arch Linux. Now we  currently ship a modified version of Mesa from SteamOS (the one we host on the AUR).

**Comment by LukeShortCloud** [comment]
I finally found the latest source code in the `jupiter-main` source repository. I updated the `mesa-steamos` and `lib32-mesa-steamos` packages to SteamOS 3.3 recently.

**Comment by theVakhovskeIsTaken** [comment]
> I finally found the latest source code in the `jupiter-main` source repository. I updated the `mesa-steamos` and `lib32-mesa-steamos` packages to SteamOS 3.3 recently.

Cool! But we don't use them as of 202207xx. We're going straight ahead to 22.2 testing with support for more hardware

**Comment by LukeShortCloud** [comment]
Are you using upstream Mesa from the official Arch Linux repository or are you using the latest development packages from SteamOS? I see there's source code for 22.2.0 available:

https://steamdeck-packages.steamos.cloud/archlinux-mirror/sources/jupiter-main/
[lib32-mesa-radv-22.2.0_devel.156798.jupiter_22.3.1-1.src.tar.gz](https://steamdeck-packages.steamos.cloud/archlinux-mirror/sources/jupiter-main/lib32-mesa-radv-22.2.0_devel.156798.jupiter_22.3.1-1.src.tar.gz)

One of my winesapOS users benchmarked `mesa-steamos` versus `mesa-tkg-git` and found that the TKG build was both faster and smoother on AMD. I contemplated switching to that but decided to stick with (1) a stable build and (2) to align with stable SteamOS 3.Y releases in winesapOS. For better or worse, because of that decision, I'm stuck on Mesa 22.0.2 for now. At least Valve backports fixes and improvements for AMD.

Glad to hear that improved hardware support is coming for HoloISO! That'll be huge!
