### ISSUE TITLE
Discovery and installing flatpak

### ISSUE THREAD

**Issue by jdwininger** [holoiso-eol/holoiso#14]
I've enabled flathub via the arch instructions on on flathub's website. Afterward all flathub's programs show up in discovery but when I try to install anything it asks for the root password. I set a password at install time but it doesnt seem to be what discovery is looking for.

my steps were
1) enter desktop mode
2) enabled flathub via terminal
3) reboot
4) enter desktop mode
5) start discovery
6) try to install anything
7) discovery asks for root password

**Comment by theVakhovskeIsTaken** [comment]
Root password is `root` by default.

**Comment by jdwininger** [comment]
Thank you, worked like a charm. feel free to close this issue.
