### ISSUE TITLE
Selected audio device doesn't persist through reboot

### ISSUE THREAD

**Issue by aaronson2012** [holoiso-eol/holoiso#140]
Hello,

When I boot up my system, the audio device defaults to my onboard audio instead of my HDMI audio. Then when I select my HDMI audio and reboot, it defaults back to the onboard audio.

Thanks!

**Comment by theVakhovskeIsTaken** [comment]
This isn't a bug, this is excepted behavior if you're choosing it in Game mode. Same thing happens on Steam Deck
