### ISSUE TITLE
Suggestion: Make an offline installer

### ISSUE THREAD

**Issue by DrKoneko** [holoiso-eol/holoiso#142]
I think it'd be cool if there was an offline installer iso, with all the necessary files on it. Idk if this is possible but it'd be cool if it was.

**Comment by theVakhovskeIsTaken** [comment]
Offline installer is either you shipping single installation snapshot image, or doing full-blown live ISO
Either way, the full SteamOS installation is around 6GB. Which is too much for archiso to have. Upon loading into it, you're running out of memory instantly.
