### ISSUE TITLE
Automatic SDDM login at boot?

### ISSUE THREAD

**Issue by MarkusMaribu** [holoiso-eol/holoiso#144]
I've got everything set up, and gamescope works as it should. The only issue is that at cold boot, im presented with the login manager. As my PC is connected to the TV, I dont have access to a keyboard, so automatic login into gamescope would be necessary.

My first instinct was to simply turn on automatic login in the system settings, but the SDDM settings aren't there. Editing the SDDM config sort of worked, but Im only able to figure out how to login into the KDE desktop.

Am I missing something?

**Comment by swer21** [comment]
The content of /etc/sddm.conf.d/autologin.conf will be automatically updated when ever you select "go to desktop mode" from gamescope and when you select "return to game mode" (icon on the desktop) . To start gamescope the file content has to be
`[Autologin]
User=steam
Session=gamescope-wayland`

I having the impression that when you use the logoff function from the plasma desktop this is not working correctly. I haven't seen this issue on a real steam deck. But when I'm using the desktop Icon it was working for me.

**Comment by MarkusMaribu** [comment]
> The content of /etc/sddm.conf.d/autologin.conf will be automatically updated when ever you select "go to desktop mode" from gamescope and when you select "return to game mode" (icon on the desktop) . To start gamescope the file content has to be
> `[Autologin]
> User=steam
> Session=gamescope-wayland`
> 
> I having the impression that when you use the logoff function from the plasma desktop this is not working correctly. I haven't seen this issue on a real steam deck. But when I'm using the desktop Icon it was working for me. 
> 

It seems to be working without really changyng anything. My guess is that I rebooted while on the desktop, so it defaulted to plasma. Thank you anyways.
