### ISSUE TITLE
how to open quck access menu

### ISSUE THREAD

**Issue by swer21** [holoiso-eol/holoiso#145]
I tried to google it but I failed. But I can't figure out how to open the quick access menu with keyboard or PS4 controller. 
Can I some how reassign a unused button to act as the quick access button. for example the share button on the ps4 controller is not used.
 
edit:
It's the PS button + X on the PS4 controller

**Comment by swer21** [comment]
It's the PS button + X on the PS4 controller

**Comment by BoofOof32** [comment]
@swer21 do you know how to do so on a Switch Pro Controller?

**Comment by swer21** [comment]
After I used better search terms I found this https://steamcommunity.com/app/1675200/discussions/2/3186865924593558269/  .
I do not know what the "The controller Guide button" in case of the Swich Pro Controller is but it is the same button as to open the main menu in game scope (It should show the proper icon in the lower left corner when a controller is connected).  So it should be the Guide button + lower face button (B in case of a nintedo controller).

**Comment by BoofOof32** [comment]
hmm, perhaps it only works on the actual SteamOS, I can't seem to get it to work on `gamepadui` on Desktop
