### ISSUE TITLE
ShadowBlip - aya-neo-fixes

### ISSUE THREAD

**Issue by cdomin1** [holoiso-eol/holoiso#146]
I know this is not exactly a bug fix but I can't figure for the life of me out how to install the 'ShadowBlip' aya neo fixes.
I have no idea how to use the AUR installer (Linux noob), but I at least figured out how to install the wifi drivers and update the kernel

How do I run these commands to install the appropriate packages?
_Run pikaur -S aya-neo-fixes-git as root.
Run systemctl enable neo-controller as root.
Run systemctl start neo-controller as root._

Any dumb down walkthrough would be super helpful, thanks!

**Comment by Illegalopcode** [comment]
yay aya-neo-fixes-git 
follow prompts
sudo systemctl enable neo-controller
sudo systemctl start neo-controller

**Comment by cdomin1** [comment]
Thank you so much!!

**Comment by cdomin1** [comment]
So I got stuck after running the intial command, is there a more detailed instructions that I can find somewhere?

**Comment by cdomin1** [comment]
Here is where I am stuck at after running first command and hitting "ALL" for each prompt:

**Comment by cdomin1** [comment]
So I got stuck after running the initial command, is there more detailed instructions that I can find somewhere?
Here is where I am stuck after running the first command and hitting "ALL" for each prompt:
Sorry in advance for all the noob questions!

**Comment by cdomin1** [comment]
![IMG_3918](https://user-images.githubusercontent.com/105389333/169668378-934f043f-6e42-4cd5-bae8-4ff89db443fe.jpg)

**Comment by forrestlay** [comment]
Try using `yay -S aya-neo-fixes-git` instead, I think using `yay aya-neo-fixes-git` just searches for the package.

**Comment by cdomin1** [comment]
> Try using `yay -S aya-neo-fixes-git` instead, I think using `yay aya-neo-fixes-git` just searches for the package.

So I tried that and it lead me to what I posted as a picture as it goes into a list of blue text information with no prompt to continue. When I scroll down the bottom of the Konsole I just see [END] and cannot do anything afterward. Is there a step I am missing after inputting **yay -S aya-neo-fixes-git**?

**Comment by Illegalopcode** [comment]
get a screengrab of the choices right before that screen
You are reviewing the aur file when you don't need to. Try hitting enter on the screen before this one.

**Comment by cdomin1** [comment]
So I think I got the packages installed but I notice now the Aya Neo will freeze on a black screen when pressing the power button to suspend or sleep and it is freezing trying to shut down or reboot as well. Not sure what to do at this point.

**Comment by pastaq** [comment]
> So I think I got the packages installed but I notice now the Aya Neo will freeze on a black screen when pressing the power button to suspend or sleep and it is freezing trying to shut down or reboot as well. Not sure what to do at this point.

Open an issue on aya-neo-fixes repo and I'll help you out. There is probably a conflict with the different way HoloISO handles shutdown than other distros

**Comment by theVakhovskeIsTaken** [comment]
> > So I think I got the packages installed but I notice now the Aya Neo will freeze on a black screen when pressing the power button to suspend or sleep and it is freezing trying to shut down or reboot as well. Not sure what to do at this point.
> 
> Open an issue on aya-neo-fixes repo and I'll help you out. There is probably a conflict with the different way HoloISO handles shutdown than other distros

HoloISO handles shutdown in same way as any distro would, except for [this](https://github.com/theVakhovskeIsTaken/holoiso_install_main/blob/main/src/holoiso-gamescope-power) gamescope workaround for checking power control sentinel persistence.

**Comment by Painbou** [comment]
Installed the package on holoiso and xbox controller is not recognized anymore. In the gamepad UI, no controls is detected.. I had to uninstall it to recover the use of the xbox controller.

**Comment by pastaq** [comment]
> 

Please open an issue [here](https://github.com/ShadowBlip/aya-neo-fixes) and I'll take a look at it.

**Comment by pastaq** [comment]
Issue was resolved in https://github.com/ShadowBlip/aya-neo-fixes/issues/6 

If anyone else experiences this issue please reinstall using ```yay -Sy aya-neo-fixes-git```
