### ISSUE TITLE
No UI, just mouse cursor and failures...

### ISSUE THREAD

**Issue by CoffeePowerUp** [holoiso-eol/holoiso#147]
I have an issue. The system seems like it loads (with two failures) and I get a black screen with the mouse cursor. CTRL+ALT+F4 works for the terminal, but that's it. 
The two errors:
Failed to start **Jupiter BIOS Update Service**
Failed to start **Jupiter Controller Firmware Update Service**

I install from one pendrive to another. I put the iso to a smaller pendrive with Rufus, installed the system onto a high speed 32 GB USB 3.0 drive. 
My specs: 

- AMD Ryzen 5 3600
- 2*8 GB DDR4 RAM 
- AMD RX 570 4GB videocard
- MSI MAG B550 Tomahawk motherboard
- 32GB Sandisk Extreme USB drive (as installation target)

**Comment by theVakhovskeIsTaken** [comment]
Sure.
Can you press CTRL+Alt+F4, login, type `steamos-session-select`?

**Comment by TomiSi12** [comment]
on my laptop i have the same issue. I can*t  press CTRL+Alt+F4 and write steamos-session-select
when i press it then it doesn't happend

**Comment by Salazaar1000** [comment]
Having a similar issue, getting "Failed to start Jupiter BIOS Update Service"

System is different though - i5 6600K on a Z170 motherboard with an AMD R9 290X

Can ctrl+alt=F4 and run steamos-session-select but system respons with 

Are you running SteamOS on KDE Plasma or SteamOS Session?

Them command prompt...

**Comment by AlexCrusade** [comment]
I understand the problem is common.  I have the same thing. Is there really no solution?
