### ISSUE TITLE
Does this new update now include proper nvidia support?

### ISSUE THREAD

**Issue by JoshDoesStuff** [holoiso-eol/holoiso#149]

**Comment by theVakhovskeIsTaken** [comment]
Probably no. You'll still need to compile gamescope from source and install NVIDIA's Driver 515 beta

**Comment by SaulGoodman1337** [comment]
> Probably no. You'll still need to compile gamescope from source and install NVIDIA's Driver 515 beta

Ist there Manual for this steps ?

**Comment by Cageman1984** [comment]
I'm in doubt... As a GTX 1050 ti user (Nvidia) I have 3 choices:

> 1) try the 515 driver
> 2) wait for either proper Nvidia integration in holoISO (not your fault guys) or in the actual release from valve (that could take decade)
> 3) steer away from SteamOS until the Gtx 1050 is replaced by and AMD

Any recommendations?

**Comment by KptnKMan** [comment]
> Probably no. You'll still need to compile gamescope from source and install NVIDIA's Driver 515 beta

Really would appreciate if there is anywhere on the internet that describes how to do this, I have trouble find it.

So far all I got:

gamescope from: https://github.com/Plagman/gamescope
Nvidia 515 beta: https://www.nvidia.com/download/driverResults.aspx/187834/en

I can at some point try getting this setup and post some details of what I did, but there is some compilation build instructions on the gamescope repo.

**Comment by asylumexp** [comment]
take a look at #64
