### ISSUE TITLE
Shutting down/restarting from SD UI requires password

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#15]
Shutting down/restarting from SD UI goes back to SDDM and asks for user password to login, but after typing in the password continues to normal shut down/restart.

Both of these functions work correctly from KDE Plasma.

**Comment by theVakhovskeIsTaken** [comment]
> Shutting down/restarting from SD UI goes back to SDDM and asks for user password to login, but after typing in the password continues to normal shut down/restart.
> 
> Both of these functions work correctly from KDE Plasma.

Looks like polkit rules ain't playing well with stuff, will checkout later

**Comment by theVakhovskeIsTaken** [comment]
Will be resolved in next `holoiso-main` snapshot.
