### ISSUE TITLE
Newest release stuck in game mode!

### ISSUE THREAD

**Issue by BOOSTERXB** [holoiso-eol/holoiso#150]
I have the newest release on a OneXplayer 4800U and I am stuck in the deck game mode and when I switch to desktop mode it just reloads into steam client and game mode. Due to the upside down display in deck mode the only way to play or game is in the desktop mode.

**Comment by FayeSpica** [comment]
Aya neo 2021 4500U same issue, and I will do a fresh installation now

**Comment by FayeSpica** [comment]
Do a fresh installation solve the issue
