### ISSUE TITLE
Dual Boot with Windows

### ISSUE THREAD

**Issue by alex3604** [holoiso-eol/holoiso#151]
Is it possible to install HoloIso on an external HDD, so i can dual boot with windows ? Installing it on external HDD, does it write something on my main internal drives ? I'm so curious to try this out, mostly now that it supports NVIDIA GPUs. If yes, please let me know how, i will happily join the community. @theVakhovskeIsTaken thanks for your work, i'm following your project since the first release and it seems awesome !

P.S. Have you considered opening a Discord Server for the community who follows your project ? So they can also discuss with each other about it, giving you direct feedback, and maybe helping each other resolving problems or issues

**Comment by Illegalopcode** [comment]
Yes, you can install it on an external drive. No it will not write to you internal drive if you don't select it. Just make sure you know the id of the drive you want to install it to.

**Comment by alex3604** [comment]
> Yes, you can install it on an external drive. No it will not write to you internal drive if you don't select it. Just make sure you know the id of the drive you want to install it to.

Can i quickly ask how i can install it on my external drive ? Like, what commands i need to put, i'm a little newbie with linux

**Comment by FayeSpica** [comment]
You can dual boot in one nvme ssd, Just follow step in this video：https://youtu.be/_6eHHr3b9Ck
note：replace steam os install to holoiso

**Comment by alex3604** [comment]
> You can dual boot in one nvme ssd, Just follow step in this video：https://youtu.be/_6eHHr3b9Ck note：replace steam os install to holoiso

I already saw the video, but i can't understand what command i got to use to list all the disk, and how to select the external drive, also, it is and hdd, not an ssd

**Comment by Mrpuppyz** [comment]
Lsblk will list the drives on the computer. Will also show the size to help determine witch drive is the one you want. In this example I have two drives one is sda with 465.8G (it's really a 500G SSD) and another drive that is nvme0n1 with 931.5G (it's really a 1 terabyte nvme SSD)
![20220525_170454.jpg](https://user-images.githubusercontent.com/103858972/170389078-7df6aabb-95f3-455b-93ae-8eb95c620c01.jpg)

**Comment by alex3604** [comment]
> Lsblk will list the drives on the computer. Will also show the size to help determine witch drive is the one you want. In this example I have two drives one is sda with 465.8G (it's really a 500G SSD) and another drive that is nvme0n1 with 931.5G (it's really a 1 terabyte nvme SSD) ![20220525_170454.jpg](https://user-images.githubusercontent.com/103858972/170389078-7df6aabb-95f3-455b-93ae-8eb95c620c01.jpg)

Cool, i'll try soon as i can, thank you so much <3

**Comment by NikunjGupta01** [comment]
What does install along side other os does, will it work with windows
