### ISSUE TITLE
Please, just please, make holoiso boot ssdm on first boot

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#153]
It's literally impossible to even get things like Nvidia (or Intel) drivers loaded without getting into kde, so we end up needing to fiddle around with launch parameters or root access. I completely understand wanting that steamdeck exact experience but you've basically made it impossible for anyone who isn't a complete giga brain Linux Chad to actually be able to boot into the os. I've two laptops I keep testing this on and I've basically got to do a ritual dance to even think about getting into a usable os.

So please, for the love of everything holy
Give us an option at first boot to load directly into kde.
Sincerely,
A person who just wants to use this.

**Comment by theVakhovskeIsTaken** [comment]
> It's literally impossible to even get things like Nvidia (or Intel) drivers loaded without getting into kde, so we end up needing to fiddle around with launch parameters or root access. I completely understand wanting that steamdeck exact experience but you've basically made it impossible for anyone who isn't a complete giga brain Linux Chad to actually be able to boot into the os. I've two laptops I keep testing this on and I've basically got to do a ritual dance to even think about getting into a usable os.
> 
> So please, for the love of everything holy
> Give us an option at first boot to load directly into kde.
> Sincerely,
> A person who just wants to use this.

I added recovery mode since latest update, just boot into it and type `mv /etc/sddm.conf.d/autologin.conf /etc/sddm.conf.d/autologin.tmp` and reboot your PC. It will automatically enter SDDM greeter.

**Comment by kogatoerigotsun** [comment]
you should add a login and wifi manager in the first boot, i wouldnt know how to do it but i know of them, _### **basically it should be as easy as a mac**_
