### ISSUE TITLE
OneXPlayer Mini (AMD 5800u)  wifi bugs

### ISSUE THREAD

**Issue by huchenghe001** [holoiso-eol/holoiso#156]
I referenced what @pastaq said 
After flashing the latest version of the iso, the bluetooth is available. I remember that the last version was unavailable. After I used the pastaq script, the wifi was still unavailable. What could be the reason?

**Comment by theVakhovskeIsTaken** [comment]
Wi-Fi is known issue since RZ608/MT7921K(E) chips are not supported by kernel <5.16.

I'm still working on backporting it, so just stay tuned till further announcements xD

**Comment by huchenghe001** [comment]
>How can i update kernel

**Comment by pastaq** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/245
