### ISSUE TITLE
Not able to switch to gamescope

### ISSUE THREAD

**Issue by MarkusMaribu** [holoiso-eol/holoiso#157]
After switching to the Desktop, Im no longer able to switch back to the gamescope session. 

When clicking the "Return to gaming mode" icon, I just get sent to the login manager (where the password doesn't do anything). At this stage, switching back to the Desktop does work.

I tried running gamescope-session in the terminal, but it just spits out

bash: gamescope-session: command not found

**Comment by tym2liv3** [comment]
This is happening for me too

**Comment by theVakhovskeIsTaken** [comment]
> After switching to the Desktop, Im no longer able to switch back to the gamescope session. 
> 
> When clicking the "Return to gaming mode" icon, I just get sent to the login manager (where the password doesn't do anything). At this stage, switching back to the Desktop does work.
> 
> I tried running gamescope-session in the terminal, but it just spits out
> 
> bash: gamescope-session: command not found

That's.....strange....
Mind running `sudo pacman -S gamescope` ?

**Comment by doxzilla** [comment]
HoloISO updated to snapshot20220608.1251 and now I am unable to switch back to game mode from the desktop via the shortcut, but I can use Konsole to do it manually with the steamos-session-select gamescope command
