### ISSUE TITLE
No DE after Snapshot2 update

### ISSUE THREAD

**Issue by MarkusMaribu** [holoiso-eol/holoiso#158]
After updating to Snapshot2, my install no longer has a DE, and I'm left with nothing but a terminal login screen.

Logging in just gives me access to the command line.

Help?

**Comment by coryalbert** [comment]
I am getting the exact same here. Maybe have to do a reinstall?

**Comment by JongAnYoo** [comment]
나도 마찬가지이다

**Comment by MarkusMaribu** [comment]
> I am getting the exact same here. Maybe have to do a reinstall?

I just reinstalled holoiso myself, but now wifi drivers wont work 😪

**Comment by Illegalopcode** [comment]
ok try this. Boot into recovery under advanced. After logged in, run holoiso-disable-sessions. then systemctl default. This got me into the DE.

**Comment by Mario-119** [comment]
Getting a similar problem, it just boots to a black screen for me

**Comment by ixervice** [comment]
Same here. Retried to logged in recovery. After run holoiso-disable-sessions, just tell me"bash:holoiso-disable-sessions:command not found".
