### ISSUE TITLE
Resolution stuck at 720p

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#16]
If this is the issue/limit because of using SteamOS recovery image instead of official PC image then mark it as closed.

Would be great if there's a config file to edit from terminal to set the resolution to 1080p, every game I open is maxed out at 720p.

This is only in SD UI.

**Comment by jdwininger** [comment]
I can verify this is also the case for me. All games are capped at 720p resolution.

**Comment by ByteSz** [comment]
To change this, you can edit /usr/bin/gamescope-session, and change "-W 1280 -H 800" to whatever desired resolution you wish to be your max. I changed mine to 3840 by 2160 and have had no issues after reinstalling any games I launched before editing this file.

**Comment by aleksasiriski** [comment]
I believe this should be in the readme if it can't automatically adjust to the display.

**Comment by peterge1998** [comment]
> I believe this should be in the readme if it can't automatically adjust to the display.

Yep. Pls clarify the resolution problem, its really strange on gamescope

**Comment by ByteSz** [comment]
> > I believe this should be in the readme if it can't automatically adjust to the display.
> 
> Yep. Pls clarify the resolution problem, its really strange on gamescope

So the resolution problem, is that even though the Deck UI itself for Steam is at the correct screen resolution, this gamescope-session file defines the Gamescope context created for the the game run through the Deck UI and by default it is set to 1280x720. In newer releases of HoloISO, I have noticed that it was changed to 1366x768 (I'm guessing this is Vakhovskel's laptop resolution). So by editing this gamescope session file, you are telling Gamescope to create a context with that screen buffer resolution for the game you are running.

**Comment by peterge1998** [comment]
> So the resolution problem, is that even though the Deck UI itself for Steam is at the correct screen resolution, this gamescope-session file defines the Gamescope context created for the the game run through the Deck UI and by default it is set to 1280x720. In newer releases of HoloISO, I have noticed that it was changed to 1366x768 (I'm guessing this is Vakhovskel's laptop resolution). So by editing this gamescope session file, you are telling Gamescope to create a context with that screen buffer resolution for the game you are running.

When testing with changing /usr/bin/gamescope-session, I am getting a black screen and can't use holoiso after booting (which I do not see too).
I created [this](https://github.com/theVakhovskeIsTaken/holoiso/issues/176) issue...
