### ISSUE TITLE
After Installation no boot up

### ISSUE THREAD

**Issue by TomiSi12** [holoiso-eol/holoiso#160]
Hello,

I have set up holoiso on Thinkserver ts130 with Intel xeon e3 12345. After installation it comes the usb drive with the install. When i boot in the hard disk there come no boot

**Comment by mathsss66** [comment]
Did u fix?

**Comment by ghost** [comment]
Same issue MSI GL63 8RC

**Comment by cazlin** [comment]
Download an x86_64 arch install iso
write to usb in GPT/EFI using something like rufus
Boot iso in EFI mode. 
I had to manually select the EFI option for my usb drive in my bios to force EFI boot. (P67/2500k)

Device /dev/sda may be different for you (sdb, ect..) if you have more than one storage device.
- partition 1 is EFI boot
- partition 2 is root (btrfs)
- partition 3 is home (ext4)
```
root@archiso ~ # lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0 688.2M  1 loop /run/archiso/airootfs
sda      8:0    0 223.6G  0 disk
├─sda1   8:1    0   242M  0 part
├─sda2   8:2    0  22.1G  0 part
└─sda3   8:3    0 201.2G  0 part

root@archiso ~ # mount /dev/sda2 /mnt
root@archiso ~ # arch-chroot /mnt /bin/bash
[root@archiso /]# mount /dev/sda1 /boot/efi
[root@archiso /]# grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
Installing for x86_64-efi platform.
Installation finished. No error reported.
[root@archiso /]# exit
exit
root@archiso ~ # reboot
```
Remove your usb and boot normally. If everything worked you should now get a grub menu for SteamOS.

**Comment by forward-observations** [comment]
Just had this issue today and your steps resolved it. Thanks!

**Comment by bobdivx** [comment]
Hi all.  I created my Iso the registration was successful.  however after the reboot I do not come across the grub.  steamos does not start.  Do you have an idea please.  thank you in advance.  mathieu

**Comment by DSchndr** [comment]
Disable CSM in Bios to force uefi-only boot.
Fixed the no-boot issue on a thinkpad yoga

**Comment by orbitcorrecton** [comment]
Thanks for the help for grub-install. I finally got it boot !
