### ISSUE TITLE
Login Manager/wifi manager for new installs?

### ISSUE THREAD

**Issue by kogatoerigotsun** [holoiso-eol/holoiso#161]
This would make it easier for beginners, which I am one, and have been stuck with the error code 'Failed to start **Jupiter Controller Firmware Update Service**' for four days because I am extremely new to using grub command line as well as my wifi connection being terrible

**Comment by kogatoerigotsun** [comment]
😨

**Comment by theVakhovskeIsTaken** [comment]
> This would make it easier for beginners, which I am one, and have been stuck with the error code 'Failed to start **Jupiter Controller Firmware Update Service**' for four days because I am extremely new to using grub command line as well as my wifi connection being terrible

what are your specs?
