### ISSUE TITLE
Resolution problems

### ISSUE THREAD

**Issue by LGuilhas** [holoiso-eol/holoiso#162]
Just installed Steam OS 3.0 in an external hdd today and after a couple of initial failed boots i got it working. I now have two issues with resolution.

1) while in gaming mode sometimes the resolution gets all messed up. I see what it seems like a quater of the top left of the ui and only after rebbotinig it starts working (some times not always). Even when is 
working by pressing the menu button the menu overlay is so large that it only shows the first two options (home and library)

2) While in desktop mode the resolution is in 4K but if i change to another 16:9 res such as 1080p the image shows shrunk/squashed on the middle of the monitor with huge black bars on top and bottom.

I am attaching a few screenshots that show both issues. 
Any recommendation on how to fix these issues?

My pc has a ryzen 5 3600 and an RX5700XT

![A63E2E90-9CAD-4D7B-912D-E056B0A5B8F2](https://user-images.githubusercontent.com/28738019/169720930-05e3bdd3-9895-4c75-948f-1a23a21144e9.jpeg)
![DBED6804-BFD4-477A-BDCF-35D9FD2BF8C6](https://user-images.githubusercontent.com/28738019/169720934-db5c5650-f888-4eb0-b6c8-53f4ce8ac4e5.jpeg)
![3BDC25B0-D4EF-491B-A88C-1C16FC9224F6](https://user-images.githubusercontent.com/28738019/169720941-5994457e-9156-45a6-9277-a13c1b9f995f.jpeg)

**Comment by jazzcat007** [comment]
In order to fix Game Mode you’ll need to enter settings and enable
Developer Mode on the System tab. Then under the new Developer tab, disable
OpenGL Compositor. In my case, i couldn’t see any of these settings because
of the scaling issue. To get around this I temporary plugged into a 1080
monitor to make the changes then plugged back into my TV afterwards.

**Comment by LGuilhas** [comment]
> In order to fix Game Mode you’ll need to enter settings and enable Developer Mode on the System tab. Then under the new Developer tab, disable OpenGL Compositor. In my case, i couldn’t see any of these settings because of the scaling issue. To get around this I temporary plugged into a 1080 monitor to make the changes then plugged back into my TV afterwards.

Thanks a lot, your a life saver. I don't have a 1080p monitor so I had to get there by trial and error. To help anyone with the same problem what I did was:

1) Connect a PS4 controller
2) Press the PS logo button to show the menu
3) Press down 6 times to get to the settings menu. And then I was able to follow your recommendation and disable the OpenGL Compositor

Additionally I was also able to fix the resolution in the desktop mode by changing to a 4:3 resolution in my case 1920x1440. It doesn't make much sense but I can't complain as I now have a fully functional system.

**Comment by peterge1998** [comment]
> Additionally I was also able to fix the resolution in the desktop mode by changing to a 4:3 resolution in my case 1920x1440. It doesn't make much sense but I can't complain as I now have a fully functional system.

How did you change the resolution in desktop mode?
I have already turned off opengl, but i am facing the same problem when connected to my 4k tv...
Currently at a 1080p monitor

The only thing i could image to work ist tty2, yay nano and edit /usr/bin/gamescope-session, but is there an easier way to do that?

**Comment by LGuilhas** [comment]
> How did you change the resolution in desktop mode? I have already turned off opengl, but i am facing the same problem when connected to my 4k tv... Currently at a 1080p monitor
> 
> The only thing i could image to work ist tty2, yay nano and edit /usr/bin/gamescope-session, but is there an easier way to do that?

I was able to change mine by using the app Launcher -> Settings -> System Settings

And then on the Hardware section I can see the option Display and Monitor and change my resolution there

**Comment by peterge1998** [comment]
> I was able to change mine by using the app Launcher -> Settings -> System Settings
> 
> And then on the Hardware section I can see the option Display and Monitor and change my resolution there

U are talking about desktop mode, right?. Is it then changed for gaming too?

**Comment by peterge1998** [comment]
I tried it again with todays release and it worked! Great job! (Swapped the rx 380 for a rx 6600, but the rest of the hardware is the same)
