### ISSUE TITLE
{Fixed} No Audio Intel Onboard

### ISSUE THREAD

**Issue by utmostmick0** [holoiso-eol/holoiso#163]
Doesnt seem to detect the onboard audio for Intel i3 , shows up in lspci

Don't usually use arch so any ideas on how to fix

thanks in advance

Edit Installed sof-firmware package an now Audio device is detected , but still no sound coming from the speakers?

**Comment by utmostmick0** [comment]
Fixed it , by install the sof-firmware package and adding a file to the home directory

Create a file called ".asoundrc" in the home directory /~ 
and put the following into it

defaults.pcm.card 0
defaults.pcm.device 5
defaults.ctl.card 0

Have sound on speakers now , haven't tried headphones or HDMI yet , hope this helps anyone with the same problem

**Comment by KinSire** [comment]
Thank you for the post and problem solving. I will try this when I come home.
