### ISSUE TITLE
Cannot login to gamescope session (AMD hardware)

### ISSUE THREAD

**Issue by bsmntoid** [holoiso-eol/holoiso#167]
Specs:
M/B: MSI Gaming Edge WiFi B550
CPU: AMD Ryzen 7 5700G
GPU: AMD Radeon RX 6600
Storage: 2TB External USB hard drive
RAM: 32GB DDR4

When trying to login to the Steam Deck UI (gamescope), it displays this error
`Starting version 250.3-1-arch`
`[FAILED] Failed to start Jupiter BIOS Update Service`
then simply kicks me back to the default SDDM login.
KDE works fine. `gamescope-session` works fine.

Any logs I need to attach?

**Comment by theVakhovskeIsTaken** [comment]
This is strange. Can you reinstall new version of ISO?

**Comment by tym2liv3** [comment]
I have exactly the same issue

**Comment by TomiSi12** [comment]
i too
but with intel

**Comment by bsmntoid** [comment]
> Can you reinstall new version of ISO?

That fixed it!

Edit: I lie. Gets past errors but then gets stuck on black screen.

**Comment by theVakhovskeIsTaken** [comment]
> > Can you reinstall new version of ISO?
> 
> That fixed it!
> 
> Edit: I lie. Gets past errors but then gets stuck on black screen.

now that's really strange. Can you boot into recovery mode and disable sessions, then manually log in?

**Comment by bsmntoid** [comment]
_now_ it loops back to the sddm login screen, this time no error? very weird indeed.

Edit: gamescope-session has stopped working too. I'll attach the output in a minute

**Comment by bsmntoid** [comment]
```
!! Failed to claim global gamescope stats session
MANGOAPP LAYER: Init
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
vulkan: selecting physical device 'AMD RADV RENOIR'
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55feeba866e0 (res 0x55feeae6b270)
wlserver: [xwayland/server.c:250] Xserver is ready
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :2
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55feeba91bd0 (res 0x55feeba8a690)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 87
/usr/bin/gamescope-session: line 181: xbindkeys: command not found
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
[2022-05-24 08:25:59.849] [info] [config.cpp:117] parsing config: '/tmp/mangohud.ptlO7GTw'
[2022-05-24 08:25:59.869] [error] [cpu.cpp:450] Could not find cpu temp sensor location
[2022-05-24 08:25:59.869] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card0-HDMI-A-1/device/hwmon/': No such file or directory
[2022-05-24 08:25:59.869] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card1-DP-4/device/hwmon/': No such file or directory
[2022-05-24 08:25:59.870] [info] [overlay.cpp:733] Uploading is disabled (permit_upload = 0)
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
(EE) failed to read Wayland events: Connection reset by peer
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
```
After this it just keeps repeating `power-button-handler.py: Can't find device for power button!`

**Comment by theVakhovskeIsTaken** [comment]
> ```
> !! Failed to claim global gamescope stats session
> MANGOAPP LAYER: Init
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> vulkan: selecting physical device 'AMD RADV RENOIR'
> vulkan: physical device supports DRM format modifiers
> vulkan: supported DRM formats for sampling usage:
> vulkan:   0x34325241
> vulkan:   0x34325258
> vulkan:   0x3231564E
> wlserver: [backend/headless/backend.c:82] Creating headless backend
> wlserver: Running compositor on wayland display 'gamescope-0'
> wlserver: [backend/headless/backend.c:18] Starting headless backend
> wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
> wlserver: [xwayland/server.c:92] Starting Xwayland on :1
> wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55feeba866e0 (res 0x55feeae6b270)
> wlserver: [xwayland/server.c:250] Xserver is ready
> wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
> wlserver: [xwayland/server.c:92] Starting Xwayland on :2
> wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55feeba91bd0 (res 0x55feeba8a690)
> wlserver: [xwayland/server.c:250] Xserver is ready
> pipewire: stream state changed: connecting
> pipewire: stream state changed: paused
> pipewire: stream available on node ID: 87
> /usr/bin/gamescope-session: line 181: xbindkeys: command not found
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> [2022-05-24 08:25:59.849] [info] [config.cpp:117] parsing config: '/tmp/mangohud.ptlO7GTw'
> [2022-05-24 08:25:59.869] [error] [cpu.cpp:450] Could not find cpu temp sensor location
> [2022-05-24 08:25:59.869] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card0-HDMI-A-1/device/hwmon/': No such file or directory
> [2022-05-24 08:25:59.869] [error] [file_utils.cpp:43] Error opening directory '/sys/class/drm/card1-DP-4/device/hwmon/': No such file or directory
> [2022-05-24 08:25:59.870] [info] [overlay.cpp:733] Uploading is disabled (permit_upload = 0)
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> (EE) failed to read Wayland events: Connection reset by peer
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> power-button-handler.py: Can't find device for power button!
> ```
> After this it just keeps repeating `power-button-handler.py: Can't find device for power button!`

So, it tries to use iGPU. Can you disable it?

**Comment by bsmntoid** [comment]
> Can you disable it?

I'll do some research and try to find a way to disable the iGPU. Thanks!

**Comment by bsmntoid** [comment]
Aye, found a solution. `VULKAN_DEVICE_INDEX` might fix it. I'll give it a shot and return with the details.

**Comment by bsmntoid** [comment]
That didn't fix it, but after adding an extra line to /usr/share/libdrm/amdgpu.ids, Vulkan now recognises and tries to use my 6600. The output is much shorter and seems much easier to debug.
```
$ gamescope-session 
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
MANGOAPP LAYER: Init
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 6600'
vulkan: physical device does not support DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
Failed to initialize Vulkan
/usr/bin/gamescope-session: line 175: kill: (11099) - No such process
```

**Comment by theVakhovskeIsTaken** [comment]
> That didn't fix it, but after adding an extra line to /usr/share/libdrm/amdgpu.ids, Vulkan now recognises and tries to use my 6600. The output is much shorter and seems much easier to debug.
> ```
> $ gamescope-session 
> Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
> MANGOAPP LAYER: Init
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> vulkan: selecting physical device 'AMD Radeon RX 6600'
> vulkan: physical device does not support DRM format modifiers
> vulkan: vkAllocateDescriptorSets failed
> Failed to initialize Vulkan
> /usr/bin/gamescope-session: line 175: kill: (11099) - No such process
> ```
> 

DRM isn't working properly because - wayland is being initialized on iGPU.
Disable it in UEFI, or either plug in your HDMI cable into motherboard

**Comment by bsmntoid** [comment]
Nope; just disabled iGPU in UEFI a few minutes ago -- Same error, except now the iGPU doesn't show up in glxinfo or vulkaninfo

**Comment by bsmntoid** [comment]
Is the issue that i'm using displayport?

**Comment by theVakhovskeIsTaken** [comment]
> Is the issue that i'm using displayport?

You can remove `eDP-1` in /usr/bin/gamescope-session and try to load, but i highly doubt that's the reason

**Comment by Chaphasilor** [comment]
> ```
> $ gamescope-session 
> Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
> MANGOAPP LAYER: Init
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
> vulkan: selecting physical device 'AMD Radeon RX 6600'
> vulkan: physical device does not support DRM format modifiers
> vulkan: vkAllocateDescriptorSets failed
> Failed to initialize Vulkan
> /usr/bin/gamescope-session: line 175: kill: (11099) - No such process
> ```
> 

I'm on an AMD Ryzen 5600G (B450) and a GTX 970, and got into DE without gamescope after working my way through #198.
When running `gamescope-session` from DE, I get a very similar output:

```sh-session
$ gamescope-session 
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
MANGOAPP LAYER: Init
vulkan: selecting physical device 'NVIDIA GTX 970'
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -1000174001)
Failed to initialize Vulkan
/usr/bin/gamescope-session: line 175: kill: (9139) - No such process
```

Any ideas?

**Edit:** Shortly after commenting I got an update notification for the latest snapshot. After installing and restarting, the output changed to this:

```sh-session
$ gamescope-session
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
MANGOAPP LAYER: Init
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
vulkan: selecting physical device 'AMD RADV RENOIR'
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
vulkan: physical device queue doesn't support presenting on our surface
vulkan_make_output failed
/usr/bin/gamescope-session: line 175: kill: (7729) - No such process
```
`System Settings > About this System` still shows `NVIDIA GTX 970` as my graphics processor...

**Comment by bsmntoid** [comment]
Looks like Snapshot 5 may have fixed it! Finally, PC couch gaming at its finest.

**Comment by theVakhovskeIsTaken** [comment]
> Looks like Snapshot 5 may have fixed it! Finally, PC couch gaming at its finest.

Great to see that it fixed!

**Comment by freddyguythe10th** [comment]
Snapshot 5 actually broke it for me. It worked fine before. I'm getting the same issue as everyone else here, but I'm using an intel processor and intel graphics.
