### ISSUE TITLE
Giving HoloIso the 'Bethesda Design Philosophy'

### ISSUE THREAD

**Issue by kogatoerigotsun** [holoiso-eol/holoiso#168]
I think that holoiso would benefit from being like Todd the Godd Howard's philosophy of things just working. @theVakhovskeIsTaken (just some humour to get me off the fact i've been stuck on the same screen for a week, but I do think that there rings some truth to Todd Howard's philosophy on software design.)

**Comment by kogatoerigotsun** [comment]
I am practically new to booting Linux operating systems, so I don't really get the various solutions to the wifi issue i have been having. I might say 'screw it' and buy a really long network cable and an antennae just to connect my pc to the internet in a way that Arch linux understands out of the box

**Comment by theVakhovskeIsTaken** [comment]
?????????????????????????????????????????????????????????????????????????????????
