### ISSUE TITLE
SteamDeck UI not scaling correctly

### ISSUE THREAD

**Issue by jayp76** [holoiso-eol/holoiso#172]
I am on latest version 20220522_1750 and the SteamDeck UI does not scale corretly. Much of the screen is missing. No problems on Linux Desktop though. Also the Games scale corretly, just SteamDeck UI does not.

I have a 29 inch Monitor with 21:9 resolution 2560x1080.
As GPU i have a Vega64.
![IMG_20220523_140503](https://user-images.githubusercontent.com/10572247/169825745-8310ac1f-eefc-4f98-9bb3-cce7cc0f3953.jpg)

![IMG_20220523_140537](https://user-images.githubusercontent.com/10572247/169825762-df2bf72e-4224-42ee-a396-7f40b5886442.jpg)

**Comment by NanoSpace-code** [comment]
I've been seeing this issue in general on the actual Deck when plugging into a monitor with a usb c hub. Not sure if relevant, it usually went away after awhile, but I thought it would be worth mentioning.

**Comment by tym2liv3** [comment]
So to solve this one enable developer mode in system menu. Then go in to the new developer menu and disable the open gl compositor

**Comment by jayp76** [comment]
Thank you, this seems to help.

**Comment by jayp76** [comment]
Problem was solved with workaround and already discussed in other issue.
