### ISSUE TITLE
Error message "Failed to start Jupiter BIOS Update service"

### ISSUE THREAD

**Issue by TheRealXyzven** [holoiso-eol/holoiso#173]
I manage to get to the login manager using the "booster initramfs" options but I cannot get past the login manager if the session is in "SteamOS gamescope".  Changing the session to Plasma X11 works and I could log into steam but I still cannoet into gamescope.

It keeps popping up with the error message and then brings me back to the login manager.  I can log into the console from tty2/3/4 with no issues so I know the OS is running fine.

Running on an intel NUC i3-4010u with 8GB ram and a 32 gb innodisk mSATA.

**Comment by theVakhovskeIsTaken** [comment]
Install new version, it has choice to install Intel gamescope

**Comment by TheRealXyzven** [comment]
> Install new version, it has choice to install Intel gamescope

used the lastest snapshot from https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220522.1905 and can confirm now that I cannot even get into the login manager.  

Non-booster options: keyboard hard locks, and I have to hard reset.
Booster options: seems to load with HDD light flashing but I cannot tty into other sessions or see any activity.
Recovery mode: Works (thank goodness) so let me know if you need log entries.

I will try the booster options with a longer wait (~30 minutes) to see if that helps/works.

EDIT: CONFIRMED that the "booster" options do not work either after 30+ minutes of running.  I will be trying my Xeon server shortly (it's my retro gaming rig) and will report back in a new post to this ticket.

**Comment by matthew42904** [comment]
I’m having this error on all of my pc’s. I have tried intel and amd laptops. I would try desktops but I don’t any amd desktops

**Comment by ghost** [comment]
> I’m having this error on all of my pc’s. I have tried intel and amd laptops. I would try desktops but I don’t any amd desktops

Apparently @theVakhovskeIsTaken said that its not suitable for laptops gpus mostly.
Would be awesome if it would though.

**Comment by TheRealXyzven** [comment]
> > I’m having this error on all of my pc’s. I have tried intel and amd laptops. I would try desktops but I don’t any amd desktops
> 
> Apparently @theVakhovskeIsTaken said that its not suitable for laptops gpus mostly. Would be awesome if it would though.

Could you provide the link to where he says that?  Arch is a versatile OS and although I can agree that GAMING maybe limited on onboard GPU or laptop APUs / cpu/gpu combo, I highly doubt running a DE should be not supported or suitable.  At least not for anything resonably modern 2010+ with at least 4GB or ram.

**Comment by TheRealXyzven** [comment]
> Install new version, it has choice to install Intel gamescope

I can confirm that this also doesn't work on in AMD or Intel version on my Xeon E3-1240 v3 server that is my "retro gaming" rig.  I have tried changing video cards, and using onboard video with no success.

**Comment by ghost** [comment]
> > Install new version, it has choice to install Intel gamescope
> 
> I can confirm that this also doesn't work on in AMD or Intel version on my Xeon E3-1240 v3 server that is my "retro gaming" rig. I have tried changing video cards, and using onboard video with no success.

Read the readme again they updated the prerequisites there.

**Comment by TheRealXyzven** [comment]
Closing this issue as none of my systems meet the prerequisites.  Thanks @MojoJojoDojo.

Keep up the good work @theVakhovskeIsTaken
