### ISSUE TITLE
After install. At loading in steam os after "ramdisk" there comes black screen

### ISSUE THREAD

**Issue by TomiSi12** [holoiso-eol/holoiso#175]
When i boot in Steam os there loading intial ramdisk and then it comes black screen and nothing happened

**Comment by theVakhovskeIsTaken** [comment]
Sure. What's your specs? Reboot to "Recovery mode" under advanced options and type `holoiso-disable-sessions`

**Comment by ghost** [comment]
Same thing here.
Installing on a laptop that uses both an AMD/Intel GPUs (Intel UHD 620/Radeon 530).
Using the "Intel" option and not the "AMD only" option
Not using gamescope and using Plasma instead works though.

**Comment by theVakhovskeIsTaken** [comment]
> Same thing here.
> Installing on a laptop that uses both an AMD/Intel GPUs (Intel UHD 620/Radeon 530).
> Using the "Intel" option and not the "AMD only" option
> Not using gamescope and using Plasma instead works though.

Your Radeon GPU isn't supported. You need to disable it, downgrade gamescope and keep using Intel iGPU if you want gamemode support

**Comment by ghost** [comment]
> > Same thing here.
> > Installing on a laptop that uses both an AMD/Intel GPUs (Intel UHD 620/Radeon 530).
> > Using the "Intel" option and not the "AMD only" option
> > Not using gamescope and using Plasma instead works though.
> 
> Your Radeon GPU isn't supported. You need to disable it, downgrade gamescope and keep using Intel iGPU if you want gamemode support

But it uses the Intel GPU by default anyway because its a laptop lol.
Gamescope is also downgraded already and so is Mesa by using the Intel option when installing.

**Comment by ghost** [comment]
Also the readme says this:
`AMD GPU with Vulkan and VDPAU support`
Which fits with my AMD GPU still.
So maybe you wanna be more specific.

**Comment by theVakhovskeIsTaken** [comment]
> Also the readme says this:
> `AMD GPU with Vulkan and VDPAU support`
> Which fits with my AMD GPU still.
> So maybe you wanna be more specific.

Yeah, right, it's kinda unspecific, maybe that's why there's alot of unsupported comments

**Comment by TomiSi12** [comment]
> Sure. What's your specs? Reboot to "Recovery mode" under advanced options and type `holoiso-disable-sessions`

i have written this there and have exit it. I am on the log in screen, but when i try to log in then it is black and come to the same screen.

pc:
Intel xeon e3 12345 
Thinkserver ts130

**Comment by TomiSi12** [comment]
> > Sure. What's your specs? Reboot to "Recovery mode" under advanced options and type `holoiso-disable-sessions`
> 
> i have written this there and have exit it. I am on the log in screen, but when i try to log in then it is black and come to the same screen.
> 
> pc: Intel xeon e3 12345 Thinkserver ts130

also on plasma i come in buty steam os there is that what i have said before

**Comment by Betaminos** [comment]
Hey there, I am facing the same issue (shows GRUB menu, afterwards black screen)

> Sure. What's your specs? Reboot to "Recovery mode" under advanced options and type `holoiso-disable-sessions`

Having run the script shows the login screen after GRUB, but trying to login (with SteamOS gamescope selected) results in a black screen and kicks me back to the login a few seconds later.

I am running an OneXPlayer, powered by an Intel 1165g/ (Intel Xe).
My installation is the full / deckexperience and Intel GPU, running this ISO: https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1

**Comment by mooock** [comment]
Be aware that having more output then just the display port, can result in another output getting used, i removed all my hdmi cables and got rid of the black screen.

**Comment by Betaminos** [comment]
> Be aware that having more output then just the display port, can result in another output getting used, i removed all my hdmi cables and got rid of the black screen.

Good idea. However, I am testing on a mobile device with only one screen and nothing plugged in or attached. As it kicks me back to the login screen, I am assuming that it gets stuck on / crashes somewhere else.

**Comment by mooock** [comment]
> > Be aware that having more output then just the display port, can result in another output getting used, i removed all my hdmi cables and got rid of the black screen.
> 
> Good idea. However, I am testing on a mobile device with only one screen and nothing plugged in or attached. As it kicks me back to the login screen, I am assuming that it gets stuck on / crashes somewhere else.

I think there is a issue with the current build, and some vulcan. it started out in this thread https://github.com/theVakhovskeIsTaken/holoiso/issues/198#

**Comment by nexus-c1** [comment]
> > > Same thing here.
> > > Installing on a laptop that uses both an AMD/Intel GPUs (Intel UHD 620/Radeon 530).
> > > Using the "Intel" option and not the "AMD only" option
> > > Not using gamescope and using Plasma instead works though.
> > 
> > 
> > Your Radeon GPU isn't supported. You need to disable it, downgrade gamescope and keep using Intel iGPU if you want gamemode support
> 
> But it uses the Intel GPU by default anyway because its a laptop lol. Gamescope is also downgraded already and so is Mesa by using the Intel option when installing.

@theVakhovskeIsTaken So, how to downgrade gamescope? I could not find the older version of the `holoiso-gamescope` package. Only `gamescope`. Installed `vulkan-intel` and `lib32-vulkan-intel`.
