### ISSUE TITLE
Resolution Problems using holoiso

### ISSUE THREAD

**Issue by peterge1998** [holoiso-eol/holoiso#176]
Hey, this is a great project. Let me describe the problem I am facing with it:
My pc running holoiso has a 1600x and a r9 380x. I have a monitor with 1080p connected to it, during installation and want to use an OLED LG 4k TV. BUT it's HDMI, if I see a picture on my 1080p monitor and connect it back to TV it's in a crappy little resolution. If I switch to desktop mode, the screen goes black and neither the TV nor the monitor displays anything. Even if I restart the pc, it's still black, and I have to reinstall.
I changed "-W 1280 -H 800" to "-W 3840 -H 2160". After rebooting and using HDMI, it's gone and everything is black when I switch to desktop mode again.
The default is "-w 1280 -h 800". Does it matter if it's -W or -w?
Is changing DP to HDMI the problem I am facing?
What else could be the problem? I have OpenGL turned off in developer settings.

**Comment by aleksasiriski** [comment]
Yes, there is a difference with -w and -W as well as -h and -H.

https://github.com/Plagman/gamescope

>` -W, -H`: set the resolution used by gamescope. Resizing the gamescope window will update these settings. Ignored in embedded mode. If `-H` is specified but `-W` isn't, a 16:9 aspect ratio is assumed. Defaults to 1280×720.

> `-w, -h`: set the resolution used by the game. If `-h` is specified but `-w` isn't, a 16:9 aspect ratio is assumed.

I believe the default is lower case, so leave it at that and just change 1280 and 800 to 3840 and 2160. It works for me for 1920 and 1080.

**Comment by peterge1998** [comment]
Okay, good to know. Yes default is lower case. I need a reboot to apply correct? Or is something like systemctl restart gamescope enough?

As note for myself:
Go into Gaming Mode. 
Push ESC. 
Click Settings. 
Under System flip on the Dev Mode toggle. 
Scroll to the bottom of the main left menu and you’ll now have a Developer tab. 
Flip the switch off for Open GL Compositor.

**Comment by theVakhovskeIsTaken** [comment]
> Okay, good to know. Yes default is lower case. I need a reboot to apply correct? Or is something like systemctl restart gamescope enough?

It's enough to just switch sessions.
