### ISSUE TITLE
Intel CPU KDE plasma is working but steamos (gamescope) doesn't work

### ISSUE THREAD

**Issue by TomiSi12** [holoiso-eol/holoiso#178]
When i try log in steamos then it comes 1 second black screen and then i load the same log in screen

My pc
ThinkServer Ts130
cpu: intel xeon e3 12345

**Comment by theVakhovskeIsTaken** [comment]
> When i try log in steamos then it comes 1 second black screen and then i load the same log in screen
> 
> My pc
> ThinkServer Ts130
> cpu: intel xeon e3 12345

...what is your gpu??? And what is your CPU, because that isn't the model

**Comment by TomiSi12** [comment]
> 

Graphics Processor: Mesa DRI Intel HD Graphics 2000
Processor Intel Xeon E31235 with 3.20GHZ

**Comment by theVakhovskeIsTaken** [comment]
> > 
> 
> Graphics Processor: Mesa DRI Intel HD Graphics 2000
> Processor Intel Xeon E31235 with 3.20GHZ

Your GPU is not supported.
