### ISSUE TITLE
Failed to start Jupiter BIOS Update Service (AMD mobile 7xxx GPU)

### ISSUE THREAD

**Issue by Krak99** [holoiso-eol/holoiso#184]
Assume this might be because I'm running a mobile HD 7730M AMD GPU (even though it does support Vulcan and VDPAU as far as I can tell)? If so, would be worth making it clear in the pre-requisites that not all AMD GPUs (especially mobile variants) are supported in the current release.

**Comment by theVakhovskeIsTaken** [comment]
Your GPU is unsupported.
It requires RX-era GFX.

**Comment by Krak99** [comment]
@theVakhovskeIsTaken ... Thanks for clarification
