### ISSUE TITLE
R9 290x

### ISSUE THREAD

**Issue by Salazaar1000** [holoiso-eol/holoiso#185]
Was having real difficulties getting this running on an r9 290x until I read the following articles:

https://bbs.archlinux.org/viewtopic.php?id=274737

https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

Figured out how to install nano, followed the instructions, rebooted a few times and all working now!

**Comment by theVakhovskeIsTaken** [comment]
That's..... Incredible? So like, gamescope works fine?

**Comment by Salazaar1000** [comment]
It did... for about half an hour. Installed and ran Lego Star Wars, restarted once or twice. Then fully powered down and it didn't work again.

Damned if I can figure out what happened!

**Comment by Salazaar1000** [comment]
Okay, so it's now is a state where with some reliability I can boot the system and get the following error:

`[FAILED] Failed to start Jupiter BIOS Update Service` 

So, CTRL+ALT+F4, log in, run `gamescope-session` and it starts and runs fine.

![PXL_20220524_221906371](https://user-images.githubusercontent.com/106034139/170135378-64b351e6-4ac2-42e5-b41d-81a056e0901f.jpg)!

Wish I knew how to get it to just 'boot' again, though.

**Comment by Roman9365** [comment]
> 

Hey @Salazaar1000 , thanks for sharing, I'm new at arch linux, could you please describe what exactly needs to be done?
I was trying to follow these articles, but with no luck...Please :)

**Comment by LightRO** [comment]
I have a R9 390X Tri-X and have almost the same roblem except for one thing: when I want to start gamescope-session, it reports that all files are missing. I have now loaded the OS 3 times on 2 different sticks and installed each time on a different HDD. 

First the bootloader is missing and then also the GUI. Yes my PC has UEFI and it generally works great :D

**Comment by MCarey2** [comment]
> > 
> 
> Hey @Salazaar1000 , thanks for sharing, I'm new at arch linux, could you please describe what exactly needs to be done? I was trying to follow these articles, but with no luck...Please :)

I just spent hours today figuring out how do get this to work, i am a complete linux noob and this is a niche problem so here are exactly the steps i followed to get my r9 290X working with holoiso as i would have killed to have this info earlier today :)

1. Install HoloIso - the exact version i used [HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso]
2. Once installation is complete do not shut down, stay in the installer on the USB/boot media and click "Chroot to valid HoloISO installation" shortcut on desktop.
3. In the console that appears, type the following:
`vim /etc/modprobe.d/amdgpu.conf`
this will create a new config text file and open it in vim a text editor
5. press the 'I' key to insert text into the text file and add these two lines:
`options amdgpu si_support=1`
`options amdgpu cik_support=1`
7. press escape and then the ':' key and type `write!` then hit enter, then the ':' key again then type `qa!` and enter, this will save and close vim.
8. Back in the console, type the following:
`vim /etc/modprobe.d/radeon.conf`
9. press the 'I' key to insert text into the text file and add these three lines:
`options radeon si_support=0`
`options radeon cik_support=0`
`blacklist radeon`
10. Follow step 7 again to save and close.
11. Shut down and boot into HoloISO, and pray it works.
