### ISSUE TITLE
Hung tasks when rebooting system, must hard power off

### ISSUE THREAD

**Issue by jayp76** [holoiso-eol/holoiso#186]
In Lord Gaben's release, tasks are hanging indefinetely when rebooting the system.
System specs: Ryzen3800x, 32GB, B550, Vega64

![1653462235945](https://user-images.githubusercontent.com/10572247/170201390-dc612561-2d03-4359-9649-64b84b667967.jpg)

**Comment by theVakhovskeIsTaken** [comment]
That isn't a bug, welcome to systemd task handling!

**Comment by jayp76** [comment]
Any tip how to circumvent this, i did not find anythiong useful when searching for hung task.

**Comment by ghost** [comment]
Have a look at Arch wiki about SystemD
