### ISSUE TITLE
Does holoISO works with R7 360?

### ISSUE THREAD

**Issue by lazydevyo** [holoiso-eol/holoiso#188]
Looking to buy a used GPU to create a steam os 3 build as a side project. I found r7 360 and 260x, but I'm not sure what are the requirements for AMD GPUs

**Comment by calroth** [comment]
I have successfully run HoloISO on a PC with a Radeon R7 260X.

Note that by default it uses the "radeon" driver, which is stable but does not support Vulkan. You need to switch it to the "amdgpu" driver. For my Radeon R7 260X I added `radeon.cik_support=0 amdgpu.cik_support=1 amdgpu.dc=1` to my kernel parameters. You may also add the equivalent to `/etc/modprobe.d/amdgpu.conf` if you prefer. You'll know it works when you can run `vkcube` from a command line.

More info: https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

**Comment by lazydevyo** [comment]
> I have successfully run HoloISO on a PC with a Radeon R7 260X.
> 
> Note that by default it uses the "radeon" driver, which is stable but does not support Vulkan. You need to switch it to the "amdgpu" driver. For my Radeon R7 260X I added `radeon.cik_support=0 amdgpu.cik_support=1 amdgpu.dc=1` to my kernel parameters. You may also add the equivalent to `/etc/modprobe.d/amdgpu.conf` if you prefer. You'll know it works when you can run `vkcube` from a command line.
> 
> More info: https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

How is the experience so far with the r7 260x? like playing games and stability overall etc.

**Comment by calroth** [comment]
> How is the experience so far with the r7 260x? like playing games and stability overall etc.

It seems fine. Haven't tried many games. Performance seems about the same as Windows (so, not excellent for anything modern, remember this is a mid-range card from 2013). Stability is OK for me. Note that due to the age of the hardware, you might be buying something that works 100%, or you may get something that's months away from failing... also note that SteamOS in general and HoloISO in particular is quite experimental.

**Comment by Roman9365** [comment]
> I have successfully run HoloISO on a PC with a Radeon R7 260X.
> 
> Note that by default it uses the "radeon" driver, which is stable but does not support Vulkan. You need to switch it to the "amdgpu" driver. For my Radeon R7 260X I added `radeon.cik_support=0 amdgpu.cik_support=1 amdgpu.dc=1` to my kernel parameters. You may also add the equivalent to `/etc/modprobe.d/amdgpu.conf` if you prefer. You'll know it works when you can run `vkcube` from a command line.
> 
> More info: https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

Hey @calroth, thanks for sharing this information, could you please describe in details how did you have kernel parameters? How did you create amdgpu.conf file. Im new in Linux and im struggling with this driver setting up. I have r9 m470x GPU (i did amdgpu working in batocera, but not for holoiso)

**Comment by calroth** [comment]
> Hey @calroth, thanks for sharing this information, could you please describe in details how did you have kernel parameters? How did you create amdgpu.conf file. Im new in Linux and im struggling with this driver setting up. I have r9 m470x GPU (i did amdgpu working in batocera, but not for holoiso)

I'm sorry, I'm not set up to provide support for this.

My suggestion is, install a standard Arch Linux version, and a standard Steam installation. For support, use the Arch Linux wiki and support channels. Then once you get it working and stable, try HoloISO again.
