### ISSUE TITLE
Grub SteamOS Boot Entry defaults to neptune rather than linux-core

### ISSUE THREAD

**Issue by IBNobody** [holoiso-eol/holoiso#189]
When I installed holoiso onto a VM, I chose linux-core (the default boot option on the ISO). When I went to boot after installation, I got an error.

![image](https://user-images.githubusercontent.com/5863888/170327717-a470f25f-abc9-49bf-a4f4-bfc208c8cd5d.png)

I found that the issue was that the Grub config defaulted to booting from linux-neptune-dri rather than what I had installed.

![image](https://user-images.githubusercontent.com/5863888/170327932-25f5ba67-00f3-4130-a4bf-7bfcc86d7bd5.png)

**Comment by theVakhovskeIsTaken** [comment]
> When I installed holoiso onto a VM, I chose linux-core (the default boot option on the ISO). When I went to boot after installation, I got an error.
> 
> ![image](https://user-images.githubusercontent.com/5863888/170327717-a470f25f-abc9-49bf-a4f4-bfc208c8cd5d.png)
> 
> I found that the issue was that the Grub config defaulted to booting from linux-neptune-dri rather than what I had installed.
> 
> ![image](https://user-images.githubusercontent.com/5863888/170327932-25f5ba67-00f3-4130-a4bf-7bfcc86d7bd5.png)

Note 1: No VM support.

**Comment by IBNobody** [comment]
That's unfortunate. The reason why I wanted to run this in a VM was because I need a build environment for SteamOS applications, and Valve doesn't ship the headers for stuff like glibc on the native Steam Deck image. So my only options here are to tamper with my SD's install (not gonna happen) or run this out of a VM.

**Comment by theVakhovskeIsTaken** [comment]
On other note, It boots fine in VMWare with neptune kernel

**Comment by IBNobody** [comment]
This bug is not that my installed image can't boot, it's that I installed it with the Linux-core option and that the default boot option ended up being Neptune rather than Linux-core. The final Grub config should be set up to match that initial setup choice.

**Comment by tildebyte** [comment]
Same issue, **bare metal**, ASUS GL504GW.

Boots fine using NV DRI driver and external monitor via HDMI, but boots to 'linux-neptune-dri' instead of expected holo

EDIT: Used "ISOR1" tagged release ISO for install
