### ISSUE TITLE
GPU power

### ISSUE THREAD

**Issue by rbrugnolli** [holoiso-eol/holoiso#19]
Is there any place that I can configure the power of the gpu, because on my desktop it is no more than 18w limiting the frequency to 400 mhz, and the game is unplayable.

**Comment by rbrugnolli** [comment]
Look at some captures.
I installed RC but still the same thing.
[https://www.dropbox.com/s/waqia4qd4rwrvba/IMG_4546.HEIC?dl=0](url)
[https://www.dropbox.com/s/6n31zwd4aj9oivq/IMG_4547.HEIC?dl=0](url)
[https://www.dropbox.com/s/7l8z1av0eymtoj9/IMG_4548.HEIC?dl=0](url)

**Comment by massatt212** [comment]
with my rx 470 i get 100% gpu usage game at 21fps to 40fps and max wattage 35
