### ISSUE TITLE
I have tried the iso image in both VMware workstation 16.2.3 and VirtualBox 6.1.34 but it detects no bootable media

### ISSUE THREAD

**Issue by enderpirate98** [holoiso-eol/holoiso#190]

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/blob/3.0/README.md
Have fun.

**Comment by deftdawg** [comment]
@enderpirate98 need to set your System to `Boot UEFI`... see https://github.com/theVakhovskeIsTaken/holoiso/issues/27#issuecomment-1157225513

**Comment by enderpirate98** [comment]
It is set to uefi from day 1.

**Comment by deftdawg** [comment]
In that case I'd recommend double checking your iso file isn't corrupted.  You can see from my screenshots on that comment that it does work with Virtualbox.
