### ISSUE TITLE
Text appearing over gamescope session

### ISSUE THREAD

**Issue by Mrpuppyz** [holoiso-eol/holoiso#191]
So I have an issue with some text showing up on my gamescope session. It is not present when a game is started and doesn't show up on desktop mode. I think the text showed up when I enabled a wwan card for Internet. This PC has a Reyzen 5700x and a RX 6700. Any recommendations I can try to get this text to go away? 

![20220525_161758.jpg](https://user-images.githubusercontent.com/103858972/170384852-77edec12-886a-4ee7-b16d-6a6a11f6d32b.jpg)![20220525_161805.jpg](https://user-images.githubusercontent.com/103858972/170384862-e8f0fb38-5582-49d7-bef1-adbc47682cbd.jpg)![20220525_161813.jpg](https://user-images.githubusercontent.com/103858972/170384870-57b5bf30-c7bc-4762-8466-741f464f0b27.jpg)![20220525_161817.jpg](https://user-images.githubusercontent.com/103858972/170384875-8987ce18-c013-461c-94cf-8a61ab5f9272.jpg)

**Comment by theVakhovskeIsTaken** [comment]
It's Steam client being bugged. Wait for next steam update, or force it to unpack runtime by deleting `.local/share/Steam`. Note that this will erase all of your games.

**Comment by Mrpuppyz** [comment]
The steam update did not fix this problem like you predicted. Can you please reopen this issue.
