### ISSUE TITLE
Distorted audio in DeckUI mode, in game only

### ISSUE THREAD

**Issue by klandrith** [holoiso-eol/holoiso#192]
Hello,
First off, thanks for the iso and the work to all who have contributed.

Now, to the issue. Audio, in game only, in the DeckUI mode is distorted, like it is playing the sound too fast. Audio in DeckUI itself appears to work fine. As does sound in Desktop mode, both in game and on the desktop.

Specs...

Asus B560M Wifi Mobo
i5 11400F
MSI OC RX 580 8GB
Connected to a 4k TV via HDMI.

**Comment by klandrith** [comment]
After applying the "fix" mentioned in [https://github.com/theVakhovskeIsTaken/holoiso/issues/123](url) it seemed to work since then and persist.

**Comment by afritsch89** [comment]
> After applying the "fix" mentioned in [https://github.com/theVakhovskeIsTaken/holoiso/issues/123](url) it seemed to work since then and persist.
@klandrith 
I hate necro-ing tickets, but I have to know... Jazzcat's fix or the kernel fix? I'm still having issues with this.

**Comment by klandrith** [comment]
> > After applying the "fix" mentioned in [https://github.com/theVakhovskeIsTaken/holoiso/issues/123](url) it seemed to work since then and persist.
> > @klandrith
> > I hate necro-ing tickets, but I have to know... Jazzcat's fix or the kernel fix? I'm still having issues with this.

Honestly, at this point I do not remember. Sorry I can't be of more help...
