### ISSUE TITLE
Boot using proxmox 7.x

### ISSUE THREAD

**Issue by andzejsp** [holoiso-eol/holoiso#197]
Is there a way to boot into the iso using VM in proxmox? Once i launch my VM it says cant find boot devices. Maybe there is a way to flash an ISO with rufus. Not to confuse with flash USB. I need an ISO i can feed into proxmox to install it on VM. Please !

**Comment by theVakhovskeIsTaken** [comment]
Note 1: No VM support
Note 2: If you use VM do it with GPU passthru and UEFI (edk2-ovmf)
