### ISSUE TITLE
ISO doesn't boot with Ventoy/Rufus

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [holoiso-eol/holoiso#2]
This is known, because those clients use `vmlinuz-linux` as their hardcoded path to mount images and boot.

Current workaround: Use BalenaEtcher

Rufus-written instance won't ever see the option to boot with Neptune kernel

Ventoy on other hand, has the bootoption, but the rootfs fails to mount.

The solution for this would be shipping a pacman.d hook to rename linux-neptune into linux temporarily, or shipping core/linux in the ISO itself

**Comment by gelson-zord** [comment]
Interesting, before Boop (stable) ISO, I could boot it up on VM, now I can't boot any ISO, even the olders one. How is this possible?
