### ISSUE TITLE
mt7921e driver

### ISSUE THREAD

**Issue by arcatva** [holoiso-eol/holoiso#201]
Hi,

Just found a workaround for fixing the mt7921e driver issue for PCIe ID 0x0608 NIC.
Adding `alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e`   in  `/etc/modprobe.d/mt7921e.conf`

Of cause we can wait for upstream kernel update the driver but adding modprobe.d conf is also a temporary fix for it.

FYI: https://askubuntu.com/questions/1380400/no-wifi-adapter-found-on-ubuntu-20-04-3-lts

**Comment by theVakhovskeIsTaken** [comment]
> Hi,
> 
> Just found a workaround for fixing the mt7921e driver issue for PCIe ID 0x0608 NIC.
> Adding `alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e`   in  `/etc/modprobe.d/mt7921e.conf`
> 
> Of cause we can wait for upstream kernel update the driver but adding modprobe.d conf is also a temporary fix for it.
> 
> FYI: https://askubuntu.com/questions/1380400/no-wifi-adapter-found-on-ubuntu-20-04-3-lts

Does this work?
If yes, then i can push this later

**Comment by arcatva** [comment]
Sorry unable to test it as installing holoiso or archlinux requires network.... Without installation I can only run liveCD under ramdisk... Modifying modprobe.d is not going to be saved after reboot... I was stuck in this logical loop🥲. Nevertheless, this modification is definitely harmless as current 0x0608e is not using any driver.

**Comment by huchenghe001** [comment]
I am RZ608, the onexplayer mini 5800u of the gas collection chamber cannot restart after inputting the command

**Comment by arcatva** [comment]
> 

You mean you stuck on boot or? Any error message for it?

**Comment by arcatva** [comment]
> I am RZ608, the onexplayer mini 5800u of the gas collection chamber cannot restart after inputting the command

You mean you stuck on boot or? Any error message for it?

**Comment by huchenghe001** [comment]
> 


我的意思是wifi还是用不了，翻译软件的问题
I mean, WiFi still doesn't work. There's a problem with the translation software

**Comment by arcatva** [comment]
> > 
> 
> 我的意思是wifi还是用不了，翻译软件的问题 I mean, WiFi still doesn't work. There's a problem with the translation software

Can lspci output shows the driver is being used? Also please check the modinfo to see if the 0608 PCIe ID added

**Comment by huchenghe001** [comment]
> > > 
> > 
> > 
> > 我的英文是wifi还是用不了，翻译软件的问题 我的意思是，WiFi还是不行。翻译软件有问题
> 
> lspci 输出可以显示驱动程序正在使用吗？另请检查 modinfo 以查看是否添加了 0608 PCIe ID

Let me try

**Comment by huchenghe001** [comment]
> 

lspci 
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7
01:00.0 Network controller: MEDIATEK Corp. Device 0608
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation PS5013 E13 NVMe Controller (rev 01)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
03:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
03:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
03:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller

modinfo sg
filename:       /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb/kernel/drivers/scsi/sg.ko.xz
alias:          char-major-21-*
version:        3.5.36
license:        GPL
description:    SCSI generic (sg) driver
author:         Douglas Gilbert
srcversion:     BEF20D92412113BE3A7C3D0
depends:
retpoline:      Y
intree:         Y
name:           sg
vermagic:       5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb SMP preempt mod_unload
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        51:46:A7:81:9B:C8:C3:BC:10:24:EB:19:A5:0D:25:47:C8:82:D0:D3
sig_hashalgo:   sha512
signature:      17:0A:DB:D7:CA:0C:40:E7:C6:97:40:2C:10:61:C6:67:95:3A:73:5B:
                0A:5E:79:55:7B:17:33:CF:25:DF:14:4F:8C:DC:F4:2C:81:5B:74:00:
                8F:42:2D:3F:AA:5F:B5:D1:C1:77:4E:FF:92:CC:19:8C:63:07:A4:C1:
                F2:90:79:9F:C2:C8:20:F7:20:26:77:D2:21:5C:B6:95:71:D8:26:A1:
                50:DC:A8:EE:75:BE:60:5D:75:B3:E7:19:6A:49:AE:66:A3:36:D2:66:
                ED:FA:47:4F:11:EB:FD:EA:BF:41:B3:02:C3:6D:0A:AF:FC:D7:3A:43:
                99:F1:17:65:6A:B1:37:C2:39:23:34:CE:61:10:E6:DB:37:EC:23:E7:
                BA:71:5F:4C:C9:38:E5:53:0A:31:A7:2F:BF:15:61:BD:C3:83:FF:23:
                A0:50:0C:63:81:16:89:A6:84:F4:C3:C4:23:70:E1:EF:9D:F5:D2:E8:
                B2:D6:A5:3C:B1:88:11:2C:A3:A9:14:B8:D6:2B:41:DD:C8:B0:4B:6E:
                F5:04:66:28:72:CB:46:AA:92:8D:66:EF:12:AC:52:54:0E:E3:50:A4:
                81:4D:34:E2:91:DD:3A:8C:C9:FF:17:41:CA:57:69:9B:55:28:E8:F4:
                F5:6F:12:E0:4E:1F:DA:13:AE:BC:D4:A4:F2:57:B6:2B:D4:AD:E3:D0:
                36:17:8E:40:FA:15:7C:74:5C:02:3A:D2:46:22:6B:03:70:CC:E7:EC:
                AC:BE:D0:F4:0D:A5:F9:FE:03:AF:1C:89:C6:80:73:A3:A4:58:DC:8C:
                28:90:27:7B:74:9B:4B:51:31:DC:DA:10:6C:3C:44:2C:8A:59:7B:62:
                E8:18:AF:0E:17:0E:49:B8:39:17:7C:C7:87:38:30:1D:EB:53:17:20:
                39:22:BE:2C:37:D4:9E:03:32:18:BB:27:EE:9B:56:99:0C:BA:5E:EB:
                78:92:D9:60:A9:98:11:49:CF:25:E9:69:01:2D:5F:78:BF:E2:A0:3A:
                16:6F:D1:5F:1D:D7:38:80:F7:C8:A5:6D:48:A8:B7:60:AF:2F:86:F1:
                E8:78:22:24:38:41:26:83:29:AA:23:B5:BC:D3:F3:64:C3:7F:06:8E:
                08:46:EC:14:33:7D:F4:61:10:BA:7E:2B:F3:FA:5A:05:95:8D:E1:5D:
                4D:25:1D:BA:D1:79:F5:5A:C6:DF:FB:9F:A1:05:46:E3:98:40:A7:F8:
                6A:8E:CD:D3:FB:7B:E9:C2:1E:0B:B7:5F:F4:83:61:6F:A0:F9:A2:A8:
                5D:FD:15:BD:9B:13:32:71:33:60:6C:7F:D8:A9:E3:B2:AF:0D:94:66:
                B4:7A:1D:42:B0:56:67:BE:05:CA:D5:77
parm:           scatter_elem_sz:scatter gather element size (default: max(SG_SCATTER_SZ, PAGE_SIZE)) (int)
parm:           def_reserved_size:size of buffer reserved for each fd (int)
parm:           allow_dio:allow direct I/O (default: 0 (disallow)) (int)

**Comment by huchenghe001** [comment]
> > > 
> > 
> > 
> > 我的意思是wifi还是用不了，翻译软件的问题 I mean, WiFi still doesn't work. There's a problem with the translation software
> 
> Can lspci output shows the driver is being used? Also please check the modinfo to see if the 0608 PCIe ID added
lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7
01:00.0 Network controller: MEDIATEK Corp. Device 0608
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation PS5013 E13 NVMe Controller (rev 01)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
03:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
03:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
03:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller

modinfo sg
filename: /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb/kernel/drivers/scsi/sg.ko.xz
alias: char-major-21-*
version: 3.5.36
license: GPL
description: SCSI generic (sg) driver
author: Douglas Gilbert
srcversion: BEF20D92412113BE3A7C3D0
depends:
retpoline: Y
intree: Y
name: sg
vermagic: 5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb SMP preempt mod_unload
sig_id: PKCS#7
signer: Build time autogenerated kernel key
sig_key: 51:46:A7:81:9B:C8:C3:BC:10:24:EB:19:A5:0D:25:47:C8:82:D0:D3
sig_hashalgo: sha512
signature: 17:0A:DB:D7:CA:0C:40:E7:C6:97:40:2C:10:61:C6:67:95:3A:73:5B:
0A:5E:79:55:7B:17:33:CF:25:DF:14:4F:8C:DC:F4:2C:81:5B:74:00:
8F:42:2D:3F:AA:5F:B5:D1:C1:77:4E:FF:92:CC:19:8C:63:07:A4:C1:
F2:90:79:9F:C2:C8:20:F7:20:26:77:D2:21:5C:B6:95:71:D8:26:A1:
50:DC:A8:EE:75:BE:60:5D:75:B3:E7:19:6A:49:AE:66:A3:36:D2:66:
ED:FA:47:4F:11:EB:FD:EA:BF:41:B3:02:C3:6D:0A:AF:FC:D7:3A:43:
99:F1:17:65:6A:B1:37:C2:39:23:34:CE:61:10:E6:DB:37:EC:23:E7:
BA:71:5F:4C:C9:38:E5:53:0A:31:A7:2F:BF:15:61:BD:C3:83:FF:23:
A0:50:0C:63:81:16:89:A6:84:F4:C3:C4:23:70:E1:EF:9D:F5:D2:E8:
B2:D6:A5:3C:B1:88:11:2C:A3:A9:14:B8:D6:2B:41:DD:C8:B0:4B:6E:
F5:04:66:28:72:CB:46:AA:92:8D:66:EF:12:AC:52:54:0E:E3:50:A4:
81:4D:34:E2:91:DD:3A:8C:C9:FF:17:41:CA:57:69:9B:55:28:E8:F4:
F5:6F:12:E0:4E:1F:DA:13:AE:BC:D4:A4:F2:57:B6:2B:D4:AD:E3:D0:
36:17:8E:40:FA:15:7C:74:5C:02:3A:D2:46:22:6B:03:70:CC:E7:EC:
AC:BE:D0:F4:0D:A5:F9:FE:03:AF:1C:89:C6:80:73:A3:A4:58:DC:8C:
28:90:27:7B:74:9B:4B:51:31:DC:DA:10:6C:3C:44:2C:8A:59:7B:62:
E8:18:AF:0E:17:0E:49:B8:39:17:7C:C7:87:38:30:1D:EB:53:17:20:
39:22:BE:2C:37:D4:9E:03:32:18:BB:27:EE:9B:56:99:0C:BA:5E:EB:
78:92:D9:60:A9:98:11:49:CF:25:E9:69:01:2D:5F:78:BF:E2:A0:3A:
16:6F:D1:5F:1D:D7:38:80:F7:C8:A5:6D:48:A8:B7:60:AF:2F:86:F1:
E8:78:22:24:38:41:26:83:29:AA:23:B5:BC:D3:F3:64:C3:7F:06:8E:
08:46:EC:14:33:7D:F4:61:10:BA:7E:2B:F3:FA:5A:05:95:8D:E1:5D:
4D:25:1D:BA:D1:79:F5:5A:C6:DF:FB:9F:A1:05:46:E3:98:40:A7:F8:
6A:8E:CD:D3:FB:7B:E9:C2:1E:0B:B7:5F:F4:83:61:6F:A0:F9:A2:A8:
5D:FD:15:BD:9B:13:32:71:33:60:6C:7F:D8:A9:E3:B2:AF:0D:94:66:
B4:7A:1D:42:B0:56:67:BE:05:CA:D5:77
parm: scatter_elem_sz:scatter gather element size (default: max(SG_SCATTER_SZ, PAGE_SIZE)) (int)
parm: def_reserved_size:size of buffer reserved for each fd (int)
parm: allow_dio:allow direct I/O (default: 0 (disallow)) (int)

**Comment by huchenghe001** [comment]
> > > 
> > 
> > 
> > 我的意思是wifi还是用不了，翻译软件的问题 I mean, WiFi still doesn't work. There's a problem with the translation software
> 
> Can lspci output shows the driver is being used? Also please check the modinfo to see if the 0608 PCIe ID added

 modinfo 
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Cezanne Data Fabric; Function 7
01:00.0 Network controller: MEDIATEK Corp. Device 0608
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation PS5013 E13 NVMe Controller (rev 01)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
03:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
03:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
03:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller

modinfo sg
modinfo: ERROR: missing module or filename.
[root@admin aya-neo-fixes]# modinfo
modinfo: ERROR: missing module or filename.
[root@admin aya-neo-fixes]# modinfo sg
filename:       /lib/modules/5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb/kernel/drivers/scsi/sg.ko.xz
alias:          char-major-21-*
version:        3.5.36
license:        GPL
description:    SCSI generic (sg) driver
author:         Douglas Gilbert
srcversion:     BEF20D92412113BE3A7C3D0
depends:
retpoline:      Y
intree:         Y
name:           sg
vermagic:       5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb SMP preempt mod_unload
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        51:46:A7:81:9B:C8:C3:BC:10:24:EB:19:A5:0D:25:47:C8:82:D0:D3
sig_hashalgo:   sha512
signature:      17:0A:DB:D7:CA:0C:40:E7:C6:97:40:2C:10:61:C6:67:95:3A:73:5B:
                0A:5E:79:55:7B:17:33:CF:25:DF:14:4F:8C:DC:F4:2C:81:5B:74:00:
                8F:42:2D:3F:AA:5F:B5:D1:C1:77:4E:FF:92:CC:19:8C:63:07:A4:C1:
                F2:90:79:9F:C2:C8:20:F7:20:26:77:D2:21:5C:B6:95:71:D8:26:A1:
                50:DC:A8:EE:75:BE:60:5D:75:B3:E7:19:6A:49:AE:66:A3:36:D2:66:
                ED:FA:47:4F:11:EB:FD:EA:BF:41:B3:02:C3:6D:0A:AF:FC:D7:3A:43:
                99:F1:17:65:6A:B1:37:C2:39:23:34:CE:61:10:E6:DB:37:EC:23:E7:
                BA:71:5F:4C:C9:38:E5:53:0A:31:A7:2F:BF:15:61:BD:C3:83:FF:23:
                A0:50:0C:63:81:16:89:A6:84:F4:C3:C4:23:70:E1:EF:9D:F5:D2:E8:
                B2:D6:A5:3C:B1:88:11:2C:A3:A9:14:B8:D6:2B:41:DD:C8:B0:4B:6E:
                F5:04:66:28:72:CB:46:AA:92:8D:66:EF:12:AC:52:54:0E:E3:50:A4:
                81:4D:34:E2:91:DD:3A:8C:C9:FF:17:41:CA:57:69:9B:55:28:E8:F4:
                F5:6F:12:E0:4E:1F:DA:13:AE:BC:D4:A4:F2:57:B6:2B:D4:AD:E3:D0:
                36:17:8E:40:FA:15:7C:74:5C:02:3A:D2:46:22:6B:03:70:CC:E7:EC:
                AC:BE:D0:F4:0D:A5:F9:FE:03:AF:1C:89:C6:80:73:A3:A4:58:DC:8C:
                28:90:27:7B:74:9B:4B:51:31:DC:DA:10:6C:3C:44:2C:8A:59:7B:62:
                E8:18:AF:0E:17:0E:49:B8:39:17:7C:C7:87:38:30:1D:EB:53:17:20:
                39:22:BE:2C:37:D4:9E:03:32:18:BB:27:EE:9B:56:99:0C:BA:5E:EB:
                78:92:D9:60:A9:98:11:49:CF:25:E9:69:01:2D:5F:78:BF:E2:A0:3A:
                16:6F:D1:5F:1D:D7:38:80:F7:C8:A5:6D:48:A8:B7:60:AF:2F:86:F1:
                E8:78:22:24:38:41:26:83:29:AA:23:B5:BC:D3:F3:64:C3:7F:06:8E:
                08:46:EC:14:33:7D:F4:61:10:BA:7E:2B:F3:FA:5A:05:95:8D:E1:5D:
                4D:25:1D:BA:D1:79:F5:5A:C6:DF:FB:9F:A1:05:46:E3:98:40:A7:F8:
                6A:8E:CD:D3:FB:7B:E9:C2:1E:0B:B7:5F:F4:83:61:6F:A0:F9:A2:A8:
                5D:FD:15:BD:9B:13:32:71:33:60:6C:7F:D8:A9:E3:B2:AF:0D:94:66:
                B4:7A:1D:42:B0:56:67:BE:05:CA:D5:77
parm:           scatter_elem_sz:scatter gather element size (default: max(SG_SCATTER_SZ, PAGE_SIZE)) (int)
parm:           def_reserved_size:size of buffer reserved for each fd (int)
parm:           allow_dio:allow direct I/O (default: 0 (disallow)) (int)

**Comment by pastaq** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/245
