### ISSUE TITLE
ThinkPad T450 intel question

### ISSUE THREAD

**Issue by da0ist** [holoiso-eol/holoiso#202]
I've got it installed (neptune: is this the right one for this hardware?) and it boots to a black screen. Following the wiki instructions, I've booted into recovery mode, but don't know how to interpret: install required packages.

Can I get a command line for "Gamescope and MESA downgrade"?

Can I get it to default to KDE? Will I be able to play games from KDE without downgrading?

**Comment by erdog** [comment]
I'm looking for the same commands. I'm using an Intel NUC.

**Comment by theVakhovskeIsTaken** [comment]
Fixed as https://github.com/theVakhovskeIsTaken/holoiso/commit/e783d546371b9d647330d54d6d10a87ff8eb08ed
