### ISSUE TITLE
gamescope-session won't start - systems with hybrid graphics without hardware switching

### ISSUE THREAD

**Issue by Funky7Monkey** [holoiso-eol/holoiso#207]
On some laptops with hybrid graphics (having both an integrated GPU in the CPU and a dedicated GPU), there is no way to switch which GPU drives the integrated display at a hardware level. On these systems it will be necessary to start `gamescope-session` using the iGPU, with games launched using the dGPU.

There are methods for running wayland with switchable graphics (https://github.com/pedro00dk/nvidia-exec), however this is experimental and only supports GNOME at this time.

On a Gigabyte Sabre 15, running `gamescope-session` outputs:

```
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
wlserver: [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
MANGOAPP LAYER: Init
vulkan: selecting physical device 'NVIDIA GeForce GTX 1050'
vulkan: physical device supports DRM format modifiers
drm: opening DRM node '/dev/dri/card1'
drm: CRTC 39 has no gamma LUT support
drm: CRTC 39 has no CTM support
drm: CRTC 49 has no gamma LUT support
drm: CRTC 49 has no CTM support
drm: CRTC 59 has no gamma LUT support
drm: CRTC 59 has no CTM support
drm: CRTC 69 has no gamma LUT support
drm: CRTC 69 has no CTM support
drm: Connectors:
drm:   DP-2 (disconnected)
drm: cannot find any connector!
Failed to initialize output
/usr/bin/gamescope-session: line 175: kill: (2750) - No such process
```

`/dev/dri/card0` on this laptop is the integrated GPU, and `card1` is the dedicated GPU (GTX 1050). Connector `DP-2` is connected to a physical miniDP port on the Sabre 15, and is the only physical output on the dGPU. The rest of the outputs (including the integrated display) are wired directly to the iGPU.

**Comment by theVakhovskeIsTaken** [comment]
I don't know anything about this honestly, open an issue in https://github.com/Plagman/gamescope
