### ISSUE TITLE
Wont install on VirtualBox

### ISSUE THREAD

**Issue by AKASGaming** [holoiso-eol/holoiso#208]
Every time I try and install HoloISO, I get up to this point:
![2022-05-26 19_30_12-Window](https://user-images.githubusercontent.com/25405047/170605382-eb06c155-d7dd-488b-8f2f-921b9403f89f.png)

Before it wouldn't even download the keys, it would just say there was an error getting them. What should I try differently?

I'm using the latest HoloISO release, and these are my VB settings:
![image](https://user-images.githubusercontent.com/25405047/170605482-8cff2da2-fd71-4a0d-b123-2b82e4d26879.png)

**Comment by ghost** [comment]
Is is an Arch issue when the system clock is out of sync. Could be an issue with your timezone. Not specific neither to VBox nor HoloISO. Check if you can get a clean arch installed following the install guide. It can help for pacstrap if you include a pacman -S archlinux-keyring (maybe could be a fix for the install script - maybe it's an issue at valves servers).

**Comment by AKASGaming** [comment]
Yeah, I assume it's a clock issue at this point
![image](https://user-images.githubusercontent.com/25405047/170801123-0f7d5306-4f0a-4835-b543-7273d38ce29c.png)
can't figure out how to get pass that tho :/

**Comment by AKASGaming** [comment]
So I think I've figured it out, I think the HoloISO image isn't packaged with any VB or VM packages like `virtualbox-guest-utils` giving the OS privileges to VB Guest Additions, which is why the time won't sync

**Comment by enderpirate98** [comment]
When I tried it the vm kept the keys but it would say massage along the lines of "installed successfully please reboot" but when I reboot it just goes back into the installer. Even when I tell it to override the installer disk and boot from the 100GB virtual hard disk it just shows a black screen of nothingness. I did check this issue yesterday and there was the guest iso for nox so hope that helps.

**Comment by AKASGaming** [comment]
If anyone's interested, this is what I did and it seems to have worked:
[https://www.archlinuxuser.com/2012/06/ignore-signature-check-when-doing.html](https://www.archlinuxuser.com/2012/06/ignore-signature-check-when-doing.html)
