### ISSUE TITLE
Big problem with DeckUI on AMD Internal GPU

### ISSUE THREAD

**Issue by Bendy3192** [holoiso-eol/holoiso#21]
Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.

**Comment by Bendy3192** [comment]
![Uploading IMG_20220505_172705.jpg…]()

**Comment by theVakhovskeIsTaken** [comment]
> Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.

Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?

**Comment by Bendy3192** [comment]
> > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> 
> Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?

I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU

**Comment by theVakhovskeIsTaken** [comment]
> > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > 
> > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> 
> I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU

Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?

**Comment by Bendy3192** [comment]
> > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > 
> > > 
> > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > 
> > 
> > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> 
> Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?

Desktop mode – Plasma, yes?

**Comment by Bendy3192** [comment]
> > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > 
> > > 
> > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > 
> > 
> > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> 
> Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?

I've found on Amd site, what my iGPU supports vulkan?..

**Comment by Bendy3192** [comment]
> > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > 
> > > 
> > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > 
> > 
> > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> 
> Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?

![Uploading IMG_20220505_184847.jpg…]()

**Comment by theVakhovskeIsTaken** [comment]
> > > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > > 
> > > > 
> > > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > > 
> > > 
> > > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> > 
> > Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?
> 
> Desktop mode – Plasma, yes?

Yes. Log-in to Plasma, and run said command in terminal

**Comment by Bendy3192** [comment]
> > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> 
> Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?

I find!
Vulkan: failed to find physical device
Failed to initialize vulkan

**Comment by theVakhovskeIsTaken** [comment]
> > > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > > 
> > > > 
> > > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > > 
> > > 
> > > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> > 
> > Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?
> 
> Desktop mode – Plasma, yes?

Yes. Log-in to Plasma, and run said command in terminal

**Comment by Bendy3192** [comment]
> > > > > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > > > > 
> > > > > 
> > > > > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> > > > 
> > > > 
> > > > I have old laptop, Acer Aspire E5-521G, 2014 year release date. Amd A8-6410 CPU with R5 Graphics/R5 M240 dedicated GPU
> > > 
> > > 
> > > Looks like your GPU doesn't support Vulkan. Can you go to desktop mode, and run `gamescope-session` in terminal?
> > 
> > 
> > Desktop mode – Plasma, yes?
> 
> Yes. Log-in to Plasma, and run said command in terminal

Message higher 
Seems, like I haven't vulkan driver – mesa?

**Comment by theVakhovskeIsTaken** [comment]
> > > Hello guys!) Now, i'm just installed latest version of Holoiso, and i have problem. When i enter in the gamescope, i have loop to login screen again and again. I see in description, which there is problem on iGPU, but i not enough knowledge to solve it. I tried, but that was unsuccessfully. Please, help me.
> > 
> > Alright. That's strange given you are using AMD iGPU. Can you give your full PC specs and which variant you have installed?
> 
> I find!
> Vulkan: failed to find physical device
> Failed to initialize vulkan

Script already installs "vulkan-radeon" drivers, but you can try to install "vulkan-amdgpu" and "lib32-vulkan-amdgpu" and tell if this changes something

**Comment by Bendy3192** [comment]
> > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > 
> > > 
> > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > 
> > 
> > Я нахожу! 
> > Vulkan: не удалось найти физическое устройство 
> > Не удалось инициализировать vulkan
> 
> Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то

I'm sorry, I'm newcomer in arch. What command do this?

**Comment by theVakhovskeIsTaken** [comment]
> > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > 
> > > > 
> > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > 
> > > 
> > > Я нахожу! 
> > > Vulkan: не удалось найти физическое устройство 
> > > Не удалось инициализировать vulkan
> > 
> > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> 
> I'm sorry, I'm newcomer in arch. What command do this?

Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session

**Comment by Bendy3192** [comment]
> > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > 
> > > > > 
> > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > 
> > > > 
> > > > Я нахожу!
> > > > Vulkan: не удалось найти физическое устройство
> > > > Не удалось инициализировать vulkan
> > > 
> > > 
> > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > 
> > 
> > I'm sorry, I'm newcomer in arch. What command do this?
> 
> Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session

Okay.. I'm installing SteamOS again. Let's see what happens this time.

**Comment by Bendy3192** [comment]
> > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > 
> > > > > 
> > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > 
> > > > 
> > > > Я нахожу!
> > > > Vulkan: не удалось найти физическое устройство
> > > > Не удалось инициализировать vulkan
> > > 
> > > 
> > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > 
> > 
> > I'm sorry, I'm newcomer in arch. What command do this?
> 
> Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session

Hm, i have an idea! Maybe, I need to switch my internal GPU to Discrete GPU and this problem disappear?

**Comment by theVakhovskeIsTaken** [comment]
> > > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > > 
> > > > > > 
> > > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > > 
> > > > > 
> > > > > Я нахожу!
> > > > > Vulkan: не удалось найти физическое устройство
> > > > > Не удалось инициализировать vulkan
> > > > 
> > > > 
> > > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > > 
> > > 
> > > I'm sorry, I'm newcomer in arch. What command do this?
> > 
> > 
> > Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session
> 
> Hm, i have an idea! Maybe, I need to switch my internal GPU to Discrete GPU and this problem disappear?

I highly doubt it will, but you can try

**Comment by Bendy3192** [comment]
> > > > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > > > 
> > > > > > > 
> > > > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > > > 
> > > > > > 
> > > > > > Я нахожу!
> > > > > > Vulkan: не удалось найти физическое устройство
> > > > > > Не удалось инициализировать vulkan
> > > > > 
> > > > > 
> > > > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > > > 
> > > > 
> > > > I'm sorry, I'm newcomer in arch. What command do this?
> > > 
> > > 
> > > Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session
> > 
> > 
> > Hm, i have an idea! Maybe, I need to switch my internal GPU to Discrete GPU and this problem disappear?
> 
> I highly doubt it will, but you can try

Ok, sorry, but how may i do this in Arch?

**Comment by theVakhovskeIsTaken** [comment]
> > > > > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > > > > 
> > > > > > > 
> > > > > > > Я нахожу!
> > > > > > > Vulkan: не удалось найти физическое устройство
> > > > > > > Не удалось инициализировать vulkan
> > > > > > 
> > > > > > 
> > > > > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > > > > 
> > > > > 
> > > > > I'm sorry, I'm newcomer in arch. What command do this?
> > > > 
> > > > 
> > > > Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session
> > > 
> > > 
> > > Hm, i have an idea! Maybe, I need to switch my internal GPU to Discrete GPU and this problem disappear?
> > 
> > 
> > I highly doubt it will, but you can try
> 
> Ok, sorry, but how may i do this in Arch?

[Honestly, don't know.](https://wiki.archlinux.org/index.php/PRIME#Discrete_card_as_primary_GPU)

**Comment by Bendy3192** [comment]
> > > > > > > > > > Привет, ребята!) Я только что установил последнюю версию Holoiso, и у меня возникла проблема. Когда я вхожу в игру, у меня снова и снова появляется экран входа в систему. Я вижу в описании, что есть проблема на iGPU, но мне не хватает знаний, чтобы решить ее. Я пытался, но это было безуспешно. Помогите пожалуйста мне.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Хорошо. Это странно, учитывая, что вы используете AMD iGPU. Можете ли вы дать полные характеристики вашего ПК и какой вариант вы установили?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Я нахожу!
> > > > > > > > Vulkan: не удалось найти физическое устройство
> > > > > > > > Не удалось инициализировать vulkan
> > > > > > > 
> > > > > > > 
> > > > > > > Скрипт уже устанавливает драйвера "vulkan-radeon", но вы можете попробовать установить "vulkan-amdgpu" и "lib32-vulkan-amdgpu" и сказать, изменит ли это что-то
> > > > > > 
> > > > > > 
> > > > > > I'm sorry, I'm newcomer in arch. What command do this?
> > > > > 
> > > > > 
> > > > > Просто пропиши "sudo pacman -S vulkan-amdgpu lib32-vulkan-amdgpu" и попробуй запустить gamescope-session
> > > > 
> > > > 
> > > > Hm, i have an idea! Maybe, I need to switch my internal GPU to Discrete GPU and this problem disappear?
> > > 
> > > 
> > > I highly doubt it will, but you can try
> > 
> > 
> > Ok, sorry, but how may i do this in Arch?
> 
> [Honestly, don't know.](https://wiki.archlinux.org/index.php/PRIME#Discrete_card_as_primary_GPU)

Yes, i find! My laptop doesn't support Vulkan Api. Unfortunately..
