### ISSUE TITLE
Gamescope-session doesn't display on latest build w/ Nvidia GPU

### ISSUE THREAD

**Issue by Mario-119** [holoiso-eol/holoiso#210]
When I run gamescope-session in the terminal, everything seems to load somewhat normally and the intro sequence audio plays in the background but nothing displays. 

[mario119@SteamOS3 ~]$ gamescope-session
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
MANGOAPP LAYER: Init
vulkan: selecting physical device 'NVIDIA GeForce RTX 2070 Super'
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef210a5b40 (res 0x55ef210a62d0)
wlserver: [xwayland/server.c:250] Xserver is ready
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :2
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef206bfc90 (res 0x55ef210ae150)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 60
/usr/bin/gamescope-session: line 181: xbindkeys: command not found
/usr/bin/gamescope-session: line 197: /tmp/steamos-short-session-tracker: No such file or directory
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef21070210 (res 0x55ef210a7990)
[2022-05-27 01:54:46.230] [info] [config.cpp:117] parsing config: '/tmp/mangohud.i09AaLlC'
[2022-05-27 01:54:46.260] [info] [overlay.cpp:733] Uploading is disabled (permit_upload = 0)
xwm: Rejecting WM_CHANGE_STATE to ICONIC for window 0x400007
steam.sh[14510]: Running Steam on steamos rolling 64-bit
steam.sh[14510]: STEAM_RUNTIME is enabled automatically
setup.sh[14605]: Steam runtime environment up-to-date!
steam.sh[14510]: Steam client's requirements are satisfied
[2022-05-27 01:54:46] Startup - updater built May 26 2022 20:40:46
[2022-05-27 01:54:46] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
Installing breakpad exception handler for appid(steam)/version(1653599776)
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-27 01:54:46] Loading cached metrics from disk (/home/mario119/.local/share/Steam/package/steam_client_metrics.bin)
[2022-05-27 01:54:46] Using the following download hosts for Public, Realm steamglobal
[2022-05-27 01:54:46] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-27 01:54:46] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-27 01:54:46] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1653599776)
[2022-05-27 01:54:46] Verifying installation...
[2022-05-27 01:54:46] Verification complete
Loaded SDL version 2.0.23-7223290
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
(steam:14649): Gtk-WARNING **: 01:54:46.966: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
ComputeStartupMode: forcing gamepadui via cliInstalling breakpad exception handler for appid(steam)/version(1653599776)
steamwebhelper.sh[14713]: Runtime for steamwebhelper: defaulting to /home/mario119/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[14713]: Using CEF sandbox (try with -no-cef-sandbox if this fails)
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
CAppInfoCacheReadFromDiskThread took 32 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1653599776)
privileged write polkit:auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValueToFileAsUser: steamos-priv-write failed /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValuetoFileAsRoot: failed to write to /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write polkit:auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValueToFileAsUser: steamos-priv-write failed /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValuetoFileAsRoot: failed to write to /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
[2022-05-27 01:54:47.651] [info] [config.cpp:117] parsing config: '/tmp/mangohud.i09AaLlC'
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef2107d910 (res 0x55ef210af280)
536870912
Error getting buffer
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef21080cd0 (res 0x55ef2107dc90)
Error getting buffer
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef210820e0 (res 0x55ef2107dc90)
Error getting buffer
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef2107f1c0 (res 0x55ef2107dc90)
Error getting buffer
MANGOAPP LAYER: Init
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Installing breakpad exception handler for appid(steam)/version(1653599776)
Installing breakpad exception handler for appid(steam)/version(1653599776)
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55ef21070aa0 (res 0x55ef2107dc90)
Error getting buffer

From what I can see in the log, it seems like it's the fault of wlserver throwing an error while trying to fetch a buffer. This is different than what happened on previous builds where gamescope-session would just exit entirely because of weird issues with Wayland. Running an RTX 2070 Super with an I7 10750h for reference. Help would be much appreciated, thanks.

**Comment by theVakhovskeIsTaken** [comment]
Reinstall latest ISO, i missed the point for grub configuration editing before it ends installation
