### ISSUE TITLE
Latest build snapshot5 blackscreen

### ISSUE THREAD

**Issue by FayeSpica** [holoiso-eol/holoiso#211]
Both aya neo (AMD 4500U) and OnexPlayer Mini (AMD 5800U)
boot but only blackscreen

**Comment by thekidflipper** [comment]
This is the same with me, but with ryzen 5600x and GTX 1660super

**Comment by thekidflipper** [comment]
![IMG_20220527_130136](https://user-images.githubusercontent.com/39328747/170632737-59850c6b-200e-43a2-9558-99ab671f064d.jpg)
I get this error

**Comment by FayeSpica** [comment]
rollback `holoinstall` script 
``` shell
GAMESCOPE_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --overwrite="*" vulkan-radeon-steamos lib32-vulkan-radeon-steamos gamescope mesa-steamos lib32-mesa-steamos)
```

to 
``` shell
GAMESCOPE_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --overwrite="*" vulkan-radeon lib32-vulkan-radeon gamescope)
```

now i can run gamescope.
@theVakhovskeIsTaken

**Comment by PeavUK** [comment]
missing vulkan - snapshot 5 - GPU option 1 selected during install.
![vulkan missing](https://user-images.githubusercontent.com/102307906/170658367-b6816aad-59ed-4bc2-89c9-51853f754870.png)
![version info](https://user-images.githubusercontent.com/102307906/170658459-ef90c8c6-f0ff-447e-b18c-26261f65f9f3.png)
![DSC_0265](https://user-images.githubusercontent.com/102307906/170658831-a4977358-66ae-450a-b26c-389ab8f5fbb1.JPG)

Following executed via terminal:

[kev@kev-pc ~]$ gamescope-session
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
SDL_Vulkan_LoadLibrary failed: Installed Vulkan doesn't implement the VK_KHR_surface extension
Failed to initialize Vulkan
/usr/bin/gamescope-session: line 175: kill: (261117) - No such process
[kev@kev-pc ~]$ 

UPDATE - Latest iso that reverts the vulkan setup has fixed this issue for me.

**Comment by ruineka** [comment]
Same black screen and I had a vulkan not found error when trying to manually start gamescope so I attempted to use pacman and I found out I don't have any wifi or Ethernet. Iwctl isn't found among other things. This is on the OneXPlayer Intel.
