### ISSUE TITLE
Supplying Correct Edid Crashes Deck-Ui

### ISSUE THREAD

**Issue by OneMello** [holoiso-eol/holoiso#212]
Hello,

I would like to get to the bottom of why supplying the edid info crashes the steam deck ui.
If you could provide ways to gather info/get logs so we can get to the bottom of this issue that would be amazing.

I've attempted to ssh into the pc while running the steam deck ui but it fails to connect, when in the kde session everything works normal. I also cannot start the gamescope session or steamos-session-select (i believe its called) while under ssh but that may be due to my user and root being under the same name. So I'll attempt those after a fresh install to see if itll succeed, if not I'll find the directories those scripts are located and run them that way.

**Comment by theVakhovskeIsTaken** [comment]
I don't know, open an issue in https://github.com/plagman/gamescope

**Comment by OneMello** [comment]
> I don't know, open an issue in https://github.com/plagman/gamescope

I'll open an enquiry there, I'll update if theres any resolution

**Comment by Betaminos** [comment]
If anyone is looking for the Issue in the list of Gamescope issues: https://github.com/Plagman/gamescope/issues/507
