### ISSUE TITLE
Not booting properly -- stuck on "ramdisk"

### ISSUE THREAD

**Issue by Vlad-Galeev** [holoiso-eol/holoiso#214]
Similar to #175, but here it only gets stuck on the ramdisk line. this might be a hardware problem, but I am not sure.  
I am using a laptop (Acer Spin SP111-32N) with an Intel iGPU (HD 505), 4GB DDR3, Pentium N4200.   
  
I am trying to use this as a test system to see if SteamOS is a valid choice as a main OS (Currently running Mint and OEM Win10), so it doesnt have to run at full performance, I just want to see it run a few windows programs.
  
What happens is I get the GRUB menu, and then after loading the SteamOS option, I get two lines of output. The first is the kernel, and the second is ramdisk. After that it just sits there doing something.

**Comment by theVakhovskeIsTaken** [comment]
Your GPU is unsupported.
