### ISSUE TITLE
mnt fstab problem on oxp nvme

### ISSUE THREAD

**Issue by ReNNoN** [holoiso-eol/holoiso#216]
Hi men,
I got to try explain most simple possible because my main language not is english.

So, I have a onexplayer 1s 1tb nvme.
I have gpt partition system with dualboot windows11 pro and Popos linux. I've tried other distro linux without problems.

When I go to install holoiso on nvme I receive many errors from mnt and fstab, etc and I can't make installation.

I show you any screenshots of this errors, I've try install on nvme08.
![B74A2B48-6503-46DA-B745-772E5AD72177](https://user-images.githubusercontent.com/5250388/170838125-7f41b011-6532-4bd3-a0eb-1b9f7c1feccd.jpeg)

I
![95D2CAC1-F4AF-4BE9-80AA-2D9A148AEADC](https://user-images.githubusercontent.com/5250388/170838128-ef8a494d-0722-4038-88c1-81863b054dff.jpeg)

![014D2C6E-70C1-4EA3-B2D4-4C68D375B621](https://user-images.githubusercontent.com/5250388/170838120-3870d8bf-ef95-4c45-aa72-526567542922.jpeg)
![18E67927-8F0E-43DB-8003-20EE95C3CDFF](https://user-images.githubusercontent.com/5250388/170838124-36eabba6-5ce4-4747-afe0-e447e13e2e21.jpeg)

**Comment by theVakhovskeIsTaken** [comment]
> Hi men, I got to try explain most simple possible because my main language not is english.
> 
> So, I have a onexplayer 1s 1tb nvme. I have gpt partition system with dualboot windows11 pro and Popos linux. I've tried other distro linux without problems.
> 
> When I go to install holoiso on nvme I receive many errors from mnt and fstab, etc and I can't make installation.
> 
> I show you any screenshots of this errors, you ![B635E572-5C89-4977-8479-7A34114D0BA9](https://user-images.githubusercontent.com/5250388/170838075-7367a070-6e38-4e57-b17a-281de8529e93.jpeg) can ![Uploading 6FF18099-76F6-4D7F-A6CE-2A5B51D9BC7F.jpeg…]( ![339BBEC4-E52B-464C-A4ED-AE9A05D6882F](https://user-images.githubusercontent.com/5250388/170838080-d7701b27-fa71-4592-b004-32438b8fd40d.jpeg)
> 
> ![D3BA2305-8B2D-4A98-9DA8-C5B2B17FA4B4](https://user-images.githubusercontent.com/5250388/170838070-e9276a3d-22ed-4029-9406-538cc3f1477f.jpeg)

You can't dualboot. You need to install HoloISO on full disk first.

**Comment by ReNNoN** [comment]
Oh! ok!! thanks you !!!! good work ;)
