### ISSUE TITLE
Installer gets stuck at boot with message "triggering uevents"

### ISSUE THREAD

**Issue by alchemistake** [holoiso-eol/holoiso#217]
I'm using GTX 2060 and Ryzen 2700x.
I created the usb drive from Ventoy and Rufus DD mode.
I tried to boot from first option.
I have tried core linux boot as well it did give "cannot start TTY processor" error.

Is this a known issue or pebkac?

**Comment by theVakhovskeIsTaken** [comment]
boot with "core/linux"

**Comment by theVakhovskeIsTaken** [comment]
> I'm using GTX 2060 and Ryzen 2700x.
> I created the usb drive from Ventoy and Rufus DD mode.
> I tried to boot from first option.
> I have tried core linux boot as well it did give "cannot start TTY processor" error.
> 
> Is this a known issue or pebkac?

Also, write your USB using balenaetcher or actual DD

**Comment by alchemistake** [comment]
balenaetcher solved the problems on corelinux aswell

**Comment by PadTrick** [comment]
had no issues on my devices with the 3.4 offline installer.
version 4 hangs on triggering uevents and doesnt continue.
tested on i7-7700HQ GTX1060 Laptop, Ryzen3500u Laptop with just the APU and Ryzen 3600 with GTX 1070Ti Desktop

tried several usb sticks with different tools (Ventory, Balena & rufus), only holoiso doesnt work. Archlinux, Fedora, Linux Mint all booting fine from USB

**Comment by I3ordo** [comment]
4790k+gtx970 on GAz97n-wifi mobo. Used Vermatim 32gb+balena etcher, operation succesfull but stuck on "triggering events..." as well

**Comment by turnipsforme** [comment]
when at boot menu, press e and add 'nomodeset' to end of the line. press enter and should work fine. u have to do this every time until you install nvidia drivers
