### ISSUE TITLE
Holoiso package made for aur

### ISSUE THREAD

**Issue by enderpirate98** [holoiso-eol/holoiso#218]
What if in a vm you could just download the package and do the installation from there in stead of having to compile a whole iso image that things could go wrong with? Well that would be fantastic as someone could just grab the official arch iso load that in a vm, download the package and install it right then and there.

**Comment by theVakhovskeIsTaken** [comment]
🤓

**Comment by theVakhovskeIsTaken** [comment]
https://user-images.githubusercontent.com/97450182/170842912-ce3b41f1-98a3-490a-a3dc-aa3ae286fc7e.mp4

**Comment by ghost** [comment]
![tenor (3)](https://user-images.githubusercontent.com/93444783/170842980-660a42d7-7fca-4daf-9e19-3f9779e8588c.gif)

**Comment by LeddaZ** [comment]
https://user-images.githubusercontent.com/35930217/170843026-8f8373e8-fcc5-4909-be47-6aa55ed4a1ec.mp4

**Comment by ghost** [comment]
> in stead

https://user-images.githubusercontent.com/93444783/170843064-f30d6705-c3d6-4fa4-89d6-847e7411c19e.mp4
