### ISSUE TITLE
Failed to start Jupiter BIOS Update service

### ISSUE THREAD

**Issue by SteamMachineX** [holoiso-eol/holoiso#220]
I'm pretty sure laptop meets the specs. I was able to get to the reboot. After I did, it brings up a page called GNU GRUB 2.06. I chose SteamOS but when I chose it I get a message "Failed to start Jupiter BIOS Update service". If its any help I'm using Intel.

**Comment by theVakhovskeIsTaken** [comment]
Use this ISO https://github.com/theVakhovskeIsTaken/holoiso/releases/download/snapshot20220526.1355-1/SteamOS_Holo-20220527_0803_amdgpu-x86_64.iso
