### ISSUE TITLE
How can I fix the Failed to start Jupiter BIOS Update service error

### ISSUE THREAD

**Issue by Toni500github** [holoiso-eol/holoiso#222]
I'm on virtualbox and I have installed the full version of steamos and I wanted to login into the steamos gamescope-Wayland desktop but the error Failed to start Jupiter BIOS Update service won't let me so I should use KDE plasma x11. Please tell me how can I fix it

**Comment by deftdawg** [comment]
@Toni500github you don't need Jupiter BIOS updater to work, you will need to go to a text TTY and tell it to run the desktop instead of gaming mode... see my comment -> https://github.com/theVakhovskeIsTaken/holoiso/issues/27#issuecomment-1157225513
