### ISSUE TITLE
Nvidia GPU Steamdeck UI is really really slow

### ISSUE THREAD

**Issue by KaiH-0** [holoiso-eol/holoiso#223]
Hi,

I am having an issue with my Nvidia GPU being really slow on the UI.

I have a Nvidia GT 1030 and its running at 1080p, I also tested 720p.

Is there anyway to fix this? I installed the newest version of holoiso.

If anyone can help that would be great :)

**Comment by theVakhovskeIsTaken** [comment]
> _*No matter how great job NVIDIA and plagman has done on adapting each other, this combination MAY still be buggy, please do not report any problems to me aside from OOBE, session launching and switching and overlay management, if you encounter any problems in-gamescope, please open issue in https://github.com/Plagman/gamescope/issues_

https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1
