### ISSUE TITLE
Request - At the begining of instalation, check are all packages are online

### ISSUE THREAD

**Issue by Cekol93** [holoiso-eol/holoiso#224]
Hello everyone!
I have problem while instaling holoiso on my device.
Some of important package (Something AMD VULKAN something) was unable to download, and overall after instalation i cannot run into system...
Is this possible to chech after downloading packages, are they online?
I have limited internet (LTE GSM ;<) And im not happy to download all packages, while some of important one are not online!
I used "SteamOS_Holo-20220507_0729_amdgpu-x86_64.iso" and this occured...
But! On "SteamOS_Holo-20220527_0803_amdgpu-x86_64.iso" Instalation went succesfully!
I have RX 550, i5 4550 , 8gb ram , 128GB SSD.

But i have scaling issues, but i dissable opengl composer, and now it works great! :>

**Comment by theVakhovskeIsTaken** [comment]
This.....is impossible, because pacman doesn't have such feature, sorry
