### ISSUE TITLE
How to get into performance overlay

### ISSUE THREAD

**Issue by Cekol93** [holoiso-eol/holoiso#227]
Hello!
I was trying to get into performance overlay like this on the right side of screen: <See screens>
[https://user-images.githubusercontent.com/97450182/167292734-90036b5f-2571-438e-8951-8d731cd4ae93.png](url)
[https://user-images.githubusercontent.com/97450182/167292731-86fed590-0260-4c5e-ac13-05d284b5fd24.png](url)
How to get into that?
Shoud i use mouse and keyboard to do that, or by gamepad?

**Comment by doxzilla** [comment]
Guide + A on gamepad will bring up the Options Menu

**Comment by Cekol93** [comment]
Thx!
Works perfectly ;>
