### ISSUE TITLE
Doesn't boot after install - Failed to start Jupiter BIOS Manager (AMD r7 2700x, 5700xt)

### ISSUE THREAD

**Issue by GrunclePug** [holoiso-eol/holoiso#228]
Got it installed, booted, and when i went to desktop, it sat at a black screen for 20 mins before i reboot it. finally worked and i got everything installed, or so i thought.

Upon restarting the system it is completely broken so i tried a new install, using sudo dd instead of balena and almost the same issue. I got past all the installing but when i went to exit to desktop, same thing happened, only this time i cant get it to boot no matter what now.

I am really looking forward to this becoming more stable and cant wait for the day i can use it as my daily driver OS!

If theres anything i can try please let me know!

**Comment by GrunclePug** [comment]
Update: May be related to having NTFS drives mounted to the system.. i had to use ntfs-3g to be able to use them before but i decided to unplug my 2nd HDD (was used as my steam drive for windows) and it booted first try. Ill use it like that for now but only have 250gb on my ssd.

Let me know if theres any info you would like on my system and ill do my best to provide it : )

Edit: Okay that was a lucky boot, back to the same black screen blinking both my monitors : (

**Comment by GrunclePug** [comment]
Update 2: Sorry for all the updates xD. Just thought this could be helpful to others:
Read through some of the other issues and stumbled upon: https://github.com/theVakhovskeIsTaken/holoiso/issues/158

Illegalopcode commented
"ok try this. Boot into recovery under advanced. After logged in, run holoiso-disable-sessions. then systemctl default. This got me into the DE."

This has worked and it did a restart to verify that i can get back in, best of luck to others with similar issue!

**Comment by VinFSilva** [comment]
Hey man, did the steps on the Illegalopcode you posted and managed to get an actual GUI, but it just shows the clock and a text asking to select a user and enter password but I just cant select anything. Any idea on how to solve this?
![0623222115_HDR](https://user-images.githubusercontent.com/61393820/175438716-b02077ee-f2b7-40fe-995f-4c8f9386e17e.jpg)

**Comment by hotshot90** [comment]
I have found that some how the user created during the install doesn't exist. I predict that is why you cant select a user to login with. 

**Steps to check:**
ctrl alt F4
sign in as root with the password from the install
find / -user user

my user from the install doesn't exist 

If any one does know a solution, assistance would be appreciated. 

**Hardware:**
[Intel Nuc Skull Canyon ](https://www.intel.ca/content/www/ca/en/products/sku/89187/intel-nuc-kit-nuc6i7kyk/specifications.html)

**Comment by VinFSilva** [comment]
> I have found that some how the user created during the install doesn't exist. I predict that is why you cant select a user to login with.
> 
> **Steps to check:** ctrl alt F4 sign in as root with the password from the install find / -user user
> 
> my user from the install doesn't exist
> 
> If any one does know a solution, assistance would be appreciated.
> 
> **Hardware:** [Intel Nuc Skull Canyon ](https://www.intel.ca/content/www/ca/en/products/sku/89187/intel-nuc-kit-nuc6i7kyk/specifications.html)

On my part the problem was solved. When you go through the install process, it is required that you input a root + password and user + password. The root name and user name can't use capital letters and I was using them in every attempt to install. I used lower case on both of them and holoiso installed and booted fine.
