### ISSUE TITLE
Snapshot 5 | gaming mode crash

### ISSUE THREAD

**Issue by OneMello** [holoiso-eol/holoiso#231]
Hello,

Installing snapshot 5 and booting it leads to a black screen and crashes,
Disabling sessions allows me to get into kde and when running gamescope via "return to gaming mode", it does its crash and kicks me to the login screen.

When xrandr my display settings or inputting my edid, rotating the screen causes the internal screen to blank with cursor, unsure if its the specific device/resolution, some weirdness with xrandr created resolutions or edid supplied info, or if its present on all devices. But would be simple to check via rotating the screen in the display configuration panel on a fresh install. My resolution is 800x1280 (5:8) for reference.

Following this comment below fixes the display rotation bug, but still blackscreens/kicks to the login page.

> igot it working by first doing these commands in plasma:

> sudo pacman -S gamescope vulkan-intel-steamos lib32-vulkan-intel-steamos mesa-steamos lib32-mesa-steamos and run gamescope-session

> Then: pacman -S extra/mesa multilib/lib32-mesa holo/gamescope

> Now everything works. I can login to gamescope without a black screen or glitchiness. I'm using an nuc with Intel UHD 600 graphics.]

Trying to get a coredumpctl for gamescope doesn't work as there is no listing for a gamescope crash, possibly suggesting something else is causing the issue.

My gpu is intel for further reference. Willing to try any further suggestions.

**Comment by houku** [comment]
So this is how to get gamescope and plasma working? Or is plasma desktop still an issue?

**Comment by OneMello** [comment]
> So this is how to get gamescope and plasma working? Or is plasma desktop still an issue?

Neither,
This is a request for assistance to get gamescope working as well as bring to light a rotation bug, plasma kde isn't an issue for me. The quoted line is from a previous user with similar issues in a clozed bug report.

**Comment by CooperRecob** [comment]
I am having issues as well
![image](https://user-images.githubusercontent.com/94502545/171082199-a7b53b01-05b7-4e6f-9742-c26214280770.jpeg)
