### ISSUE TITLE
Change from btrfs to ext4 and FRZR

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#232]
Is there any possibility to integrate FRZR as readonly file system, like it is on ChimeraOS? That would make updates MUCH easier to deploy and also provide a more stable OS.

Also, why would you have a home partition as ext4, why not have one btrfs partition and use subvolumes to seperate root and home..?

**Comment by theVakhovskeIsTaken** [comment]
Read-only rootfs: Single user, predeployed, unable to pretty much perform any stuff with it, Intel users are going to have their gamescope broken, because newer packages are incompatible with them.

So, at this point: no. No plans or even thoughts about including frzr/rauc or atomic updates at-all

**Comment by aleksasiriski** [comment]
Also, why would you have a home partition as ext4, why not have one btrfs partition and use subvolumes to seperate root and home..?
