### ISSUE TITLE
Performance overlay and performance settings and updates issue

### ISSUE THREAD

**Issue by houku** [holoiso-eol/holoiso#233]
I don't know if it's right to say it here since steamOS 3 is valve issue but HoloISO is here issue and tries to bring the steamOS 3 to dekstop, so close it if I shouldn't issue it here, but if it's ok to issue it here, then continue ahead

So I installed steamOS 3 with some tinkering on my gpd win 2, but I found that when I added the performance overlay setting doesn't work, it's supposed to be (as far I know) in the top left, but it isn't there no matter the number I put it on,

Now I don't wanna say that performance advance settings thing doesn't work, but I find it logical that if on the gpd win 2 the overlay doesn't work, maybe the performance settings don't work either,

Thanks in advance

**Comment by theVakhovskeIsTaken** [comment]
Intel devices doesn't have that working because gamescope which is working on Intel is too old
