### ISSUE TITLE
NVIDIA using LLVM

### ISSUE THREAD

**Issue by pacoa-kdbg** [holoiso-eol/holoiso#234]
Hi, 
I installed using the NVIDIA option, 
howerver, after log in into steam OS, to realize that under "Video Card" it is listed "Mesa/X.org llvmpipe (LLVM 13.0.0" instead of nvidia driver/card

updated both steamos and full system packages (steamos-update check && steamos-update now; pacman -Syu ), reboot, system took some minutes to login into steamOS but still the same "Video Card" is shown.

If I loggin to KDE, and run nvidia-smi, I can see the card and the driver installed 
(NVIDIA SMI 5.15.43.04 CUDA Version 11.7

Let me know which logs are needed and thanks for the great support

**Comment by theVakhovskeIsTaken** [comment]
> Hi, I installed using the NVIDIA option, howerver, after log in into steam OS, to realize that under "Video Card" it is listed "Mesa/X.org llvmpipe (LLVM 13.0.0" instead of nvidia driver/card
> 
> updated both steamos and full system packages (steamos-update check && steamos-update now; pacman -Syu ), reboot, system took some minutes to login into steamOS but still the same "Video Card" is shown.
> 
> If I loggin to KDE, and run nvidia-smi, I can see the card and the driver installed (NVIDIA SMI 5.15.43.04 CUDA Version 11.7
> 
> Let me know which logs are needed and thanks for the great support

I can't do anything about it. This is literally how GPU works in gamescope right now
