### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by zivgreenberg11** [holoiso-eol/holoiso#237]
Hay, I installed the software, but when I opened it, it opens a coding place that you need to write bash commeds.
What should I do?

**Comment by Grimish-ng** [comment]
Probably have to leave more information to see if its even pertinent. Imagine posting to Valve's boards with "I installed your steam but its not working."

**Comment by theVakhovskeIsTaken** [comment]
Not working on Iphone 15 pro max too👎👎👎👎👎
