### ISSUE TITLE
Provide graphics driver for VMWare

### ISSUE THREAD

**Issue by shakeyourbunny** [holoiso-eol/holoiso#241]
Can you provide graphics driver for VMWare please?

Thank you.

**Comment by LukeShortCloud** [comment]
This has been added as part of the latest HoloISO update: https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1 . I created a fork of the Mesa drivers from SteamOS and re-enabled support for all upstream drivers. These packages are all up on the AUR.

- https://aur.archlinux.org/packages/mesa-steamos
- https://aur.archlinux.org/packages/lib32-mesa-steamos

We have been using this for a while in my [winesapOS](https://github.com/LukeShortCloud/winesapOS) project. Let us know if you run into issues using it!

**Comment by theVakhovskeIsTaken** [comment]
> This has been added as part of the latest HoloISO update: https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1 . I created a fork of the Mesa drivers from SteamOS and re-enabled support for all upstream drivers. These packages are all up on the AUR.
> 
> - https://aur.archlinux.org/packages/mesa-steamos
> - https://aur.archlinux.org/packages/lib32-mesa-steamos
> 
> We have been using this for a while in my [winesapOS](https://github.com/LukeShortCloud/winesapOS) project. Let us know if you run into issues using it!

Got reverted btw :P DRI/RADV was still old, so that was pointless to use, nevertheless, thanks

**Comment by theVakhovskeIsTaken** [comment]
> Can you provide graphics driver for VMWare please?
> 
> Thank you.
> 

VMWare drivers work fine for me?
