### ISSUE TITLE
rz608-fix-git AUR Package (UPDATED)

### ISSUE THREAD

**Issue by pastaq** [holoiso-eol/holoiso#245]
Since a lot of users were having issues with the RZ608/MT7921K module in some devices I made an AUR package with the known fix. Once You've updated to kernel 5.17+ it shouldn't be needed. Installing this from the AUR or from the github source should fix the connectivity issues. This was 20% altruism and 80% people keep bugging me with troubleshooting questions privately. Be aware that once the module is working it wil break restart/suspend unless you install my other package ```aya-neo-fixes-git``` because it doesn't properly support low power mode. 

- This will not work with with kernel 5.13 as that kernel was not compiled with the mt7921e driver flag enabled. You must use kernel 5.16 for this to work. 

## Update kernel
```
sudo pacman -Sy linux
sudo mkinitcpio -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img -k 5.16.2-arch1-1.1
```
if mkinitcpio fails run ```ls /usr/lib/modules``` and replace 5.16.2-arch1-1.1 with your latest version

- I seem to be missing a step here, as there doesn't seem to be a preset for the kernel in this OS and manually generating the image never gets picked up by grub. Any assistance here would be great.

## From the AUR:
```
yay -Sy rz608-fix-git
sudo udevadm control -R
```

## From source
```
git clone https://github.com/ShadowBlip/rz608-fix.git
cd rz608-fix
sudo make install
```

If this doesn't fix you issue please open an issue on https://github.com/ShadowBlip/rz608-fix/issues

Alternatively, try [ChimeraOS](https://chimeraos.org/download) where this module works OOTB and you can get the same gamepadui/steamos experience with a little less headache.

**Comment by pastaq** [comment]
@theVakhovskeIsTaken Any help with the kernel upgrade process for this guide? I can't seem to get a new initramfs to be bootable with the core/linux install method or by updating the kernel. Grub never picks up the new image.

**Comment by theVakhovskeIsTaken** [comment]
> @theVakhovskeIsTaken Any help with the kernel upgrade process for this guide? I can't seem to get a new initramfs to be bootable with the core/linux install method or by updating the kernel. Grub never picks up the new image.

It should be same as vanilla arch, as i don't use Dracut, just run mkinitcpio -P if you encounter issues with building stuff

**Comment by theVakhovskeIsTaken** [comment]
Not required as of now, since 5.18 kernel is shipped as alternate option
