### ISSUE TITLE
Using Powerbutton in Gaming Mode shuts down Device instead of putting it to sleep

### ISSUE THREAD

**Issue by NightHammer1000** [holoiso-eol/holoiso#247]
Expected behavior would be to:
Short Press: Go to Sleep
Long Press: Bring up Power Menu

Both shutdown the Steam Deck in the Current Version.

**Comment by theVakhovskeIsTaken** [comment]
Yeah, that's the thing. Currently, i can't track power button events because there's no common way to do it.

**Comment by NightHammer1000** [comment]
I don't think this should be closed as it's still an issue that can be figured out.

**Comment by NightHammer1000** [comment]
@theVakhovskeIsTaken 
Actually. I found a fix.

Edit:
/etc/systemd/logind.conf

Change:
#HandlePowerKey=poweroff
to
HandlePowerKey=suspend

Now Gamemode will suspend instead of Powering Down.
Longpress still does not work but thats less of an Issue.

**Comment by NightHammer1000** [comment]
Even better set HandlePowerKey=ignore because, at least on the deck, the Steamclient Itself seems to handle the ACPI Events.
Now even Longpress for the Powermenu Works!

**Comment by theVakhovskeIsTaken** [comment]
> @theVakhovskeIsTaken 
> Actually. I found a fix.
> 
> Edit:
> /etc/systemd/logind.conf
> 
> Change:
> #HandlePowerKey=poweroff
> to
> HandlePowerKey=suspend
> 
> Now Gamemode will suspend instead of Powering Down.
> Longpress still does not work but thats less of an Issue.

Can you show the original output on deck image, i'm not near my PC to check steamos image

**Comment by NightHammer1000** [comment]
Sorry. Can't.
Have HoloISO installed permanently now that the Power button works.
