### ISSUE TITLE
Can't install and boot

### ISSUE THREAD

**Issue by LoneFennecFoxy** [holoiso-eol/holoiso#248]
I've installed and tried both the nvidia and Intel method, but neither boot, up to the deck experience, I've noticed a couple errors while installing though but that's during install, not something I can control![image](https://user-images.githubusercontent.com/74285788/171484179-e8fe675c-fe86-4c8a-862b-c289c35f3e4d.jpeg)

**Comment by LoneFennecFoxy** [comment]
Gonna add that my system is a lenovo legion y530
The specs are:
CPU: Intel i7 8750H
Ram: 32gb 2666 ddr4 ram
Onboard GPU: Intel HD 630
GPU: Nvidia gtx 1050 ti
Wireless: Intel AC 9650
Ethernet: RTL8111

**Comment by LoneFennecFoxy** [comment]
Just going to add that this is where I get stuck during boot![image](https://user-images.githubusercontent.com/74285788/171527577-28c578bb-9124-4e70-a6ce-730b7bb562a3.jpeg)

**Comment by zuralon** [comment]
my i7 is a7th geng but same issue 
i try install intel igp and nvdia gpu and try 2 linux vertion and i get stuck to loadinginitial ramdisk

**Comment by theVakhovskeIsTaken** [comment]
> Gonna add that my system is a lenovo legion y530
> The specs are:
> CPU: Intel i7 8750H
> Ram: 32gb 2666 ddr4 ram
> Onboard GPU: Intel HD 630
> GPU: Nvidia gtx 1050 ti
> Wireless: Intel AC 9650
> Ethernet: RTL8111

You need to disable iGPU or connect external HDMI display, because gamescope isn't able to switch GPU

**Comment by zuralon** [comment]
how can i disable my igpu if no omption in bios ?

**Comment by LoneFennecFoxy** [comment]
> > Gonna add that my system is a lenovo legion y530
> > The specs are:
> > CPU: Intel i7 8750H
> > Ram: 32gb 2666 ddr4 ram
> > Onboard GPU: Intel HD 630
> > GPU: Nvidia gtx 1050 ti
> > Wireless: Intel AC 9650
> > Ethernet: RTL8111
> 
> You need to disable iGPU or connect external HDMI display, because gamescope isn't able to switch GPU

It still doesn't work with the Intel GPU drivers installed instead of the nvidia one. Is that still related or something else?
