### ISSUE TITLE
No Headphone audio in game mode

### ISSUE THREAD

**Issue by blake-haas** [holoiso-eol/holoiso#249]
In KDE desktop the headphones (aux) work fine. In game mode there is no audio. I tried switching sources. No go. My device is an Aya neo. It used to work fine until the latest steam update. It seems like every other steam update breaks something.

**Comment by kovspbru** [comment]
I have Aya neo 2021 pro - and for me headphones are not working when plugged in. Reboot or sleep\wake enables them.
Did not try it in decktop mode btw.
