### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by dravpin** [holoiso-eol/holoiso#25]
i was making my way through the install and now im stuck after the part where it downloads the packages https://imgur.com/eM2sfHo https://imgur.com/7TgAgOU it says its installed so i restart and get https://imgur.com/VEOzIv6 so obviously thats not right
thats only one error tho it changes every time i wipe my system and retry the install
the error before this one it was something about missing keys and then it started asking me if i wanted to delete a bunch of stuff which ended https://imgur.com/VEOzIv6 here again
is there something im doing wrong?

**Comment by theVakhovskeIsTaken** [comment]
Interesting, that's kinda strange. Can you boot into Windows environment and run `diskpart`, `sel dis *`, `clean`?
 
Looks like your drive is having a bad day....

**Comment by dravpin** [comment]
> Interesting, that's kinda strange. Can you boot into Windows environment and run `diskpart`, `sel dis *`, `clean`?
> 
> Looks like your drive is having a bad day....

uh you see im running it in a vm its a fresh virtual disk which makes it even stranger

**Comment by dravpin** [comment]
> Interesting, that's kinda strange. Can you boot into Windows environment and run `diskpart`, `sel dis *`, `clean`?
> 
> Looks like your drive is having a bad day....

heres the other error i was talking about https://imgur.com/EGS8rVp saying yes gives me this https://imgur.com/tybipRu

and after doing it for all of them it starts asking me to delete packages cause it doesnt have the keys or there corrupted and after saying no to deleting all of them it says the install is complete and to restart so i do and i end up here again https://imgur.com/VEOzIv6 which i assume it means something didnt go right

**Comment by dravpin** [comment]
It seems it always at the keyring part that something goes wrong screenshots

https://imgur.com/4MTTZcq 

https://imgur.com/pZ48e63

https://imgur.com/EODYa4R
