### ISSUE TITLE
Holos-20220602_1045 install fails (Generated ISO)

### ISSUE THREAD

**Issue by ruineka** [holoiso-eol/holoiso#250]
I created the ISO to include the latest commits and the installer fails when trying to use the Intel option.

![PXL_20220602_155854457.jpg](https://user-images.githubusercontent.com/16360335/171674041-07543d6b-45d2-42c2-8d87-a15e05ee4878.jpg)

**Comment by huchenghe001** [comment]
me too
Maybe there's something wrong with steam's network
I tried 20 times without success

**Comment by konradknitter** [comment]
I had same issue few times over Wi-Fi. One of packages returned 404, install script just continued - it do not retries, or gives option to the user.
This could be improved.

I connected Ethernet cable and it finally finished. Did you try Ethernet?
