### ISSUE TITLE
Unable to mount external SSD/HDD

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#253]
I know this isn't meant to be used for tech support.
All my external drives cannot be mounted for some reason, on a vanilla arch I'm able to mount NTFS drives without issues but it doesn't work here for some reason and unfortunately I don't know how to troubleshoot this.

My device is an Aya Neo FE.

**Comment by theVakhovskeIsTaken** [comment]
Yeah, the kernel is bit older, you should get the ntfs3 backport on aur: yay -S ntfs3-dkms
