### ISSUE TITLE
stuck at (loading initial ramdisc)

### ISSUE THREAD

**Issue by BrimfieldKristofferkrum** [holoiso-eol/holoiso#254]
rtx a2000 12gb
amd 5700g
asus rog strix x570i
using nvme as storage and happens after fresh install of the last release will test with todays.

**Comment by jasonfish** [comment]
Same issue here on my Intel NUC.

**Comment by Noobot9k** [comment]
I get the same when I remove my gpu and reinstall with intel graphics drivers. 

When I install my gpu and install with the nvidia drivers I get the black screen everyone is talking about.
