### ISSUE TITLE
Installs good - Boots to Grub, choose SteamOS, then black screen

### ISSUE THREAD

**Issue by CanadianIceTech** [holoiso-eol/holoiso#256]
Here's the setup currently:

Intel H510M-A Pro Motherboard
Core i5-10400 CPU
8GB Ram
250GB NVME Drive
No Video card (trying to use onboard hdmi output)

Due to budget constraints, trying to use the onboard video for now and see if it'll maybe run as an emulation station for now (NES/SNES, N64 if possible). 

During the install I selected the Intel GPU for the GPU drivers
Rebooted, got to GRUB. Chose "SteamOS". Continues to boot SteamOS, and ends up at a blank black screen.

Is a GPU mandatory for this, or is there a way to make it work with onboard video? I made sure the CPU I got had the onboard video capabilities as it was initially going to be used to operate our CNC router and didn't want to add a video card to save on costs.

**Comment by Esei10** [comment]
I have a similar thing happening to me. My machine is an old laptop with and INTEL iGPU and an AMD dGPU.  I tried installing with AMD and INTEL drivers. Both times only the recovery option could get to a shell (hitting control+D gets me a black screen). The fallback option for linux-neptune-dri gives me a quick flash of text saying "failed to start linux bios ... update". When I press the power button I see a flash of text: 4 lines of "... amd_ring_0 is already ..." an then a single line I cant read.
The fallback option for linux does the same exact thing, only the "failed to start linux bios ... update" never appears.

**Comment by LillyLaFrog** [comment]
Same thing is happening to me, I don't have a gpu on this computer

**Comment by Noobot9k** [comment]
I am having the same problem with an i5 4460 and a gtx950

**Comment by Lolo280374** [comment]
Hey there, got the same issue as you with that black screen.
It appears that it tries to force the boot in gamescope on startup, so, to disable it you have to boot in the recovery mode of HoloISO (use the recoveryinit command to see options to disable/enable it.)
Then, you'll be able to go to KDE Plasma, and try to get your drivers installed/working. (Tho, i have no idea how to install drivers)

**Comment by deftdawg** [comment]
As an alternative to recovery mode, sometimes you can get to a text tty from the black screen after Jupiter bios updater failed by pressing 'ctrl+alt+F4` or 'ctrl+alt+F5`, logging in and then edit the sddm.conf mentioned in `steamos-session-select` (use `which` to find it).

**Comment by paegan69** [comment]
Ok I have a similar issue but slightly different situation. I have a busted HP laptop with AMD video so I thought it would make and awesome "HoloDeck" device. Unfortunately after a flawless installation upon reboot I get a black screen even though the HD leds are flashing indicating stuff is still happening. 
Where my situation is a bit different from the norm is that the laptop is connected to a TV via HDMI since the native LCD has long since been destroyed. From previous distro experiences it would seem that the OS video output is defaulting to the LCD screen which is non-existant and leaving all other outputs blank.
My main question is there a config file or startup switch that I can apply to force video output to HDMI after boot? GRUB loads fine its just the wrong output after that.

**Comment by deftdawg** [comment]
Figure out how to enable ssh and then go in through the network, if it has Ethernet or USB Ethernet that's probably easier than WiFi (which may or may not have firmware)... Good luck

> Ok I have a similar issue but slightly different situation. I have a busted HP laptop with AMD video so I thought it would make and awesome "HoloDeck" device. Unfortunately after a flawless installation upon reboot I get a black screen even though the HD leds are flashing indicating stuff is still happening. 
> Where my situation is a bit different from the norm is that the laptop is connected to a TV via HDMI since the native LCD has long since been destroyed. From previous distro experiences it would seem that the OS video output is defaulting to the LCD screen which is non-existant and leaving all other outputs blank.
> My main question is there a config file or startup switch that I can apply to force video output to HDMI after boot? GRUB loads fine its just the wrong output after that.

**Comment by paegan69** [comment]
> Figure out how to enable ssh and then go in through the network, if it has Ethernet or USB Ethernet that's probably easier than WiFi (which may or may not have firmware)... Good luck

Hi, thx for the reply! ok I managed to get to a command prompt with `ctrl+alt+F4/F5` but i have no idea what to do next to force the output switch, any hints?

EDIT UPDATE: Managed to get open ssh installed and can connect remotely. Unfortunately at this point i'm kind of stuck. After doing some reading I tried running xrandr to see what's detected but all i get is `Can't open display` so i have no no idea what to do next...

UPDATE 2: FInally got deparate and ran `journalctl` and digging through the logs it would seem that the amd drivers don't seem to recognise my APU video
```
Sep 11 19:33:28 beatdown kernel: amdgpu 0000:00:01.0: amdgpu: get invalid ip discovery binary signature from vram
Sep 11 19:33:28 beatdown kernel: amdgpu 0000:00:01.0: amdgpu: amdgpu_discovery is not set properly
Sep 11 19:33:28 beatdown kernel: amdgpu 0000:00:01.0: amdgpu: failed to read ip discovery binary from file
Sep 11 19:33:28 beatdown kernel: [drm:amdgpu_discovery_set_ip_blocks [amdgpu]] *ERROR* amdgpu_discovery_init failed
Sep 11 19:33:28 beatdown kernel: amdgpu 0000:00:01.0: amdgpu: Fatal error during GPU init
Sep 11 19:33:28 beatdown kernel: amdgpu 0000:00:01.0: amdgpu: amdgpu: finishing device.
Sep 11 19:33:28 beatdown kernel: amdgpu: probe of 0000:00:01.0 failed with error -22
```

and `lspci -k` gives me:
```
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R6 Graphics]
        DeviceName: Onboard IGD
        Subsystem: Hewlett-Packard Company Device 22a9
        Kernel modules: amdgpu
00:01.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri HDMI/DP Audio Controller
        Subsystem: Hewlett-Packard Company Device 22a9
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
```

I did install using the AMD video option so hopefully some1 can use this info to point me in the right direction.
