### ISSUE TITLE
Stuck at a different backscreen with every advanced option

### ISSUE THREAD

**Issue by Esei10** [holoiso-eol/holoiso#257]
My machine is an old laptop with and INTEL iGPU and an AMD dGPU. I tried installing with AMD and INTEL drivers. Both times only the recovery option could get to a shell (hitting control+D gets me a black screen). The fallback option for linux-neptune-dri gives me a quick flash of text saying "failed to start linux bios ... update". When I press the power button I see a flash of text: 4 lines of "... amd_ring_0 is already ..." an then a single line I cant read.
The fallback option for linux does the same exact thing, only the "failed to start linux bios ... update" never appears.
The normal option for both linux and neptune-linux-dri give me a black screen immediately.

**Comment by deftdawg** [comment]
Gamescope isn't working... Drop down to a text tty `ctrl+alt+F4 or F5` then login and use `steamos-session-select` to get to a desktop. This is assuming your machine isn't hard locking.
