### ISSUE TITLE
My laptop won't start HoloOS

### ISSUE THREAD

**Issue by ayamasasaki** [holoiso-eol/holoiso#258]
I tried to install it in all methods how to install it. I put the stick to install the HoloISO system and then select NVIDIA (I have an Nvidia GTX 1650 card), then wait for the drivers to install, reboot and then remove the stick at the end and then it says "Media check" persentece ... '', meaning I can't find my holoiso hard drive but when I install another arch linux like Endervor OS it works, I would also like to understand why HoloISO doesn't work for me.

I have a laptop MSI GF75 Thin 9SC and my spec is i7 gn9 and GTX 1650

**Comment by ayamasasaki** [comment]
I deactivated the secure boot and I set it to UEFI and I set everything, in the installer arch it sees my hard drive but when I boot it to enter holoiso it doesn't do anything, it starts the laptop and after it does little, it actually says that it does not have a hard drive to open the system.

right here I have video how I installed:

https://www.youtube.com/watch?v=IS5U3Ntz9JA
https://www.youtube.com/watch?v=HKVlxZzEyNA

**Comment by Wedon2033** [comment]
I have the same problem. After installation, it does not see the boot disk where the OS was installed. MOTILE laptop, cpu 3200U, 16gb RAM, 480gb SSD

**Comment by andras-szuecs** [comment]
I had a similar experience, it wouldn't work for most settings. But if I selected the second option(compatibility, but not writing to ram), and iGPU instead of dGPU, then it magically started working. Is this some Nvidia problem?

Btw I have a razer blade with intel i7-10750H and rtx 2070

**Comment by ayamasasaki** [comment]
I try again to install HoloOS on my laptop  GF 75 Thin 9SC MS-17F2 and HoloOS don't recognize my HDD and I want to know why because I have all recommended specification and I don't know why is not recognize my HDD and won't start.

Spec:

CPU - i7 9750H with UHD 630U
GPU - GTX 1650
RAM - 16 Gig samsung

https://youtu.be/tmPuxuzFLvM

**Comment by TheGithubJoshua** [comment]
@theVakhovskeIsTaken keeps closing major issues with no fix, not even marked as Won't fix.

**Comment by theVakhovskeIsTaken** [comment]
@TheGithubJoshua I think reading readme will makes my decisions clear as day
