### ISSUE TITLE
Unable to mount beta 3.2 installation

### ISSUE THREAD

**Issue by Ew4n1011** [holoiso-eol/holoiso#259]
When getting to the mounting process on booting the installation media (beta installed from github actions) it tries to mount the drive for the installation media (`Mounting '/dev/disk/by-label/HOLOISO202205'`) for 30 seconds and then fails, booting to rootfs.

Update: Using a USB that flashes when it is being used, it seems to shut off all usb ports upon reaching that stage.

**Comment by theVakhovskeIsTaken** [comment]
i have one sole question

why did you go straight for CI builds?

**Comment by Ew4n1011** [comment]
It was to see if it could fix an error that was happening with the release build, later seeing your reply on the telegram group saying my graphics card won't be compatible no matter what, I'll close this issue now.
