### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by reasonchimpanzee** [holoiso-eol/holoiso#26]
Attempting to install on a specific partition throws an error saying partitions 1, 2, etc have been written, but we have been unable to inform the kernel of the change. Typing either ignore or cancel produces the same error and typing it enough results in trying to continue the installation but failing
![E6A8A2FE-91D2-49D9-AEDB-9BD9AA5E66A0](https://user-images.githubusercontent.com/105034981/167069855-8620c5e7-28f2-4fed-8996-e4a784f044cf.jpeg)

**Comment by firemdkfighter** [comment]
It is necessary to choose a disk, not a partition
