### ISSUE TITLE
Wont install due to Internet?

### ISSUE THREAD

**Issue by hawari21** [holoiso-eol/holoiso#263]
Hello there,

I have a problem here with Steam OS installation, so today i was installing Steam OS using balena ethcer, so far so good. Until TTY pops screen appear and i followed the instruction by typing "Holoinstall", and it really takes a couple minute until something like this show up "Internet connection available, existing", then tried to typing "Holoinstall" again but it still same. My internet connection is connected by lan and i watch a youtube video about installing Steam OS 3, and it supposed partition part appear after typing "Holoinstall" but in my case it is not...

Anyway, is there a way i can fix this, or did i just missing something?

**Comment by Mrpuppyz** [comment]
Can you run 
ping google.com 
to make sure you are getting a connection?
