### ISSUE TITLE
Audio crackling

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#264]
I have audio crackling everywhere, in KDE and in SDUI. My audio setup is through the TV via HDMI, amdgpu RX 470

I know that this setup works flawlessly on a vanilla arch with pipewire...
The issue gets fixed by doing `systemctl --user restart pipewire-pulse` but doesn't persist after reboot.

It stays fixed when switching to desktop but comes back when switching to SDUI. I looked in journalctl and found that running steam (in SDUI) crashes pipewire-pulse module echo-cancel.

**Comment by GFOXSH** [comment]
Good afternoon! Try this:
`sudo mv /usr/lib64/pipewire-0.3/libpipewire-module-echo-cancel.so /usr/lib64/pipewire-0.3/libpipewire-module-echo-cancel.so.bak`
This is not entirely correct, but I could not find a config that loads the echo-cancel library, but it works fine for me.

**Comment by aleksasiriski** [comment]
Just switched to ChimeraOS since I saw that they have SDUI as well.
