### ISSUE TITLE
Stuck at “ failed to start Jupiter bios update service”

### ISSUE THREAD

**Issue by shaun9111** [holoiso-eol/holoiso#265]
Tried both Belena etcher and Rufus using dd. my hardware is Msi RX 5704gb, Ryzen 3600,  32 GB ram and Asus prime b550 board. Installing to 500gb internal ssd.

**Comment by g3nsvrv** [comment]
same here

**Comment by shaun9111** [comment]
> 

I was able to bypass the issue by typing holoiso-disable-sessions in the recovery menu which you get to during the boot up process but then I got stuck at the login screen unable to select a user to type a password. I did a google and found a comment that says your created username can’t have a capital letter in it. So I reinstalled but I haven’t logged in yet because I’m out doing laundry. I’ll let you know if it works.

**Comment by shaun9111** [comment]
> same here

So it did fix it but I have other problems now lol

**Comment by g3nsvrv** [comment]
> > 
> 
> I was able to bypass the issue by typing holoiso-disable-sessions in the recovery menu which you get to during the boot up process but then I got stuck at the login screen unable to select a user to type a password. I did a google and found a comment that says your created username can’t have a capital letter in it. So I reinstalled but I haven’t logged in yet because I’m out doing laundry. I’ll let you know if it works.

worked for me, thank you <3

**Comment by shaun9111** [comment]
You’re welcome 😁

**Comment by Gamerseee** [comment]
> > 
> 
> I was able to bypass the issue by typing holoiso-disable-sessions in the recovery menu which you get to during the boot up process but then I got stuck at the login screen unable to select a user to type a password. I did a google and found a comment that says your created username can’t have a capital letter in it. So I reinstalled but I haven’t logged in yet because I’m out doing laundry. I’ll let you know if it works.

Were do you write that in details ? Because i don't know exactly and i still have the issue.
