### ISSUE TITLE
Unable to access gamescope - GTX1050

### ISSUE THREAD

**Issue by Lolo280374** [holoiso-eol/holoiso#267]
Hello there,
I'm trying to get HoloISO installed on my Laptop, with a GTX 1050/Intel UHD Graphics 630 iGPU.
When installation, i choosed the NVIDIA option, and once reboot i got a black screen.
Tried with this time the Intel option, same thing.
I resulted in disabling auto-login SDDM feature, which allows me to login to KDE. However, no gamescope.
I tried running `gamescope` in terminal,  which said:
`vulkan: failed to find physical device, Failed to initialise vulkan.`
Any ways of getting Gamescope to work with my NVIDIA GPU/Intel iGPU?

**Comment by theVakhovskeIsTaken** [comment]
_*No matter how great job NVIDIA and plagman has done on adapting each other, this combination MAY still be buggy, please do not report any problems to me aside from OOBE, session launching and switching and overlay management, if you encounter any problems in-gamescope, please open issue in https://github.com/Plagman/gamescope/issues_
