### ISSUE TITLE
Virtual Machine support

### ISSUE THREAD

**Issue by XargonWan** [holoiso-eol/holoiso#27]
Is it possible to make it bootable form VMs, expecially VirtualBox?

**Comment by g3nsvrv** [comment]
> Is it possible to make it bootable form VMs, expecially VirtualBox?

Works on VMware using Kernel 5 64 bits or higher
(not official support, but at least I was able to setup using UEFI boot, and installing the open-vm-tools)
![image](https://user-images.githubusercontent.com/11720535/167167363-dffd6061-508c-4208-ad96-3599de21fc9a.png)

**Comment by korejan** [comment]
Works in qemu, I had to install edk2-ovmf to enable UFEI booting. I can't login into a wayland session though.
![unknown](https://user-images.githubusercontent.com/64199710/167253974-a5b18883-a0e4-42a7-bf71-7848f2a6e422.png)

**Comment by ubergeek77** [comment]
@korejan Would you be able to share how else you were able to get this running in KVM? You seem to be using `virt-manager`. I am as well. I booted the install .iso in UEFI mode, and the install goes fine, but the first boot after install just results in a black screen. I already have `ovmf` installed on Ubuntu, and the KVM is absolutely booting in UEFI mode:

![image](https://user-images.githubusercontent.com/3455585/171077913-73fcb377-6859-47e1-8c13-0d453baf05f6.png)

I also tried in Hyper-V, with similar results: #104 

By chance, are you passing through a GPU? Or added any additional hardware to make it work in KVM? The issues I'm seeing on both Hyper-V and KVM seem to be related to the lack of a GPU. If that's not it, then I can't wrap my head around why else this won't boot, so I'm curious as to how you got yours working.

Any notes on how you got yours working would be much appreciated.

**Comment by deftdawg** [comment]
@ubergeek77 

I'm able to get to the desktop in VirtualBox with the following:
- `Enable UEFI` in System
- 64MB + 3D enabled video

Once HoloISO finishes installing Arch and the system reboots, make sure your VM is still capturing keyboard input (move down and up in the grub menu to check).  Start SteamOS.

When the screen goes black, the system tried to start GameScope mode, use `Ctrl+Alt+F4` or `Ctrl+Alt+F5` to drop down to non-graphical tty terminal, if this doesn't work you may have to reboot and try again.

![image](https://user-images.githubusercontent.com/4991612/173992432-9d0b1703-de4f-4647-adfb-3c23ecc04d66.png)

You should get a `login:` prompt and login as `root` or your user(+ `sudo su -`) (see above); then you'll need to run the following shell commands:

```sh
pacman -S virtualbox-guest-utils # Essential
systemctl enable vboxservice # Essential
pacman -S bat htop hwinfo neofetch # Optional
systemctl enable sshd # Optional
ip a # Optional - take note of your IP if you need to SSH in
steamos-session-select plasma-persistent # Essential - tells OS to start in Plasma Desktop mode; system will reboot immediately
```

![image](https://user-images.githubusercontent.com/4991612/173992679-e2796574-d2db-4a07-9347-95692af0a11a.png)

Good hunting! 😄

**Comment by ubergeek77** [comment]
Thanks a lot @deftdawg ! I never would have guessed it needed guest utils.

> steamos-session-select plasma-persistent

Does Game Mode work at all in the VM?

Either way, this is great info. I don't use VitualBox, but this is enough of a hint that I can hopefully get it working too (and, if not, suck it up and use VirtualBox 😅 )

**Comment by deftdawg** [comment]
Think virtualbox needs it's guest-utils for accelerated video, you might be able to do something more fancy with qemu/kvm and virt-manager(GPU pass through?) , but I'm trapped on windows for now.

I very much doubt gamescope (aka "Gaming mode") will work at all with crappy the low-mem VMSVGA virtualbox video card... Maybe you'll have better luck with virt-manager.

**Comment by enderpirate98** [comment]
Can I get the exact vm settings so that I know things will work 100%?

**Comment by QHM-MING** [comment]
> Works in qemu, I had to install edk2-ovmf to enable UFEI booting. I can't login into a wayland session though. ![unknown](https://user-images.githubusercontent.com/64199710/167253974-a5b18883-a0e4-42a7-bf71-7848f2a6e422.png)

hello，I want to install holoISO in my qemu ,but failed .can you shou me your qemu parameter video adapter and  Display Spice . 
by the way can you zip your teamos.qcow2 to my email hc610907195@gmail.com
