### ISSUE TITLE
ISO Update 1 holoinstal eating carriage return

### ISSUE THREAD

**Issue by pastaq** [holoiso-eol/holoiso#270]
Attempting to test kernel 5.18.1 on the latest ISO. I was able to connect to WiFi on RZ608 and enter commands as normal, but the install script is outputting ^M, the carriage return symbol, to terminal instead of entering text when asking for barebones vs decksperience. I am unable to proceed with the install.

**Comment by theVakhovskeIsTaken** [comment]
This is strange, i just tested it and it worked fine

**Comment by pastaq** [comment]
Issue seems to have resolved itself, wasn't present when I tried to replicate. Closing for now. Will reopen if it happens again.
