### ISSUE TITLE
GTX 9xx support just isn't there.

### ISSUE THREAD

**Issue by Noobot9k** [holoiso-eol/holoiso#271]
[Others](https://github.com/theVakhovskeIsTaken/holoiso/issues/262#issue-1260909682) are having this issue too.

my EVGA GTX 950 Silent Cooling just doesn't work. Gets stuck on [a black screen](https://github.com/theVakhovskeIsTaken/holoiso/issues/257#issue-1260675983) after installation and during boot.

Intel graphics weren't working either for my i5 4460. Same problem as with the 950.

When I swapped to a 1070ti I was able to boot into the OS, go through setup, and interact with the interface.

P.S. don't use an Intel i5 4460 with SteamOS. It may be meant to run on low-end hardware but not ancient hardware. I couldn't even launch Sonic Mania and the interface was a slideshow.

**Comment by doxzilla** [comment]
> P.S. don't use an Intel i5 4460 with SteamOS. It may be meant to run on low-end hardware but not ancient hardware. I couldn't even launch Sonic Mania and the interface was a slideshow.

That seems like more of an Nvidia driver issue; my test rig is a i7-4770k + RX480 and I can run Cyberpunk 2077 set to the Steam Deck preset graphics config at a solid 30fps.

**Comment by Lolo280374** [comment]
Hey there, got the same issue with that black screen.
It appears that it tries to force the boot in gamescope, so to disable it you have to boot in the recovery mode of HoloISO (use the recoveryinit command to see options to disable/enable it.)
Then, you'll be able to go to KDE Plasma, and try to get your drivers installed/working.

**Comment by Mohandevir** [comment]
I was able to download and install Nvidia drivers 515 for my GTX980m and desktop works fine, but Gamescope refuses to launch. Any idea?

Great job, by the way,
Thanks!

**Comment by psclrzn** [comment]
Correct me if I am wrong, but I think the 515 driver only supports Turing or Later GPUs.  So that would mean at 16xx, 20xx and above.

https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus

**Comment by Mohandevir** [comment]
I think I get your point... Nvidia still support Maxwell gpu with driver updates, but not the with the open-gpu-kernel-modules:
"The open-gpu-kernel-modules can be used on any Turing or later GPU"

**Comment by byzocker** [comment]
> Correct me if I am wrong, but I think the 515 driver only supports Turing or Later GPUs.  So that would mean at 16xx, 20xx and above.
> 
> https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus

The 515 driver works on 900 series gpus

Edit: just not the kernel module

**Comment by Mohandevir** [comment]
> > Correct me if I am wrong, but I think the 515 driver only supports Turing or Later GPUs.  So that would mean at 16xx, 20xx and above.
> > https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
> 
> The 515 driver works on 900 series gpus
> 
> Edit: just not the kernel module

And let me guess... The open source kernel module is required by Gamescope?

**Comment by byzocker** [comment]
> > > Correct me if I am wrong, but I think the 515 driver only supports Turing or Later GPUs.  So that would mean at 16xx, 20xx and above.
> > > https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
> > 
> > The 515 driver works on 900 series gpus
> > 
> > Edit: just not the kernel module
> 
> And let me guess... The open source kernel module is required by Gamescope?

As far as I know no, it didn't work because it required certain vulkan Extensions that weren't in the Nvidia driver until 515

**Comment by Mohandevir** [comment]
> > > > Correct me if I am wrong, but I think the 515 driver only supports Turing or Later GPUs.  So that would mean at 16xx, 20xx and above.
> > > > https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
> > > 
> > > 
> > > The 515 driver works on 900 series gpus
> > > Edit: just not the kernel module
> > 
> > 
> > And let me guess... The open source kernel module is required by Gamescope?
> 
> As far as I know no, it didn't work because it required certain vulkan Extensions that weren't in the Nvidia driver until 515

But since I installed the driver from the nvidia download page, shouldn't it work with Gamescope, in this case? Are there required files that are getting removed in the process (removing original driver)? I just know that the default driver is not working at all (no Gamescope and no games will launch) and on the desktop, games will launch with driver 515, downloaded from Nvidia. Still, Gamescope refuses to launch.

**Comment by mitcoes** [comment]
Would GTX 750 TI, being Maxwell powered too, considered a  part of the 9xx ish GPUs family?

**Comment by TheBlueOompaLoompa** [comment]
@Mohandevir You may have to reinstall holoiso, in holoiso setup you need to pick the option for nvidia gpus and it should install the proper drivers automatically. Never download drivers from Nvidia's website when using linux, the offical Nvidia installer causes all kinds of dependency hell down the line and often doesn't work.

**Comment by Mohandevir** [comment]
Might not be the right thread, but holoiso is installed on two computers... The other is a Ryzen 5 3600 with GTX 1660 Super. I can't get Gamescope to recognized my GPU. It's stuck on mesa driver which is totally useless for Nvidia GPUs. Tried running Witcher 3 thus and it's a slideshow. On the desktop (X11 probably), it runs just fine.

To be sure, I booted in rescue mode and did the following, on a brand new install:
nvidia-modprobe
pacman -S dkms nvidia-dkms nvidia-utils opencl-nvidia

Nothing works.

Did I miss something?

Edit: For the record, with the Nividia driver downloaded from nvidia, I have good performances but weird artifacting, when I try to force Gamescope in another resolution ratio than the Steam Deck's native one (ex: playing in 1920x1080 vs 1200x800). I must force it to 1920x1200 and than reduce it (in game) to 1920x1080 which gives black bezels on the sides.

**Comment by Mohandevir** [comment]
Could it be related to this?
https://github.com/Plagman/gamescope/issues/492

**Comment by Mohandevir** [comment]
> @Mohandevir You may have to reinstall holoiso, in holoiso setup you need to pick the option for nvidia gpus and it should install the proper drivers automatically. Never download drivers from Nvidia's website when using linux, the offical Nvidia installer causes all kinds of dependency hell down the line and often doesn't work.

Just did that on my GTX980m based laptop (discrete graphics only, in bios)... My goal is to use it as a console, hooked to my TV with Gamescope, but I will wait for a futur update. I'll be using it in desktop mode, in the meantime.

**Comment by Grotstompa** [comment]
My 2080 TI seems to be supported on the list, and I can't get SteamOS to load either. I'm currently stuck on, "loading initial ramdisk". In fact, the only way I could get it to even install was by selecting "HoloOS More Compatibility", if I selected Neptune it would sit on "Triggering uEvents". Maybe I'm just being a n00b.

It seems this build isn't ready for Nvidia without a lot of shotgun effect tinkering either way, I think I'll pass on this until it's updated to support Nvidia better. Unless someone has a simple solution. I wonder how long we have until Steam officially launches their desktop version? Cheers

**Comment by Mohandevir** [comment]
I don't know where to write this and I didn't want to open a new issue (since it's not one). It's just a little update to say that with a fresh install, with the latest iso, my GTX 1660 Super is now supported, recognized and the nvidia driver is correctly installed, ootb.

I will try on my GTX980m laptop later.

Thanks for your awesome work!

**Comment by theVakhovskeIsTaken** [comment]
You're correct so far, according to feedbacks.

Oldest GPU that works fine with gamescope is indeed pascal+
