### ISSUE TITLE
onexplayer mini   Screen orientation problem

### ISSUE THREAD

**Issue by huchenghe001** [holoiso-eol/holoiso#278]
Enter the TTY terminal mode: ctrl+alt+f2 return to the graphical desktop: ctrl+alt+f1, in the handheld mode, but I use echo x > /sys/class/graphics/fbcon/rotate_ All, the handheld mode is still reversed. Is there any way to adjust the direction of the handheld mode to the positive direction? The desktop mode can set the display direction, but the handheld mode cannot

**Comment by alansari** [comment]
clone and build this git repository:
https://github.com/ruineka/gamescope-onexplayer
Replace the gamescope in /usr/bin by the one you built and voila gamescope session will be in the correct orientation.
