### ISSUE TITLE
Virtio Drivers

### ISSUE THREAD

**Issue by Trozmagon** [holoiso-eol/holoiso#279]
Not an issue, just a question as I can't test it myself just yet. Does anyone know if virtio drivers are included?

Thanks.

**Comment by ghost** [comment]
it seems to recognize virtio for me

**Comment by Trozmagon** [comment]
Nice one, thanks for reporting that here. I'll be building a VM on Unraid using a passed through RX 5600 XT sometime next week, just waiting on parts to arrive. I'll post my findings here once I'm done.

**Comment by ghost** [comment]
It's more like virtio is supported by vanilla Arch rather than SteamOS.

**Comment by Trozmagon** [comment]
> It's more like virtio is supported by vanilla Arch rather than SteamOS.

Of course, but what I'm unaware of is what's been removed from Arch. I know Valve released a massive update months ago reducing the image size to under 10gb, to achieve that they had to remove some things. Either way I have all the parts now to build my new server so I'll have a full update on what's working and what's not this week :)

**Comment by ghost** [comment]
Well, I don't think that valve has removed anything from the default arch kernel but rather only optimized or added some stuff.
Also: 10GB removed doesn't say anything. A default arch install with linux, linux-firmware, vim/nano, sudo, efibootmgr, grub and dhclient comes in with about 130 packages - download size about 120MB - extracted on disk roughly 250MB. So whatever valve removed was obvious nothin on the base system.
The current steam deck recovery image comes with quite a lot heavily compressed. If they thin it out by remove redundant stuff like a 2nd image or so this should have no consequences down to the arch base system.

**Comment by Trozmagon** [comment]
Regardless I've now tested it and it works fine.
