### ISSUE TITLE
Default home partition

### ISSUE THREAD

**Issue by pricedspacefan** [holoiso-eol/holoiso#282]
When installing the OS it defaults to the root partition which is 20gb for me, how can I combine the separate home partition, and the root partition. Or how can I default to the larger user home partition?

Appreciate any help.

**Comment by Shivox** [comment]
It might be that you have installed an older ISO, it was fixed in the latest build with this [commit](https://github.com/theVakhovskeIsTaken/holoiso/commit/01981e466c0519e041228a53a21d1bedc53e119c) it the installation script was missing the `mount` command.

**Comment by pricedspacefan** [comment]
> It might be that you have installed an older ISO, it was fixed in the latest build with this [commit](https://github.com/theVakhovskeIsTaken/holoiso/commit/01981e466c0519e041228a53a21d1bedc53e119c) it the installation script was missing the `mount` command.

Historically I have been clean installing the older iso's on my nvme0n1 device, I used the latest release and it has the root partition installed and set as the default, The rest of the space is used by the created user i made, Another /home partition.

When using the newest release I think it goes free space, then the smaller partition, then 20gb root, then 450 gb home partition, left to right.

I will clean install again when in front of the device.

**Comment by pricedspacefan** [comment]
Well last night, I used [HoloISO: Lord Gaben's treasure (snapshot5)](https://github.com/theVakhovskeIsTaken/holoiso/releases/tag/snapshot20220526.1355-1). And it had the root partition but automounted the user 450gb partitition as the primary.

Maybe it can be resolved in future updates by backing up the home folder to the root partition? If the goal is to keep the /home data backed up? 

I still a linux newb. I could have tried figuring out how to change the automounting configuration file, but in the limited time that I had, I could not find any quick answers, reinstalling the os -_-, is how i fixed it LOL.
