### ISSUE TITLE
Vibration not working with Aya Neo

### ISSUE THREAD

**Issue by FormBurden** [holoiso-eol/holoiso#283]
Yesterday I installed HoloISO on my Aya Neo, works great, except for the fact that I cannot get any game to vibrate at all. Before HoloISO I had regular Arch Linux and vibration worked correctly in games with Steam. I did test with the joyutils to see if vibration works, and it does, plus I tested in a website in chromium that tests for controllers and vibration works correctly. 

Modules are loaded correctly with usbhid and joydev, I also have the wifi fixed that others were running into as well as the aya-neo-fixes if any of that even matters.

What I have tried:

1. Using a controller to see if the situation was the same. It is. I tried with my KingKong Pro 2 controller which mimics the xbox 360 controller if using wired, same issue, no vibration. Using bluetooth with the controller makes it an Xbox One Controller. The steam client is able to identify the controller through a vibration, which only seems to be a thing on bluetooth, since the Xbox 360 cannot identify through a vibration on Steam Client. Xbox One controller does vibrate in Steam Client... but still nothing in games. Then again, the Xbox One controller with vibration in games thru bluetooth is always a hastle in Linux, most of the time no vibration.

2. I tried launching a game from its .exe equivalent like Stardew Valley to see if it was the steam client interfering, but still same result: no vibration. 

What I haven't tried yet:

1. Possibly thinking it could be the Steam client for whatever reason, I haven't installed the regular steam client since it conflicts with the steam-jupiter version which I'm guessing is SteamOS's steam. Didn't want to ruin the dependencies and such. Yet...

2. Haven't tried non-Steam games yet, like Origin, GOG, etc.

Anyway, anything I can do? It's pretty awesome that the Aya Neo can almost become a Steam Deck or at least use the SteamOS, but the no vibration is a game-killer for me. 

Is anyone else here running their Aya Neo with HoloISO, which I know some are, but if you are, do you get vibration in your games?

Any info/logs I can give, please let me know.

Edit: Some device stats:

OS: SteamOS Holo x86_64 
Host: AYANEO 2021 Pro Retro Power 
Kernel: 5.18.1-arch1_testHoloISO_20220606.1811 
Packages: 871 (pacman) 
Shell: zsh 5.8 
Resolution: 1280x800 
DE: Plasma 5.23.5 
WM: KWin 
Theme: Vapor [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 4800U with Radeon Graphics (16) @ 1.800GHz 
GPU: AMD ATI 03:00.0 Renoir 
Memory: 2118MiB / 12956MiB

**Comment by Grimish-ng** [comment]
Have had the same problem with just a simple laptop install and a number of controllers.
