### ISSUE TITLE
The System don't boot up after the setup.

### ISSUE THREAD

**Issue by itsmosaik** [holoiso-eol/holoiso#284]
Finally, my system boot up and gave me a welcome screen. but there is one problem, after updating on the setup and rebooting, its showing only blank screen. does this normal & have to waiting for the setup to continue?

**Comment by Brummby** [comment]
I had the same issue, mine appears to of been caused by running more than one screen.
I unplugged two screens and rebooted and it came good for me.
I also need to boot with only one screen connected once installed.
