### ISSUE TITLE
Gamescope-Session Resolution

### ISSUE THREAD

**Issue by rbrugnolli** [holoiso-eol/holoiso#290]
After the last updates, even putting the FullHD resolution in the gamescop-session, I don't have resolution options above HD, I don't even want FullDH, at 1440x831 it's very good with FSR, before I could but now it won't.
Does anyone have an idea about.

**Comment by Shivox** [comment]
For me Steam launches with the correct resolution, but as soon as I go into a game's page, it will make the startup sound again and the splash screen and scales down to the HD resolution (I assume 720p or 800p).

I'm on Nvidia RTX 3080 Ti

**Comment by godtoall82** [comment]
Same. Adjusted gamescope-session to 4k resolution and cannot set any game above 720p.

**Comment by jazzcat007** [comment]
Same issue for me. 4K in UI / 720p as highest resolution option in all games. Games are windowed in the middle of the screen with black borders. I'm on an RX6600.

**Comment by rbrugnolli** [comment]
This solved my problem.

https://www.gamingonlinux.com/2022/06/steam-deck-now-lets-you-override-display-resolution-for-games/page=1/#comments

**Comment by jazzcat007** [comment]
Thanks!

**Comment by Shivox** [comment]
> This solved my problem.
> 
> https://www.gamingonlinux.com/2022/06/steam-deck-now-lets-you-override-display-resolution-for-games/page=1/#comments

In my opinion it's not really a solution, that's just a way to override the resolution on a per-game basis, the solution would be that the games resolution would default to whatever the gamescope-session is set to.

**Comment by rbrugnolli** [comment]
> > This solved my problem.
> > https://www.gamingonlinux.com/2022/06/steam-deck-now-lets-you-override-display-resolution-for-games/page=1/#comments
> 
> In my opinion it's not really a solution, that's just a way to override the resolution on a per-game basis, the solution would be that the games resolution would default to whatever the gamescope-session is set to.

I don't think you understand, it's not a solution, it's the way that now the steam interface configures the resolution in games, the default is 720p, if you want more you'll have to put it directly in the game.

**Comment by jazzcat007** [comment]
I wonder if there's a global setting.

**Comment by rbrugnolli** [comment]
> I wonder if there's a global setting.

Somewhere it must be, it must be the same as what happens with the TDP of the video card, I don't think they would tie it to the software.

**Comment by deftdawg** [comment]
This problem is a symptom of gamescope Ui optimization for steam deck, earlier builds would scale to native resolution of any display one connected to it.  I had a deck plugged into a 4k monitor, but the downside is the deck's hardware can't handle high res gaming, so a change was made to have gamescope default to the deck's native resolution on any display it attaches to, this way performance is consistent everywhere like on a console. 

Hopefully there's a way to adjust the behaviour back somehow.

**Comment by jazzcat007** [comment]
This problem is a symptom of gamescope Ui optimization for steam...


👍

**Comment by deftdawg** [comment]
Bottom has messing around I did, didn't work but maybe there's other values to plug into gamescope to change the res/scaling... Anyway I gotta go out today, so dump this here maybe some of you will want to have a go... 

`gamescope --help` gives:
```
usage: gamescope [options...] -- [command...]
Options:
  --help                         show help message
  -w, --nested-width             game width
  -h, --nested-height            game height
  -r, --nested-refresh           game refresh rate (frames per second)
  -m, --max-scale                maximum scale factor
  -i, --integer-scale            force scale factor to integer
  -W, --output-width             output width
  -H, --output-height            output height
  -n, --nearest-neighbor-filter  use nearest neighbor filtering
  --cursor                       path to default cursor image
  -R, --ready-fd                 notify FD when ready
  -T, --stats-path               write statistics to path
  -C, --hide-cursor-delay        hide cursor image after delay
  -e, --steam                    enable Steam integration
Nested mode options:
  -o, --nested-unfocused-refresh game refresh rate when unfocused
  -b, --borderless               make the window borderless
  -f, --fullscreen               make the window fullscreen
Embedded mode options:
  -O, --prefer-output            list of connectors in order of preference
  --default-touch-mode           0: hover, 1: left, 2: right, 3: middle, 4: passthrough
Debug options:
  --disable-layers               disable libliftoff (hardware planes)
  --debug-layers                 debug libliftoff
  --debug-focus                  debug XWM focus
  --synchronous-x11              force X11 connection synchronization
  --debug-hud                    paint HUD with debug info
  --debug-events                 debug X11 events
  --force-composition            disable direct scan-out
  --disable-xres                 disable XRes for PID lookup
Keyboard shortcuts:
  Super + F                      toggle fullscreen
  Super + N                      toggle nearest neighbour filtering
  Super + S                      take a screenshot
```


```sh
cd ~
cp $(which gamescope-session) . 
# Patch the script
sed -i 's/ 1280 / ${SCREEN_WIDTH:-1280} /;s/ 800 / ${SCREEN_HEIGHT:-800} /' gamescope-session


# Set to our current X session width
export SCREEN_WIDTH=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
export SCREEN_HEIGHT=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)


# Exit normal steam before trying to start or steam will unminimize instead of starting gamescope 
./gamescope-session

# killall gamescope gamescope-session # from ssh to get control back
```

**Comment by AHandheldFan** [comment]
I'm wondering if there's been any movement/progress on this? I would also like it to default to my displays native resolution.
On a desktop or any device that isn't a Deck or Handheld, it makes sense to not default to 800p. I get that the 800p default is 'by design' but surely it can be overwritten somehow.
I have found that commenting out STEAM_MULTIPLE_XWAYLANDS line allows gamescope to run at displays native resolution BUT it breaks HDR and VRR.
