### ISSUE TITLE
Cannot set any game to resolution over 720p in Gamescope.

### ISSUE THREAD

**Issue by WTFPCStuff** [holoiso-eol/holoiso#293]
All games are forced to 720p in Gamescope, though it appears I can FSR over that in Control from the heroic launcher, unable to confirm if this works in other titles.

**Comment by doxzilla** [comment]
Check out [this comment](https://github.com/theVakhovskeIsTaken/holoiso/issues/114#issuecomment-1125971335) from #114, also info from #16, and also take a look at the [gamescope github page](https://github.com/Plagman/gamescope)

**Comment by WTFPCStuff** [comment]
> Check out [this comment](https://github.com/theVakhovskeIsTaken/holoiso/issues/114#issuecomment-1125971335) from #114, also info from #16, and also take a look at the [gamescope github page](https://github.com/Plagman/gamescope)

Regrettably, this did not seem to work. Steam games still only allow ~720p resolutions.

Logged in as root
Used nano to open the file. Found the gamescope settings
As a best practice I modified the existing values instead of deleting them to be -w 1920 -h 1080
Saved the file.
Opened the file, confirmed it saved.
Rebooted
Tried a game. No success.
Revisited the instructions, saw mention of 'reinstalling the games, installed a new a game. No success.
Rebooted, installed another game. No success.

**Comment by doxzilla** [comment]
For games installed via Steam the resolution is locked to resolutions below 1280x800 unless you to the game properties and set the resolution to something over 720p.

**Comment by konradknitter** [comment]
Hey,

I unable to set resolution higher than mentioned using DeckUI.
When boot to desktop I can set resolutions up to configured in Plasma desktop (at least 4K tested).

Are you experiencing issues also using Plasma desktop?

I’m very interested to get higher resolutions using DeckUI.

**Comment by tmcd35** [comment]
Been running HoloISO in 4K, works not problems.  Three changes are needed in the gamescope-sessions file.

1) remove the -h and -w resolutions
2) replace with your desired max resolution with capitalised flags -H and -W
3) remove the max-scaling line 

Also, you may need to be in the Beta channel for SteamOS for the latest features.  In each games steam config there is an option now to override the max resolution on a per game basis.  This may need to set to get higher resolution options in game.

Finally there is now a UI scaling slider in the Display settings that allows you to customise UI scaling and get the best out of higher resolutions for the DeckUI.
