### ISSUE TITLE
laggy ui and audio

### ISSUE THREAD

**Issue by matthew42904** [holoiso-eol/holoiso#296]
i think i only have one pc that is supported from what i can see. it has 2 xeon e5-2650v2's, 64gb of ram and a 1650s. when i boot it up it is very laggy until i switch into desktop mode but it still has laggy audio for some reason. im using the hdmi for audio. i have tried headphones but the same issue. any ideas on what the issue may be?

**Comment by KinSire** [comment]
I also have audio problems. MSI Gamin Plus MAX B450 motherboard with Realtek ALC892 HD Audio and it is not detecting the onboard soundcard. So it has selected my Graphics card (XTX RX6700XT Merc 319) as a sound output through HDMI. And the sound is stuttering so much that there is no point in gaming or watching videos. 

AMD Ryzen 3 - 1200AF
DDR4 3200mhz 2x8GB
