### ISSUE TITLE
Is a i5 2500K & R9 290 configuration supported? 

### ISSUE THREAD

**Issue by KalRego** [holoiso-eol/holoiso#298]
... because I cannot even boot from USB!! The same USB works with my razen 7 2700U laptop!!

**Comment by ghost** [comment]
The CPU and the system around it should still be supported by Arch - so I would first give a try if you can get vanilla Arch to work.
If you can't boot from usb on the system in question that's mostly just some settings. Look out for something that says "CSM - Compatibility Support Mode" or "Legacy Mode" - and make sure to disable it or change it to UEFI mode.

**Comment by KalRego** [comment]
Thank you for your swift response !! 

My system supports Arch!! I had Manjaro installed for a couple of months. 

I will try again with new settings!!

**Comment by ghost** [comment]
if you can get manjaro to run you should be able to get hokoiso to run
it's most likely jzst either some setting or the boot device not correctly formatted

**Comment by cazlin** [comment]
I am running HoloISO_Stable-20220606_2330-x86_64 on an ASUS sabertooth p67 i5-2500K. (AMD ATI Radeon RX 580 8G)
I have to use supergrub on a usb flash drive to load the EFI boot file as the latest p67 bios does not seem to be able to detect the steamos EFI partition or file. Everything else hardware wise seems to work just fine other than the EFI boot issues on a 2500k,

**Comment by KalRego** [comment]
I will try it!! Thank you very much!! Any links pointing to supergrub?
