### ISSUE TITLE
DeckUI resolution issue & Bluetooth

### ISSUE THREAD

**Issue by VolyFnap** [holoiso-eol/holoiso#30]
When you select a language that contains Cyrillic, the screen resolution breaks (exp. Russian)
https://i.imgur.com/JsXbCZt.jpeg
https://i.imgur.com/aDyIRGV.jpg

If you select English, everything is fine, except for additional menu
https://i.imgur.com/BqF1svx.jpg

(24'1920x1080, RX580, i7 7700K)

I have a "Broadcom BCM94360CS2 Desktop PCIE PCI-E Wireless Adapter WLAN Wi-Fi Card BT 4.0 2.4G/5GHz"
Bluetooth does not work on starting the system, it can turn on through the desktop mode, but in DeckUI it still doesn't work, it also have to turn on manually every start the system.
https://i.imgur.com/ZyDsD3A.jpeg

**Comment by VolyFnap** [comment]
I think, deckUI trying to set 1280x800

**Comment by aleksasiriski** [comment]
To change this, you can edit /usr/bin/gamescope-session, and change "-W 1280 -H 800" to whatever desired resolution you wish to be your max. I changed mine to 1920 by 1080 and have had no issues.

Also if you happen to have weird scaling problems, in SD UI enable developer options and in developer settings disable OPENGL rendering.

**Comment by aleksasiriski** [comment]
Also if you happen to have weird scaling problems, in SD UI enable developer options and in developer settings disable OPENGL rendering.

**Comment by ByteSz** [comment]
+1 on the bluetooth issue, my bluetooth was working fine back on Rub Rub RC1 and below. Now it won't work, even when reinstalling bluez while in the deck UI.

Seems like overall based on my experience, RC1 was more stable but just lacking the rolling updates.
