### ISSUE TITLE
[Feature Request] Steam Deck install guidelines

### ISSUE THREAD

**Issue by cmalvi** [holoiso-eol/holoiso#301]
I was thinking to install holoiso on my Steam Deck because I'd like to switch DE to gnome and use pacman package instead of flatpak.
My concerns are the followings:

- Do I get bios and firmware update from valve? (I don't know if they're are shipped from Jupiter repo or other)

- Does all gamescope feature works, including tdp and gpu clock related?

- in general, there are any drawback from using stock steam os?

**Comment by NightHammer1000** [comment]
1.) No you dont.
2.) As far as I have seen in the two weeks using it yes.
3.) Not many from what I have seen. You need to tinker around a bit to get the DeckUI Powermenu to work and the Mount the SD Card but besides that it worked quite well.

Just switched away from it to give Windows a try.

**Comment by cmalvi** [comment]
Thank you for the info.
Do you plan about writing a readme section about steam deck?

**Comment by NightHammer1000** [comment]
Not really. Sorry. 
I am way to much in "OS Flux" to stay on Holo ISO long enough to do something like that.

**Comment by cmalvi** [comment]
Oh no problem, now I'm too busy to test myself but I'll do when I have time.

Other that distro test, a firmware update would be perfect to give users a complete free choice. Maybe Valve will give us some update about when steamOS is released

**Comment by theVakhovskeIsTaken** [comment]
> I was thinking to install holoiso on my Steam Deck because I'd like to switch DE to gnome and use pacman package instead of flatpak.
> My concerns are the followings:
> 
> - Do I get bios and firmware update from valve? (I don't know if they're are shipped from Jupiter repo or other)
> 
> - Does all gamescope feature works, including tdp and gpu clock related?
> 
> - in general, there are any drawback from using stock steam os?

1. Firmware/UEFI updates are shipped by 'jupiter-biosupdate' feature in 'jupiter-hw-support' package supplied by Valve. Regardless of what combination you will have, firmware updates will still be delivered to you, but cannot guarantee that they will work

2. Gamescope features work as intended, except somehow TDP/GPU clock stuff doesn't function for some people (probably related to steamos-priv-write functionality)

3. I don't know :)

**Comment by cmalvi** [comment]
Good to know about Firmware update, already seen this package from pacman update on stock SteamOS.
Regarding TDP/GPU, i don't totally understood your reply

**Comment by cmalvi** [comment]
Ok no problem :)

When I have enough time I’ll try to do it

**Comment by ehartford** [comment]
I am also interested in installing holoiso on the steam deck so that I can use it as my development machine.  But I prefer gnome.

**Comment by NightHammer1000** [comment]
As Information for anyone seeking a more Open OS but do not want to lose the Steam Deck Feel I suggest Bazzite.
https://universal-blue.org/blog/2023/08/20/bazzite-10/#bazzite-on-deck
