### ISSUE TITLE
Don't boot 

### ISSUE THREAD

**Issue by TRINCETT** [holoiso-eol/holoiso#304]
![IMG_20220622_153924170](https://user-images.githubusercontent.com/93570862/175132221-b98bbf92-c9f7-4be9-8585-2fa1c0f459af.jpg)
Im stuck here after install

**Comment by ghost** [comment]
well - your arch install successfully booted fully into login prompt - so "don't boot" is wrong (makes this issue invalid)

**Comment by TRINCETT** [comment]
Yeah, i see, i tried to install it again with another network and it works but now it shows a black screen, i tried with amd and intel graphics option but nothing happens, i think its cause i have a hybrid amd/intel gpu :c

**Comment by Grimish-ng** [comment]
So you are almost there, follow the guide to recovery mode, holoiso disable session, Yada Yada. It's plastered all over on how to perform this initially if you have a blank screen.

**Comment by Savillion** [comment]
Enable Xhci handoff in bios settings, also make root and user names different and reinstall I fixed this that way.
