### ISSUE TITLE
Issue downloading holoiso.db

### ISSUE THREAD

**Issue by rohanxtreme** [holoiso-eol/holoiso#306]
Hi Team,
After configuring WiFi and selecting install device I am getting the following error.
I tried using some fixes provided earlier but they don't seem to work as well.
The following is the text i see: (unfortunately not able to upload image for some reason)

  __Synchronizing package databases... 
  holoiso.db failed to download 
  holostaging 
  jupiter-main 
  holo 
  core 
  extra 
  error: failed retrieving file 'holoiso.db' fron vakdl.enablers.workers.deu : The requested URL returned error: 500 
  error: failed to synchronize all databases (failed to retrieve some files)
  ==> ERROR: Failed to install packages to new root 
  Pacstrap complete. 
  Rebuilding kernel nodules. 
  chroot: failed to run connand adepnode: No such file or directory 
  chroot: failed to run command ankinitopion: No such file or directory 
  mount: unt/home: Rount point does not exist.__ 

Any assistance will be hugely appreciated.

![error](https://user-images.githubusercontent.com/12132374/175290458-65c6fec7-4ee6-4a94-bd75-aa0e4f23db4f.png)

**Comment by ltomes** [comment]
I am getting chroot failed errors during install as well:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/4184677/175650896-0998752d-0242-4b2c-9f95-b0e590036dd7.png">
The above reboots to a black screen.

This is `ISOR1`

@rohanxtreme I choose `2` (booster) for the extra repository, and I believe I made if further/I don't see chroot errors:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/4184677/175653580-5adf5fd0-481d-49e7-b8a2-d1461fed7edc.png">
I will let you know if this works better...

Some warnings along the way:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/4184677/175655497-920c8fb0-756a-4868-9579-dfc969f28cb5.png">
It certainly failed in a different way when using `booster` 😄 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/4184677/175655590-e95a2e4b-ab13-4fc8-98f5-456e462202cd.png">

Long pause here: 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/4184677/175655795-a94dd216-10f1-4272-bcd0-a3f5d927f821.png">

Building an iso from https://github.com/theVakhovskeIsTaken/holoiso/pull/307 now. When the iso is built I will attempt to install with that and see if things are in a working state.

**Comment by deftdawg** [comment]
```
error: failed retrieving file 'holoiso.db' from vakdl.enablers.workers.dev : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```
Think this message is happening when gamescope tries to check for updates, not sure if that impacts new installs or not

**Comment by Teila** [comment]
I am getting 404 errors on the holoiso.db now

**Comment by leattrrapereve** [comment]
I think the hosting of the files is down.

**Comment by luchihoratiu** [comment]
@Teila and @leattrrapereve: I ran into the same issue and opened https://github.com/theVakhovskeIsTaken/holoiso/issues/316
