### ISSUE TITLE
AMD RX 590 - black screen 

### ISSUE THREAD

**Issue by Gert1967** [holoiso-eol/holoiso#309]
installed the newest iso and only get black screen after install.

Tried with other AMD gpu's with the same result.

any suggestion ...

**Comment by Grimish-ng** [comment]
Like the majority of people on first run, follow the instructions to get into recovery mode on Grub, select Advanced options, use bottom kernel recovery Holo kernel 5.18. Avoid Jupitor for until it functional. 
Ctrl-D / password yada.
Input into the bash terminal:
 holoiso-disable-session
 reboot

At Grub prompt select Advanced again, boot Holo kernel (not recovery or fallback) avoid jupitor again. 
During session (blank screen) or login screen switch to TTY sessions by hitting Ctrl-Alt-[F2-F4] 
Authenticate with user created on install. 
Into bash terminal:
gamescope-session

You should see the screen and hear the sound. Set yourself up in steam. 
Reboot into recovery or switch to desktop mode and enable auto sessions again by typing holoiso-enable-sessions.
This is how alot of individuals may have to run it initially to get KMS binary on the disk.

**Comment by jdev082** [comment]
> Like the majority of people on first run, follow the instructions to get into recovery mode on Grub, select Advanced options, use bottom kernel recovery Holo kernel 5.18. Avoid Jupitor for until it functional. Ctrl-D / password yada. Input into the bash terminal: holoiso-disable-session reboot
> 
> At Grub prompt select Advanced again, boot Holo kernel (not recovery or fallback) avoid jupitor again. During session (blank screen) or login screen switch to TTY sessions by hitting Ctrl-Alt-[F2-F4] Authenticate with user created on install. Into bash terminal: gamescope-session
> 
> You should see the screen and hear the sound. Set yourself up in steam. Reboot into recovery or switch to desktop mode and enable auto sessions again by typing holoiso-enable-sessions. This is how alot of individuals may have to run it initially to get KMS binary on the disk.

Wondering if this would work for an intel iGPU with same issue. It didn't, holoiso-disable-session command not found.
**typing holoiso-disable-sessions worked** though the gamescope session command fails because of a load of errors. like no such process, ev2fixaudio.sh no file or directory, etc. its a mess
