### ISSUE TITLE
Can't leave gaming mode

### ISSUE THREAD

**Issue by JonPinto** [holoiso-eol/holoiso#315]
when I select desktop mode in the UI, it just loads forever. And when I ctrl alt f4 to exit to terminal - It's a bit unclear but it seems to crash? I just stop getting a signal, and I have have to press the mini PC power button to wake it, sending me right back to the UI where I left.

**Comment by xonick01** [comment]
I am having the same issue , I have reinstalled twice no luck .

**Comment by Maykin-99** [comment]
I had the same issue today.
It turned out because I've changed my sudoers file (`/etc/sudoers.d/<username>`) to not allow `sudo` without a password by removing `NOPASSWD:`
Readding `NOPASSWD:` "fixed" the issue for me.
