### ISSUE TITLE
`holoiso.db` and `holostaging.db` failed to download

### ISSUE THREAD

**Issue by luchihoratiu** [holoiso-eol/holoiso#316]
Getting the following error when running `holoinstall`:
```sh-session
error: failed retrieving file 'holostaging.db' from vakdl.enablers.workers.dev : The request URL returned error: 404
error: failed retrieving file 'holoiso.db' from vakdl.enablers.workers.dev : The request URL returned error: 404
```
Accessing https://vakdl.enablers.workers.dev/ shows:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/39198766/176262977-9efc590b-61fd-451b-afe4-3b929aaabfc0.png">

Are there any alternatives available to change to in `pacman.conf` or any idea when the server will be up again @theVakhovskeIsTaken?

**Comment by luchihoratiu** [comment]
Building our own ISO seems to be also affected by this: https://github.com/luchihoratiu/holoiso/runs/7100672104
```sh-session
...
[mkarchiso] INFO: Using pacman CacheDir: /var/cache/pacman/pkg/ 
[mkarchiso] INFO: Copying custom airootfs files...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Installing packages to '/__w/holoiso/holoiso/work/x86_64/airootfs/'...
==> Creating install root at /__w/holoiso/holoiso/work/x86_64/airootfs
==> Installing packages to /__w/holoiso/holoiso/work/x86_64/airootfs
:: Synchronizing package databases...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0  1683    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
error: failed to synchronize all databases (error invoking external downloader)
==> ERROR: Failed to install packages to new root
Error: Process completed with exit code 1.
...
```

**Comment by ltomes** [comment]
@luchihoratiu There is an issue with the package install locations as well that has a pending PR: https://github.com/theVakhovskeIsTaken/holoiso/pull/307 
So once that db/request is 200ing you may need to build from that branch as well.

**Comment by luchihoratiu** [comment]
Hoping it gets fixed soon (it's been like this since yesterday but didn't have time investigating/understanding what the error meant until now)

**Comment by nerdmouse** [comment]
Just wanted to mention that I also have this issue and I'm glad it's not user error lol

**Comment by changeforan** [comment]
Same issue here, already confirmed that there is no problem with my network. Can someone take a look?

**Comment by KoRnLDU** [comment]
It works intermittently. I was able to install it but only holostaging.db was downloaded. It gave me an incomplete Steam OS, but sort of functional. I tried reinstalling but I was not able to download either holoiso.db and holostaging.db. Just waiting for developers to fix the server.

**Comment by luchihoratiu** [comment]
@KoRnLDU you were lucky I guess. I had over 10 attempts and didn't manage to download either of them. 😅

**Comment by YvesStraten** [comment]
I had a similar experience unfortunately. I could not install at all, probably because of that error. Hopefully it gets fixed 🙏

**Comment by luchihoratiu** [comment]
It seems to be back online and working:
![Screenshot_20220629-152052289 (1)](https://user-images.githubusercontent.com/39198766/176434963-efc80f62-d56c-46bd-b98b-31c0f268eadd.jpg)

**Comment by YvesStraten** [comment]
LETSGOOOOOOOOOOOOOOOOOOOO!! Thank you so much! 🙏

**Comment by luchihoratiu** [comment]
It would be cool if someone could mirror those just in case it happens again. I think that modifying the `pacman.conf` files with the mirrored link would be enough to get people unstuck. (if @theVakhovskeIsTaken agrees with this also of course)

**Comment by JoshuaDoes** [comment]
I'll make a mirror tonight! Just started the install after many fails last night
