### ISSUE TITLE
Always Booting to a Terminal

### ISSUE THREAD

**Issue by freddyguythe10th** [holoiso-eol/holoiso#317]
Whenever I boot into the iso, it shows a terminal asking for a username and password. The holoiso commands don't seem to exist. Booting into recovery mode does the same thing. A few versions before this one worked but ever since they added FSR support for Intel GPU's I've had this issue among a few others.

**Comment by Savillion** [comment]
Enable Xhci handoff in bios settings, also make root and user names different and reinstall I fixed this that way.

**Comment by BlivionIaG** [comment]
> Enable Xhci handoff in bios settings, also make root and user names different and reinstall I fixed this that way. 

Hi, i have installed it with xhci handoff enabled and have a different username for root and user, what should I look for ?

**Comment by mitch030504** [comment]
i had this issue today, try redownloading the latest iso and reflashing it

**Comment by BlivionIaG** [comment]
I reinstalled it in the mean time, it worked
