### ISSUE TITLE
[feature] Docker image for developers

### ISSUE THREAD

**Issue by Merith-TK** [holoiso-eol/holoiso#318]
Basically, an docker image where developers can test their programs whether or not they work inside of SteamOS without having to potentially re-image their deck every time they identify what packages are needed to be bundled

**Comment by FranjeGueje** [comment]
Yes please. Now I have this need. I want to compile cleanly

**Comment by theVakhovskeIsTaken** [comment]
https://vakdl.enablers.workers.dev/6:/recoveryimg/bootstrap/SteamOS_3-2_steamdeck-main_20220630_2230.tar.gz

Import as docker image by `docker import SteamOS_3-2_steamdeck-main_20220630_2230.tar.gz holo`

**Comment by Merith-TK** [comment]
We meant as an image we can `docker pull`, so automated testing can utilize it.

**Comment by theVakhovskeIsTaken** [comment]
> We meant as an image we can `docker pull`, so automated testing can utilize it.

docker pull thevakhovske/holoiso
