### ISSUE TITLE
Remote play doesn't work

### ISSUE THREAD

**Issue by andytuinman3** [holoiso-eol/holoiso#319]
I installed HoloISO on my intel nuc. Gaming on the device itself won't do the job so I thought I would use it as a sort of steam link.

But if I select a game to stream it loads and then immediately goes back to the gaming mode menu. I checked all settings and compared it to my steam deck which are the same settings. On the deck it works fine on HoloISO it does not.

When I disable hardware decoding in the remote play settings on the nuc I do get sound and control but no image. When enabled it just crashes back to the menu.

Is this a known issue?

**Comment by DynamicGoose** [comment]
You have to turn off hardware decoding in the remote play client settings.

**Comment by andytuinman3** [comment]
Even with hardware decoding off it doesn't work. I just get a black image with the game sound and controls working. Just no picture. With hardware decoding on it just crashes back to the menu.

**Comment by cbail-kc** [comment]
Having this issue as well, @andytuinman3 were you able to resolve this?

**Comment by andytuinman3** [comment]
Nope never fixed it. I just ordered a usb c hub to plug in my Steam Deck to the TV. I will leave this issue opened for anyone who has the same problem. But for now I will use the deck on the tv

**Comment by cbail-kc** [comment]
Darn. I'm using my holoiso device as an HTPC, so would like it to be able to stream itself without having to hook up my deck. I will probably try and add moonlight as a steam game and stream that way.

**Comment by mwtremblay** [comment]
I intend to use my HoloISO machine as an HTPC as well and would love for the remote play feature to work. I also get a black screen when trying to use Steam Link as described by previous commenters.
