### ISSUE TITLE
Laptop doesn't load steamos first boot expierience (oobe)

### ISSUE THREAD

**Issue by blabla9999** [holoiso-eol/holoiso#320]
It loads directly into this screen every time i boot up the laptop.
![16565846597285895064043489259594](https://user-images.githubusercontent.com/63928075/176654947-97707c6c-e001-40cd-88e2-3f46d4beb01c.jpg)
I can't select a user of make a new one

Thanks for the help in advance

**Comment by pyoroe** [comment]
reinstall the os as set the username to "me", that seemed to fix it for me, also, what are you laptop's specs? we're gonna need them to see if you can run gamescope well.

**Comment by blabla9999** [comment]
It Worked thanks
