### ISSUE TITLE
Can you support pre 6th gen intel iGPUs at some point?

### ISSUE THREAD

**Issue by jdev082** [holoiso-eol/holoiso#323]
My laptop here has Intel Integrated Graphics 2000. Unsurprisingly, the Deck UI doesn't work. It simply says 'failed to initialize vulkan' and this is entirely because my iGPU doesn't support Vulkan. Can at some point, this support pre 6th gen processors/iGPUs

**Comment by theVakhovskeIsTaken** [comment]
Nope.

**Comment by jdev082** [comment]
Oh well then...
