### ISSUE TITLE
Desktop mode (KDE) run in wayland session

### ISSUE THREAD

**Issue by neptalactone** [holoiso-eol/holoiso#324]
Is there a way to make desktop mode (KDE) to run with wayland session?
Everytime i switch from handheld gamescopte (deck) mode, the desktop/KDE run with X11 session.

![Screenshot_20220702_151107](https://user-images.githubusercontent.com/34985816/176992516-d05f2ee2-56ea-4bdf-9c50-b82c0e7c9f7c.png)

Both my graphics card (iGPU and dGPU use AMD) so it should be fine run the desktop mode with wayland.

**Comment by theVakhovskeIsTaken** [comment]
The session switching is hardcoded for use with X11 plasma.
