### ISSUE TITLE
dota 2 slow performance

### ISSUE THREAD

**Issue by jimpascua** [holoiso-eol/holoiso#325]
I installed holoiso on my old machine (intel e5 2650, 32gb ram, rx 560) and dota 2 performance is abysmal. I get like 20 fps or so on the main screen as well as ingame. 

what I tried:

disabling shader cache
updating 
following the arch wiki for dota 2

With windows installed on the same machine it gets like 80-100 fps. I haven't tried other distro but any help would be appreciated.

**Comment by starfireprime** [comment]
I just started playing with this and I'm guessing that steamos is limiting the TDP of your desktop card. I have a RX6600 that pulls 100W in Horizon Zero Dawn's benchmark mode in Windows 11, but is capped at 30W in the steam deck OS.  Scores and FPS are lower accordingly.  I've seen some posts and chatter on how to lift the cap, but I haven't been successful yet.

**Comment by jimpascua** [comment]
Hey man thanks for the response, so I checked the other threads with regards to the TDP limit you mentioned and found this

https://github.com/theVakhovskeIsTaken/holoiso/issues/294#issuecomment-1167051433

I followed this one and the fps doubled but still only half of what I get on windows but atleast its playable now.

**Comment by starfireprime** [comment]
I still can't get my TDP over 30W according to gamescope, even with the mods to steamos-priv-write and looking at config.vbs.  I'll keep trying... 
Thanks!

**Comment by PIPIPIG233666** [comment]
> I still can't get my TDP over 30W according to gamescope, even with the mods to steamos-priv-write and looking at config.vbs. I'll keep trying... Thanks!

I have 6650xt and the hack just worked after a reboot

**Comment by starfireprime** [comment]
> I have 6650xt and the hack just worked after a reboot

Just to be clear - you modified steamos-priv-write as 

if [[ "$WRITE_PATH" == /sys/class/hwmon/hwmon*/power*_cap ]]; then
   echo "decline harder: $WRITE_VALUE -> $WRITE_PATH" | systemd-cat -t p-steamos-priv-write -p err
   exit 0
fi

and that was all ? - or was there additional settings/changes?  I've set up gamescope to display when I'm in the SteamOS menus as well as in game.  In the menus, there's a hint that the TDP is higher as 20% GPU translates to ~13W.  But once I pop into Horizon Zero Dawn to run the benchmark, and the GPU% cranks up, Gamescope shows just under 30w and poor FPS (about 20).  So I must be missing something somewhere. :<  .  If I run from the desktop mode, I do get better FPS (about 57), still 1/2 what I would get in windows with the same settings.

**Comment by PIPIPIG233666** [comment]
> > I have 6650xt and the hack just worked after a reboot
> 
> Just to be clear - you modified steamos-priv-write as
> 
> if [[ "$WRITE_PATH" == /sys/class/hwmon/hwmon*/power*_cap ]]; then echo "decline harder: $WRITE_VALUE -> $WRITE_PATH" | systemd-cat -t p-steamos-priv-write -p err exit 0 fi
> 
> and that was all ? - or was there additional settings/changes? I've set up gamescope to display when I'm in the SteamOS menus as well as in game. In the menus, there's a hint that the TDP is higher as 20% GPU translates to ~13W. But once I pop into Horizon Zero Dawn to run the benchmark, and the GPU% cranks up, Gamescope shows just under 30w and poor FPS (about 20). So I must be missing something somewhere. :< . If I run from the desktop mode, I do get better FPS (about 57), still 1/2 what I would get in windows with the same settings.

Yeah, you can do `cat /sys/class/hwmon/hwmon*/power*_cap` to see if it is actually limiting the TDP

**Comment by starfireprime** [comment]
> Yeah, you can do `cat /sys/class/hwmon/hwmon*/power*_cap` to see if it is actually limiting the TDP

Thanks for your help - after several attempts and having power1_cap reset to 15W, I edited steamos-priv-write one more time, rebooted, wrote a script to dump power1_cap every five seconds to a log file, and then: ran the benchmark from the desktop,  switched to game mode, ran the benchmark again, switched back to the desktop and checked the log.  I was fully expecting the power1_cap to switch, but of course, no it remained 100000000 the entire time.  Go figure.    I'm still losing quite a bith of performance over windows 11 (101 FPS vs 57 in steamos), but it seems to be holding for now.

Edit - checked my notes - the performance drop isn't too bad between Win11 and SteamOS (71 FPS -> 57 FPS).  Both showing 100W.

**Comment by jimpascua** [comment]
I've installed Ubuntu on another drive on the same machine and got pretty much the same performance with Holo after all the changes with the config. Either this is the best performance this game will run on linux, which is a shame since its native or I'm still missing something but I've already put in a couple of hours and its no longer worth it for the purpose that I'm aiming for this old tower.

I'll probably try this again on my main machine after a few more years just to see the improvements. This project is great letting people experience the deckos on any machine, thank you to all the contributors of this piece.

**Comment by jimpascua** [comment]
close
