### ISSUE TITLE
Iso download 

### ISSUE THREAD

**Issue by Abhs15** [holoiso-eol/holoiso#326]
When i start downloading the Iso form (https://nightly.link/theVakhovskeIsTaken/holoiso/actions/runs/2451108977/holoiso.zip)  it doesn't show the size of the file im downloading not only that but it doesn't finish downloading it just stops reciving packets and stops the download and i have to start downloading all over again just to see the same issue is this only with me guy or is the server not working or something.

**Comment by mitch030504** [comment]
sounds like a browser issue
its 1.16GB 
if it stops downloading at that point just change the file extension of the file from like .tmp or whatever it is to .zip and it should work

**Comment by Abhs15** [comment]
ok tnx for the info it has finished downloading all tho it still doesnt show the size of the iso when it downloaded but im glad it atleast downloaded.
