### ISSUE TITLE
Can you upload steamos 3 (holoinstall) repository to other places

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#327]
In China, users cannot directly access Google Drive and github.com ,so I
cannot install holoinstall completely，Can you upload steamos 3
(holoinstall) repository to other places

**Comment by alansari** [comment]
if this is still an issue you can use ruineka's, a legend in the community, mirror:

To use add these lines to your pacman.conf located at /etc/pacman.conf

[ruineka]
Server = https://github.com/ruineka/repo/blob/main/os/$arch
SigLevel = Never

Though i doubt this is still an issue with the new CDN implementation in holoiso

**Comment by theVakhovskeIsTaken** [comment]
Fixed by moving to new CDN.
