### ISSUE TITLE
install without format?

### ISSUE THREAD

**Issue by logan001** [holoiso-eol/holoiso#328]
Is there any way to install it without formating?
a patch for the holo install script?
i want to install it on ext4 partition but don't want to format it due to other files. there is also enough space for holoiso. i just don't want to format the partition.
it will be nice to have option to select the efi boot partition too.
edit: the iso does not have all necessary files for complete installation without internet?

**Comment by theVakhovskeIsTaken** [comment]
It will never have anything for offline installation, because this won't be convinent for anyone

**Comment by logan001** [comment]
ok, well not everybody has wifi and i for one have pppoe and sometimes i forget where i put that user name and password for it :)
but why you closed the issue?
i still want a way to install it without formatting the partition.
