### ISSUE TITLE
Optimus GPU (GTX1050Ti)

### ISSUE THREAD

**Issue by GrediusX** [holoiso-eol/holoiso#329]
Is there any way to enable the discrete graphics card on holoiso? I have a laptop with iGPU+GTX1050Ti (Optimus) but I can't figure out how to enable it. Followed some guides online but desktop mode and deck UI won't load anymore.

**Comment by theVakhovskeIsTaken** [comment]
`or NVIDIA GTX 9xx+ iGPU/GPUs (preferably without Optimus [PRIME])`
