### ISSUE TITLE
Performance overlay black window

### ISSUE THREAD

**Issue by Slo2018** [holoiso-eol/holoiso#332]
I have GeForce RTX 30 Series and i have bug in Performance overlay (black window). Latest NVIDIA Drivers installed.

**Comment by Savillion** [comment]
I'ts because nvidia drivers doesnt work correctly. I have a 1070ti and i got problem too. Many people has.

**Comment by theVakhovskeIsTaken** [comment]
NVIDIA driver issue. Sorry
