### ISSUE TITLE
Steam Not Updating

### ISSUE THREAD

**Issue by tmcd35** [holoiso-eol/holoiso#334]
I've installed HoloISO from ISO Update 1.  I've run all the updates in Pacman, set up for the Beta versions of Steam and SteamOS, and run 

sudo pacman -Sy holoiso-updateclient

and

steamos-update check && steamos-update now

This was in the middle of last week and got me to SteamOS 3.2 R2 Beta.  Since then valve has announced version 3.3 Beta.  I can't seem to upgrade to this new Beta.  Both the Pacman UI and the above two commands show the system as up to date.  When I click on the Check For Updates in the new Steam UI I get the following error:

"An error was encountered during the update process, please try again."

Is there a reason I am not able to get version 3.3?  Also my Kernel is still 5.13, I thought one of the more recent patch notes was to force the Kernel to 5.18?  Or am I misunderstanding something here?

Thanks.

**Comment by tmcd35** [comment]
Okay the Steam client is updating, I have the new UI scaling feature released to beta today (very nice and useful), but the underlying Holoiso OS isn't updating - Steam OS 3.2 R2, Kernel 5.13, Mesa 22.0, etc.  Is there anyway to force an update without doing a reinstall from the latest ISO?

**Comment by alansari** [comment]
run pacman -Sy holostaging/holoiso-updateclient and check to make sure the update client date is >714 before steamos-update check && steamos-update now

**Comment by tmcd35** [comment]
Thanks Alan,

I should have closed this a day or two back. Appears confusion on my part in terms of upgrade tracks.  I'd installed a snapshot build and the updates weren't relevant for my build.  A new snapshot update was released a couple of days ago and as expected I did jump to version 3.3 and a new sbapshot build number.
