### ISSUE TITLE
Screen flickering when using AMD 5700g iGPU

### ISSUE THREAD

**Issue by r3claimer** [holoiso-eol/holoiso#335]
Hello,

While using Holoiso combined with the 5700g integrated graphics I get the screen cutting in and out about every 10-15 seconds. I believe this a linux kernel issue or mesa driver issue. I had the same issue with ubuntu and retropie. Updating the kernel to 5.18 and latest mesa fixed the issue. So I believe this is related to missing / bad drivers in the 5.13 zen kernel that ships with holoiso.

**Comment by konradknitter** [comment]
Hi, I got it working well on 5700g iGPU without any graphical issues. Installed yesterday without any additional drivers. 

Welcome to help in debugging.
This is my version:

[h1@h1 ~]$ neofetch
              .,,,,.                  h1@h1 
        .,'onNMMMMMNNnn',.            ----- 
     .'oNMANKMMMMMMMMMMMNNn'.         OS: SteamOS Holo x86_64 
   .'ANMMMMMMMXKNNWWWPFFWNNMNn.       Kernel: 5.13.0-valve10.1-2-neptune-dri-02144-g7fffaf925dfb 
  ;NNMMMMMMMMMMNWW'' ,.., 'WMMM,      Uptime: 27 mins 
 ;NMMMMV+##+VNWWW' .+;'':+, 'WMW,     Packages: 864 (pacman), 15 (flatpak) 
,VNNWP+######+WW,  +:    :+, +MMM,    Shell: bash 5.1.16 
'+#############,   +.    ,+' +NMMM    Resolution: 1920x1080 
  '*#########*'     '*,,*' .+NMMMM.   Terminal: /dev/pts/0 
     `'*###*'          ,.,;###+WNM,   CPU: AMD Ryzen 7 5700G with Radeon Graphics (16) @ 3.800GHz 
         .,;;,      .;##########+W    GPU: AMD ATI 08:00.0 Cezanne 
,',.         ';  ,+##############'    Memory: 5674MiB / 15288MiB 
 '###+. :,. .,; ,###############'
  '####.. `'' .,###############'                              
    '#####+++################'                                
      '*##################*'
         ''*##########*''
              ''''''
