### ISSUE TITLE
Built-in speakers not working on Steam Deck

### ISSUE THREAD

**Issue by Gecked-Deck** [holoiso-eol/holoiso#34]
Here is the output to pactl list sinks as I was told that may be useful

[gecked@gecked ~]$ pactl list sinks
Sink #122
        State: SUSPENDED
        Name: echo-cancel-sink
        Description: Echo-Cancel Sink
        Driver: PipeWire
        Sample Specification: float32le 2ch 48000Hz
        Channel Map: aux0,aux1
        Owner Module: 4294967295
        Mute: no
        Volume: aux0: 55050 /  84% / -4.54 dB,   aux1: 55050 /  84% / -4.54 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor Source: echo-cancel-sink.monitor
        Latency: 0 usec, configured 0 usec
        Flags: DECIBEL_VOLUME LATENCY
        Properties:
                node.name = "echo-cancel-sink"
                device.description = "Echo-Cancel Sink"
                media.class = "Audio/Sink"
                node.group = "echo-cancel-11"
                node.link-group = "echo-cancel-11"
                node.virtual = "true"
                node.latency = "480/48000"
                media.name = "Echo-Cancel Sink"
                stream.is-live = "true"
                adapt.follower.node = ""
                object.register = "false"
                factory.id = "6"
                audio.adapt.follower = ""
                factory.mode = "merge"
                library.name = "audioconvert/libspa-audioconvert"
                clock.quantum-limit = "8192"
                client.id = "59"
                object.id = "57"
                object.serial = "122"
        Formats:
                pcm

Sink #165
        State: SUSPENDED
        Name: alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_1__sink
        Description: Raven/Raven2/FireFlight/Renoir Audio Processor Speaker
        Driver: PipeWire
        Sample Specification: s16le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 4294967295
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor Source: alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_1__sink.monitor
        Latency: 0 usec, configured 0 usec
        Flags: HARDWARE DECIBEL_VOLUME LATENCY
        Properties:
                object.path = "alsa:pcm:1:hw:acp5x,1:playback"
                api.alsa.path = "hw:acp5x,1"
                api.alsa.open.ucm = "true"
                api.alsa.pcm.card = "1"
                api.alsa.pcm.stream = "playback"
                audio.channels = "2"
                audio.position = "FL,FR"
                device.routes = "1"
                alsa.mixer_device = "_ucm0009.hw:acp5x"
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = ""
                alsa.id = "CS35L41 Stereo Playback multicodec-1"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "1"
                alsa.card = "1"
                alsa.card_name = "acp5x"
                alsa.long_card_name = "Valve-Jupiter-1"
                alsa.driver_name = "snd_soc_acp5x_mach"
                device.profile.name = "HiFi: hw:acp5x,1: sink"
                device.profile.description = "Speaker"
                card.profile.device = "0"
                device.id = "62"
                factory.name = "api.alsa.pcm.sink"
                priority.driver = "664"
                priority.session = "664"
                media.class = "Audio/Sink"
                node.nick = "acp5x"
                node.name = "alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_1__sink"
                device.description = "Raven/Raven2/FireFlight/Renoir Audio Processor Speaker"
                device.icon_name = "audio-card"
                device.bus = "pci"
                device.bus_path = "pci-0000:04:00.5-platform-acp5x_mach.0"
                node.pause-on-idle = "false"
                factory.id = "18"
                client.id = "32"
                clock.quantum-limit = "8192"
                node.driver = "true"
                factory.mode = "merge"
                audio.adapt.follower = ""
                library.name = "audioconvert/libspa-audioconvert"
                object.id = "43"
                object.serial = "165"
                node.max-latency = "4096/48000"
        Ports:
                [Out] Speaker: Speaker (type: Speaker, priority: 100, availability unknown)
        Active Port: [Out] Speaker
        Formats:
                pcm

Sink #166
        State: SUSPENDED
        Name: alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink
        Description: Raven/Raven2/FireFlight/Renoir Audio Processor Headphones
        Driver: PipeWire
        Sample Specification: s32le 2ch 48000Hz
        Channel Map: front-left,front-right
        Owner Module: 4294967295
        Mute: no
        Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        Base Volume: 65536 / 100% / 0.00 dB
        Monitor Source: alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink.monitor
        Latency: 0 usec, configured 0 usec
        Flags: HARDWARE DECIBEL_VOLUME LATENCY
        Properties:
                object.path = "alsa:pcm:1:hw:acp5x,0:playback"
                api.alsa.path = "hw:acp5x,0"
                api.alsa.open.ucm = "true"
                api.alsa.pcm.card = "1"
                api.alsa.pcm.stream = "playback"
                audio.channels = "2"
                audio.position = "FL,FR"
                device.routes = "1"
                alsa.mixer_device = "_ucm0009.hw:acp5x"
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = ""
                alsa.id = "Playback/Capture nau8821-hifi-0"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "1"
                alsa.card_name = "acp5x"
                alsa.long_card_name = "Valve-Jupiter-1"
                alsa.driver_name = "snd_soc_acp5x_mach"
                device.profile.name = "HiFi: hw:acp5x,0: sink"
                device.profile.description = "Headphones"
                card.profile.device = "1"
                device.id = "62"
                factory.name = "api.alsa.pcm.sink"
                priority.driver = "680"
                priority.session = "680"
                media.class = "Audio/Sink"
                node.nick = "acp5x"
                node.name = "alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink"
                device.description = "Raven/Raven2/FireFlight/Renoir Audio Processor Headphones"
                device.icon_name = "audio-card"
                device.bus = "pci"
                device.bus_path = "pci-0000:04:00.5-platform-acp5x_mach.0"
                node.pause-on-idle = "false"
                factory.id = "18"
                client.id = "32"
                clock.quantum-limit = "8192"
                node.driver = "true"
                factory.mode = "merge"
                audio.adapt.follower = ""
                library.name = "audioconvert/libspa-audioconvert"
                object.id = "53"
                object.serial = "166"
                node.max-latency = "4096/48000"
        Ports:
                [Out] Headphones: Headphones (type: Headphones, priority: 200, availability group: Headphone, not available)
        Active Port: [Out] Headphones
        Formats:
                pcm
[gecked@gecked ~]$

**Comment by Gecked-Deck** [comment]
Fixed by running `sudo pacman -Syu`

**Comment by DocMAX** [comment]
Not fixed for me
