### ISSUE TITLE
Can't install system.

### ISSUE THREAD

**Issue by e-legy** [holoiso-eol/holoiso#340]
It prompts the following error
`Error: Partition(s) 1 to 64 on /dev/nvme0p1n4 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use. As a result,the old partiton(s) will remain in use. You should reboot now before making further changes.
Ignore/Cancel?`

**Comment by LightRO** [comment]
This is normal. 
You can't install this System on an Partition, you need a entire Hard Disk.

**Comment by e-legy** [comment]
I saw on telegram that the author will support partition-only installation.
