### ISSUE TITLE
Change Default DeckUI boot settings

### ISSUE THREAD

**Issue by konradknitter** [holoiso-eol/holoiso#341]
Hello,

I got HoloISO working overall nicely.

The default Steam DeckUI boots into 1080p - with restrictions on gamescope to render game up to 720p/800p that is not ideal.

When launched with Plasma I can configure games up to monitor resolution.

Inside of Plasma I can boot Steam DeckUI and use it up to 4K (monitor resolution) using command:
“Gamescope -e -w 3840 -h 2160 -W 3840 -H 2160 -f — steam -steamos3 -gamepadui”
When steam is shutdown.

Although, performance seems degraded, and I can’t get features as Performance Overlay working there.

Did anyone discovered where in the HoloOS Deck resolution is configured? How to change it’s gamescope settings?
Edits in /usr/bin/gamescope-session seems to have no effect on DeckUI.

**Comment by PIPIPIG233666** [comment]
> with restrictions on gamescope to render game up to 720p/800p that is not ideal.

There is no such restriction, in the menu, you can even select the option to render at ~8~4K.

**Comment by kenthinson** [comment]
> > with restrictions on gamescope to render game up to 720p/800p that is not ideal.
> 
> There is no such restriction, in the menu, you can even select the option to render at 8K.

Sorry you are incorrect. Games are limited to 720p. At least on my test system with a RX6700XT. The game will not render at a higher resolution than 720p even on a 1440p display.

**Comment by PIPIPIG233666** [comment]
https://youtu.be/Uc846GmFynM
I literally played at 1080P...

Did you even get what I meant...
In the game settings menu of steam, there's an option where you can change the [resolution](https://s2.loli.net/2022/07/11/6Nh3BVtzQbeSlXk.jpg)

It's not GPU dependent.

**Comment by kenthinson** [comment]
> https://youtu.be/Uc846GmFynM I literally played at 1080P...
> 
> Did you even get what I meant... In the game settings menu of steam, there's an option where you can change the [resolution](https://s2.loli.net/2022/07/11/6Nh3BVtzQbeSlXk.jpg)
> 
> It's not GPU dependent.

Ah thanks for making it more clear. Yeah I didn't get what you meant because you just said "in the menu" not specifying what menu you were talking about before. Game menu? (nope was limited to 720p) SteamDeck system menu? (No options for resolution at all). So yeah details are important :)

**Comment by alansari** [comment]
you need to edit /usr/bin/game-scope session.  Change the gamescope command with whatever you like...  the -w -h will set the resolutions the games can see, the -W -H will set the gamescope output resolution scaling parameters to use with FSR or similar.  I would highly recommend getting the latest gamescope-session from aur and then using the .config/environment.d overrides as needed.
