### ISSUE TITLE
"Only 9xx+ GPUs are supported"

### ISSUE THREAD

**Issue by krillme** [holoiso-eol/holoiso#346]
What exactly does this mean? My understanding of this was any 900 series NVIDIA GPU or newer would work, yet with a GTX 1080 I get stuck at "loading initial ramdisk" which seems to be a sign of an unsupported GPU. 

So does this actually mean that _only_ 900 series GPUs are supported? Perhaps it could be reworded slightly to avoid confusion if this is the case.

**Comment by Lolo280374** [comment]
Hey there, I had the same problem as you on my GTX 1050. The system would simply not boot.
I took a bit of time to search on the list of NVIDIA, and my RTX was apparently supported. I tried installing on it, and it worked.
Maybe you should try to look if your GPU is compatible, [https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus](right there)

**Comment by krillme** [comment]
Interesting, seems the GTX 1080 isn't on that list so I guess it isn't supported.

**Comment by byzocker** [comment]
> Interesting, seems the GTX 1080 isn't on that list so I guess it isn't supported.

Weird, my GTX 1050 works without any problems on holoiso

**Comment by Dokman** [comment]
weird my 950M doesn't work

**Comment by m1wx** [comment]
On a weekend I tried installing on my laptop with 1650 and it didn’t work also. Only logged in to kde desktop by typing some commands in recovery mode.

**Comment by waui** [comment]
> On a weekend I tried installing on my laptop with 1650 and it didn’t work also. Only logged in to kde desktop by typing some commands in recovery mode.

what commands did you use?

**Comment by Lolo280374** [comment]
> Weird, my GTX 1050 works without any problems on holoiso

I also tried with a GTX 1050 Laptop and it didn't worked at all...

**Comment by Grotstompa** [comment]
My 2080 TI seems to be on the supported list, and I can't get SteamOS to load either. I'm currently stuck on, "loading initial ramdisk". In fact, the only way I could get it to even install was by selecting "HoloOS More Compatibility", if I selected Neptune it would sit on "Triggering uEvents".

It seems this build isn't ready for Nvidia without a lot of shotgun effect tinkering either way. I think I'll pass on this until it's updated to support Nvidia better. Unless someone has a simple solution. I wonder how long we have until Steam officially launches their desktop version? Cheers
