### ISSUE TITLE
both 'holoiso-main' and 'jupiter-hw-support' own the file -> no steamOS UI

### ISSUE THREAD

**Issue by jf049** [holoiso-eol/holoiso#347]
At the moment, the reason why issues such as [!304](https://github.com/theVakhovskeIsTaken/holoiso/issues/304) exist (no shell/DE after installation, only TTY) is because of both `holoiso-main` and `jupiter-hw-support` owning `/usr/bin/jupiter-controller-update`, and so the default installation procedure fails to install the DE and SteamOS UI.

You can reproduce this issue with:
`# pacman -Syu --needed holoiso-main`

The problem is with these two upstream packages.

The workaround is to issue this command, and while it solves the issue, **this is still not a recommended way to fix**:
`# pacman -S --overwrite "*" holoiso-main`
After that, you simply `systemctl enable sddm --now`.

**Comment by theVakhovskeIsTaken** [comment]
> At the moment, the reason why issues such as !333 exist (no shell/DE after installation, only TTY) is because of both `holoiso-main` and `jupiter-hw-support` owning `/usr/bin/jupiter-controller-update`, and so the default installation procedure fails to install the DE and SteamOS UI.
> 
> You can reproduce this issue with:
> `# pacman -Syu --needed holoiso-main`
> 
> The problem is with these two upstream packages.
> 
> The workaround is to issue this command, and while it solves the issue, **this is still not a recommended way to fix**:
> `# pacman -S --overwrite "*" holoiso-main`
> After that, you simply `systemctl enable sddm --now`.
> 

wrong.

**Comment by LightRO** [comment]
Why would this be wrong? You should at least have an explanation at hand instead of just writing "wrong".

**Comment by theVakhovskeIsTaken** [comment]
> Why would this be wrong? You should at least have an explanation at hand instead of just writing "wrong".

![image](https://user-images.githubusercontent.com/97450182/178293471-73e9c947-383d-4dca-ad1a-85eb4fc4faac.png)
The fact that installer manages it already?

**Comment by Abhs15** [comment]
i think those fixes have been added on the newest snapshot i had an issue where it boots in to tty mode and black screen when i enable sddm but after this snapshot it has been fixed.

**Comment by jf049** [comment]
> > Why would this be wrong? You should at least have an explanation at hand instead of just writing "wrong".
> 
> ![image](https://user-images.githubusercontent.com/97450182/178293471-73e9c947-383d-4dca-ad1a-85eb4fc4faac.png) The fact that installer manages it already?

The recent "ISO Update 2" doesn't have this issue anymore indeed. Not a good solution, but fine for now. If possible, it'd be better to solve this kind of file/depencency conflict.

Thank you for your work, but please be respectful next time to at least those who doesn't just say "mah gtx900s doesn't work" instead of giving vague one-word answers as it doesn't give people any incentive to help with, engage into and possibly making useful merge requests for your project.

Closing.
