### ISSUE TITLE
Steam Os not installing all packages 

### ISSUE THREAD

**Issue by Divuff** [holoiso-eol/holoiso#35]
Once I run Holoinstall and reboot, it takes me to the standard SSDM(Simple Desktop Display Manager), with no option for what DE I want to boot into.

Running (pacman -Qe) makes it seem like it only installed the first round of packages but for whatever reason it didn't install the rest

**Comment by theVakhovskeIsTaken** [comment]
Thanks for feedback! I'll freeze the release for now!

**Comment by theVakhovskeIsTaken** [comment]
Resolved.
