### ISSUE TITLE
BlackScreen [Laptop]

### ISSUE THREAD

**Issue by Dokman** [holoiso-eol/holoiso#351]
i've installed in MSI Ge72 2QL Apache, with both, intel and nvidia driver, and i've got black screen instead of the login screen.

**Comment by Nerozki** [comment]
i am experiencing the same issue

**Comment by m1wx** [comment]
> i've installed in MSI Ge72 2QL Apache, with both, intel and nvidia driver, and i've got black screen instead of the login screen.

On boot select recovery under advanced.
Then once logged in type: 

holoiso-disable-sessions 

then:

systemctl default

This should put you in into kde login screen.

Credit: Illegalopcode

**Comment by Nerozki** [comment]
@m1wx where exactly do i add this command?

**Comment by m1wx** [comment]
> @m1wx where exactly do i add this command?

when you get brief moment to select boot options. Look for one which says recovery at the end

**Comment by Dokman** [comment]
> 

thank you!

**Comment by Dokman** [comment]
> > i've installed in MSI Ge72 2QL Apache, with both, intel and nvidia driver, and i've got black screen instead of the login screen.
> 
> On boot select recovery under advanced. Then once logged in type:
> 
> holoiso-disable-sessions
> 
> then:
> 
> systemctl default
> 
> This should put you in into kde login screen.
> 
> Credit: Illegalopcode

Thank you!

**Comment by Dokman** [comment]
When I login and type the command holoiso-disable-sessions it give me the console this error:

Command not found

**Comment by vos6434** [comment]
After I login the screen goes black and then goes back to the login screen.
