### ISSUE TITLE
TTY5 

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#352]
When switching to TTY. It asks for a login with your username before it the root. However no matter which account I enter which I set up during install says incorrect password.

**Comment by ghost** [comment]
![IMG_20220711_225614](https://user-images.githubusercontent.com/52523598/178399595-46642c88-dc25-4f0a-9ae1-69f1f153aac8.jpg)

**Comment by Ew4n1011** [comment]
Did you change your keyboard layout? The ones on tty default to en_US qwerty.

**Comment by ghost** [comment]
this issue has been solved by using another usb drive!
