### ISSUE TITLE
[Report] trying the new feature alongside other OS gives error

### ISSUE THREAD

**Issue by logan001** [holoiso-eol/holoiso#354]
## Your Issue: (took a picture and write the error here)
```
Calculation start and end of free space 
expr: non-integer argument
expr: non-integer argument
partitioning:[:111: unknown condition: -gt
Creating partion...
error: invalid number
error: partition(s) 1,2,3,4.............64 on /dev/nvme0n1p3 have been written, but we have been unable to inform the kernel of this change.....
ignore/cancel
```

## Your device's full specs
```
CPU: 5750GE
GPU: APU
i have 4 hdds + 1 nvme
the nvme has 3 partition (now). i've created the 3rd partition with gparted at the end of disk (ext4)
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
can't install
```

**Comment by theVakhovskeIsTaken** [comment]
Known issue right now, it's recommended to keep around 57.9Gb free from the end of the disk to make sure it works.

we recieved few corresponding reports to it, so stay in touch.

**Comment by logan001** [comment]
should be 57.9 or more or just 57.9? my partition is 63.84Gb

**Comment by theVakhovskeIsTaken** [comment]
> should be 57.9 or more or just 57.9? my partition is 63.84Gb

Yes, 57.9

**Comment by MODDER04** [comment]
I tried with 57.9 not working and I tried with more same thing not working

**Comment by USL5264** [comment]
I have a 500gb partitionof unallocated free space  that is in between partitions. Will that be ok?

**Comment by wynn1212** [comment]
This issue has now being address.
https://github.com/theVakhovskeIsTaken/holoiso-install-script/pull/4

**Comment by logan001** [comment]
tested and i was able to install it. had other problems after 1st reboot. now to search or report that bug

**Comment by bisaalz** [comment]
This is still not working for me. A proper guide for dualboot would have been helpfull.
