### ISSUE TITLE
[Report] Can't install in either VirtualBox or VMware

### ISSUE THREAD

**Issue by NickFixed** [holoiso-eol/holoiso#356]
## Your Issue:
```
I tried to install HoloIso in a Virtual Machine to test it out before using it on real hardware
but when i tried to install an old version, the setup goes correct without issue, still couldn't boot for some reason.

With the latest version i now get a new error saying:
"Error: Something went wrong when mounting Home partitions. Please try again!"
```

## Your device's full specs
```
CPU: Intel Core i7-4750HQ
GPU: Nvidia Geforce GTX 980m
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Stable-20220711_1550-x86_64.iso
```

## Your installation type:
```
deckperience.
```

## Have you updated your installation recently?
```
No, fresh install.
```

![image_2022-07-13_004735516](https://user-images.githubusercontent.com/103857423/178611215-a0af288a-6710-426c-b45f-dabe552efc08.png)

**Comment by Juijote** [comment]
I am also experiencing generic problems.

**Comment by Kissycat** [comment]
Same here, and I install it to a usb storage.

**Comment by dron1885** [comment]
QEMU/KVM also.

**Comment by HikariKnight** [comment]
> QEMU/KVM also.

For Qemu you need to use virtio as the video adapter and enable opengl and 3d accelleration.
![image](https://user-images.githubusercontent.com/2557889/179546102-9bb0dcf9-2171-425a-9810-573573c1b9b8.png)


Once the installation is done you need to run `holoiso-disable-sessions` before rebooting, if you do not do this before rebooting then you will have to boot into recovery mode to run the command.

This will get you a login screen and access to the plasma desktop, however the gamescope-session will not work without access to a full physical gpu that is supported by gamescope-session, not a virtual one.

**Comment by shakeyourbunny** [comment]
Currently (as of 2022-07-20), the graphical installer of holoiso does run, but not the installation.

It would be really nice to include in the GPU selection dialog the VMWare SVGA driver. Neither of three GPU selections (AMD, nvidia, intel) works within the VMWare box.

Perhaps include the openvmware-tools in the installer iso too?

**Comment by shakeyourbunny** [comment]
My motivation for a VMWare installation is simple: I would really like to develop things for SteamOS and doing that on my Steam Deck directly is not really that great if I want to try things out safely.

**Comment by PikkonMG** [comment]
2nd this. Would be nice to get this working in VMWare, VirtualBox, Hyper-V

**Comment by NathanDreamweaver** [comment]
3rd this. Alternatively, if someone knew some workarounds to make it work it'd be quite appreciated.

**Comment by theVakhovskeIsTaken** [comment]
No VM support.

**Comment by ValfarDeveloper** [comment]
Please reopen this issue because it is not happening only on Virtual Machines, I just got it in an Aya Neo Next device. Please refer to my comment in this issue: https://github.com/theVakhovskeIsTaken/holoiso/issues/639#issuecomment-1374522723 on that issue the OP could solve it wiping the empty space with zeroes, so probably in the installation script should be included that part (only a suggestion, not sure how it works)

**Comment by awsms** [comment]
> No VM support.

meme distro. why isn't it mentionned anywhere in the README.md
