### ISSUE TITLE
[Report] Won't Install

### ISSUE THREAD

**Issue by Dropdead86** [holoiso-eol/holoiso#357]
I've downloaded the lastest iso from github
The install launches, everything is fine until I get to choose my desired drive
Then I get the following error: "Error: Could not stat device - No such file or directory."

It doesn't matter what drive I choose, I'm still faced with that error.

What am I doing wrong ?
UEFI is enabled, Secure boot is disabled.
Is there something else in the BIOS I need to switch or or off ?

```
CPU: 5800X3D
GPU: RX 6700XT (XFX QICK319)
MoBo: MSI x570s Tomahawk Wifi Max (Latest Bios rev)

**Comment by Dropdead86** [comment]
I apparently managed to download the iso from the wrong place.
Everything worked fine once I figured out my mistake.
SteamOS is installed and working as intended.

**Comment by ghost** [comment]
What did you download from, I'm having the same issue
