### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by USL5264** [holoiso-eol/holoiso#358]
## Your Issue:
```
Unable to install for Dual Boot
```

## Your device's full specs
```
CPU: Intel i5 8250u 
GPU: Intel UHD620
```

## Your OS version
snapshot19700101_1011-beta2a
```

## Your installation type:
```
deckperience
```

Unable to install. Getting Partition does not exist even though I am using a unallocated space of 500gb

**Comment by USL5264** [comment]
![Uploading 4BE0F10C-5BE0-4356-BEE2-6DA5D397A337.jpeg…]()

**Comment by wynn1212** [comment]
This issue has now being address.
https://github.com/theVakhovskeIsTaken/holoiso-install-script/pull/4

**Comment by wynn1212** [comment]
Duplicate of #354
