### ISSUE TITLE
Problem with Wifi [MEDIATEK Corp. Device 7961]

### ISSUE THREAD

**Issue by fenpaws** [holoiso-eol/holoiso#359]
## Your Issue:

Today i decided to give Holoiso a shot and installed it with the latest version, the installation worked fine with wifi.

After I installed Holoiso and also boot into it, I no longer have wifi. It seems like the kernal modules for the wifi card are missing.

lspci -v showed me the following for that card:
```
04:00.0 Network controller: MEDIATEK Corp. Device 7961
        Subsystem: Lite-On Communications Inc Device 3802
        Flags: fast devsel, IRQ 255, IOMMU group 12
        Memory at fc02000000 (64-bit, prefetchable) [disabled] [size=1M]
        Memory at fc02100000 (64-bit, prefetchable) [disabled] [size=16K]
        Memory at fc02104000 (64-bit, prefetchable) [disabled] [size=4K]
        Capabilities: <access denied>

```

## Your device's full specs
```
Acer Nitro AN517-41 V1.08
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz
GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB
GPU: AMD ATI 05:00.0 Cezanne
RAM: 32GB
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220711.2136
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Its a fresh install, 2022/07/13
```

**Comment by PIPIPIG233666** [comment]
Booting w/ the 5.18 kernel should help.

**Comment by fenpaws** [comment]
ah okay that seams do  the trick, now I'm curious.

I had to boot into the  holoiso-linux kernel, now i wonder what's the difference is between these two kernels. And what exactly are those neptune-drivers.

is there a way to pin that Linux to be automatically booted when i start holoiso? Since i always need to select advanced and then boot with the holoiso-linux

**Comment by PIPIPIG233666** [comment]
Neptune is the default deck kernel shipped by Valve.
To set default kernel, you can install grub customizer and configure default boot option there.

**Comment by fenpaws** [comment]
AH okay, thanks for the info. Then i close this issue now.
