### ISSUE TITLE
Nvidia GPU 

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#36]
Would it be possible to release an iso alongside this one that has the Linux-steamos kernel and headers? It is possible to launch the deckUI and components using the launch options -steamos3 -gamepadui 
 -steampal. Would love to know!

**Comment by Gecked-Deck** [comment]
Game mode is not accessible due to gamescope and wayland is severely lacking on Nvidia. Just use the Deck launcher on another arch based distro
