### ISSUE TITLE
[Report] Cant use 120 hz of my tv

### ISSUE THREAD

**Issue by peterge1998** [holoiso-eol/holoiso#360]
## Your Issue:

I own a LG OLED55C17LB where my holoiso pc is connected to via a hdmi 2.1 cable.

## Your device's full specs
```
CPU: R5 1600X
GPU: RX6600
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Installed with latest iso from 12.7.
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nope
```

**Comment by PIPIPIG233666** [comment]
Add `-r 120` to the the launch parameter of gamescope script at `$(which gamescope-session)`.

**Comment by peterge1998** [comment]
> Add `-r 120` to the the launch parameter of gamescope script at `$(which gamescope-session)`.

U mean `/usr/bin/gamescope-session`? Dont understand the command substitution at `$(which gamescope-session)` :p

In which line is it? The script is huge... Searching for a Launch Section/Comment doesnt match... Thx!

**Comment by PIPIPIG233666** [comment]
> > Add `-r 120` to the the launch parameter of gamescope script at `$(which gamescope-session)`.
> 
> U mean `/usr/bin/gamescope-session`? Dont understand the command substitution at `$(which gamescope-session)` :p
> 
> In which line is it? The script is huge... Searching for a Launch Section/Comment doesnt match... Thx!

https://github.com/Samsagax/gamescope-session/blob/cb00bea5047aac8cba1d557c2036d5ac56235b3a/usr/bin/gamescope-session#L57

`40-60` to whatever you like, say `48-120` (this num looks good bc i have freesync/gsync)

https://github.com/Samsagax/gamescope-session/blob/cb00bea5047aac8cba1d557c2036d5ac56235b3a/usr/bin/gamescope-session#L108

then add the `-r 120` here

**Comment by peterge1998** [comment]
> https://github.com/Samsagax/gamescope-session/blob/cb00bea5047aac8cba1d557c2036d5ac56235b3a/usr/bin/gamescope-session#L57
> 
> `40-60` to whatever you like, say `48-120` (this num looks good bc i have freesync/gsync)
> 
> https://github.com/Samsagax/gamescope-session/blob/cb00bea5047aac8cba1d557c2036d5ac56235b3a/usr/bin/gamescope-session#L108
> 
> then add the `-r 120` here

I  tried editing changing `export STEAM_DISPLAY_REFRESH_LIMITS=40,60` to `80,120` but I can not the the file with vim bc readonly. How do edit it?
Do i need to change #L57 and #L108 or is #L57 enough? Thx!

**Comment by PIPIPIG233666** [comment]
>  bc readonly

sudo...

>  #L57 and #L108 or is #L57 enough

both

**Comment by peterge1998** [comment]
Awesome! That did it!
But they were in different lines than you wrote. Here are my line numbers and my edits for snapshot20220714.1259:
`L74 export ...=80,120`
`L157 -r 120 \`
Then setting the refresh rate to 120 works via the right menu in gaming mode!

**Comment by peterge1998** [comment]
Just to document this in here: there is no need to setup -W 3840 -H 2160, the resolution can be changed in the steam per game settings: https://www.gamingonlinux.com/2022/06/steam-deck-now-lets-you-override-display-resolution-for-games/

**Comment by ChaosBlades** [comment]
I forgot the \ and now my install won't show any video. I am guessing that this script will get overridden every time SteamOS updates as well. I think I'll just go back to ChimeraOS. SteamOS is too centered around the Deck hardware atm and what the community can do is limited.

**Comment by theVakhovskeIsTaken** [comment]
> ## Your Issue:
> 
> I own a LG OLED55C17LB where my holoiso pc is connected to via a hdmi 2.1 cable.
> 
> 
> ## Your device's full specs
> ```
> CPU: R5 1600X
> GPU: RX6600
> ```
> 
> ## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
> ```
> Installed with latest iso from 12.7.
> ```
> 
> ## Your installation type:
> ```
> deckperience
> ```
> 
> ## Have you updated your installation recently?
> ```
> nope
> ```
> 

Last note: gamescope update should allow you now to use HFR in DeckUI/ and maybe games

**Comment by peterge1998** [comment]
> I forgot the \ and now my install won't show any video. I am guessing that this script will get overridden every time SteamOS updates as well. I think I'll just go back to ChimeraOS. SteamOS is too centered around the Deck hardware atm and what the community can do is limited.

It doesnt get overwritten with every update, in my opinion the os is perfect for consoles too.

**Comment by peterge1998** [comment]
> Last note: gamescope update should allow you now to use HFR in DeckUI/ and maybe games

I am not at home right now. How is the setting called? Is it in options near to the per game resolution?

**Comment by ChaosBlades** [comment]
Well I tested ChimeraOS and it doesn't quite work right there either. Turns out to be a licensing issue and HDMI 2.1 does not work on Linux period at the moment and for the foreseeable future.

https://gitlab.freedesktop.org/drm/amd/-/issues/1417

Best you can do is `transmit 4K @ 120Hz but it gets transmitted in YCbCr 4:2:0 (which is within HDMI 2.0 specs) instead of YCbCr 4:4:4 or RGB` I can confirm this on my AV receiver.

So it is kind of a moot point that you need to mess with scripts to get it working at least at 4K over HDMI.

Guess I will go back to HoloISO then and keep an eye on that thread.

**Comment by peterge1998** [comment]
> Well I tested ChimeraOS and it doesn't quite work right there either. Turns out to be a licensing issue and HDMI 2.1 does not work on Linux period at the moment and for the foreseeable future.
> 
> https://gitlab.freedesktop.org/drm/amd/-/issues/1417
> 
> Best you can do is `transmit 4K @ 120Hz but it gets transmitted in YCbCr 4:2:0 (which is within HDMI 2.0 specs) instead of YCbCr 4:4:4 or RGB` I can confirm this on my AV receiver.
> 
> So it is kind of a moot point that you need to mess with scripts to get it working at least at 4K over HDMI.
> 
> Guess I will go back to HoloISO then and keep an eye on that thread.

;o
I dont know that much, but i can run games at 4k 120hz which is fine for me!
