### ISSUE TITLE
[Report] etc/stab can't be found

### ISSUE THREAD

**Issue by CodeBreakerSI** [holoiso-eol/holoiso#361]
-Latest stable install from 2 days ago
-etc/stab can't be found while in the installation process

**Comment by wynn1212** [comment]
Did you mean
```
mount: /mnt/home: can't find in /etc/fstab.
```
If this is the case. Then it's a duplicate of #356  And this problem is now being addressed.
https://github.com/theVakhovskeIsTaken/holoiso-install-script/pull/3
