### ISSUE TITLE
Can't use DeckUI

### ISSUE THREAD

**Issue by moreracamilo** [holoiso-eol/holoiso#363]
When my pc boots into gaming mode using gamescope, i get a black screen. I succeded in getting into desktop mode changing the auto login parameters, but when i try switching into gaming mode it sends me to the login page and only allows me to enter using plasma. My cpu is supossed to support vulkan so i don't know what to search for. Also when i run the command `gamescope` on the terminal, it seems to be working fine. I'm new into Arch Linux so maybe it's something i'm not seeing.

I'm using a mini PC from ViewSonic.
Model: VOT 335 Plus Pro
Cpu: Intel Celeron n3350
Igpu: Intel HD 500
Ram: 4gb ddr4
Storage: 60gb msata drive

**Comment by Cooler0951** [comment]
Same problem

**Comment by Cooler0951** [comment]
But I have: Nvidia GTX 1070, 16 GB RAM, 500 GB HDD, Intel Core i5 4670k, without iGpu

**Comment by ZombieBear** [comment]
Your GPU isn't supported by the new Nvidia drivers atm, I'm in the same boat with my 1080ti. Nothing we can do but wait and hope Nvidia gets their drivers sorted

**Comment by moreracamilo** [comment]
But HD 500 graphics shoud be supported and i sill can't make them work

**Comment by lavilao** [comment]
Newer gamescope does not work with Intel HD graphics, You have to downgrade gamescope to 3.9.5 (I think)

**Comment by SSchott** [comment]
I am confused. In the README it says:

> Only 10xx+ GPUs are FULLY supported. Although 9xx support exists in drivers, gamescope doesn't launch on it. Choose your GPU type while installing HoloISO. If you encounter any issues, reboot to recovery mode, type recoveryinit, connect to network using nmtui and install required packages.

I also have a 1070 Ti, and I can get into the GUI, but it is clearly buggy. If I select a game, it crashes. I guess the wording there is off?

**Comment by ZombieBear** [comment]
Nvidia support is still spotty, I'm on a 1080ti and can't even get into gamescope, but plasma used to work. On the new installer i can't even get into the DE. The gamescope developers are addressing every issue reported very quickly, so sadly at this point this is something that we're stuck waiting on Nvidia to solve in their drivers

**Comment by Frostyman758** [comment]
Hi, I'm on an Optimus laptop and can get into deckui and it completely works.

You need to make sure you modify the gamescope -session desktop file to use Nvidia related stuffs

**Comment by Frostyman758** [comment]
You don't need the open source drivers either.

**Comment by moreracamilo** [comment]
> Newer gamescope does not work with Intel HD graphics, You have to downgrade gamescope to 3.9.5 (I think)

The Intel install prevents gamescope from upgrading past 3.9.5, so it doesn't seem to be the problem either. I tried on another pc with HD 500 graphics and it has the same issue

**Comment by lavilao** [comment]
> > Newer gamescope does not work with Intel HD graphics, You have to downgrade gamescope to 3.9.5 (I think)
> 
> The Intel install prevents gamescope from upgrading past 3.9.5, so it doesn't seem to be the problem either. I tried on another pc with HD 500 graphics and it has the same issue

Then maybe it's the mesa drivers, I recently tried gamescope 3.9.5 self compile with mesa 22 something and it still crashes, which versión of mesa does holoiso comes with?
