### ISSUE TITLE
Enhancement add wifi-menu package to iso

### ISSUE THREAD

**Issue by crlink271986** [holoiso-eol/holoiso#365]
Wiifi-menu as it implies is a menu driven wifi connection (text) of iwctl it's on arch linux's pacman repo (maybe even aur could make connecting to wifi easier for install just a thought

**Comment by PIPIPIG233666** [comment]
I concur w this, but iwd is ez to use as well

**Comment by jrcharney** [comment]
> Wiifi-menu as it implies is a menu driven wifi connection (text) of iwctl it's on arch linux's pacman repo (maybe even aur could make connecting to wifi easier for install just a thought

Younger me would have been OK with this, with `iwd` is probably the better alternative especially since NetworkManager is often the cause of misbehaving Wifi.  See [what I wrote as a solution](https://github.com/theVakhovskeIsTaken/holoiso/issues/434#issuecomment-1214267551) to #434 as a reference.

**Comment by theVakhovskeIsTaken** [comment]
Noted.
