### ISSUE TITLE
fix: make Holo iso compatable with ventoy

### ISSUE THREAD

**Issue by crlink271986** [holoiso-eol/holoiso#366]
hi so i use ventoy most often (A multiboot iso usb installer) most arch distros work well holo iso doesn't (doesn't want to extract the fs for install and drops to initfs shell after timeout expires idk if it's ventoy itself or a fix on your end so maybe look at it I will post this issue on ventoy's github if it isn't fixable on your end

**Comment by Sparda333** [comment]
Try Easy2Boot instead

**Comment by Tourgasm** [comment]
> Try Easyboot instead

I looked up Easyboot and it's an old program for multiboot ISO's the question is: Is this the one you are talking about or are you talking about Easy2Boot?

**Comment by Sparda333** [comment]
> > Try Easyboot instead
> 
> 
> 
> I looked up Easyboot and it's an old program for multiboot ISO's the question is: Is this the one you are talking about or are you talking about Easy2Boot? 

Yeah my mistake it is Easy2boot

**Comment by npaladin2000** [comment]
Any way we can tweak things to use Ventoy instead? I'm not a fan of easy2boot
