### ISSUE TITLE
[Report] RX580X stuck at 300mhz

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#368]
So every time I open a game it caps my gpu clock to 300mhz and also limits my TDP. 
I tried changing things in gamescope and the config file but nothing.
I also tried:
```
"InstallConfigStore"
{
	"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"perf"
				{
					"GameProfiles"
					{
						"769"
						{
							"0"
							{
								"0"		"0d0000803f1001180120012802300138c801400048005000580f600168dc0b70017805800100880100900100980100a0013c"
							}
						}
					}
				}
				"AutoUpdateWindowEnabled"
				{
				}
				"ipv6check_http_state"		"good"
				"ipv6check_udp_state"		"good"
				"ShaderCacheManager"
				{
```

but it didnt work at all

**Comment by jmp7624** [comment]
This will fix it. It did for me
https://github.com/theVakhovskeIsTaken/holoiso/issues/294#issuecomment-1167051433

**Comment by ghost** [comment]
Thanks it fixed the problem for me as well
