### ISSUE TITLE
Is an AMD Radeon R5 430 supported?

### ISSUE THREAD

**Issue by RustyReich** [holoiso-eol/holoiso#369]
I'm confused on exactly what range of AMD graphics cards are supported. For example, would a Radeon R5 430 be supported since it is a 4xx card? Or does it need to be an RX 4xx card, not an R5? Trying to decide what would be the cheapest card to buy to just try messing around with holoISO

**Comment by Roman9365** [comment]
If your old ATI/AMD video card is from Southern Islands or Sea Islands families, you can enable the AMDGPU driver support to enable Vulkan and OpenGL 4.6 support in your Holoiso system.

Souther Islands models are : HD7750-HD7970, R9 270, R9 280, R9 370X, R7 240, R7 250
Sea Islands models are : HD7790, R7 260, R9 290, R7 360, R9 390

Holoiso **wont** work without Vulkan support!

**Comment by RustyReich** [comment]
> If your old ATI/AMD video card is from Southern Islands or Sea Islands families, you can enable the AMDGPU driver support to enable Vulkan and OpenGL 4.6 support in your Holoiso system.
> 
> Souther Islands models are : HD7750-HD7970, R9 270, R9 280, R9 370X, R7 240, R7 250 Sea Islands models are : HD7790, R7 260, R9 290, R7 360, R9 390
> 
> Holoiso **wont** work without Vulkan support!

According to [this site](https://www.techpowerup.com/gpu-specs/radeon-r5-430-oem.c2893), the R5 430 supports both Vulkan 1.2 and OpenGL 4.6, however it's not on the list of cards that you mentioned. Can I still expect it to work? Perhaps I should just try it out and report back.

**Comment by Mate1980** [comment]
> If your old ATI/AMD video card is from Southern Islands or Sea Islands families, you can enable the AMDGPU driver support to enable Vulkan and OpenGL 4.6 support in your Holoiso system.
> 
> Souther Islands models are : HD7750-HD7970, R9 270, R9 280, R9 370X, R7 240, R7 250 Sea Islands models are : HD7790, R7 260, R9 290, R7 360, R9 390
> 
> Holoiso **wont** work without Vulkan support!

I'm trying to install Holoiso with an hd7790. How can i enable the driver to support Vulkan?
