### ISSUE TITLE
Wget is not installed by default 

### ISSUE THREAD

**Issue by Divuff** [holoiso-eol/holoiso#37]
Wget is needed for holoinstall, but is not installed by default requiring the user to:
_pacman -Sy_
_pacman -S wget_ 
and then run 
_holoinstall_

**Comment by theVakhovskeIsTaken** [comment]
[Resolved](https://github.com/theVakhovskeIsTaken/holoiso/commit/9e43fc446d256ae226a46d3bb227b4edeb836f36)
