### ISSUE TITLE
How can i change the TDP of Holoiso?

### ISSUE THREAD

**Issue by Koniasy** [holoiso-eol/holoiso#370]
Why does my TDP adjustment not work?
My mechine is onexplayer mini(5800u），The power consumption of the whole machine has been constant even if I change the TDP in the settings.
Anyone have any solutions for this?
Thank u!

**Comment by alansari** [comment]
https://github.com/ShadowBlip/HandyPT <-- big shoutout to pastaq for making this possible
follow instructions on the github page.  Currently setting don't persist across reboots, but can be easily reapplied. 

Or for a more manual/advanced method is yay -S ryzenadj -> create a systemd script that wants default.target suspend.target and run your script with custom settings like tcltmp and tclskintmp which i find more useful.

**Comment by pastaq** [comment]
> https://github.com/ShadowBlip/HandyPT <-- big shoutout to pastaq for making this possible follow instructions on the github page. Currently setting don't persist across reboots, but can be easily reapplied.
> 
> Or for a more manual/advanced method is yay -S ryzenadj -> create a systemd script that wants default.target suspend.target and run your script with custom settings like tcltmp and tclskintmp which i find more useful.

I'm looking to add tcltmp & tclskintmp in a future update. Probably not 0.2.0 as that's already going to be a pretty big feature set at this point. Maybe 0.3.0 w/ persistence. Thus will need lots of validation testing for safe params though. I've been pushing my Aya Neo pretty hard and it seems to thermally throttle earlier than it should so I see the need.

**Comment by McWalters00** [comment]
> https://github.com/ShadowBlip/HandyPT <-- big shoutout to pastaq for making this possible
> 
> follow instructions on the github page.  Currently setting don't persist across reboots, but can be easily reapplied. 
> 
> 
> 
> Or for a more manual/advanced method is yay -S ryzenadj -> create a systemd script that wants default.target suspend.target and run your script with custom settings like tcltmp and tclskintmp which i find more useful.

Crankshaft doesn’t work anymore, is there another solution?

**Comment by pastaq** [comment]
> > https://github.com/ShadowBlip/HandyPT <-- big shoutout to pastaq for making this possible
> > follow instructions on the github page.  Currently setting don't persist across reboots, but can be easily reapplied.
> > Or for a more manual/advanced method is yay -S ryzenadj -> create a systemd script that wants default.target suspend.target and run your script with custom settings like tcltmp and tclskintmp which i find more useful.
> 
> Crankshaft doesn’t work anymore, is there another solution?

You can manually install RyzenAdj for now and create a boot script with your preferred settings. I'm working on an alternative to crankshaft but it's slow moving at the moment.

**Comment by McWalters00** [comment]
> > > https://github.com/ShadowBlip/HandyPT <-- big shoutout to pastaq for making this possible
> 
> > > follow instructions on the github page.  Currently setting don't persist across reboots, but can be easily reapplied.
> 
> > > Or for a more manual/advanced method is yay -S ryzenadj -> create a systemd script that wants default.target suspend.target and run your script with custom settings like tcltmp and tclskintmp which i find more useful.
> 
> > 
> 
> > Crankshaft doesn’t work anymore, is there another solution?
> 
> 
> 
> You can manually install RyzenAdj for now and create a boot script with your preferred settings. I'm working on an alternative to crankshaft but it's slow moving at the moment.

I’m not very strong in this area but how can we create a script with it?

**Comment by pastaq** [comment]
You'll need to make a systemd unit file that runs the ryzenadj command at startup. Take a look at the systemd documentation for how to do that. Use the ryzenadj help files or wiki to figure out the command you want to run.

**Comment by McWalters00** [comment]
> You'll need to make a systemd unit file that runs the ryzenadj command at startup. Take a look at the systemd documentation for how to do that. Use the ryzenadj help files or wiki to figure out the command you want to run.

OK, thank you for your answers
