### ISSUE TITLE
[Report] System does not go to sleep

### ISSUE THREAD

**Issue by peterge1998** [holoiso-eol/holoiso#374]
## Your Issue:
When i select power > sleep the screen goes black but i can not control my pc anymore
I have to force power off it then...

## Your device's full specs
R5 1600x
Rx 6600

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220716.1259
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
Y, see https://github.com/theVakhovskeIsTaken/holoiso/issues/378

**Comment by shoesio** [comment]
I have this issue with Neptune core, resolved with Holoiso core. (AMD gpu / intel i5)

**Comment by peterge1998** [comment]
> I have this issue with Neptune core, resolved with Holoiso core. (AMD gpu / intel i5)

What is neptune core? Custom kernel?

**Comment by shoesio** [comment]
Sorry my bad - I mean Neptune kernel. There are two kernel options for Holoiso, “Neptune” and “Holoiso”. I swapped and this problem was resolved for me.

**Comment by peterge1998** [comment]
> Sorry my bad - I mean Neptune kernel. There are two kernel options for Holoiso, “Neptune” and “Holoiso”. I swapped and this problem was resolved for me.

Where can u change the kernel?

**Comment by shoesio** [comment]
Easiest way is on boot - a message should appear as it starts up giving you the options.

**Comment by peterge1998** [comment]
Not working either...
