### ISSUE TITLE
Switch Support ?

### ISSUE THREAD

**Issue by Lolothepro** [holoiso-eol/holoiso#375]
Like L4T Ubuntu, but with HoloISO.
https://archlinuxarm.org/
https://archlinuxarm.org/about/downloads
https://wiki.switchroot.org/en/Linux/Distributions
https://github.com/Stary2001/l4t-arch
Used the Arch Linux ARM packages
And port SteamOS x86 packages to arm64

While this is a lot of work, perhaps you could create an independent Nintendo Switch compatibility team.

**Comment by Super-6-1** [comment]
Imo I don't see this being worth the effort mostly in part of 99% of games run on x86 and not arm. The switch is a 7 year old hardware alongside that hardware already being another 5 years if I'm right. You wouldn't get very far at all.

**Comment by Lolothepro** [comment]
But a specificity of HoloISO is that you can use your PC and play the game on the Steam Deck.

**Comment by ZombieBear** [comment]
That's available on any Linux distribution that can run the steam client, isn't it?

**Comment by Lolothepro** [comment]
Yes and ? The Steam client is only compatible with AMD64

**Comment by ZombieBear** [comment]
Good point i hadn't considered. But this exists https://www.gamingonlinux.com/2022/04/box86-and-box64-get-steam-play-proton-working-much-better-on-arm-devices/, which includes support for steam play, hope it helps

**Comment by theVakhovskeIsTaken** [comment]
when valve does arm64 steamos then you can hope for it
