### ISSUE TITLE
[Feature] [TESTED AND PROVEN] Optimus laptop, gamescope session 

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#377]
I'd like to submit my conclusive research into getting gamescope running on Optimus Prime based laptops with Nvidia GPUs. Using Nvidia -tkg and the following launch options gamescope becomes fully functional in this setup.

DRI_PRIME=1 MESA_VK_DEVICE_SELECT=10de:1347 NV_PRIME_RENDER_OFFLOAD=1 VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia gamescope --generate-drm-mode fixed --xwayland-count 1 -f -w 1920 -h 1080 -r 60 -e -- steam -steamos -gamepadui -steamdeck

I request that holoiso add this as an installation option for us Prime laptop users.
To my knowledge, should be as simple as changing the program dir in the session config...
With that, you nay also want to include Optimus -manager with a custom config that defaults boot modes to hybrid. 

Additionally, disabling mangohud globally made be required as well as enabling the Intel performance option.

P.S, would love a shout-out for this

~fox~

**Comment by Super-6-1** [comment]
I wouldn't mind seeing this ether, would to use have a use from my razer laptop.

**Comment by kmk2977** [comment]
@Frostyman758 where to write this or how did u achieved to install it on optimus laptops

**Comment by Frostyman758** [comment]
Hi, plug it into the terminal and it should just launch. I recommend downloading the gamescope-session package from the chimera team to make it fully functional. Other than that, pretty much just works

**Comment by kmk2977** [comment]
@Frostyman758 the thing is holo iso won't boot with nvidia on it so will I have to install Intel drivers and then paste this into the console once it boots up??

**Comment by kmk2977** [comment]
@Frostyman758 can u please tell step by step it didn't work for me

**Comment by Frostyman758** [comment]
It should boot with Nvidia drivers installed...

**Comment by kmk2977** [comment]
I selected Intel as GPU driver and then pasted this code it shows some werid error

**Comment by Skyvee** [comment]
Hi @Frostyman758 ,so sorry to ping so late after the original post, but what are the steps to getting this to work? and will I need to follow them every time I want to use the gamescope? thank you so much

**Comment by Frostyman758** [comment]
Literally just copy and paste into a terminal..

**Comment by KiralyCraft** [comment]
This is highly specific for @Frostyman758's device. You should replace `10de:1347` with the corresponding ID of your GPU, which you can find out by doing `lspci -nn | grep -i vga`. For example, this command gives me (on my single-GPU desktop):

> 07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)

So I'd need to put `1002:67df` in there. Also remember to change `-w 1920 -h 1080 -r 60` to your resolution and refresh rate.

**Comment by theVakhovskeIsTaken** [comment]
> I'd like to submit my conclusive research into getting gamescope running on Optimus Prime based laptops with Nvidia GPUs. Using Nvidia -tkg and the following launch options gamescope becomes fully functional in this setup.
> 
> DRI_PRIME=1 MESA_VK_DEVICE_SELECT=10de:1347 NV_PRIME_RENDER_OFFLOAD=1 VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia gamescope --generate-drm-mode fixed --xwayland-count 1 -f -w 1920 -h 1080 -r 60 -e -- steam -steamos -gamepadui -steamdeck
> 
> I request that holoiso add this as an installation option for us Prime laptop users.
> To my knowledge, should be as simple as changing the program dir in the session config...
> With that, you nay also want to include Optimus -manager with a custom config that defaults boot modes to hybrid. 
> 
> Additionally, disabling mangohud globally made be required as well as enabling the Intel performance option.
> 
> P.S, would love a shout-out for this
> 
> ~fox~



> This is highly specific for @Frostyman758's device. You should replace `10de:1347` with the corresponding ID of your GPU, which you can find out by doing `lspci -nn | grep -i vga`. For example, this command gives me (on my single-GPU desktop):
> 
> > 07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)
> 
> So I'd need to put `1002:67df` in there. Also remember to change `-w 1920 -h 1080 -r 60` to your resolution and refresh rate. 
> 

And this, is why i don't do it. Because it's not unified to be used with ALL systems :D

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/gamescope-steamos-pkgbuild/commit/99db858635617f6c99863b9c902a5ededcc4864f

WIP.
