### ISSUE TITLE
Surface Pro 3 - No Wifi

### ISSUE THREAD

**Issue by PatrickJnr** [holoiso-eol/holoiso#38]
Wireless Adapter can't be found using iwctl, Checked the ArchWiki and still could not fix it. I think I need the marvel firmware stuff.

**Comment by theVakhovskeIsTaken** [comment]
Got you. Will ship `linux-firmware-marvell` on next release then.

**Comment by PatrickJnr** [comment]
What iso should I use? since you've uploaded an update only package atm.


Nvm. Still can't install latest iso 🥺

**Comment by PatrickJnr** [comment]
Sorry for being a pain, still can't detect devices with the latest iso @theVakhovskeIsTaken
