### ISSUE TITLE
No Bootable Devices Found after install[Report]

### ISSUE THREAD

**Issue by Nickmate99** [holoiso-eol/holoiso#380]
## Your Issue: No bootable devices found
```
*type your problem here* Flashed using Rufus in DD mode (4096k) and Etcher, installed Jupiter and Linux-iso, after install wont boot. Tried different iso builds. 
```

## Your device's full specs
```
Dell 790
CPU: i5 2500
GPU:  RX6400
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by doomhound188** [comment]
I'm having the same issue with a lenovo M81 with an i7 2600, I think its a limitation of the UEFI implementation on old hardware 
i7 2600
GTX 1050ti
