### ISSUE TITLE
Sleep/Suspension fails to boot properly (freezing)

### ISSUE THREAD

**Issue by Super-6-1** [holoiso-eol/holoiso#387]
## Your Issue:
``` Sleep/Suspension not working, boots to freeze
*type your problem here*
``` When the power button is pressed, the device acts like its going to sleep/suspension, when its pressed again to wake up the screen comes back to normal but nothing works, sound, controls, screen stays frozen. Have to hard reset to fix the issue. 

## Your device's full specs
```
APU: Ryzen 7 4800U 

Aya neo 2021 pro
```

## Your OS version :
```snapshot20220716.2021
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Installed as of yesterday with nothing to update. 
```

**Comment by alansari** [comment]
https://github.com/ShadowBlip/rz608-fix

clone and install this to fix suspend

**Comment by Super-6-1** [comment]
> https://github.com/ShadowBlip/rz608-fix
> 
> clone and install this to fix suspend

I've done this and it doesn't seem to fix any issues

**Comment by schmak01** [comment]
I am having the same issue, listed fix did not work.  I am using an R5 5500 and 6700XT. I had a previous version of Holo installed and did a reformat to the latest version today.  It shuts off the screen, but never goes into the lower state modes, power appears to still be fully on.  Fans and power light on as normal.  I have to fully shut down by either the PSU switch or holding the power button for 10 seconds to power down and reboot to get the screen back.  Using mouse/keyboard/controller do not bring the screen back. 

The same behaviour happens on reboot. 

Operating System: SteamOS 3.3
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve22-1-neptune-02213-gb68995364335 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5500
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Comment by schmak01** [comment]
If it helps any, when I manually select SteamOS with the Holo-Linux instead of the default selection or neptune, sleep, reboot, everything works great.

**Comment by Super-6-1** [comment]
> If it helps any, when I manually select SteamOS with the Holo-Linux instead of the default selection or neptune, sleep, reboot, everything works great.

What I did for this was download grub configurator in the discovery app and set the holoiso kernel as default.

**Comment by Super-6-1** [comment]
Update: so I finally got it working. Install the fix 

https://github.com/ShadowBlip/rz608-fix

Then download grub configurator in discovery and set the kernel to the normal holoiso kernel, not the other two, fallback or recovery) reboot and it should work.

**Comment by schmak01** [comment]
Thanks, I did the fix but I am curious if it is needed.  I manually edited the /boot/grub/grub.conf file in kate, just copied the lines for the holoiso kernel and pasted over the neptune for default.
