### ISSUE TITLE
After installing the latest update, the controller stopped working. It is aya neo fe. I'm going to install steamOs again from scratch...

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#388]
After installing the latest update, the controller stopped working. It is aya neo fe. I'm going to install steamOs again from scratch...

**Comment by JongAnYoo** [comment]
There seems to be a bug that prevents the xbox controller from being mounted in the latest version of the OS.

**Comment by FabianBittner** [comment]
This seems to be still the case. Just installed HoloISO on my Aya Neo Pro 2021 and have the same issue. Controller is not working at all, just "Esc" Button reacts and goes back. Any fix for that existing yet?
