### ISSUE TITLE
[Report]There seems to be a bug that prevents the xbox controller from being mounted in the latest version of the OS.

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#389]
There seems to be a bug that prevents the xbox controller from being mounted in the latest version of the OS.

**Comment by CorValidum** [comment]
Not just Xbox but it was unable to find any BT device when turned on and searched for at least 3min...

**Comment by patrickjquinn** [comment]
There were controller firmware-related changes pushed in the steam stable channel that has broken controller support entirely for me too (Aya Neo 2021).

**Comment by Pender6666** [comment]
Not only that but I guess it affects all input devices connected via USB. My wireless mouse and keyboard (Microsoft conected via dongle) doesn't work too after boot on DeckUI. No mouse, keyboard and controller. Keyboard works ok on grub screen, tho.

**Comment by robisaacnz** [comment]
I also have this problem on the very latest version. Ryzen 5 5600G. No USB device (mouse, keyboard, several controllers) functions once booted to the Steam Deck UI.

**Comment by Pender6666** [comment]
I managed to work around it. Boot with advanced options then choose "SteamOS, Linux linux-holoiso" instead linux-neptune. Worked here, have a try.
