### ISSUE TITLE
drmSetClientCap(ATOMIC) failed

### ISSUE THREAD

**Issue by RustyReich** [holoiso-eol/holoiso#390]
So I'm trying to get holoISO running on an old AMD R5 430. At first, it would freeze at `loading initial ramdisk` for each grub selection, but I was able to get past that be booting into recovery and running `holoiso-disable-sessions`.

Then I was able to boot into the non-neptune grub option and make it to the login screen. Once there, I was only able to sign into the Plasma desktop, as the gamescope session would crash. While there, I ran `vulkaninfo` and discovered that vulkan was not working properly. I was able to solve this issue by following [this guide](https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support) to enable CIK support and get the proper driver loaded. I also downgraded gamescope to version 3.9 while doing this, not sure if that was necessary but it didn't seem like it could hurt.

After that, `vulkaninfo` was running, but was still throwing an error relating to an nvidia vulkan driver. To get rid of that error, I unintalled `nvidia-utils` as there is no nvidia card in this machine so it seemed unneeded.

Now, running `vulkaninfo` appears to show that vulkan is working correctly. Here is the output when ran:
```
WARNING: radv is not a conformant Vulkan implementation, testing use only.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.203


Instance Extensions: count = 19
===============================
        VK_EXT_acquire_drm_display             : extension revision 1
        VK_EXT_acquire_xlib_display            : extension revision 1
        VK_EXT_debug_report                    : extension revision 10
        VK_EXT_debug_utils                     : extension revision 2
        VK_EXT_direct_mode_display             : extension revision 1
        VK_EXT_display_surface_counter         : extension revision 1
        VK_KHR_device_group_creation           : extension revision 1
        VK_KHR_display                         : extension revision 23
        VK_KHR_external_fence_capabilities     : extension revision 1
        VK_KHR_external_memory_capabilities    : extension revision 1
        VK_KHR_external_semaphore_capabilities : extension revision 1
        VK_KHR_get_display_properties2         : extension revision 1
        VK_KHR_get_physical_device_properties2 : extension revision 2
        VK_KHR_get_surface_capabilities2       : extension revision 1
        VK_KHR_surface                         : extension revision 25
        VK_KHR_surface_protected_capabilities  : extension revision 1
        VK_KHR_wayland_surface                 : extension revision 6
        VK_KHR_xcb_surface                     : extension revision 6
        VK_KHR_xlib_surface                    : extension revision 6
...
```
I've cut the output short because it is very long for this post, but can post the entire output if that would be helpful in troubleshooting.

Unfortunately, trying to load into a gamescope session from the login screen still shows nothing but a black screen, kicking me back to the login after a few seconds. If I press Cntrl+Alt+F4 at the login screen to bring up the terminal, I can run `gamescope-session` from there and get the following output:
```
/usr/bin/gamescope-session: line 28: /usr/bin/ev2fixaudio.sh: No such file or directory
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
wlserver: [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
WARNING: radv is not a conformant Vulkan implementation, testing use only.
vulkan: selecting physical device 'AMD RADV OLAND'
vulkan: physical device does not support DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
drm: drmSetClientCap(ATOMIC) failed
Failed to initialize output
/usr/bin/gamescope-session: line 76: kill: (1479) - No such process
```
From this, it appears that gamescope is failing at the line `drm: drmSetClientCap(ATOMIC) failed` which I'm assuming is because of the line `vulkan: physical device does not support DRM format modifiers`.

Is the fact that the card does not `support DRM format modifiers` implying that the card is simply not supported, even though it appears to support vulkan just fine?

**Comment by ReisenBagels** [comment]
Managed to experience the same behaviour, Upon booting up desktop mode I began starting a game(as prior to the steps using the arch wiki I could not launch any titles). This allowed me to boot the game and play. After which I began running gamescope-session in konsole which returned a wayland error appearing to progress further.

Using another ttys (ctrl+alt+F2) I attempted to run gamescope there which returned the same behaviour as above. Restarting the workstation and attempting again proved to be futile. I will attempt to reproduce this again at a later date.
