### ISSUE TITLE
[REQUEST] GCN 2.0 (GFX7xx) and GCN 3.0 (GFX8xx) support

### ISSUE THREAD

**Issue by iamhumanipromise** [holoiso-eol/holoiso#392]
GCN 3.0 (R9 390X, R9 Fury for example) support FP16 and FP32, though there is no performance difference between the two. Functionally: GFX8xx cards should work - just as they do "experimentally" with ROCM/HSA/HIP/etc compute stacks. No one bothers adding the GPU, so they don't get added -- but should work just fine. 

Is that what is holding back support for GCN 3.0-series cards? "GCN 4.0 is essentially a port of GCN 3.0 to 14nm and 12nm" someone once said. 

What would it take to add support for them? A request at the mesa gitlab for various hardware IDs to be added somewhere? This request here for a holoiso specific file to enable the additional hardware ids? 

Additionally, the various rocm compilers have gfx7xxx support still present while scrolling through the compile logs - so it would be interesting to see if GCN 2.0 support was feasible "down the line"

**Comment by theVakhovskeIsTaken** [comment]
https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support
