### ISSUE TITLE
Stop changes made in system folder from reverting back

### ISSUE THREAD

**Issue by godtoall82** [holoiso-eol/holoiso#394]
I have a DS4 controller with custom ABXY buttons. I went into the folder containing the controller button images and replaced the standard PS icons with ABXY icons, but the changes I made reverted back to standard PS buttons upon entering gaming mode. Is there anyway to stop this from happening?

**Comment by Pender6666** [comment]
Did you tried make it read only?

**Comment by godtoall82** [comment]
> Did you tried make it read only?

This did the trick. Thanks!
