### ISSUE TITLE
Upgrade process?

### ISSUE THREAD

**Issue by rkr87** [holoiso-eol/holoiso#396]
Is there a set process to install a more recent version of Holoiso over the top of an existing install?

I don't want to lose everything in /holo-home/

**Comment by PIPIPIG233666** [comment]
To update: sudo pacman -Sy holostaging/holoiso-updateclient or steamos-update check && steamos-update now

^ directly copied from telegram support group pinned message

**Comment by rkr87** [comment]
hmmm I get the following errors;

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: target not found: holoiso-updateclient
error: target not found: steamos-update

**Comment by PIPIPIG233666** [comment]
You need to update your sources first then.
Add

> [holoiso]
> Server = http://dl.thevakhovske.pw/pacman/$repo/os/$arch
> SigLevel = Never
> 
> [holostaging]
> Server = http://dl.thevakhovske.pw/pacman/$repo/os/$arch
> SigLevel = Never
> 
> [jupiter-main]
> Include = /etc/pacman.d/mirrorlist
> SigLevel = Never
> 
> [holo]
> Include = /etc/pacman.d/mirrorlist
> SigLevel = Never

to /etc/pacman.conf.

After that, refresh using `sudo pacman -Syu` and run the update again.

**Comment by rkr87** [comment]
Gave it a try and got the error below;

```
 lib32-mesa-steamos-22.0.0_devel.148040.radeonsi_20220217-5-x86_64                                                  0.0   B  0.00   B/s 00:00 [#######################################################################################] 100%
(2/2) checking keys in keyring                                                                                                                [#######################################################################################] 100%
(2/2) checking package integrity                                                                                                              [#######################################################################################] 100%
:: File /var/cache/pacman/pkg/lib32-mesa-steamos-22.0.0_devel.148040.radeonsi_20220217-5-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.
```
I'm just going to back up my critical files and do a fresh install with the latest iso.

Thanks for the help.

**Comment by PIPIPIG233666** [comment]
Why did you choose n? Just enter y and proceed...

**Comment by rkr87** [comment]
> Why did you choose n? Just enter y and proceed...

That was the 2nd time I tried it, first time I pressed y and got the same result.

**Comment by Maykin-99** [comment]
The update process isn't working for me.
I'm in the Deck UI in the "Preview" channel, but I'm still on v3.2 and Kernel is at 5.13.0.

```
$ steamos-update check
System up to date.
```

```
$ sudo pacman -Syu
:: Synchronizing package databases...
 holoiso-beta is up to date
 holostaging is up to date
 jupiter-main is up to date
 holo is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: grub: ignoring package upgrade (2:2.06-4 => 2:2.06-4.5)
warning: holoiso-updateclient: local (rel.20220718.1953-1) is newer than holoiso-beta (rel.20220530.1913-1)
warning: ignoring package replacement (linux-firmware-20220119.0c6a7b3-2 => linux-firmware-neptune-20220624.650ab31-1)
warning: ignoring package replacement (linux-firmware-20220119.0c6a7b3-2 => linux-firmware-neptune-rtw-debug-20220524-1)
 there is nothing to do
```

**Comment by DocMAX** [comment]
Do i understand correctly: We don't get the updates from Steam directly but from your repository? So we can't get the updates imedatelly but we have to wait for HoloISO repo update?

**Comment by PIPIPIG233666** [comment]
> The update process isn't working for me. I'm in the Deck UI in the "Preview" channel, but I'm still on v3.2 and Kernel is at 5.13.0.
> 
> ```
> $ steamos-update check
> System up to date.
> ```
> 
> ```
> $ sudo pacman -Syu
> :: Synchronizing package databases...
>  holoiso-beta is up to date
>  holostaging is up to date
>  jupiter-main is up to date
>  holo is up to date
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
> :: Starting full system upgrade...
> warning: grub: ignoring package upgrade (2:2.06-4 => 2:2.06-4.5)
> warning: holoiso-updateclient: local (rel.20220718.1953-1) is newer than holoiso-beta (rel.20220530.1913-1)
> warning: ignoring package replacement (linux-firmware-20220119.0c6a7b3-2 => linux-firmware-neptune-20220624.650ab31-1)
> warning: ignoring package replacement (linux-firmware-20220119.0c6a7b3-2 => linux-firmware-neptune-rtw-debug-20220524-1)
>  there is nothing to do
> ```

Deck UI has nothing to do with the kernel, just check if you have newer ones installed and select it in grub boot menu.
