### ISSUE TITLE
steamos-session-select doesn't exist

### ISSUE THREAD

**Issue by rkr87** [holoiso-eol/holoiso#397]
I'm unable to access gaming mode via the desktop shortcut as I get an error say the above executable doesn't exist - anything I can do to fix this without a fresh install?

**Comment by bvanroll** [comment]
I just installed for the first time and am also missing this command :/
`[beppe@desktop bin]$ which steamos-session-select
which: no steamos-session-select in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
`

(also i don't know if this is relevant but i was missing pacman.conf. I just grabbed it from the root of the project)

**Comment by rkr87** [comment]
> I just installed for the first time and am also missing this command :/ `[beppe@desktop bin]$ which steamos-session-select which: no steamos-session-select in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl) `
> 
> (also i don't know if this is relevant but i was missing pacman.conf. I just grabbed it from the root of the project)

I had the same issue re pacman.conf. I haven't identified exactly what causes it but it seems after a fresh install the files are there, something triggers all steamos and holoiso scripts to be deleted. I've seen this happen 3 times now, I'm not certain of the cause but I think it's related to either installing packages via pacman, updating grub or running os-prober, as those are things I do fairly early following a fresh install. 

For now, after my most recent fresh install I took backups of the /etc/ /bin/ and /usr/ directories and I restore in to them whenever I notice the files have gone again.

**Comment by bvanroll** [comment]
Interesting. I did not use os prober/update grub and also did not use pacman to install any packages before encountering the missing config file. 
I believe my only actions after dinishing holoiso's installation were installing an update from the gamemode ui, removing chromium and installing firefox (flatpack).

Next boot however it was impossible to return to desktop mode from gamemode so I reinstalled holoiso and did get the command.

Using it to try and set kde plasma as the default just dumped me back into gamemode. (I couldn't find documentation on how the command worked so I just used the command from this reddit post https://www.reddit.com/r/SteamOS/comments/ulwmld/comment/i83rj8t/)

**Comment by rkr87** [comment]
Hmm interesting, I wonder if it's related to uninstalling Chromium as that's the first thing I do on fresh install too.

As far as changing default booting and ensuring the session switch always works I made the following changes to my install (the default steamos-session-select script wouldn't switch from gamemode to desktop for me).

**/bin/steamos-session-select**
Change:
`sudo systemctl reset-failed sddm && touch /tmp/steamos-sessionselect-sentinel && sudo systemctl restart sddm`
To:
`sudo pkill -f "gamesc*" && sudo startplasma-x11 && sudo systemctl reset-failed sddm && sudo systemctl restart sddm`

**/etc/sddm.conf.d/autologin.conf**
To start in gamemode:
`Session=gamescope-wayland`
to start in desktop mode:
`Session=plasma.desktop`

**Comment by bvanroll** [comment]
Nice thanks for the info, i'll try this out next time i try out holoiso again!
