### ISSUE TITLE
[Report]How to adjust grub's default startup

### ISSUE THREAD

**Issue by huchenghe001** [holoiso-eol/holoiso#398]
## Your Issue:

The default boot system cannot be used because the Linux system kernel is not updated with wifi. It is more troublesome to enter the system with the keyboard every 

## Your device's full specs
```
CPU: r7 5800u

**Comment by PIPIPIG233666** [comment]
grub-customizer

**Comment by KingOfFalcons** [comment]
grub customizer wont load. any other suggestions?

**Comment by ConvexTlc97** [comment]
Still not fixed? Where is the documentation from the creators on how to change the grub without grub customizer since it Borks systems.
