### ISSUE TITLE
Cant open game mode

### ISSUE THREAD

**Issue by Skyvee** [holoiso-eol/holoiso#401]
Im on an i7 8750H gtx 1060m laptop with the latest nvidia version of holoiso and the gaming mode will not open, either through the login screen or on the desktop. It shows the boot terminal for a few seconds and then brings me to the login page again.

**Comment by Frostyman758** [comment]
Hi, in order to fix this, you need to pass certain variables into the launch CMD for the gamescope session and then it will work

**Comment by Skyvee** [comment]
thanks, what are the variables I need to pass, and where do I pass them?
