### ISSUE TITLE
/var/mnt: special device /dev/sda3 does not exist; Something went wrong when mounting root partitions.

### ISSUE THREAD

**Issue by tasnimtamim** [holoiso-eol/holoiso#405]
Specification; Ryzen 3 2200G, 8GB RAM, Vega 8 APU, 500GB WD Blue HDD

This is the error:
![image](https://user-images.githubusercontent.com/52713990/180708604-5e6f4fae-8430-42e2-a95c-9613bd2e32ec.png)
And the prompt for selecting disk:
![image](https://user-images.githubusercontent.com/52713990/180708702-025ef591-1862-4081-bdd1-b46ad9fd2709.png)
I chose to install alongside other OS/Partitions. No erase was done. I have tried making a extra 200GB unallocated partition from Windows as well as keeping it intact and letting the setup do the resizing/partitions. Both gave same issue. Even disconnected all my other 2 drives and only having 1 HDD plugged in. Same.
I would prefer not erasing the drive as well. The installation worked flawlessly fine (albeit a whole hour long) on my Intel CDC laptop as just a test, but only causing issues on my PC.

**Comment by ValfarDeveloper** [comment]
Related to [#639](https://github.com/theVakhovskeIsTaken/holoiso/issues/639)

**Comment by TF5113** [comment]
managed to solve the problem?

**Comment by TF5113** [comment]
I also have this problem

**Comment by ELadrimonos** [comment]
I also have this problem when trying to install alongside another partition
