### ISSUE TITLE
Is there a Dockerfile or reproduction steps for the `thevakhovske/holoiso` Docker image?

### ISSUE THREAD

**Issue by randombk** [holoiso-eol/holoiso#406]
Hi, looking at the build pipeline, it seems to depend on the `thevakhovske/holoiso` Docker image. What is this image, and are there steps to reproducing it?

**Comment by olegshulyakov** [comment]
@randombk Are you looking for this instructions? https://github.com/theVakhovskeIsTaken/holoiso/pull/371

**Comment by randombk** [comment]
No quite, but the PR helps.

I was referring to this step in the CI pipeline: https://github.com/theVakhovskeIsTaken/holoiso/blob/3.4/.github/workflows/build.yml#L16

This doesn't seem to be documented anywhere, which is concerning to me because there's no traceable steps for how the ISOs on the release page were generated. I know we're far from getting reproducible builds, but every little bit helps.

**Comment by theVakhovskeIsTaken** [comment]
> Hi, looking at the build pipeline, it seems to depend on the `thevakhovske/holoiso` Docker image. What is this image, and are there steps to reproducing it?

https://vakdl.enablers.workers.dev/6:/recoveryimg/bootstrap/SteamOS_3-2_steamdeck-main_20220630_2230.tar.gz

_Import as docker image by docker import SteamOS_3-2_steamdeck-main_20220630_2230.tar.gz holo_

This image is created by running "pacstrap -U /mnt base base-devel" on a separate folder as rootfs bootstrap, and then importing to dockerhub.
