### ISSUE TITLE
Black screen after gui login

### ISSUE THREAD

**Issue by bbgoose92** [holoiso-eol/holoiso#41]
Installed with all default settings, I only get a black screen after logging in, can't crtl alt f2 either.
I have an HP omen 16
Ryzen 7 5800h
Rx 6600m 
16 gb RAM
1 tb NVME
I get a mouse for around one second, then that disappears too.

**Comment by ludaka** [comment]
Same issue with nvidia gpu and core i5 4th gen .. i has thinking that its bcs nvidia is not supported and i boot it like they said with nomodeset=1 .. but then it won't even boot

**Comment by theVakhovskeIsTaken** [comment]
> Installed with all default settings, I only get a black screen after logging in, can't crtl alt f2 either.
> I have an HP omen 16
> Ryzen 7 5800h
> Rx 6600m 
> 16 gb RAM
> 1 tb NVME
> I get a mouse for around one second, then that disappears too. 

Can you select `Plasma (X11)` in session selection, login and run `gamescope-session` in terminal?

**Comment by bbgoose92** [comment]
> > Installed with all default settings, I only get a black screen after logging in, can't crtl alt f2 either.
> > I have an HP omen 16
> > Ryzen 7 5800h
> > Rx 6600m
> > 16 gb RAM
> > 1 tb NVME
> > I get a mouse for around one second, then that disappears too.
> 
> Can you select `Plasma (X11)` in session selection, login and run `gamescope-session` in terminal?

I'll boot up and try this, thanks. 
Also to be clear when installing the default boot selection isnt Linux-neptune is that intended?

**Comment by bbgoose92** [comment]
Issue completely fixed on updating to the newest stable build.

Thank you
