### ISSUE TITLE
[iwctl does not work with gui install]

### ISSUE THREAD

**Issue by Tourgasm** [holoiso-eol/holoiso#413]
## Your Issue:
```
using the GUI when going into konsole, typing in iwctl gives me an issue that the network configuration is disabled. 
Will not allow me to access my WI-FI. However it sees my WLAN card. 
Using EASY2BOOT as I have multiple ISOs on my only USB drive.
```

## Your device's full specs
```
CPU: intel i5 11400
GPU: Nvidia RTX 3060
WLAN: Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)

```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
HoloISO_Stable-20220711_1550-x86_64
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/A 
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by theVakhovskeIsTaken** [comment]
Just connect thru taskbar icon:
![image](https://user-images.githubusercontent.com/97450182/182023789-3badffd0-a4c4-406c-a249-b000037d9a7c.png)
