### ISSUE TITLE
Shipping a newer Version of GLIBC

### ISSUE THREAD

**Issue by NightHammer1000** [holoiso-eol/holoiso#414]
Installed Version is 2.33-5

Upstream Arch is 2.35-6

Manually updating broke nothing as far as I can see.
Probably should be supplied by the Holoiso Repository.

This ensures compatibility with a lot of programms you can get of github and with Chaotic-AUR

**Comment by nachfuellbar** [comment]
https://github.com/ValveSoftware/Proton/issues/6051

if you update this package - please not up to 2.36 which is the current version in Arch Linux
