### ISSUE TITLE
Refuses to install on any drive

### ISSUE THREAD

**Issue by TheZoroark007** [holoiso-eol/holoiso#42]
I tried for hours now to install this iso (I tried the newest version and the first one) but failed.  No matter if I select a partition on my SSD or on an USB drive, it always leads to the errors shown in the pictures below.  If I ,however, try to install the .iso in a virtual machine, it works without any problem. Does anyone know what I can do to fix this issue ? 
![1](https://user-images.githubusercontent.com/19749084/167249561-1dc03ddc-29d2-470f-a996-f8570b082d91.jpg)
![2](https://user-images.githubusercontent.com/19749084/167249563-5dd84202-8927-4744-872d-6bf40aba323c.jpg)
![3](https://user-images.githubusercontent.com/19749084/167249565-3d4a565b-aecc-4879-b083-dd843f3cb802.jpg)

**Comment by theVakhovskeIsTaken** [comment]
You need to choose the drive itself, not partition.

I don't support dualboot.
