### ISSUE TITLE
Nivida GameStream, moonlight stream

### ISSUE THREAD

**Issue by Albusaidi30** [holoiso-eol/holoiso#420]
Hi

Thanks for this inovation of steam UI , its great and simple GUI.

I'm wondering if nivida geforce can be install in steam os on desktop view, becouse i am planning to run this on a server and stream the steam games through Gamestream to moonlight in thin clints like raspberry pi . 

So is there a way to communcate with moonlight using steam os since its both build with linux . there is also a program called sunshine stream it works like Gamestream of nivida and can contact with moonlight .

Any help its for everyone. 

Thanks

**Comment by joeblack2k** [comment]
No

**Comment by d4rkdpg** [comment]
Use sunshine ?

**Comment by Albusaidi30** [comment]
> Use sunshine ?

I'm planning to try this one 😁

**Comment by Coolykoen** [comment]
More specifically, you will want to use this repo, as the original sunshine dev went inactive a long time ago: https://github.com/LizardByte/Sunshine

If you want Steam deck (or by extension, HoloISO) specific install instructions, you're welcome to join our official Moonlight Gamestream Community discord server: https://discord.com/invite/CGg5JxN

There is already a sunshine specific channel including instructions for on the Deck. :)
