### ISSUE TITLE
Doesn't support Intel AX210 Wifi 6E chip out of the box

### ISSUE THREAD

**Issue by Bitl** [holoiso-eol/holoiso#424]
When trying to install HoloISO to a USB using my main PC (Ryzen 5 2600, GTX 1060, 16GB RAM), it doesn't detect my network adapter in the live CD, which is an Intel AX210 chip.

**Comment by theVakhovskeIsTaken** [comment]
tried booting using kernel version 5.18?

**Comment by NekoMio** [comment]
Same problem in AX201 chip, My PC has i7 12700F and RTX 3080ti 32GB RAM, Using kernel version 5.18.

**Comment by Bitl** [comment]
> tried booting using kernel version 5.18?

Currently using the latest stable version

**Comment by danyi** [comment]
According to the official reply It's a known issue, newer firmware will probably be included in the next release according to Mr. V. https://github.com/theVakhovskeIsTaken/holoiso/issues/434

**Comment by Worldgate** [comment]
So, has this card been supported yet?  It's been what 3 months and was considering it for my little steambox/emubox setup.
