### ISSUE TITLE
No Sound from Steam Deck Speakers

### ISSUE THREAD

**Issue by DocMAX** [holoiso-eol/holoiso#426]
I get no sound from Steam Deck speakers. I compared pactl list status output with original Steam OS and can't find big differences. I have attached both outputs.
[pa_holoiso.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/9257369/pa_holoiso.txt)
[pa_steamos.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/9257370/pa_steamos.txt)

Using latest HoloISO version and 100% Volume of course.

**Comment by DocMAX** [comment]
Ok, fixed that myself. You need to copy the firmware files from original Steam Deck to /lib/firmware/cs35l41-dsp1-spk-prot.wmfw. Don't thank me all at once! Closed!

**Comment by RobSjaras** [comment]
Thank you for posting the solution @DocMAX, I needed this as well for my setup. It's nice having a completely stand alone version of SteamOS on an SD card, only thing missing was the speakers!

Next up I got to figure out on how to port over the functionality for monitor refresh rate change and also adaptive screen brightness

**Comment by DocMAX** [comment]
You are welcome. Glad i found someone interested in this. I'm currently invetigating more and found out that basically all you need for the SteamDeck interface is a modern distribution and the gamescope and mangoapp package. The only thing is that Steam is telling me about updates which i don't know yet how to disable.

**Comment by BatoceraNation** [comment]
> Ok, fixed that myself. You need to copy the firmware files from original Steam Deck to /lib/firmware/cs35l41-dsp1-spk-prot.wmfw. Don't thank me all at once! Closed!

Hi!  I'm rather new with Linux.  I found the file and when I tried to copy it to /lib/firmware location, I received an "access denied".  How do I copy it to that location since it seems to be write protected?

Thanks!
