### ISSUE TITLE
[Report] nvidia optimus laptop doesn't output to hdmi in game mode 

### ISSUE THREAD

**Issue by gettbitgirl** [holoiso-eol/holoiso#427]
My laptop has an AMD apu as well as an nvidia gtx 1660 ti. in desktop mode everything works great and it uses the correct gpu and will recognize both screens. in game mode however, there is no output to the secondary screen and it doesn't even acknowledge there's one connected.

## Your device's full specs
```
CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
GPU: AMD Radeon Vega 8 Graphics and Nvidia Gtx 1660 TI mobile
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220711.1512
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
yes 
```

**Comment by Frostyman758** [comment]
If I had to guess, it's probably because gamescope is auto assigning the AMD card to run and not the Nvidia card. You need to know which is connected to your HDMI port. If it's the Nvidia, you should just be able to change "gamescope-session" with the proper ones.
