### ISSUE TITLE
[Question] BTRFS for /home?

### ISSUE THREAD

**Issue by DocMAX** [holoiso-eol/holoiso#428]
HoloISO formats the home dir in EXT4. Is there any reason why it's not btrfs?
I changed it to btrfs and it seems to work without issues.

**Comment by PIPIPIG233666** [comment]
https://www.reddit.com/r/SteamDeck/comments/ucj5m3/any_idea_why_valve_went_with_ext4_for_home/?utm_medium=android_app&utm_source=share
