### ISSUE TITLE
Installation and Wifi Issues

### ISSUE THREAD

**Issue by TechHutTV** [holoiso-eol/holoiso#429]
Hello everybody, there are a few issues I've been having with the new 3.1 version. Installation process from the desktop is cool and all, but there are issues with wifi cards now that don't support the SteamOS kernel. Even booting into the desktop you still need to use iwctl after selecting the latest kernel. 

More importantly the install script is not finishing some very important downloading steps.I can't get any further.

![Screenshot_20220804_224436](https://user-images.githubusercontent.com/76761586/182968094-9dd80475-7d26-480a-8dfb-b1bc25c1f1a5.png)

**Comment by danyi** [comment]
According to the official reply It's a known issue, newer firmware will probably be included in the next release according to Mr. V. #434
