### ISSUE TITLE
GPD WIN 3: Black screen and no audio

### ISSUE THREAD

**Issue by DocMAX** [holoiso-eol/holoiso#432]
After successfull install of HoloISO on GPD WIN 3 i get a black screen only. Although it seems to boot in background, as i can ping it via network.

**Comment by DocMAX** [comment]
OK, after spending some lifetime hours into that this i came up with solutions.

Black screen fix:
Resolved bei modifiying the /usr/bin/gamescope-session. I Added "export LIBSEAT_BACKEND=logind" and a "sleep 15" after gamescope is loaded. Also i ajusted the gamescope resolution parameters to my resolution.

Sound fix:
Add either snd_hda_intel.dmic_detect=0 or snd_intel_dspcfg.dsp_driver=1 to the kernel command line. Both do work.

PS: Don't thank me all at once!

**Comment by nex86** [comment]
How did you fix the wifi issue when installing holoiso?

**Comment by DocMAX** [comment]
Had no wifi issues. Did i mention it somewhere?

**Comment by nex86** [comment]
> Had no wifi issues. Did i mention it somewhere?

no but I have, 
I'm not able to connect to any of my networks, no wifi adapter showing up.
do you have win 3 with intel AX ???

**Comment by DocMAX** [comment]
Thats strange. Haven't done anything on the wifi. Works out of the box.
ae:00.0 Network controller: Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz (rev 1a)
Are you using latest arch linux?

**Comment by nex86** [comment]
> Are you using latest arch linux?

?????
I'm using this: http://thevakhovske.pw/dl/holoiso-stable
