### ISSUE TITLE
HOLO OS BLACK Screen THE THIS SHOWS UP

### ISSUE THREAD

**Issue by Dolo22** [holoiso-eol/holoiso#436]
![IMG_20220808_014624308](https://user-images.githubusercontent.com/110524566/183378301-4d768445-d02d-49f3-a85b-55bb74e12483.jpg)
I'm using laptop Intel i5-2200 something

**Comment by nex86** [comment]
looks like it failed accessing the boot device.
that must be a pretty old laptop, if its igpu only then its most likely unsupported anyways.

**Comment by Dolo22** [comment]
>damn too bad I was testing if I could bring it alive again
