### ISSUE TITLE
The download link does not work!

### ISSUE THREAD

**Issue by Aerialflame7125** [holoiso-eol/holoiso#438]
When i click on the download link, the page loads, then does nothing! I am downloading a older version because of this.

**Comment by BordersJambo** [comment]
Same behaviour here. Page opens, then immediately closes. Nothing downloaded.

**Comment by ccajas** [comment]
I replaced http: with https: for the URL, and then the download worked.

Did that after seeing this console error message on Chromium with the http link:

`Mixed Content: The site at 'https://github.com/' was loaded over a secure connection, but the file at [githubusercontent.com URL... ] was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked.`

**Comment by nachfuellbar** [comment]
Same behaviour
BUT
I could download when i opened a new tab and copied the link into it
