### ISSUE TITLE
linux-firmware-neptune

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#44]
Doing `sudo pacman -Syu` asks to change linux-firmware to linux-firmware-neptune because it's using linux-neptune kernel. Default answer is Yes and doing that results in "No video output" after SDDM autologins to gamescope session.

The solution would be to blacklist `linux-firmware-neptune` in pacman conf so that it never gets installed.

When I get the time I can write this up if you don't do it in the meantime.

**Comment by theVakhovskeIsTaken** [comment]
pacman -Syyu shouldn't be used now, as steamos-update is replacing it.

I'm gonna add linux, grub and linux-firmware-neptune to ignorepkg then.
