### ISSUE TITLE
Holoiso is stuck on black screen when it boot after the installation

### ISSUE THREAD

**Issue by Bowser04** [holoiso-eol/holoiso#441]
I have install holoiso3.1 on my laptop next to windows 11(secure boot disable).
I have add efi entry with easyEFI (on windows) to boot in Holoiso because he is not bootable in the bios.
After that i am able to see the grub of holoiso but after booting steamos, i can see some lines of text then a black screen appears.

My laptop :
CPU: i7 1165g7
integrated GPU: iris Xe 96EU
GPU: nvidia mx450

thanks in advance

**Comment by iMonZ** [comment]
I have the same problem
i9 11xxxx
GPU: NVIDIA RTX A3000

**Comment by theVakhovskeIsTaken** [comment]
> I have install holoiso3.1 on my laptop next to windows 11(secure boot disable).
> I have add efi entry with easyEFI (on windows) to boot in Holoiso because he is not bootable in the bios.
> After that i am able to see the grub of holoiso but after booting steamos, i can see some lines of text then a black screen appears.
> 
> My laptop :
> CPU: i7 1165g7
> integrated GPU: iris Xe 96EU
> GPU: nvidia mx450
> 
> thanks in advance

since you use laptop, you can forget about your dGPU. Downgrade gamescope and install vulkan-intel lib32-vulkan-intel, thus use iGPU

**Comment by iMonZ** [comment]
> > I have install holoiso3.1 on my laptop next to windows 11(secure boot disable).
> > I have add efi entry with easyEFI (on windows) to boot in Holoiso because he is not bootable in the bios.
> > After that i am able to see the grub of holoiso but after booting steamos, i can see some lines of text then a black screen appears.
> > My laptop :
> > CPU: i7 1165g7
> > integrated GPU: iris Xe 96EU
> > GPU: nvidia mx450
> > thanks in advance
> 
> since you use laptop, you can forget about your dGPU. Downgrade gamescope and install vulkan-intel lib32-vulkan-intel, thus use iGPU

I thought it’s compatible with NVIDIA gpu? Or it isn’t? What’s the problem here?

**Comment by iMonZ** [comment]
Can we keep this issue opened please?
Maybe it's fixable instead of pushing it under the couch right?

**Comment by iMonZ** [comment]
![image](https://user-images.githubusercontent.com/11319871/185758201-e7fb7603-8813-4d3f-926a-89df4e099373.jpg)


I get this while trying booting into recovery mode

**Comment by iMonZ** [comment]
Ok so I booted into recovery and switched off the steamos ui.
In plasma I tried to run it and get this error:
![image](https://user-images.githubusercontent.com/11319871/185758515-988b8356-59eb-49bb-b44d-fcef3bf3d985.jpg)


Any idea? @theVakhovskeIsTaken

**Comment by ghost** [comment]
Same here, using lastest ISO update 3.2 on a desktop PC.

- AMD Ryzen 5 5600X
- AMD Radeon RX 5700XT

**Comment by ranenvious** [comment]
Same issue, on a desktop with an old as hell GPU though. (we figured it was better to give it SOMETHING over integrated graphics)

**Comment by sklaffa** [comment]
Same here. Just tried to install the latest HoloISO 4.0 on an Intel Core i7 3770 using integrated GPU (Intel HD 4000 connected to a LG LED TV via HDMI). Installation OK, at first boot some text writings appear on screen then it goes black and stays that way regardless of what I do (move the mouse, push random keyboard keys, etc.)

**Comment by grantwest** [comment]
@iMonZ How do you disable the steamos ui?

**Comment by sagar9399** [comment]
Same 
Laptop Xiaomi 
11th gen i5 11300H
Integrated gpu
![16844979937576361341238429334538](https://github.com/HoloISO/holoiso/assets/123379494/0a568325-4a5a-4336-8b17-c99b868a707e)

**Comment by sagar9399** [comment]
> Same here. Just tried to install the latest HoloISO 4.0 on an Intel Core i7 3770 using integrated GPU (Intel HD 4000 connected to a LG LED TV via HDMI). Installation OK, at first boot some text writings appear on screen then it goes black and stays that way regardless of what I do (move the mouse, push random keyboard keys, etc.)

Ummm..... You try pressing Ctrl+D

**Comment by SomeDetarame** [comment]
Almost same problem, have HoloISO and Windows 10 on different SSDs, black srceen after 2 lines with some like "linux-neptune booting" black screen and nothing, but i was used SteamOS for a while, was playing 2 games: Crossout and Mordhau (think that 1st game can be the source of problem),
system stoped booting after one restart, OS before restart show crash message about "your GPU drivers" when try to launch game, after that — black screen. that message bug and boot black screen was like two times – after first time i reinstalled system.


CPU — AMD Ryzen 7 3700X
GPU — AMD Radeon RX550
RAM Memory — 8 GB
not using laptop, i have stationary pc

**Comment by morpheus8888** [comment]
Same problema here, iris graphic Inter Series 8
