### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by nex86** [holoiso-eol/holoiso#442]
Is there a discord server around holoiso?
I know theres a Telegram chat, but i don't think thats the best way to discuss or get help.
its good to post updates, but then you can really only discuss whats been posted and theres no general discussion.

If there isn't any, maybe a good idea if someone could start one?
I would do it but I'm too busy with work and my life to administrate a server currently.

**Comment by n8ohu** [comment]
I have a Discord Server that I could add a few HoloISO related channels to, if the author would be willing to permit it.

**Comment by theVakhovskeIsTaken** [comment]
Unplanned.
