### ISSUE TITLE
cannot output video at the same time -- Copying model

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#444]
I'm using STEAMOS3.1

I have an external monitor attached

But the laptop's built-in screen goes black

I want both the internal screen and the external screen to output

So I can show it live

**Comment by danyi** [comment]
I'm using STEAMOS3.1

I have an external monitor attached

But the laptop's built-in screen goes black

I want both the internal screen and the external screen to output

So I can show it live

**Comment by theVakhovskeIsTaken** [comment]
Nope. This won't work at all unless you're using Desktop mode. Gamescope exclusively reserves display input due to how it's built.
