### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by npaladin2000** [holoiso-eol/holoiso#446]
## Your Issue:
```
Problem updating, appears to be packages in two repos
```

## Your device's full specs
```
Aya Neo 2021 Pro
```
## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Trying to
```

Packages (9) holoiso-main-snapshot20220716.2021-1
             holoiso-updateclient-rel.20220718.1953-1
             jupiter-hw-support-20220810.1-1  lib32-libva-2.13.0-1
             lib32-libxinerama-1.1.4-1  linux-neptune-5.13.0.valve22.final2-1
             steam-jupiter-stable-1.0.0.74-2.19  steamdeck-kde-presets-0.11-1
             xorg-xwayland-jupiter-jupiter.20220720.9a2055dd6-3

Total Installed Size:  545.99 MiB
Net Upgrade Size:        6.29 MiB

:: Proceed with installation? [Y/n] y
(9/9) checking keys in keyring                     [######################] 100%
(9/9) checking package integrity                   [######################] 100%
(9/9) loading package files                        [######################] 100%
(9/9) checking for file conflicts                  [######################] 100%
error: failed to commit transaction (conflicting files)
/usr/bin/jupiter-controller-update exists in both 'jupiter-hw-support' and 'holoiso-main'
/usr/bin/steamos-polkit-helpers/steamos-priv-write exists in both 'jupiter-hw-support' and 'holoiso-main'
Errors occurred, no packages were upgraded.

I'm probably going to disable "jupiter-hw-support" to get around this, this is mainly an FYI

**Comment by theVakhovskeIsTaken** [comment]
Force update by adding --overwrite="*" flag.

This will not be needed soon, since jupiter-hw-support package contents and OS snapshot will have unified content

**Comment by npaladin2000** [comment]
That did the trick, thank you
