### ISSUE TITLE
How can I open the Steam Perfomance Overlay from QAM-Battery (Ayaneo Air)

### ISSUE THREAD

**Issue by tiltysola** [holoiso-eol/holoiso#449]
I switched on the display performance overlay in steam button, but when I entered game, I can't see any overlay on the screen.

How could I turn on and get the fps, tdp information?

**Comment by theVakhovskeIsTaken** [comment]
> I switched on the display performance overlay in steam button, but when I entered game, I can't see any overlay on the screen.
> 
> How could I turn on and get the fps, tdp information?

home/H/aya + A

**Comment by tiltysola** [comment]
> 

I have tried A + aya button, but it just opened the Quick Access Menu. I can't enable the performance overlay from QAM.

**Comment by tiltysola** [comment]
Sorry, it's my fault. I forgot to change the basic performace slider.
