### ISSUE TITLE
Issue touchscreen aya neo

### ISSUE THREAD

**Issue by mva94** [holoiso-eol/holoiso#45]
Ayaneo touchscreen doesn't work at all , like drivers aren't installed , you know of a way ?
Thanks for the great work!

**Comment by theVakhovskeIsTaken** [comment]
Can you boot using stock Arch kernel by choosing "Advanced options and SteamOS with linux linux"?

**Comment by mva94** [comment]
And then see if it works? 
Or what ?

**Comment by theVakhovskeIsTaken** [comment]
> works

yes?

**Comment by mva94** [comment]
It doesnt change  anything touchscreen doesn't work

**Comment by mva94** [comment]
@theVakhovskeIsTaken is there a way to install the drivers of the touchscreen?

**Comment by theVakhovskeIsTaken** [comment]
Alright, can you run `sudo pacman -S python-evdev` and run `yay -S aya-neo-fixes-git` to see if this fixes your issues

**Comment by mva94** [comment]
Still no touchscreen

**Comment by forrestlay** [comment]
The touchscreen on my Aya Neo 2021 worked out of box (on stock Arch kernel), so this may be a device-specific or installation-specific issue.

**Comment by mva94** [comment]
Its the aya neo next

**Comment by mva94** [comment]
@theVakhovskeIsTaken hey any news regarding the issue?

**Comment by slaminger** [comment]
I've provided the temp fix for this to several users and the main dev has provided a fix in another issue thread. I just reached out on telegram.

**Comment by DaMushroomCloud** [comment]
> I've provided the temp fix for this to several users and the main dev has provided a fix in another issue thread. I just reached out on telegram.

What was the temp fix?
