### ISSUE TITLE
Perfomance Overlay Display an error

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#450]
![image](https://user-images.githubusercontent.com/1498746/184788531-dfeaf3bc-43a7-4eba-acc1-df9a339df299.png)
My CPU is AMD 6800U
My GPU frequency and power consumption do not display properly

**Comment by bowes332frank** [comment]
AMD 5600G HAVE SAME ISSUE!
You may also unable to make FSR prefix from OFF to ON.

**Comment by danyi** [comment]
> AMD 5600G HAVE SAME ISSUE! You may also unable to make FSR prefix from OFF to ON.

https://github.com/theVakhovskeIsTaken/holoiso/issues/445
