### ISSUE TITLE
Can't access any SSD's

### ISSUE THREAD

**Issue by Slo2018** [holoiso-eol/holoiso#451]
I can't mount SSD's (all NTFS).

**Comment by jrcharney** [comment]
If you are trying to mount an NTFS, you need to install the packages `fuse` and `ntfs-3g`.

```
sudo pacman -S fuse ntfs-3g
```

If you want to automatically mount or add read/write permissions to the disk, there's something that needs to be done with the `/etc/fstab` file. I forget what, but I'm currently trying to remember, especially with this one disk I set up recently on one of my machines for file storage.
