### ISSUE TITLE
Latest 3.1 installer is installing Nvidia drivers on complete AMD system

### ISSUE THREAD

**Issue by nanonerd-io** [holoiso-eol/holoiso#453]
I have an AMD system (Ryzen 5600g w/ RX 6600 XT) . No Nvidia card installed whatsoever. When I start the installer, it goes through the normal install process but never prompts me to choose my GPU (whereas on my other system with an Nvidia 3070 I do get asked to choose my GPU). I can see during the installation process that it is installing the most current Nvidia 5.15 drivers. Is there anyone to force the installation of AMDGPU/mesa drivers?

**Comment by theVakhovskeIsTaken** [comment]
Yeah, Steam's depencency "vulkan-driver" some takes "nvidia-utils" even though its not needed and unused and vulkan-radeon still gets installed.

Can't do much anything as far as i've tried, but i'm aware of that
