### ISSUE TITLE
Hack for bonded network?

### ISSUE THREAD

**Issue by DocMAX** [holoiso-eol/holoiso#455]
I get this error if i try to user other than eth0 or wlan0 network. In my case a binded network. Is there any hack that could fix this?

![grafik](https://user-images.githubusercontent.com/5351323/185388331-8ec10f5a-88b1-49c3-b373-8bd86e267bc4.png)

Also:
https://steamcommunity.com/app/1675200/discussions/1/3448087385670849828/
https://github.com/ValveSoftware/steam-for-linux/issues/8739

**Comment by theVakhovskeIsTaken** [comment]
_what_

**Comment by DocMAX** [comment]
Sorry, accidently clicked on save.

**Comment by theVakhovskeIsTaken** [comment]
> I get this error if i try to user other than eth0 or wlan0 network. In my case a binded network. Is there any hack that could fix this?
> 
> ![grafik](https://user-images.githubusercontent.com/5351323/185388331-8ec10f5a-88b1-49c3-b373-8bd86e267bc4.png)
> 
> Also:
> https://steamcommunity.com/app/1675200/discussions/1/3448087385670849828/
> https://github.com/ValveSoftware/steam-for-linux/issues/8739
> 

Huh? my wlp1s0 interface shows perfectly fine, probably an issue on Valve's side

**Comment by DocMAX** [comment]
you need to create a bonded network. eth0 + wlan0 (wlp1s0) "merged" into bond0. this way you can swap cable seamlessly without loosing ip. anyway, it's a very special use-case and probably nobody will care... :-(
has to look like this:
```
docmax@steamdeck: ~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc noqueue master bond0 state UP group default qlen 1000
    link/ether 90:e8:68:9f:b2:41 brd ff:ff:ff:ff:ff:ff
    altname wlo1
    altname wlp3s0
3: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether f8:e4:3b:1d:9f:ba brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.112/24 brd 192.168.1.255 scope global dynamic noprefixroute bond0
       valid_lft 39293sec preferred_lft 39293sec
    inet6 fe80::45fb:22b3:976b:6166/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
6: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
    link/ether f8:e4:3b:1d:9f:ba brd ff:ff:ff:ff:ff:ff
    altname enp4s0f3u1u1
```

**Comment by theVakhovskeIsTaken** [comment]
> you need to create a bonded network. eth0 + wlan0 (wlp1s0) "merged" into bond0. this way you can swap cable seamlessly without loosing ip. anyway, it's a very special use-case and probably nobody will care... :-(
> has to look like this:
> ```
> docmax@steamdeck: ~ $ ip a
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: wlan0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc noqueue master bond0 state UP group default qlen 1000
>     link/ether 90:e8:68:9f:b2:41 brd ff:ff:ff:ff:ff:ff
>     altname wlo1
>     altname wlp3s0
> 3: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
>     link/ether f8:e4:3b:1d:9f:ba brd ff:ff:ff:ff:ff:ff
>     inet 192.168.1.112/24 brd 192.168.1.255 scope global dynamic noprefixroute bond0
>        valid_lft 39293sec preferred_lft 39293sec
>     inet6 fe80::45fb:22b3:976b:6166/64 scope link noprefixroute
>        valid_lft forever preferred_lft forever
> 6: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
>     link/ether f8:e4:3b:1d:9f:ba brd ff:ff:ff:ff:ff:ff
>     altname enp4s0f3u1u1
> ```

"Yeah it's probably reproducible on actual Steam Deck, so report it in every single sd forum you got" /s


I'd suggest you to wait for Steam runtime maintainers answer under your issue, as thing looks indeed interesting
