### ISSUE TITLE
Update Issue with `holoiso-main` `snapshot20220818.1032-1`

### ISSUE THREAD

**Issue by irfanhakim-as** [holoiso-eol/holoiso#456]
As stated in the title. Upon updating packages in the Discover store, attempting to update `holoiso-main` from `snapshot20220817.1947-1` to `snapshot20220818.1032-1` resulted to an Update Issue.

Specifically:
```
File conflicts found:
holoiso-main <-> jupiter-hw-support (/usr/bin/jupiter-biosupdate): conflicting files
Please report this issue to the packagers of your distribution
```

All previous updates worked perfectly fine, so this is my first time encountering an update issue when updating packages in the Discover store on holoiso. Maybe something for the maintainers to look at?

**Comment by theVakhovskeIsTaken** [comment]
You don't use Discover for updates.

steamos-update check && steamos-update now

**Comment by irfanhakim-as** [comment]
> You don't use Discover for updates.
> 
> steamos-update check && steamos-update now

This solved my issue perfectly. I remember trying to find the proper way of updating holoiso but found only few and conflicting answers on reddit and so on. It would be great if this one-liner was added to the repo's README as the update method/process. Thanks for ur help!

**Comment by S1ngl3-x** [comment]
> > You don't use Discover for updates.
> > steamos-update check && steamos-update now
> 
> This solved my issue perfectly. I remember trying to find the proper way of updating holoiso but found only few and conflicting answers on reddit and so on. It would be great if this one-liner was added to the repo's README as the update method/process. Thanks for ur help!

Perhaps even with some sort of "flatpak update" command to make it one command for whole system update.
