### ISSUE TITLE
File conflics found

### ISSUE THREAD

**Issue by piranime** [holoiso-eol/holoiso#457]
Holoiso-main <-> jupiter-hw-support /usr/bin/jupiter-biosupdate conflicting files

Please report this issue to the packagers of your distribution

Need any files? Run commands let me know
![IMG_20220818_132158](https://user-images.githubusercontent.com/111530991/185466784-c8a66f7d-306b-49c2-a8c9-297d7588f302.jpg)

**Comment by JohanLeirnes** [comment]
Same here

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/456#issuecomment-1219753202
