### ISSUE TITLE
some installation issue?

### ISSUE THREAD

**Issue by Jmkwang** [holoiso-eol/holoiso#46]
When i installing holoiso to my aya neo next(AMD 4800U), with a SN770, 
first it show i need to update /etc/fstab
and unable to open the disk(WD sn770) device or resource busy  
and log keep shows that /mnt is not a mountpoint
I dont get it and what can i do to? Thx!

**Comment by theVakhovskeIsTaken** [comment]
Can you try to run sfdisk --delete /dev/nvme0n1 and wipefs -a /dev/nvme0n1 first?

**Comment by theVakhovskeIsTaken** [comment]
I suppose author has resolved the issue.

**Comment by Jmkwang** [comment]
! Thanks alot and i did have resolved the issue and succesfully get in the steamos, thank u very much!!

**Comment by Jmkwang** [comment]
and now i am having issue getting steam online lol, perhaps due to my network.
