### ISSUE TITLE
holoiso-main snapshot20220819.0846-1 file conflicts

### ISSUE THREAD

**Issue by flightsoftware21** [holoiso-eol/holoiso#460]
Update issue:

File conflicts found:

holoiso-main <-> jupiter-hw-support (/usr/bin/jupiter-biosupdate,
holoiso-main <-> jupiter-hw-support (/usr/bin/steamos-polkit-helpers/steamos-priv-write): conflicting files

[errormsg](https://user-images.githubusercontent.com/77760565/185710718-6f1e4cd1-8963-4a69-893c-179a6939e21f.png)

Occurs when attempting update to holoiso-main snapshot20220819.0846-1.

**Comment by theVakhovskeIsTaken** [comment]
> Update issue:
> 
> File conflicts found:
> 
> holoiso-main <-> jupiter-hw-support (/usr/bin/jupiter-biosupdate,
> holoiso-main <-> jupiter-hw-support (/usr/bin/steamos-polkit-helpers/steamos-priv-write): conflicting files
> 
> [errormsg](https://user-images.githubusercontent.com/77760565/185710718-6f1e4cd1-8963-4a69-893c-179a6939e21f.png)
> 
> Occurs when attempting update to holoiso-main snapshot20220819.0846-1.

You **don't** use discover to update.

Just click "check for updates" in Deck UI

**Comment by godtoall82** [comment]
I am having the same issue, but also get an update error when trying to update in the deck UI.

**Comment by agentwolf88** [comment]
Same
