### ISSUE TITLE
Stuck in a infinite boot loop

### ISSUE THREAD

**Issue by NutmegBurrito** [holoiso-eol/holoiso#462]
![B58D7FDB-7319-430B-9067-4C7EA8BADF66](https://user-images.githubusercontent.com/111614158/185716453-23dbedec-34f3-4784-9182-d4169bef16cc.jpeg)
![49C5F8AD-DC89-4754-AE80-840BF4D978B7](https://user-images.githubusercontent.com/111614158/185716458-8cd28831-fcc4-4b94-9d58-6fd4b45eaf48.jpeg)
## Your Issue:
Stuck in an infinite boot loop on HoloISO.
*type your problem here*
After updating steam-os through game mode and rebooting, I have been stuck in an infinite loop of:

Loading Linux linux-neptune  …
Loading initial ramdisk …

It keeps trying to boot but will not work.

## Your device's full specs

CPU: Intel i7 11th gen
GPU: NVIDIA GeForce 2070 super

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
5.13.0-valve23-1-neptune-02219-gf0b4ecc8cab6

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
Yes

## Have you updated your installation recently?
Yes

**Comment by NutmegBurrito** [comment]
UPDATE: I was able to go in recovery mode and ‘holoiso-disable-sessions’ and boot straight into desktop mode. Game mode is the only thing that does not work.

**Comment by theVakhovskeIsTaken** [comment]
> UPDATE: I was able to go in recovery mode and ‘holoiso-disable-sessions’ and boot straight into desktop mode. Game mode is the only thing that does not work. 

Try gamescope-session in desktop terminal with steam closed, and see if it starts

**Comment by NutmegBurrito** [comment]
![image](https://user-images.githubusercontent.com/111614158/185771701-39a27ed8-6943-45ef-a618-83763b147fde.png)
I've attached what the terminal says when trying gamescope-session with steam closed. Gaming mode did not appear but I did hear the start up sound.

**Comment by jrcharney** [comment]
I've seen similar issues involving `libseat` with installing other desktop environments such as `sway` (which is like the Wayland version of `i3`).  See if `polkit` is installed.

```
sudo pacman -S polkit
```

**Comment by NutmegBurrito** [comment]
Thank you for the response! Once I downloaded polkit, that seemed to do the trick!
