### ISSUE TITLE
[Report] Display Scaling Not Saving

### ISSUE THREAD

**Issue by tmcd35** [holoiso-eol/holoiso#464]
## Your Issue:
```
I am running a 4K resolution.  When I go into Display Settings and manually editing UI scaling is does not save my preferences between settings.  Once selected it always loads one notch up from a full 4K resolution.  Not sure if this is an underlying SteamOS issue or an HoloISO issue.
```

## Your device's full specs
```
CPU: AMD Ryzen 5 5600X
GPU: AMD Radeon RX6600XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220819.0846
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/A
```

## Your installation type:
```
decksperience
```

## Have you updated your installation recently?
```
20/08/2022 - this problem has existed since Auto UI Scaling was introduced to the UI settings
```

**Comment by theVakhovskeIsTaken** [comment]
Report to @valvesoftware/steam-for-linux
