### ISSUE TITLE
[Report] Unable to start Gamescope mode with NVIDIA GPU

### ISSUE THREAD

**Issue by iMonZ** [holoiso-eol/holoiso#467]
## Your Issue:
```
*type your problem here*
```

Unable to start gamescope session with NVIDIA GPU.
Maybe I have an too old gamescope version?

![F0BFDF02-18BF-4AFD-B16F-DF1116391789](https://user-images.githubusercontent.com/11319871/185759102-181a5867-c58b-41a7-9ba2-f902b9ba62ad.jpeg)

## Your device's full specs
```
CPU: Apple A15 Bionic
GPU: Apple Lighting 2nd gen
```
Lenovo P15 g2 i9-11XXX
NVIDIA RTX A3000
64GB RAM

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
How? Pacman:
![image](https://user-images.githubusercontent.com/11319871/185759149-0bde69f6-0b7e-4816-b67c-8dce4a090c1b.jpg)

```

**Comment by theVakhovskeIsTaken** [comment]
Close Steam and run this again

**Comment by iMonZ** [comment]
> Close Steam and run this again

Okay nice! So SteamOS UI starts in a window.
But when I Boot into steamos directly without holoiso-disable I just get a black screen

**Comment by theVakhovskeIsTaken** [comment]
> > Close Steam and run this again
> 
> Okay nice! So SteamOS UI starts in a window.
> But when I Boot into steamos directly without holoiso-disable I just get a black screen

KDE environment knows how to select primary GPU, gamescope doesn't. Plus, he probably ONLY has dGPU on his machine. Your case is PRIME/Optimus/GPU switching related

**Comment by theVakhovskeIsTaken** [comment]
> > Close Steam and run this again
> 
> Okay nice! So SteamOS UI starts in a window.
> But when I Boot into steamos directly without holoiso-disable I just get a black screen

Do you have iGPU on your system?

Does BIOS allow you to ENTIRELY disable your iGPU?

**Comment by iMonZ** [comment]
> > > Close Steam and run this again
> > 
> > 
> > Okay nice! So SteamOS UI starts in a window.
> > But when I Boot into steamos directly without holoiso-disable I just get a black screen
> 
> Do you have iGPU on your system?
> 
> Does BIOS allow you to ENTIRELY disable your iGPU?

I have an iGPU. Sadly I can't disable it. Is there another way?

**Comment by iMonZ** [comment]
Okay thanks! It worked.

The only problem is that the scale is very bad.
Is there a way to change the scale?
And it's very laggy

**Comment by iMonZ** [comment]
And also how do I get HoloISO updates? How can I install them?

**Comment by theVakhovskeIsTaken** [comment]
> Okay thanks! It worked.
> 
> The only problem is that the scale is very bad.
> Is there a way to change the scale?
> And it's very laggy

Yeah, it's just NVIDIA and Valve problem at same time. Let's just settle till they fix Vulkan related issues

**Comment by theVakhovskeIsTaken** [comment]
> And also how do I get HoloISO updates? How can I install them?

If you got DeckUI to boot fine, just tick "Check for Updates" in settings.

**Comment by iMonZ** [comment]
> > And also how do I get HoloISO updates? How can I install them?
> 
> If you got DeckUI to boot fine, just tick "Check for Updates" in settings.

Great to hear!
If I change it from beta to preview will I still be able to get the HoloISO update?
Just to be sure I don’t encounter a lock out

**Comment by iMonZ** [comment]
> > Okay thanks! It worked.
> > The only problem is that the scale is very bad.
> > Is there a way to change the scale?
> > And it's very laggy
> 
> Yeah, it's just NVIDIA and Valve problem at same time. Let's just settle till they fix Vulkan related issues

All right good to know.
Thanks for your time and help. And for the HoloISO project :)
