### ISSUE TITLE
Sleep mode of SteamOS mode 

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#47]
If you press the power button in SteamOs mode, it does not go into slim mode.
However, if you press the 'Power' icon in the Steam UI and select 'Sleep', it goes into sleep mode.

machine : aya neo fe 4800U 

Thank you for your efforts!!!

**Comment by JongAnYoo** [comment]
In desktop mode, you can use the sleep function through the power button.

**Comment by theVakhovskeIsTaken** [comment]
Huh? Can you unpack this and run `sudo python powerbutton.py` in terminal and send me the output?
[powerbutton.zip](https://github.com/theVakhovskeIsTaken/holoiso/files/8646611/powerbutton.zip)

I suppose powerbutton handler requires some tuning...

**Comment by JongAnYoo** [comment]
Output Here!

[yjaking@SteamOSPC Downloads]$ sudo python powerbutton.py
/dev/input/event15 Microsoft X-Box 360 pad 0
/dev/input/event17 B.O.W Mouse e0:d4:64:da:0c:9f
/dev/input/event16 B.O.W Keyboard e0:d4:64:da:0c:9f
/dev/input/event8 Logitech USB Optical Mouse usb-0000:03:00.4-1.1/input0
/dev/input/event14 HD-Audio Generic Front Headphone ALSA
/dev/input/event13 HD-Audio Generic Mic ALSA
/dev/input/event12 HD-Audio Generic HDMI/DP,pcm=9 ALSA
/dev/input/event11 HD-Audio Generic HDMI/DP,pcm=8 ALSA
/dev/input/event10 HD-Audio Generic HDMI/DP,pcm=7 ALSA
/dev/input/event9 HD-Audio Generic HDMI/DP,pcm=3 ALSA
/dev/input/event7 Microsoft X-Box 360 pad usb-0000:03:00.3-4/input0
/dev/input/event6 PC Speaker isa0061/input0
/dev/input/event5 Video Bus LNXVIDEO/video/input0
/dev/input/event4 Goodix Capacitive TouchScreen input/ts
/dev/input/event3 AT Translated Set 2 keyboard isa0060/serio0/input0
/dev/input/event2 Power Button LNXPWRBN/button/input0
/dev/input/event1 Power Button PNP0C0C/button/input0
/dev/input/event0 Lid Switch PNP0C0D/button/input0

**Comment by theVakhovskeIsTaken** [comment]
> Output Here!
> 
> [yjaking@SteamOSPC Downloads]$ sudo python powerbutton.py /dev/input/event15 Microsoft X-Box 360 pad 0 /dev/input/event17 B.O.W Mouse e0:d4:64:da:0c:9f /dev/input/event16 B.O.W Keyboard e0:d4:64:da:0c:9f /dev/input/event8 Logitech USB Optical Mouse usb-0000:03:00.4-1.1/input0 /dev/input/event14 HD-Audio Generic Front Headphone ALSA /dev/input/event13 HD-Audio Generic Mic ALSA /dev/input/event12 HD-Audio Generic HDMI/DP,pcm=9 ALSA /dev/input/event11 HD-Audio Generic HDMI/DP,pcm=8 ALSA /dev/input/event10 HD-Audio Generic HDMI/DP,pcm=7 ALSA /dev/input/event9 HD-Audio Generic HDMI/DP,pcm=3 ALSA /dev/input/event7 Microsoft X-Box 360 pad usb-0000:03:00.3-4/input0 /dev/input/event6 PC Speaker isa0061/input0 /dev/input/event5 Video Bus LNXVIDEO/video/input0 /dev/input/event4 Goodix Capacitive TouchScreen input/ts /dev/input/event3 AT Translated Set 2 keyboard isa0060/serio0/input0 /dev/input/event2 Power Button LNXPWRBN/button/input0 /dev/input/event1 Power Button PNP0C0C/button/input0 /dev/input/event0 Lid Switch PNP0C0D/button/input0

So, let's try tinkering with it then!
Can you run `sudo sed -i 's/isa0060\/serio0\/input0/PNP0C0C\/button\/input0/g' /usr/lib/hwsupport/power-button-handler.py` and run SteamOS session, then try to use power button?

**Comment by JongAnYoo** [comment]
First of all, thank you for your quick response.
You are a wonderful person.

But the results are not good.
Still in the same SteamOS session, pressing the power button does not go into sleep mode.
This is also a common symptom of people using AYA Neo around them.

**Comment by JongAnYoo** [comment]
source code is here!



#!/usr/bin/python

import evdev
import threading
import os

powerbuttondev = None

devices = [evdev.InputDevice(path) for path in evdev.list_devices()]
for device in devices:
	if device.phys == "PNP0C0C/button/input0":
		powerbuttondev = device;
	else:
		device.close()

longpresstimer = None

def longpress():
	os.system( "~/.steam/root/ubuntu12_32/steam -ifrunning steam://longpowerpress" )
	global longpresstimer
	longpresstimer = None

if powerbuttondev != None:
	for event in powerbuttondev.read_loop():
		if event.type == evdev.ecodes.EV_KEY and event.code == 116: # KEY_POWER
			if event.value == 1:
				longpresstimer = threading.Timer( 1.0, longpress )
				longpresstimer.start()
			elif event.value == 0:
				if longpresstimer != None:
					os.system( "~/.steam/root/ubuntu12_32/steam -ifrunning steam://shortpowerpress" )
					longpresstimer.cancel()
					longpresstimer = None

	powerbuttondev.close()
	exit()

print ( "power-button-handler.py: Can't find device for power button!" )

**Comment by JongAnYoo** [comment]
I modified the source code arbitrarily

Even after changing to PNP0C0C --> LNXPWRBN and testing, the slim mode did not work.

**Comment by JongAnYoo** [comment]
Investigating the event with hexdump, the event that responds when the power button is pressed seems to be 'event2'.

**Comment by FayeSpica** [comment]
after `sudo sed -i 's/isa0060\/serio0\/input0/PNP0C0C\/button\/input0/g' /usr/lib/hwsupport/power-button-handler.py`
aya neo shutdown immediately

**Comment by FayeSpica** [comment]
I clear all codes in power-button-handler.py, it's same

**Comment by NightHammer1000** [comment]
Can you try this?
https://github.com/theVakhovskeIsTaken/holoiso/issues/247#issuecomment-1148632464

This worked for the Steam Deck. I am curious if it works on other devices as well.
If yes it means the Gaming Mode follows standard ACPI Events.

**Comment by gfl699468** [comment]
I have a oxp mini amd, and find a solution for my device, you could try it:
Step 1.
> According #247 
> Edit:
> /etc/systemd/logind.conf
> Change:
> #HandlePowerKey=poweroff
> to
> HandlePowerKey=ignore
> now, press the power button will not shutdown the device immediately, device only poweroff with long press

Step 2.
> Run `sudo evtest`, select an input and press power button, by doing this on all input, find which eventX fire a event when you press button.
> Get phys of the device from `cat /proc/bus/input/devices` and update the /usr/lib/hwsupport/power-button-handler.py accordingly(or just create the InputDevice with the path '/dev/input/eventX')

Step 2.5.(Maybe only for oxp mini amd)
> For oxp mini amd, press power button will not fire a event, it will fire a press event and a release event when you release the button, so long press will never be triggered. An solution is to update /usr/lib/hwsupport/power-button-handler.py script, change logic from detect long press to detect double press

Step 3.
> Run `~/.steam/root/ubuntu12_32/steam -ifrunning steam://longpowerpress` in ssh brings up the power menu with no problem, but sudo will cause a coredump.
> So update /usr/bin/gamescope-session @ line 188,
> change
> > (while true; do
> >     /usr/lib/hwsupport/power-button-handler.py
> > done) &

> to

> > (while true; do
> >     sudo -E /usr/lib/hwsupport/power-button-handler.py
> > done) &

> should fix the problem
