### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by yzzyvd** [holoiso-eol/holoiso#471]
## Your Issue:
After being able to login into recovery mode with Plasma, the Updates for Jupiter have a Conflict 
```
*type your problem here*
```
Hi, I ran into some issues after rebooting my Laptop so I can boot into SteamOS, but Jupiter BIOS was failing to update. I did reinstall HoloISO with GPR? Idk the other thing of MBR with DD Mode in Rufus. Same fail as before. I ran SteamOS then in Recovery Mode with Plasma successfully. Then I logged into Steam, and wanted to update it from Plasma. But then this window popped up and I don’t know what to do.
## Your device's full specs
```
CPU: Intel i7 4710HQ
GPU: NVIDIA GTX 850M
```

## Your OS version (`SteamOS(HoloISO) 3.2 | 
![Uploading image.jpg…]()
`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
![image](https://user-images.githubusercontent.com/79205395/185948316-b73170ab-c81e-4c82-8cc7-e9a8b6d4f97a.jpg)

```

**Comment by theVakhovskeIsTaken** [comment]
your hw is unsupported, make sure you read readme correctly

**Comment by yzzyvd** [comment]
sorry, i hope i didnt waste your time in any way! have a good day!
