### ISSUE TITLE
how to use gyro for ayaneo air

### ISSUE THREAD

**Issue by chnlzh2** [holoiso-eol/holoiso#474]
## Your Issue:
```
*type your problem here*
```

## Your device's full specs
```
CPU: Apple A15 Bionic
GPU: Apple Lighting 2nd gen
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by Droidware** [comment]
How is anyone supposed to help when you don't provide logs from when you loaded "gamescope-session" in the terminal 

And I don't think the Aya Neo Air even has gyro support 

And for the specs they definitely don't use Apple's bionic chipset.

Try using a brain next time you make issue on a git repo.

**Comment by Randysteele992** [comment]
> How is anyone supposed to help when you don't provide logs from when you loaded "gamescope-session" in the terminal
> 
> And I don't think the Aya Neo Air even has gyro support
> 
> And for the specs they definitely don't use Apple's bionic chipset.
> 
> Try using a brain next time you make issue on a git repo.

The Aya Neo Air definitely has gyro support.

**Comment by alphonsez1** [comment]
You can first try to install [HandyGCCS](https://github.com/ShadowBlip/HandyGCCS) and press the `LC+RC` at the same time to enable Gyro (the two `...` buttons next to LB and RB, see picture below). It triggers one vibration when enabling the gyro.

![image](https://user-images.githubusercontent.com/71942669/189166531-1bfa08a6-99b5-409e-82a8-ff817b967dbd.png)

The Gyro support works by converting Gyro readings to R-stick actions. If you want to disable Gyro, press LC+RC again.

I find that when Gyro is enabled, the input latency is high and there is always some R stick action even I'm not moving if I use R-stick when Gyro is on. If it also happens to you, you can try my branch that contains the fixes: https://github.com/alphonsez1/HandyGCCS/tree/fix/gyro-latency
