### ISSUE TITLE
Aya neo 2021 pro support

### ISSUE THREAD

**Issue by MagZu** [holoiso-eol/holoiso#475]
Hello,

I got an Aya neo 2021 pro and figured i would give some info that might be useful
I see there is some "if statement" in the grub config along with device list in variables like for Aya Neo Air.

Played around with the settings for Air on my Aya Neo 2021 pro and can confirm those settings work for Aya Neo 2021 pro from looking at the grub_cmdline part it looks like what i used to set.

So the devicename for Aya neo pro 2021 is "AYANEO 2021 PRO" seems like a simple copy and paste then this project supports this device :D 

PS. i werent sure to post this as an issue or if i could just do a pull request, but i will leave this for you guys!
Nice project so far, been following for a long time in the background ;) 

Edit:
what was tested and working:
builtin game controls
external keyboard & mouse via usb-c hub
Wifi
bluetooth
screen rotation
volume buttons inside of steam deck experience
screen brightness controls

**Comment by Painbou** [comment]
I can confirm, I am using it with an Aya Neo Pro 2021. Everything works, however I cannot update the OS now. I get an error on the 3.3 whenever I want to update and I do not know why. I did install the fixes from ShadowBlip: https://github.com/ShadowBlip to be able to configure TDP, put it in sleep mode and have full controller support.

Thank you.
