### ISSUE TITLE
Internet speed seems to be limited

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#476]
I seem to have a strange problem
my computer is 6800u
My wifi is AX210
My router also supports wifi6
But the download speed is very slow when connected to wifi
No more than 10MB/S
I tested the internet speed on the website and the download is only 100m
After restarting the computer, I entered windos 11 and tested the speed on the same webpage
Downloads reached 500m

So I went back to steamos and connected the RJ45 LAN
mine but i found
I tested the internet speed on the website and the download is still only 100m
I checked the interface information and found that the protocol speed is only 100m duplex
But I check on the router that it is 1000m duplex
Even if I manually change to 1000m duplex in steamos
But it's still only 10MB/S
Seems to be limited somewhere
I have no idea how to solve this problem

**Comment by jrcharney** [comment]
More than likely it's your local internet service provider than the hardware.

An AMD Ryzen 7 6800U is a pretty nice gaming laptop processor. In fact, [ETA Prime did a video on that about a few months ago](https://www.youtube.com/watch?v=-6D6NT5rGyk).  I'm rolling with a Ryzen 9 5950X on my home computer and its pretty sweet.  So it's not you.

Out of curiosity, who is your ISP?

**Comment by danyi** [comment]
No, I use China Telecom in China and the broadband is 1000M

I have both SteamOS and Windos11 installed on this computer

Testing bandwidth on the same page will result in significantly slower than Windos11 under SteamOS

**Comment by theVakhovskeIsTaken** [comment]
Can't reproduce issue on two of RTL8111Hs as ethernet devices, RTL8822CE and RTL8852AE and Intel 5123 as Wi-Fi devices.

A problem, that's probably related to the firmware blobs. Does the issue persist on other distributions?

**Comment by danyi** [comment]
On the new version, my RJ45 is manually changed to 1G, which is normal, but the wifi problem is still the same. My hardware is AX210

**Comment by danyi** [comment]
This is normal on the other Linux in question

**Comment by danyi** [comment]
I tried update 3.2 and wifi still crashes on the installation screen, AX210

**Comment by VGON7** [comment]
same problem！
