### ISSUE TITLE
esta consumindo muito da minha memoria ram instalei em pc rizen 5600g com 16gb memoria mais quando estou jogando nao para de subir o uso de memoria por favor me ajudem a resolver se nas configuracoes consigo ou tenho que fazer dowload de uma nova imagem

### ISSUE THREAD

**Issue by kevinfox33** [holoiso-eol/holoiso#477]
## Your Issue:
```
*type your problem here*
```

## Your device's full specs
```
CPU: Apple A15 Bionic
GPU: Apple Lighting 2nd gen
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by jrcharney** [comment]
Oof. Esse é um título longo. Eu posso não saber português (felizmente o Google Translate fará tudo o que eu escrever nesta resposta parecer certo), mas acho que provavelmente posso ajudar.

Preciso que você faça algumas correções em seu relatório de problemas e substitua parte do texto do espaço reservado que foi colocado lá. Se você puder usar `lspci -nnk` e `lsusb`, isso também seria útil.

**Comment by gruberdev** [comment]
> Oof. Esse é um título longo. Eu posso não saber português (felizmente o Google Translate fará tudo o que eu escrever nesta resposta parecer certo), mas acho que provavelmente posso ajudar.
> 
> Preciso que você faça algumas correções em seu relatório de problemas e substitua parte do texto do espaço reservado que foi colocado lá. Se você puder usar `lspci -nnk` e `lsusb`, isso também seria útil.

I am a native Brazilian-Portuguese speaker, and maybe I can chime in and help with the communication breakthrough. 

In the title, he mentions his RAM usage keeps going up and asks whether there's something he can do to reduce the memory usage or improve performance. So, here are a few questions I'd like to ask him:

- Did you change any of the default configurations regarding swap? 
- Which hardware are you using to run HoloISO? Have you run @jrcharney commands? If so, their output is essential for debugging this issue.

RAM usage increases as time goes along when there's no swap partition mounted; that is expected. How fast it increases is the real question. To understand if there's something wrong with your setup or not, if you could provide details on how fast the memory usage increases and list the applications involved, it'd be helpful as well.

---

Tradução:
Eu sou Brasileiro, então posso te ajudar @kevinfox33. Eu compreendi o que o colega @jrcharney  falou e tem duas perguntas essenciais para a gente conseguir te ajudar:

- Você mudou alguma das configurações relacionadas a sua partição de swap? Como está organizado as partições onde voce instalou o HoloISO?
- Você chegou a rodar os comandos que o @jrcharney sugeriu? `lspci -nnk` e `lsusb`. Eles são importantes para que a gente possa identificar seu hardware, e dizer o que pode ter de errado com ele.

Importante notar que é esperado que o uso da memória RAM, principalmente quando não se tem swap configurado, suba com o uso. Isso deve ser ainda mais notável em jogos. Então a real pergunta é se a taxa em que o consumo de memória está crescendo no seu PC em um ritmo anômalo, seria interessante se você acha que é o caso, providenciar dados sobre o quão rápido a memória está sendo consumindo e que programas estão abertos. O que acha @kevinfox33?

**Comment by jrcharney** [comment]
> I am a native Brazilian-Portuguese speaker, and maybe I can chime in and help with the communication breakthrough.

Thanks for helping him, as well as any other Portuguese speakers, with this issue.  I know some Spanish, but that's a completely different language.

Honestly, I don't think I've ever really needed to set up a swap partition typically because often I set up my computer with plenty of RAM. They say 8 GB is the minimum that you need, but I find 16 GB to be better. I snagged a pretty good deal on Amazon with this mini PC that I'm using as a "Steam box" that has 32GB of SODIMM DDR4 DRAM on it, so I haven't really thought much about a swap partition.

Are there any benefits to creating a swap partition, and should I consider partitioning my `holo-home` partition to be slightly smaller to add a swap partition?
