### ISSUE TITLE
Aya neo next no touch screen or wifi. 

### ISSUE THREAD

**Issue by slaminger** [holoiso-eol/holoiso#48]
I know what's wrong. WiFi it needs to modprobe the mediatek wifi 6/bt module and the goodix drivers are messed up on Linux. I just got it working on Ubuntu this evening. Will test on steam os here next and share my findings. I'd like to help this along.

**Comment by theVakhovskeIsTaken** [comment]
RZ608 should be fixed as https://github.com/theVakhovskeIsTaken/valve_linux_neptune/commit/a996fe00180a1ca975a23f92be7a5d503d7b2a3b
