### ISSUE TITLE
holoISO / steamOS not updating

### ISSUE THREAD

**Issue by uberdisko** [holoiso-eol/holoiso#481]
im just wondering if this is normal or not but when i get updates, a couple items cannot be updated like holoiso-main and steam-jupiter-stable
![Screenshot_20220826_231342](https://user-images.githubusercontent.com/51147367/187038993-a84c69f6-b5fa-40b3-91ba-c4e5d8b10a66.png)

**Comment by jrcharney** [comment]
Have you tried using `sudo pacman -Syyu` in a terminal console like Konsole?

**Comment by uberdisko** [comment]
> 
![Screenshot_20220827_143219](https://user-images.githubusercontent.com/51147367/187043663-30406ff0-f2d8-4c24-99ed-7c91def5dcda.png)


i just ran the command and here were the results

**Comment by uberdisko** [comment]
is this not right? should these packages be updating?, i dont mind reinstalling im just trying to make sure everything is running properly

**Comment by theVakhovskeIsTaken** [comment]
Use "Update" button in Deck UI or steamos-update

**Comment by uberdisko** [comment]
i keep getting a error in the Deck UI too

**Comment by uberdisko** [comment]
![Screenshot_20220829_104842](https://user-images.githubusercontent.com/51147367/187229460-6ad58905-be61-4f9c-8afc-c61fd5f80440.png)

**Comment by agentwolf88** [comment]
I have the same problem.

**Comment by godtoall82** [comment]
Same. It’d be cool if issues were kept open until they were fixed.

**Comment by theVakhovskeIsTaken** [comment]
> ![Screenshot_20220829_104842](https://user-images.githubusercontent.com/51147367/187229460-6ad58905-be61-4f9c-8afc-c61fd5f80440.png)
> 

I told you exactly what to do, use steamos-update check and steamos-update now

**Comment by jrcharney** [comment]
It should be noted that on some package managers (such as `apt` and `pacman`) that some packages are not updated until some kind of "lock" is disabled on it. Why there is a lock in the first place is kind of complicated, but I'm sure a Google search will explain in greater detail.

It is annoying however to see that there could be an update to fix a problem or add features that won't be processed, but sometimes there a method to this madness.
