### ISSUE TITLE
Steam link crashes game mode

### ISSUE THREAD

**Issue by shoesio** [holoiso-eol/holoiso#486]
## Your Issue:

Game mode crashes when Steamlink initiates, returning to “validating installation” boot message after a minute or two.

seems to work ok when started in desktop mode

Was working fine(ish!) before updating from game mode 

same result with two clients

here’s a paste bin of the streaming log: pastebin.com/LtiY4Qjx

FYI have manually amended the default gamescope settings to 1280x720, this was previously working fine.

```

## Your device's full specs
```
CPU: Intel i5-8500 6 core @ 3ghz  iMac 
24gb ram
Gpu Amd Radeon RX 470
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220828.1634
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Yes yes yes 
```

**Comment by shoesio** [comment]
Just tried a clean reinstall of HoloISO (reinstalled from install usb) and same problem recurs with completely vanilla settings

**Comment by shoesio** [comment]
Looks like this is specific to Holoiso core - resolved if I switch to Neptune

**Comment by theVakhovskeIsTaken** [comment]
Is this issue resolved on later versions or?
