### ISSUE TITLE
[Report] Incorrect screen orientation in deck mode with an external display

### ISSUE THREAD

**Issue by alphonsez1** [holoiso-eol/holoiso#489]
## Your Issue:
Hi, I've recently installed Holoiso in my Ayaneo Air. Everything looks great except that when I connect it to an external monitor in deck UI, the picture is stretched and rotated. See the picture below. The handheld built-in display is good. The external display also works fine in desktop mode. 

![image](https://user-images.githubusercontent.com/71942669/188036061-af3e885e-b4de-4d0d-9091-59942cc9a740.png)

## Your device's full specs
```
CPU: AMD 5560U
GPU: AMD Radeon RX Vega 6
6 Compute Units, 1,600 MHz
```

## Your OS version:
```
snapshot20220828.1634
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?

Yes, through auto update right after the installation.

**Comment by alphonsez1** [comment]
I find that `--force-orientation left` is the issue. If I just override it with `--force-orientation normal` in `gamescope-session` it works with an external monitor. 

I'm now trying to figure out how to detect an external monitor and fix the issue. Hopefully this can be done with the script rather than modifying the `gamescope` source code.

**Comment by alphonsez1** [comment]
It looks like the display probe and update is done inside the same `gamescope` process. I have a fix that works for me in this fork: https://github.com/alphonsez1/gamescope/tree/force-orientation-internal-display
It applies the force orientation only to internal displays.

**Comment by theVakhovskeIsTaken** [comment]
> It looks like the display probe and update is done inside the same `gamescope` process. I have a fix that works for me in this fork: https://github.com/alphonsez1/gamescope/tree/force-orientation-internal-display
> It applies the force orientation only to internal displays.

Really nice💪, Will update with following code, thanks!

**Comment by jrcharney** [comment]
Worth noting, I had a similar situation occur on another system that uses Arch Linux where I am using the Sway Window Manager on this one device I was using. It was this command.

```
swaymsg output DSI-1 transform 90
```

Where `DSI-1` was the display of the laptop I was using. This could be substituted with `HDMI1` if an HDMI device is plugged in.

**Comment by crispyfritos** [comment]
I am pretty new to GitHub but I have this same exact issue when connecting my OneXPlayer (with the most recent HoloISO release) to my TV. It is tilted on its side here on the Deck UI but displays perfectly in handheld mode and the desktop is oriented in the correct landscape position. I noticed the fix or workaround in the previous comments and I am curious how I can implement this or will it be included in a newer version of HoloISO? Thank you so much and for the hard work you all are doing. I love having Linux on my OneXPlayer while also being a Manjaro user on my Macbook!

**Comment by theVakhovskeIsTaken** [comment]
Fully fixed since last update.
