### ISSUE TITLE
After install and first log in, entire steam log in screen's scaling is unreadable

### ISSUE THREAD

**Issue by ByteSz** [holoiso-eol/holoiso#49]
Like the title says, after getting through language/timezone selection, the entire steam deck ui login screen's scaling is really screwed up with high resolutions (I am running at 4K on a TV).

Seems to fix either from unplugging and replugging video cable, or by connecting to a different resolution screen. Figured I should make this an issue so that this information could be added to the release notes or known issues, since there's no way to fix Valve's gamescope scaling issues here.

**Comment by theVakhovskeIsTaken** [comment]
Just restart it one more time, and complete setup, then go to `Developer settings` and disable `OpenGL Composer`
Same behavior also happens on Steam Deck with external display.
