### ISSUE TITLE
download link not working help

### ISSUE THREAD

**Issue by teezom** [holoiso-eol/holoiso#491]
404 error????

**Comment by JesseKoldewijn** [comment]
What do you mean? Can you give us more info than just "It's not working"?

Like: 
-what is not working?
-what are you trying to do?
-what have you tried already?

And that kind of info.

**Comment by schusterro** [comment]
The single link to an ISO from the project home page is not working. You could have found that out with very little effort.
[https://github.com/bhaiest/holoiso/releases/latest](url)

**Comment by JesseKoldewijn** [comment]
@teezom go to http://dl.thevakhovske.pw and click through it to get the iso you want (meaning you could go for stable and/or beta). But I agree with @schusterro that you should just do some looking into this type of stuff before placing an issue.

**Comment by byzocker** [comment]
> @teezom go to http://dl.thevakhovske.pw and click through it to get the iso you want (meaning you could go for stable and/or beta). But I agree with @schusterro that you should just do some looking into this type of stuff before placing an issue.

that link is broken 

edit:
```
ERR_CONNECTION_REFUSED
```
seems broken to me

**Comment by JesseKoldewijn** [comment]
> 

Sounds like that's a local issue on your end. I got them opened on two separate devices here on two different networks
