### ISSUE TITLE
[ISO3.2 install] fails to download packages from steamdeck-packages.steamos.cloud

### ISSUE THREAD

**Issue by Sweepi** [holoiso-eol/holoiso#492]
## Your Issue:
```
With ISO 3.2, installing fails because packages from "steamdeck-packages.steamos.cloud" cannot be loaded, its 404.
Pinging it works, though.
I cannot copy paste terminal output because there is no browser available in the live image (which would be a nice touch!).

Therefore, screenshot of shame:

https://user-images.githubusercontent.com/35932592/188211028-761d0bc5-441f-4707-9d12-edaf99a4e9cb.jpeg

```
![817CE68F-64BE-473B-BA08-35ED7C891974](https://user-images.githubusercontent.com/35932592/188211028-761d0bc5-441f-4707-9d12-edaf99a4e9cb.jpeg)

## Your device's full specs
```
should not matter
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Name: HoloISO_Stable_GUI-20220902_1353-x86_64.iso
Size: 1906307072 bytes (1817 MiB)
CRC32: 410F676A
CRC64: A2C1E4E8E3005E06
SHA256: 40D4EDCC85B5B844E9CAEBA24EDBA4B438851EE41120AC30DDCA50F3953F4FB1
SHA1: 9F8F0A401D99194E1B29C36946FF346FA2EC27CC
BLAKE2sp: 896652DB87BC75A1123D0A9B2E6F193E676B3F2BEE9050EDB8FB54C7D990FA63

```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
n/a
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
n/a
```

**Comment by JimOkurku16** [comment]
same issue here.

 seems to be a server issue as mine says "failed to download" for both holoiso.db and holostaging.db after running sudo pacman -Sy git, everything after that downloads just fine (jupiter-main, holo and core downloads fine doing pacman -Sy) for holoinstall it just tells me I don't have a internet connection even tho I am clearly connected via cable and pinging google returns with a response.

some server is down as I was installing the system and it just told me "oh hey you aren't connected" even tho I can ping google and rerunning the script gives up.

**Comment by yesterdays-jam** [comment]
Probably a server issue as I've been having issues doing steamos-update check, it returns a 404 for holoiso.db and holostaging.db from steamdeck-packages.steamos.cloud

**Comment by teezom** [comment]
me too is it fixed ?

**Comment by iHad169** [comment]
me too

**Comment by Grimish-ng** [comment]
This fixed yet?

**Comment by yesterdays-jam** [comment]
> This fixed yet?

I joined the devs telegram channel and did a command line he posted to update my install (added the new server lists), so it's "fixed" for me since the Steamos update command works now.

**Comment by Grimish-ng** [comment]
Okay cool - I just checked the pacman.conf file and noticed that it differs from my currently installed one in which they all point to a single mirror which is
cat /etc/pacman.d/mirrorlist 
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

This appears to be old since the pacman.conf on the github page doesn't reference the mirror in alot of the repositories. There may be some manual editing as after i made changes I see a holo_mirror which still doesn't exist but after when I forced an update I no longer receive an error a database error for the holo & staging repositories.

**Comment by BonQerss** [comment]
i’m attempting this fix but it says i’m out of storage space? how do i safely clear storage space? i don’t understand how i’m out of space either i used a 64 gig thumb drive

**Comment by MisterSheeple** [comment]
I'm having the same problem, although I'm not even using HoloISO, I just recently used the recovery image on my Steam Deck and I'm getting this error whenever I download something with pacman. Is there a known solution?
