### ISSUE TITLE
Can't use Deck UI on Intel 4th gen

### ISSUE THREAD

**Issue by KorinFlakes** [holoiso-eol/holoiso#494]
## Your Issue:

Everything installed correctly but on first boot I was met with a black screen. I booted into recovery, ran holoiso-disable-sessions and managed to boot into the plasma desktop. When I switch to TTY4 and run gamescope-session I get the a large error ending in drmFormatDesc != nullptr

Searching google I found this thread https://github.com/Plagman/gamescope/issues/508 that claims to fix the problem by "applying [this patch](https://gitlab.freedesktop.org/mesa/mesa/-/commit/70ce634dc6d9c61db8af4dc5cb888b3ef51deef8.patch) on Mesa" from [this merge request](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/17182)

Problem is I'm not exactly sure how to do that. Is it possible a fix can be provided by holoiso for intel users?

## Your device's full specs
```
Operating System: SteamOS 3.3
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve24-1-neptune-02226-g5b8545e4c5a1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4570S CPU @ 2.90GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4600
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220902.1940
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
I don't know where the log file is located but will happily provide one if someone points me in the right direction.
```

## Your installation type:
```
deckperience
```

Any help would be greatly appreciated.

**Comment by theVakhovskeIsTaken** [comment]
This fix is already merged here. Your GPU is simply not supported.

**Comment by methanoid** [comment]
Is it? I have Radeon RX580 and i5-4690K and I have same issue with the OOBE not even loading...  I've tried the fixed ISO and the one available at Github. I'd love to get this working
