### ISSUE TITLE
stuck in a loop

### ISSUE THREAD

**Issue by logan001** [holoiso-eol/holoiso#495]
After update from deck ui and a reboot i get stuck in a loop where the login screens appear starts to log in and then i'm back in text mode with a "_" upper left corner. after 1 minute or so i'll get back to login screen and repeat the process. the laptop does not restart. i can't alt+Fxx to get some dmesg.
it happend the same on my computer too.

laptop has 4500u and desktop has 5750ge cpus. both are with their own APU as graphic cards
edit: forgot to mention that both use beta channel

**Comment by theVakhovskeIsTaken** [comment]
Fixed.

**Comment by jrcharney** [comment]
How is this considered "fixed"?
