### ISSUE TITLE
[Report] random dims/suspected sleeping and power managment go to default 

### ISSUE THREAD

**Issue by houku** [holoiso-eol/holoiso#498]
## Your Issue: my holoiso install randomly goes dark brightness and power managment cant be disabled
```
*type your problem here*
```
i just did above
## Your device's full specs
```
              .,,,,.                  houku@houku 
        .,'onNMMMMMNNnn',.            ----------- 
     .'oNMANKMMMMMMMMMMMNNn'.         OS: SteamOS Holo x86_64 
   .'ANMMMMMMMXKNNWWWPFFWNNMNn.       Host: VivoBook_ASUSLaptop X515MA_X515MA 1.0 
  ;NNMMMMMMMMMMNWW'' ,.., 'WMMM,      Kernel: 5.18.1-arch1_testHoloISO_20220606.1811 
 ;NMMMMV+##+VNWWW' .+;'':+, 'WMW,     Uptime: 5 hours, 34 mins 
,VNNWP+######+WW,  +:    :+, +MMM,    Packages: 992 (pacman), 17 (flatpak) 
'+#############,   +.    ,+' +NMMM    Shell: bash 5.1.16 
  '*#########*'     '*,,*' .+NMMMM.   Resolution: 1920x1080 
     `'*###*'          ,.,;###+WNM,   DE: Plasma 5.23.5 
         .,;;,      .;##########+W    WM: kwin 
,',.         ';  ,+##############'    Theme: Vapor [Plasma], Breeze [GTK2/3] 
 '###+. :,. .,; ,###############'     Icons: breeze-dark [Plasma], breeze [GTK2/3] 
  '####.. `'' .,###############'      Terminal: konsole 
    '#####+++################'        CPU: Intel Celeron N4020 (2) @ 2.800GHz 
      '*##################*'          GPU: Intel GeminiLake [UHD Graphics 600] 
         ''*##########*''             Memory: 4700MiB / 7773MiB 
              ''''''
                                                              
                                                              

```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
the september second 2022 version
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
no, i want to use it on a laptop
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
no, its a fresh install
```

**Comment by F1ReB4LL** [comment]
Same story for Anbernic Win600 and "HoloISO_4.3.1_ux_changes-20230611_1f384dcbe0_pre-ver-1-x86_64.iso" installed ontop of "HoloISO_4.2_ux_changes-20230414_a192ee2182_installation_reuse-fixes1-1-x86_64.iso". The picture goes dark brightness right after the boot up, but if you connect a mouse and move it (so the cursor appears) - the brightness becomes fine until the cursor disappears again. Enabling fps/cpu/gpu counters overlay also fixes it until reboot. Happens in both game and desktop modes. If to reboot with the fps/cpu/gpu overlay enabled the exact opposite situatuon happens - the picture becomes super-bright until you move the cursor. Rollbacking to HoloISO_4.2 iso fixes the issue.
