### ISSUE TITLE
[Report] no controls working on Aya neo 2021

### ISSUE THREAD

**Issue by houku** [holoiso-eol/holoiso#499]
## Your Issue: 
```
no controls working on Aya neo 2021
```

## Your device's full specs
```
Amd Ryzen 5 rDNA Aya neo 2021 not pro stuff
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
The September second 2022 version thjngy
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah, and no controls are working
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Nope, couldn't even go through setup
```

**Comment by theVakhovskeIsTaken** [comment]
Have you tried HandyGCCS? Or secondary kernel option?

**Comment by houku** [comment]
> secondary kernel option?

i just tried the other advance option "linux kernel" not neptune, and the controls work, is there a way to make it a default?

**Comment by houku** [comment]
there seem to be an issue where i press the home button, its just getting blurry but not showing any options, any help?

**Comment by theVakhovskeIsTaken** [comment]
> there seem to be an issue where i press the home button, its just getting blurry but not showing any options, any help?
> 

Update your OS and try again, confirmed MESA issue.
