### ISSUE TITLE
Bluetooth does not work within SteamOS UI

### ISSUE THREAD

**Issue by ByteSz** [holoiso-eol/holoiso#50]
Just installed the stable release, and the Bluetooth does not pick up anything nor work at all out of the box. After installing bluez nothing changed either, and it's still broken as far as I can tell.

Was working on Rub Rub RC1 with zero issues before.

**Comment by theVakhovskeIsTaken** [comment]
Can you run `sudo systemctl start bluetooth` again?

**Comment by ByteSz** [comment]
This did not fix it at all. Even tried doing enable instead.
