### ISSUE TITLE
how to add drivers (wifi to the iso or build new iso)?

### ISSUE THREAD

**Issue by crlink271986** [holoiso-eol/holoiso#501]
hi so slight problem I ave an intel wifi AX200 chip in my laptop that will not detect (presumably the module/driver is not in the isos kernel anyone can point me in the right direction I do have WSL (windows 11) so i can build using it just need to know how to intergrate the module into the source code otherwise i have not net to install holo

**Comment by ryzendew** [comment]
That is also my issue no wifi for me so the install isnt possible
