### ISSUE TITLE
[Report] EFI Partition created as FAT16, but not everything can boot from FAT16

### ISSUE THREAD

**Issue by NathanDreamweaver** [holoiso-eol/holoiso#502]
## Your Issue:
```
HOLOEFI partition gets created as FAT16, but my device can only boot from FAT32. I know it is not the only device that does that.
```

## Your installation type:
```
deckperience
```

**Comment by methanoid** [comment]
Can I add to this a question, is FAT16 necessary, or can we reformat it as FAT32 and will HoloISO install to a FAT32 EFI partition?

**Comment by methanoid** [comment]
It seems Holoiso will work fine with a standard FAT32 EFI partition so I have to ask WHY do we get old useless FAT16 and such a small one? Some OS you may want to dual boot require EFI partition to be 500-600MB minimum

**Comment by NathanDreamweaver** [comment]
That last one from what I've seen is because it creates a second efi partition instead of adding onto the existing one. Wouldn't mind if it was fat32

**Comment by methanoid** [comment]
Closed but WHAT was done?
