### ISSUE TITLE
Black screen when switching to Desktop mode 

### ISSUE THREAD

**Issue by Redelements** [holoiso-eol/holoiso#505]
## Your Issue:
```
Black screen when switching to Desktop mode 
```

## Your device's full specs
```
CPU: Ryzen 5800X
GPU: AMD 5700 XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220904_1926
3.3
Stable (e77701daf4)
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```

```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Yes I tried updating from game view. 
```

**Comment by LoadingStill** [comment]
Same issue with my set-up as well.

New install, first boot from the ISO Update 3.2

rx 6900 xt
ryzen 7 5800x

Black screen occurs when trying to enter desktop mode.  But steam big picture works after reboot.

The issue is a black screen, no audio, cursor is not seen.
Tries with and without controllers, multiple monitors, single monitor, clean drive to install.  I can not get to logs due to not being able to pull up the terminal.  I tried both steams default kernel and the kernel provided by HoloISO.

**Comment by DubCity7274** [comment]
I also had this problem a while back. A quick solution would be when booting select "advanced options for steamos" and in the next menu "steamos with Linux-holoiso (recovery mode)"

Next type your password and edit /etc/sddm.conf.d/autologin.conf

Search for the line that starts with "Session=" and change whatever follows that to "plasma.desktop". 

This will boot you into desktop session every time, personally I don't use the deck session so this was my permeant solution.

**Comment by Redelements** [comment]
Hey thanks for the help man. Unfortunately I got stuck again. When trying to access autologin.conf it says I do not have permission. :(

**Comment by DubCity7274** [comment]
> Hey thanks for the help man. Unfortunately I got stuck again. When trying to access autologin.conf it says I do not have permission. :(

Hmmm, its should prompt for root privileges. Before trying to access it type sudo and enter the root password just to make sure. 

If that doesn't work you could try booting into ubuntu on a usb and modifying it that way.

**Comment by muldy** [comment]
```
[General]
DisplayServer=wayland

[Autologin]
User=muldy
#Session=gamescope-wayland.desktop
Session=plasma.desktop
```
Didn't work for me, same blank screen on boot

**Comment by muldy** [comment]
Actually disconnecting all displays except the primary worked, after that I did connect them and added then in the desktop environment.
I can only boot/switch to desktop mode with one display connected.

**Comment by MichailIoannou** [comment]
> "Actually disconnecting all displays except the primary worked.."

I second this, thanks. I will make a new report if you like to chime in
