### ISSUE TITLE
Stuck on Loading initial ramdisk

### ISSUE THREAD

**Issue by mpop1** [holoiso-eol/holoiso#506]
Tring to install Holo iso.  when I boot after the install (the install USB boots fine) it get stuck on loading initial ramdisk.  Non of the advance options boot, except for recovery.

Graphic card is NVidia GT 1030, installed the NVidia drivers at installation time.

**Comment by Lolo280374** [comment]
I don't know if that will help you, but you can try to boot to Recovery Mode and use the command **holo-disable-sessions** (not sure if that's the correct one, you should check). This command will disable auto-login in the game mode session, and you should be able to go to Desktop mode and fix what's wrong.

**Comment by mpop1** [comment]
I did try that (found that suggestion in a google search) but it did not help.

**Comment by Lolo280374** [comment]
> I did try that (found that suggestion in a google search) but it did not help.

Then i really have no idea. I did try to install HoloISO on my Nvidia Laptop, it got stuck at the same part as you did.
Didn't try to disable sessions.

**Comment by BonQerss** [comment]
any solution?

**Comment by mpop1** [comment]
Nop not yet

**Comment by mra282** [comment]
I experienced the same issue on a clean install of version 3.2. To ensure that it was not just an error with install, usb flashing or download I redownloaded the image reflashed and tried again with same results. Specs of system: i7 4770k, Nvidia GTX 1070, 16GB Ram

**Comment by mpop1** [comment]
Well the only solution I could come up with, is I removed the graphics card, and using the "graphics" card built into the mother board.  I tried their other solution (https://github.com/theVakhovskeIsTaken/holoiso/issues/511) but that failed, I tested to see if the output was going to the DVI-D port (bought a DVI to HDMI converter) no joy.  lets just face it they don't support NVIDIA.  And using the built in mother board graphics card is our only solution till valve themselfs releases offically the OS for all systems.

**Comment by Frostyman758** [comment]
Hi, I'm the author of #511, can I see your gamescope -session file, please?

**Comment by Frostyman758** [comment]
Additionally, I need to know what laptop you have.

**Comment by mpop1** [comment]
I am not using a laptop, I am using a desktop (the graphics card as stated at the start is a NVidia GT 1030)

and the game scope is The base one with the changes you stated with the code of [10de:1d01]

so it came out to be
[gamescope-session.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/9629930/gamescope-session.txt)

**Comment by Frostyman758** [comment]
Preliminary: 
Should be as a space then \ after your code
And should be --force-composition \

**Comment by mpop1** [comment]
sorry for the delay here Frostyman made said changes and still no joy still stuck on Loading Inital ramdisk.

**Comment by Frostyman758** [comment]
Send your actual gamescope-session file.

**Comment by Frostyman758** [comment]
Not in .txt

**Comment by mpop1** [comment]
I have to add the .txt extention as I can not attach the file with out it as it rejects it as unsupported but it is the actual file.
[gamescope-session.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/9649094/gamescope-session.txt)

I got it by going to the /usr/bin then sftping it to a remote computer, then from my main computer sftping it down to the main computer to upload here (I can not directly upload from the computer in question as even in recovery mode I can not get the UI going, so I am working straight from the bash shell)

**Comment by colingoodman** [comment]
Bumping this to note that I am having the same issue (stuck loading ramdisk on boot) with a Nvidia GPU. `nvidia-smi` when chroot'd to the installation fails `couldn't communicate with the NVIDIA driver.`

**Comment by Angheloss** [comment]
This is also happening to me but with an intel igpu (changed it to a nvidia gpu still not working same problem)

**Comment by zenithmcdisco** [comment]
if you have a dedicated gpu and an integrated gpu and this happens, you can fix it by simply taking out the dedicated gpu both this os and chimera have this problem so if you have the same problem with chimera do the same but it then goes to a buggy verifying installationascreen for me

**Comment by FredsMedia** [comment]
> I don't know if that will help you, but you can try to boot to Recovery Mode and use the command **holo-disable-sessions** (not sure if that's the correct one, you should check). This command will disable auto-login in the game mode session, and you should be able to go to Desktop mode and fix what's wrong.

Sorry I’m a little late. Just wondering when you say fix what’s wrong, what exactly should we do to fix it?

**Comment by theVakhovskeIsTaken** [comment]
NVIDIA GPUs are explicitly unsupported.
