### ISSUE TITLE
Can’t return to gaming mode after update

### ISSUE THREAD

**Issue by godtoall82** [holoiso-eol/holoiso#508]
Whenever I try going back from desktop, gaming mode fails to launch and I end up back in desktop. Even rebooting puts me in desktop instead of gaming.

**Comment by godtoall82** [comment]
Seriously, any help would be appreciated. Below is what I get when trying to run gamescope-session in konsole:

[session output.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/9611977/session.output.txt)

**Comment by Grimish-ng** [comment]
Check your /etc/sddm.conf.d/autologin.conf
Specifically look at:
Session=gamescope-wayland.desktop

**Comment by godtoall82** [comment]
Thanks for the help. File was changed to Session=plasma.desktop

No idea how that happened.

**Comment by Grimish-ng** [comment]
No problem. Same thing happened to me - your issue look surprisingly similar. Good to hear that was the case and you got it resolved.
