### ISSUE TITLE
If your hardware is incompatible, your reports won't be even taken a look at.

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [holoiso-eol/holoiso#509]
Just a small note.

**Comment by npaladin2000** [comment]
May I suggest a compatibilty list if so?

**Comment by theVakhovskeIsTaken** [comment]
> May I suggest a compatibilty list if so? 

_AMD RX Vega+/APU iGPU; 4xx/5xx, 5xxx/6xxx GPU or Intel UHD 630+ iGPU or NVIDIA GTX 9xx+ iGPU/GPUs (preferably without Optimus [PRIME])_

**Comment by Bchauncey0831** [comment]
I'm currently using a Toshiba Satellite C55 
AMD A8 quad core processor
AMD Radeon R5 graphics
4GB ram. (plan to get more RAM obviously)

Currently having problems installing and booting was wondering if my hardware was supported

**Comment by ghost** [comment]
when booting the iso, the stage `copying squashfs image to ram` with 4gb ram gives a "no space left on device" error for me so i assume you'll need to get more ram first, @Bchauncey0831 (i'm not a dev for this project, don't quote me on this)

**Comment by Bchauncey0831** [comment]
Yes I have recently thrown in a spare 4Gb stick of ram
