### ISSUE TITLE
Keyring issue not fixed

### ISSUE THREAD

**Issue by dravpin** [holoiso-eol/holoiso#51]
the iso version [SteamOS_Holo-20220507_0729_amdgpu-x86_64.iso]

https://imgur.com/b62EA8m

**Comment by theVakhovskeIsTaken** [comment]
That issue is probably on your side. Since i couldn't get to reproduce that.

**Comment by dravpin** [comment]
<img width="1363" alt="Screen Shot 2022-05-08 at 10 14 04 AM" src="https://user-images.githubusercontent.com/33169362/167300397-4969f53c-b3e7-495c-9758-371be10249cd.png">

what am i doing wrong then im preceding with the install normally

**Comment by theVakhovskeIsTaken** [comment]
Your ISP might not like the connection or some, have you tried to use VPN before installing?

**Comment by dravpin** [comment]
no i haven't

**Comment by dravpin** [comment]
(update) VPN im using nord VPN hasn't fixed the issue

**Comment by dravpin** [comment]
Using to core option instead of neptune lets me proceed with the install but once i reboot ofter the install i cannot login to wayland because when i enter my password i get failed to start jupiter controller firmware update service then i get put back in the login screen https://imgur.com/a/odlrjM2

**Comment by dravpin** [comment]
selecting plasma 11 at the top and loging in results in a black screen
