### ISSUE TITLE
For my Nvidia [Prime] Friends ~fox

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#511]
Hi folks, I hope this post finds you well. I'm fairly certain many of you recognize my name at this point due to my numerous posts on this Repo, and I'm sorry I'm basically unreachable.

**I am not a coder, I am not a programmer, I have 0 coding skills. Do not ask me to magically make this work for you or for me to do this for you, I will not. Also, Unless your laptop was built with only an Nvidia GPU, do not expect working internal display, ever. You must be connected to an external display.**

**Also note, if your device does not use the dgpu as the node for the HDMI port (as in it powers the port), this method will not work for you because the GPU can't render frames to the external display.**

_Preliminary research would say that anything made in the last 4 years with a 10series or better NGPU should be able to get up and running, my laptop is from 2019. Definitely try it out, even it you don't think it'll work_

**And now for the steps!**

 **[Setup]**
Alright, without any more problems, here's the steps to get Gamescope/Gamepadui working on your "Deck"

1. Install the Iso selecting the Neptune Kernel. If you can't get wifi or whatever working, I can't help you. 
When it asks you what GPU you want, select Nvidia.

2. Boot into the device, and use the recovery terminal to load directly into session manager(sddm) 
 _(Or if you're like me, it just magically worked out of the box and you can just switch to the desktop environment)_

3. Open the terminal and type the following command: `lspci -nnk | grep VGA` It should list out your two GPU devices and look something like this:

`00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [10de:1f99] (rev a1)
`
Write down the stuff in brackets _(I'll call it [code] for later)_ for your Nvidia GPU, in my case I copied 10de:1f99 for my TU117M

**[Modifying the session]**

Once you've obtained the information from above, you're ready to modify a file to get the session working.

1. Open Dolphin, the file manager and click on `Holo-root` this is your root directory. once you've clicked, look at the top right corner for the search button and search for the file `gamescope-session` when it shows up, right click and select "Open with Kwrite"

2. in the file, scroll down to where you see `gamescope  \`  we will be adding stuff under this header.
3. first add underneath it the following:
`--disable-layers \ `
`-force-composition \`
`--generate-drm-mode fixed \`

3. Finally add

`--prefer-vk-device [code] \`where the [code] is the numbers/letters you copied earlier. click save and leave Kwrite.

Now you should be able to click the Return to gamemode shortcut and have it reboot to the gamepadui session. If it doesn't work for you, I can't help. Doing this worked perfectly for me and continues to work through holo updates unless that file is modified/replaced I hope this helps everyone who's been waiting like me!

You can even get EmuDeck and Decky loader to work, I absolutely love the work Train and his team are doing!

Happy decking I guess lol
 ~~Fox
![helpyou](https://user-images.githubusercontent.com/98052869/190254688-8f4eee19-6738-4eb5-b565-967920438c2a.png)

Some more Photos for proof
![20220914165154_1](https://user-images.githubusercontent.com/98052869/190260667-53046907-1c38-4278-b397-38eab809145f.jpg)

![Uploading 20220907150146_1.jpg…]()
Home menu is a bit scuffed because non-steam shortcuts require sleep/wake to load, probably something on Valve's end
![20220914164947_1](https://user-images.githubusercontent.com/98052869/190260778-76ef85ad-949d-4376-84ac-5275b369ea5c.jpg)

**Comment by theVakhovskeIsTaken** [comment]
sex.
will be merged later.

**Comment by Frostyman758** [comment]
I got tired of people complaining to me on the telegram channel, I think both of us are completely tired of it. I've gotten this to work on every Arch Distro I've used, I know it works. Don't feel like you need to support these people anymore, just link them here and have them figure it out, if I can do it, they definitely can. I'm basically spoon feeding it. I should probably include a picture of the modified Gamescope-session, though. Also sleep can cause Deckui to have no sound but it works in-game so who really cares, eh.

**Comment by theVakhovskeIsTaken** [comment]
> I got tired of people complaining to me on the telegram channel, I think both of us are completely tired of it. I've gotten this to work on every Arch Distro I've used, I know it works. Don't feel like you need to support these people anymore, just link them here and have them figure it out, if I can do it, they definitely can. I'm basically spoon feeding it. I should probably include a picture of the modified Gamescope-session, though. Also sleep can cause Deckui to have no sound but it works in-game so who really cares, eh.

i've already tested the option few days ago on separate branches, so yeah that's all pretty much okay

**Comment by ruineka** [comment]
Figured I'd stop by here and share my results.![PXL_20220915_183722735.jpg](https://user-images.githubusercontent.com/16360335/190485427-5e10f9ae-9191-4db7-8de1-5bd1c24f724c.jpg)

![PXL_20220915_183824003.jpg](https://user-images.githubusercontent.com/16360335/190485445-0faea447-7de9-4ef3-80d9-f0374688c76a.jpg)

**Comment by packyan** [comment]
many laptop with GTX 9XX M series gpu also use the dgpu as the node for the HDMI port, so does it means the method work for older gpus?

**Comment by Frostyman758** [comment]
@packyan if you're hardware is mapped properly to let the Nvidia GPU bypass the framebuffer copy to the igpu and it works properly on desktop, it should work. 

The main limitations is just knowing Wich laptops are mapped properly.
