### ISSUE TITLE
[Report] Bluetooth not working on Intel AX210 card

### ISSUE THREAD

**Issue by lgcavalheiro** [holoiso-eol/holoiso#514]
## Your Issue:
```
I just installed an Intel AX210 wifi and bluetooth card on this machine i'm turning into a "homemade console", the wifi works fine OOTB, but i can't get the bluetooth service to work. 
I'll be referencing everything i tried so far at the end of the issue, but `systemctl status bluetooth` returns:
○ bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)

Sep 17 00:39:05 holo systemd[1]: Bluetooth service was skipped because of a failed condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
Sep 17 01:49:58 holo systemd[1]: Bluetooth service was skipped because of a failed condition check (ConditionPathIsDirectory=/sys/class/bluetooth).

```

## Your device's full specs
```
CPU: Intel i5-10400F (12) @ 4.300GHz 
GPU:  AMD RX 6500 XT 4gb
MOBO: Maxsun H510 ITX (MS-TZZ H510ITX E1.3G)
RAM: 2x8gb 2666mhz
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220904.1926
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Tried through the UI and through `steamos-update`, both were up to date. Discover was also up to date.
```

### Enabling the service again
```
Running `systemctl enable bluetooth.service` and `systemctl start bluetooth.service` didn't change the status of the service.
```

### Changing from neptune kernel to linux-holoiso
```
That also didn't make a difference (changed through the advanced settings on boot).
```

### Modprobing btusb
```
That does help enabling and running bluetooth.service, but the OS doesn't detect the ax210 card, so i still can't connect anything. The status after this is:
● bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; vendor preset: disabled)
     Active: active (running) since Sat 2022-09-17 02:47:23 -03; 2s ago
       Docs: man:bluetoothd(8)
   Main PID: 7992 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 19023)
     Memory: 2.0M
        CPU: 9ms
     CGroup: /system.slice/bluetooth.service
             └─7992 /usr/lib/bluetooth/bluetoothd

Sep 17 02:47:23 holo systemd[1]: Starting Bluetooth service...
Sep 17 02:47:23 holo bluetoothd[7992]: Bluetooth daemon 5.63
Sep 17 02:47:23 holo systemd[1]: Started Bluetooth service.
Sep 17 02:47:23 holo bluetoothd[7992]: Starting SDP server
Sep 17 02:47:23 holo bluetoothd[7992]: Bluetooth management interface 1.20 initialized
```

Also, here's the output from `journalctl -b -g bluetooth`:
```
Sep 17 02:43:44 holo NetworkManager[413]: <info>  [1663393424.6152] Loaded device plugin: NMBluezManager (/usr/lib/NetworkManager/1.34.0-1.1/libnm-device-plugin-bluetooth.so)
Sep 17 02:43:54 holo systemd[1]: Bluetooth service was skipped because of a failed condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
Sep 17 02:44:53 holo kded5[3932]: bluedevil: Bluetooth operational changed false
Sep 17 02:44:53 holo systemd[1]: Bluetooth service was skipped because of a failed condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
Sep 17 02:44:53 holo systemd[557]: Starting Bluetooth OBEX service...
Sep 17 02:44:53 holo systemd[4097]: obex.service: Failed to locate executable /usr/lib/bluetooth/obexd: No such file or directory
Sep 17 02:44:53 holo systemd[4097]: obex.service: Failed at step EXEC spawning /usr/lib/bluetooth/obexd: No such file or directory
Sep 17 02:44:53 holo systemd[557]: Failed to start Bluetooth OBEX service.
Sep 17 02:45:35 holo systemd[557]: Started Bluetooth.
Sep 17 02:46:13 holo polkitd[606]: Operator of unix-session:3 successfully authenticated as unix-user:holo to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-unit-files for system-bus-name::1.115 [systemctl enab>
Sep 17 02:46:24 holo polkit-kde-authentication-agent-1[4059]: Message of action:  "Authentication is required to start 'bluetooth.service'."
Sep 17 02:46:26 holo polkitd[606]: Operator of unix-session:3 successfully authenticated as unix-user:holo to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.121 [systemctl start blu>
Sep 17 02:46:26 holo systemd[1]: Bluetooth service was skipped because of a failed condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
Sep 17 02:46:52 holo kernel: Bluetooth: Core ver 2.22
Sep 17 02:46:52 holo kernel: Bluetooth: HCI device and connection manager initialized
Sep 17 02:46:52 holo kernel: Bluetooth: HCI socket layer initialized
Sep 17 02:46:52 holo kernel: Bluetooth: L2CAP socket layer initialized
Sep 17 02:46:52 holo kernel: Bluetooth: SCO socket layer initialized
Sep 17 02:47:21 holo polkit-kde-authentication-agent-1[4059]: Message of action:  "Authentication is required to start 'bluetooth.service'."
Sep 17 02:47:23 holo polkitd[606]: Operator of unix-session:3 successfully authenticated as unix-user:holo to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.128 [systemctl start blu>
Sep 17 02:47:23 holo systemd[1]: Starting Bluetooth service...
Sep 17 02:47:23 holo bluetoothd[7992]: Bluetooth daemon 5.63
Sep 17 02:47:23 holo systemd[1]: Started Bluetooth service.
Sep 17 02:47:23 holo audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 02:47:23 holo kernel: audit: type=1130 audit(1663393643.514:195): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 02:47:23 holo dbus-daemon[412]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.131' (uid=0 pid=7992 comm="/usr/lib/bluetooth/bluetoothd ")
Sep 17 02:47:23 holo bluetoothd[7992]: Bluetooth management interface 1.20 initialized
Sep 17 02:47:23 holo kernel: Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Sep 17 02:47:23 holo kernel: Bluetooth: BNEP filters: protocol multicast
Sep 17 02:47:23 holo kernel: Bluetooth: BNEP socket layer initialized
Sep 17 02:47:23 holo kded5[3932]: bluedevil: Bluetooth operational changed true
```

**Comment by theVakhovskeIsTaken** [comment]
Just to make sure, is your linux-firmware up to date? Does device itself show up under lspci | grep -i network ?

**Comment by lgcavalheiro** [comment]
Yes, the card shows up as `05:00.0 Network controller: Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz (rev 1a)`.
About the linux-firmware, `pacman -Ss linux-firmware | grep installed` returns these:
```
holoiso/linux-firmware 20220815.8413c63-1 [installed]
holoiso/linux-firmware-whence 20220815.8413c63-1 [installed]
core/linux-firmware 20220119.0c6a7b3-2 [installed: 20220815.8413c63-1]
core/linux-firmware-whence 20220119.0c6a7b3-2 [installed: 20220815.8413c63-1]
```

I noticed there this may be some sort of regression issue with 5.13 that is described here: https://bugzilla.kernel.org/show_bug.cgi?id=213829 
Maybe there's a valve-neptune 5.12 or something that i could try to downgrade to and see if it fixes the issue? (`uname -r` returns ` 5.13.0-valve24-1-neptune-02226-g5b8545e4c5a1`)

**Comment by leonewt0n** [comment]
I'm having similar issues with a UB500 bluetooth adapter

Systemctl status reports bluetooth service as running. My xbox controller just doesn't show up when I push the pair button or other bluetooth devices.

**Comment by bleetube** [comment]
> I'm having similar issues with a UB500 bluetooth adapter

Yep, my TP-link UB500 bluetooth usb adapter does not see any signals while running HoloISO. I dual boot Manjaro (Linux 5.15), where it does work. I investigated this for a bit and my best bet is it's due to an older kernel in HoloISO (Linux 5.13). This is a Bluetooth 5.0 dongle. I tried plugging in my old Bluetooth 4.0 dongle and that one works fine.

**Comment by bleetube** [comment]
@lnew253 
>  My xbox controller just doesn't show up when I push the pair button or other bluetooth devices.

That's a separate issue, and not bluetooth related.  You just need the driver for the wireless Xbox controller adapter:
```
yay -Sa xone-dkms
```

**Comment by leonewt0n** [comment]
> @lnew253
> 
> > My xbox controller just doesn't show up when I push the pair button or other bluetooth devices.
> 
> That's a separate issue, and not bluetooth related. You just need the driver for the wireless Xbox controller adapter:
> 
> ```
> yay -Sa xone-dkms
> ```

No the controller works plugged in over usb. It doesn't see any bluetooth device.

**Comment by lgcavalheiro** [comment]
Are there any other kernel versions i can try with holoiso? I think this might be a module missing for the kernel I'm using or something (5.13). I have a Cambridge Silicon Radio bluetooth dongle that will only worl on 5.19, so I'm wondering if this is the problem. If i can't find another kernel, I'll see if i can source another ssd and try to get the bluetooth working on arch as a test. I tried with a 519-wip kernel or something but holoiso is still using 5.13....

**Comment by lgcavalheiro** [comment]
Ok i managed to run some more tests on my current install of holoiso:

I'm using a generic CSR 5.0 bluetooth dongle to test how the kernel versions i got react to bluetooth, since the AX210 seems to not work on any of them, this dongle is recognized by the system as `Bus 001 Device 006: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)`

- linux-neptune 5.13: Bluetooth service activates, but can't pair or find any devices;
- linux-holoiso 5.18.1: Works OOTB
- linux-neptune-519-wip: Works OOTB

For now i guess i'll use the dongle to get some bluetooth working on the machine, defaulting to `linux-holoiso` (had to uninstall all other kernels, since `grub-configure` is breaking the grub file, and editing by hand would not change from linux-neptune for some reason). 

I'll continue looking into this to see if i can find something else to try out, i'm starting to think i installed the AX210 card wrong (maybe the order of the main and aux antennas needs to be reverted?) or the card is faulty or something.

**Comment by titoudoc** [comment]
Hello, got a Nuc 11 extreme (with intel AX210 card) and same issue here.

Fresh install of the last release (ISO Update 3.3), and no bluetooth working.

But what is weird, during first boot of installator, on desktop (before really installing holoiso to HDD), bluetooth was working and detect peripheral... But after reboot, on the deck no bluetooth... so no wireless gamepad... :'(

**Comment by grimlokason** [comment]
Hello,

linux-neptune 5.13: Bluetooth service activates, but can't pair or find any devices; << that kernel version is know to have some bluetooth issue :/
