### ISSUE TITLE
[Request]Add support for 32Bit EFI Shell

### ISSUE THREAD

**Issue by sketrick** [holoiso-eol/holoiso#515]
## Your Issue:
Installation doesn't start as my Windows tablet has 32bit EFI shell and 64Bit Intel CPU.

I can install 64Bit Windows but I need the installation media that has both 32bit and 64bit versions in one, to start the installation.

Thanks.

**Comment by uejji** [comment]
What is your hardware?  I might be mistaken, but I can't think of any hardware that is 64-bit but uses 32-bit UEFI since Baytrail, and that certainly isn't supported here.
