### ISSUE TITLE
 Audio Not Working on Steam Deck

### ISSUE THREAD

**Issue by BatoceraNation** [holoiso-eol/holoiso#516]
## Your Issue:
```
Audio not working on Steam Deck
```
Hi!  I run the YouTube channel Batocera Nation which focuses on Batocera OS.  I'm trying to install Holoiso on a MicroSD card.   The goal is to install Batocera OS on the internal memory of the Steam Deck.  Then I would like to run Holoiso on a MicroSD so that I can have the best of both worlds.  Holoiso was installed successfully on a MicroSD.  It loads and boots up correctly.  All the buttons and features work just like on the real Steam Deck.  However, the audio does NOT work.  Everything else works except for audio.

Is there a way that I could fix this issue? 

Indeed, this solution would be useful for anyone wanting to install another OS on the Steam Deck (including Windows) while running Holoiso on a microSD or thumb drive.

Thank you for your time,
Manny

## Your device's full specs
```
Steam Deck
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Latest version
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
No
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Steam Deck did do an update after everything loaded and booted.
```

**Comment by AaronBaird1** [comment]
which kernel did you install? i had the same problem a few months back and gave up but thinking back I think I chose the wrong kernel.  I think the dev included the steamdeck kernel as an option during install (neptune)

**Comment by BatoceraNation** [comment]
Yes.  Neptune.  Which one am I supposed to use?

**Comment by AaronBaird1** [comment]
> 

ohh ok, must be another problem then.  The neptune kernel should have the audio drivers built in since its straight from valve.

Just for troubleshooting, do headphones work?  What does the toast notification say when you press the volume buttons?

what does `sudo lspci` output?

**Comment by theVakhovskeIsTaken** [comment]
> ## Your Issue:
> ```
> Audio not working on Steam Deck
> ```
> Hi!  I run the YouTube channel Batocera Nation which focuses on Batocera OS.  I'm trying to install Holoiso on a MicroSD card.   The goal is to install Batocera OS on the internal memory of the Steam Deck.  Then I would like to run Holoiso on a MicroSD so that I can have the best of both worlds.  Holoiso was installed successfully on a MicroSD.  It loads and boots up correctly.  All the buttons and features work just like on the real Steam Deck.  However, the audio does NOT work.  Everything else works except for audio.
> 
> Is there a way that I could fix this issue? 
> 
> Indeed, this solution would be useful for anyone wanting to install another OS on the Steam Deck (including Windows) while running Holoiso on a microSD or thumb drive.
> 
> Thank you for your time,
> Manny
> 
> ## Your device's full specs
> ```
> Steam Deck
> ```
> 
> 
> ## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
> ```
> Latest version
> ```
> 
> ## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
> ```
> No
> ```
> 
> ## Your installation type:
> ```
> deckperience
> ```
> 
> ## Have you updated your installation recently?
> ```
> Steam Deck did do an update after everything loaded and booted.
> ```
> 

Make sure you boot using linux-neptune (Stock Steam Deck kernel), if that doesn't resolve anything. Install holo-pipewire and holo-wireplumber

**Comment by BatoceraNation** [comment]
Yes, I'm using linux-neptune version.  Can someone kindly let me know what are the exact commands that I need to enter into the terminal to install holo-pipewire and holo-wireplumber.  I'm really new with Linux.  With Batocera, there really aren't any commands to enter.  It's an OS designed to work without any user knowledge of Linux.

Thanks!

**Comment by AaronBaird1** [comment]
@BatoceraNation in Konsole: `yay -S holo-pipewire holo-wireplumber`

**Comment by BatoceraNation** [comment]
> @BatoceraNation in Konsole: `yay -S holo-pipewire holo-wireplumber`

Thank you so much!!  I will definitely try this!

**Comment by BatoceraNation** [comment]
> @BatoceraNation in Konsole: `yay -S holo-pipewire holo-wireplumber`

Well, I tried it.  It did install successfully.  Rebooted and now my Steam Deck doesn't see any audio device when I checked in Deck's settings.

So strange that everything else works except for the audio.

**Comment by AaronBaird1** [comment]
@BatoceraNation I took a look at the documentation for wireplumber and it definitely does not look beginner friendly. https://wiki.archlinux.org/title/WirePlumber

Did headphones work before? If so it sounds like the driver is loaded it's just not outputting to the speakers. Probably a simple fix in that case but I don't have holo on my deck right now to test.

Another option would be the stock valve image on your external drive with this https://gitlab.com/popsulfr/steamos-btrfs

Makes the file system permanent.

**Comment by BatoceraNation** [comment]
> @BatoceraNation I took a look at the documentation for wireplumber and it definitely does not look beginner friendly. https://wiki.archlinux.org/title/WirePlumber
> 
> Did headphones work before? If so it sounds like the driver is loaded it's just not outputting to the speakers. Probably a simple fix in that case but I don't have holo on my deck right now to test.
> 
> Another option would be the stock valve image on your external drive with this https://gitlab.com/popsulfr/steamos-btrfs
> 
> Makes the file system permanent.

Hi hh1599!  The headphones were working correctly before.  I dug some more and I found this:
https://github.com/theVakhovskeIsTaken/holoiso/issues/426

DocMax said to "copy the firmware files from original Steam Deck to /lib/firmware/cs35l41-dsp1-spk-prot.wmfw"

I found the file and when I tried to copy it to /lib/firmware location, I received an "access denied". How do I copy it to that location since it seems to be write protected?

I think this might be our solution and need to get to this final step.

Thanks,
Manny

**Comment by Frostyman758** [comment]
You need to run dolphin at root. That's a root directory.

**Comment by theVakhovskeIsTaken** [comment]
Alright, so.

run: sudo pacman -Rdd linux-firmware && sudo pacman -S linux-firmware-neptune && sudo mkinitcpio -P

That'll should install all of the Deck related blobs

**Comment by BatoceraNation** [comment]
> Alright, so.
> 
> run: sudo pacman -Rdd linux-firmware && sudo pacman -S linux-firmware-neptune && sudo mkinitcpio -P
> 
> That'll should install all of the Deck related blobs

theVakhovskeIsTaken:
Thank you SO much!  That did the trick!  So happy that now I can install Batocera on it and have SteamOS running on my MicroSD card if I choose.  I have the best of both worlds.

Since you are the Developer of this, I'm curious, whether this will eventually be baked into the official Holoiso image so that we won't have to enter those commands?  I plan to do a tutorial in the near future about this for my channel and I'm curious whether this will be a future and permanent requirement to get sound on the Steam Deck.

In either case, thanks to all who took the time to respond to this Linux newbie.  Special thanks to the Developer for providing me with the solution.  I really appreciate you all!

-- Manny

**Comment by theVakhovskeIsTaken** [comment]
> > Alright, so.
> > 
> > run: sudo pacman -Rdd linux-firmware && sudo pacman -S linux-firmware-neptune && sudo mkinitcpio -P
> > 
> > That'll should install all of the Deck related blobs
> 
> theVakhovskeIsTaken:
> Thank you SO much!  That did the trick!  So happy that now I can install Batocera on it and have SteamOS running on my MicroSD card if I choose.  I have the best of both worlds.
> 
> Since you are the Developer of this, I'm curious, whether this will eventually be baked into the official Holoiso image so that we won't have to enter those commands?  I plan to do a tutorial in the near future about this for my channel and I'm curious whether this will be a future and permanent requirement to get sound on the Steam Deck.
> 
> In either case, thanks to all who took the time to respond to this Linux newbie.  Special thanks to the Developer for providing me with the solution.  I really appreciate you all!
> 
> -- Manny

Sure it will! Most of the "non-generic" re-implemented components already have a check whether it's running/installing on Steam Deck, so is gonna be installer
