### ISSUE TITLE
 Playing games on a 4k TV, the resolution is adjusted to 4k, or 1080 or other resolutions, there will be black borders on both sides of the screen, does anyone know how to solve it? Many thanks

### ISSUE THREAD

**Issue by VGON7** [holoiso-eol/holoiso#517]
Playing games on a 4k TV, the resolution is adjusted to 4k, or 1080 or other resolutions, there will be black borders on both sides of the screen, does anyone know how to solve it? Many thanks

**Comment by TheFlagCourier** [comment]
By black borders, do you mean [_overscan_](https://en.wikipedia.org/wiki/Overscan) compensation? Or that black borders are added on top of the image? Or that the rendered display is squished into an odd aspect ratio?
