### ISSUE TITLE
Can't adjust the resolution when running non-steam games

### ISSUE THREAD

**Issue by VGON7** [holoiso-eol/holoiso#518]
Can't adjust the resolution when running non-steam games

**Comment by AaronBaird1** [comment]
switch to beta. i dont know if that works in holo since im not running it right now but steam just added that feature on the deck

**Comment by VGON7** [comment]
> switch to beta. i dont know if that works in holo since im not running it right now but steam just added that feature on the deck

thanks,it works!

**Comment by theVakhovskeIsTaken** [comment]
![IMG_20220925_144129_947.jpg](https://user-images.githubusercontent.com/97450182/192141568-6d2270a6-eb10-4b14-90c4-eef41fad4704.jpg)

Works fine on beta channel, not a HoloISO issue anyways, closing.
