### ISSUE TITLE
TDP limiting doesn't work

### ISSUE THREAD

**Issue by pett-j** [holoiso-eol/holoiso#52]
I am using the Ayaneo Pro with the 4800U, but the slider does nothing. But clock frequency slider does work.

Gamescope also shows the wrong percentage for the GPU usage.

**Comment by theVakhovskeIsTaken** [comment]
Hmmmm.
Can you run `sudo pacman -S upower vpower cpupower`?

**Comment by pett-j** [comment]
They are installed and up to date, but no change after reinstalling a rebooting.

**Comment by pett-j** [comment]
The issue is still there, any suggestions?

**Comment by fruitchewy** [comment]
Seeing this issue as well. I didn't expect it to function in the first place, but since the readme specifies that TDP adjustment works and it's still an AMD platform it would be cool to see it working.
