### ISSUE TITLE
[Report] Updated readme

### ISSUE THREAD

**Issue by nijahplays** [holoiso-eol/holoiso#522]
New Ventoy flasher update dropped with support for HoloISO

Please update the readme!

**Comment by ChaosBlades** [comment]
Here are the release notes.
https://www.ventoy.net/en/doc_news.html

> 4. Add support for HoloISO. ([#1644](https://github.com/ventoy/Ventoy/issues/1644))

These issues can also be closed.
https://github.com/theVakhovskeIsTaken/holoiso/issues/366
https://github.com/theVakhovskeIsTaken/holoiso/issues/339
https://github.com/theVakhovskeIsTaken/holoiso/issues/98
https://github.com/theVakhovskeIsTaken/holoiso/issues/2 (This one is also requesting Rufus support)

**Comment by haldi4803** [comment]
Nice!
