### ISSUE TITLE
[Report]Aya neo Air Home Button  not working

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#523]
There is no button that can be used as the home button on the Aya Neo Air.
In Aya Fe, pressing the H button works as a home button, but in Aya Neo, pressing the 'Aya' button does not work as a home button.
Is there any way to solve this??

**Comment by EricFL1998** [comment]
you need to install handyGCCS,a fix for ayaneo air, it's not a holoiso problem.

**Comment by JongAnYoo** [comment]
> 

thank you. solved it.
