### ISSUE TITLE
Black screen in DirectX and Vulkan based games on GPD Win 3

### ISSUE THREAD

**Issue by Sumechoo** [holoiso-eol/holoiso#528]
## Your Issue:
```
It's just an assumption for now, but it looks like there is a problem with DX and Vk based games. Everytime I trying to run one of them I getting the black screen without any output from a gamescope. Only output I recieve is just a sound. Also tried a valheim and it runs well when I choose to play it through the OpenGl, but with the Vulkan the result is the same as for other games.
```

## Your device's full specs
```
CPU: Core i5 1135g7
GPU: Intel Xe 80eu
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220921.1733
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
clean install from latest iso of github releases and then updated it with system settings
```

**Comment by norbertbonnici** [comment]
Seconded, portal works from desktop Experience for some reason. Any fixes would be appreciated.

**Comment by deftdawg** [comment]
I have a an intel 1165g7, if I turn on FSR games go black before mangohud shows up... If I turn it off they're ok, not sure if you have the same thing.

As for Valheim, that one is Linux native, yes? If so, FSR wouldn't be applied to it...
