### ISSUE TITLE
Bluetooth not working in SD UI on Boop (snapshot 2)

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#53]
Worked perfectly on snapshot 1, now doesn't work in SD UI on snapshot 2.

Enabling bluetooth works but it doesn't show any devices in the menu.

**Comment by theVakhovskeIsTaken** [comment]
Pretty strange, works for me fine on RTL8222CE.

Try running sudo systemctl enable bluetooth

**Comment by aleksasiriski** [comment]
Had to replug the bluetooth adapter. Works now.
