### ISSUE TITLE
[Report] How can I update the nvidia proprietary drivers?

### ISSUE THREAD

**Issue by iMonZ** [holoiso-eol/holoiso#531]
Hey, How can I update the proprietary drivers. 
Or are they updated automatically?
HoloISO installed 5.15.57 but the latest are 515.76

**Comment by Frostyman758** [comment]
You're really not supposed to, it'll brick the driver's and stop them from working. Unless you want to have it not work, just wait for the kernel to be updated, and then you can update drivers

**Comment by iMonZ** [comment]
> You're really not supposed to, it'll brick the driver's and stop them from working. Unless you want to have it not work, just wait for the kernel to be updated, and then you can update drivers

I understand that. But how can I then update the drivers?

**Comment by grimlokason** [comment]
You can choose the arch way ( via pacman ), or the nvidia way ( from their website ), but you should not wait for support here after that ^^'

if i was you, i'll wait them to be integrated in the holo's repo.

If you want to learn you should not use a prepackaged distro like holo, but an official one. ( arch, gentoo, ubuntu ( kof kof kof ) ... )

**Comment by Grimish-ng** [comment]
A load of nonsense - not being "supposed to". 

YOu can play around with them. Sort of the point of open source in general - Having it YOUR way. Now foreword - Personally, I have absolutely 0 issues with switching to and from AMD, hybrid, to dedicated nvidia on my laptop. etc. Thats not always the case. I woudl also like to stress that the beta nvidia open drivers have 0 support on laptops right now, they won't be ready for awhile - unless you are brave don't use them. Stick with proprietary.

So before you install or remove any drivers - make sure you still have a backup display output. If you have not done this before I would stick with the above advice and be cautious. This stuff can be frusterating for anyone getting familiar with it experienced or not. 

grimlokason is correct in the their assessment. Summing it up I would recommend simply not doing it unless you are learning on another system altogether to get familiar with how it works.

**Comment by grimlokason** [comment]
And if you Really want to play with holoiso, you need to learn how to chroot to restore if you break something,
You also need to learn how the installation is done ( by reading the scripts : https://github.com/theVakhovskeIsTaken/holoiso-install-script )

**Comment by jurassicjordan** [comment]
be weary that the nvidia driver update can break things for KDE depending on hardware. (rtx cards are fine but gtx 1660s black screen)

**Comment by sciroccogti82** [comment]
I would not recomend it since you currently cant update grub on holoiso.

**Comment by Grimish-ng** [comment]
A blank screen is not the end of the world and more than likely fixable. Same thing with grub. Honestly just compile everything from source once you get your install done. Things will behave better, cooler, faster, inclusing the newer 520.56 driver for nvidia. Yes you can update everything, patch or downgrade. Just got to know how to do it.
