### ISSUE TITLE
Can't install on nvme

### ISSUE THREAD

**Issue by michaelkocian** [holoiso-eol/holoiso#532]
## Your Issue:
```
Cannot run the installment when my Samsung 980 1TB SSD is plugged into the NVMe slot.
Installation is not possible even on a different disk. The installation hangs infinitely just after the image.

If I unplug the NVMe SSD and install it on a SATA HDD everything works. But when I reconnect the NVMe it won't start.
Windows can be installed on the NVMe SSD flawlessly.
```

![20221003_213345](https://user-images.githubusercontent.com/50811306/193663683-45f77f78-0f09-48b6-80db-c69d1a7f1fd4.jpg)

## Your device's full specs
```
https://www.acer.com/ac/en/MY/content/model/DT.BH4SM.001

CPU: Intel n6005
GPU: Intel UHD
SSD: Samsung 980 1TB SSD disk M.2 (PCIe 3.0 4x NVMe)
```

## Have you updated your installation recently?
```
Clean install version 3.2
```

## Last note
```
The windows installation doesn't show UEFI prefix in the boot manager, nor the SSD name. Can that be a lead?
```
![20221003_214310](https://user-images.githubusercontent.com/50811306/193665066-0e7a071e-683f-40b4-9d67-1bece8146660.jpg)

**Comment by b-m-f** [comment]
Fastboot and SecureBoot disabled?

**Comment by michaelkocian** [comment]
Yes, both are turned off.

**Comment by toxuin** [comment]
is your SATA controller in RAID mode? I had to switch mine (Dell Precision 3620) into AHCI before my nvme drive would even show up.

**Comment by michaelkocian** [comment]
It is in AHCI as fas as I can tell.
![20221015_111616](https://user-images.githubusercontent.com/50811306/195978997-157ff0f5-2cd6-46c3-92ee-e4c7b2fad638.jpg)
