### ISSUE TITLE
I want to know the principle of holoiso and steamos, and why steamos cannot be started on a normal computer. Because I used my friend's steam deck's hard disk to insert into my computer, but it could not be started

### ISSUE THREAD

**Issue by strongonion** [holoiso-eol/holoiso#533]
I want to know the principle of holoiso and steamos, and why steamos cannot be started on a normal computer. Because I used my friend's steam deck's hard disk to insert into my computer, but it could not be started

**Comment by grimlokason** [comment]
steam deck is an optimized linux dedicated to a specific hardware..
If you want to learn how it work and why it does boot, you'll need to learn how kernel work. ( choosing option, compiling, installing, booting... ) and installing 3rd party drivers like nvidia's binary.

**Comment by Grimish-ng** [comment]
You can take a precompiled arch kernel and use most of them while installing valves packages for sddm, mesa, X, Wayland, etc and get it to work. This doesnt work well but it is workable. How do i know? I played around with it alot before holoiso out of curiosity. The problem primarily is the directory structure and how steamos lays everything down vs a default arch installation.
