### ISSUE TITLE
The game controller has no response on aokzoe

### ISSUE THREAD

**Issue by Gawah** [holoiso-eol/holoiso#534]
## Your Issue:
 The game controller has no response on aokzoe，but can recognize it. 
IdVendor : 0x045e
IdProduct : 0x028e
Name : Microsoft X-Box 360 pad
In systemsetting I can see the game controller device:
![IMG_0503](https://user-images.githubusercontent.com/105637287/194000221-217d9b8f-cbdc-4b62-a9e1-ad055ca88f9a.PNG)
But when I operate the joystick, the value does not change

## Your device's full specs
```
CPU: Amd Ryzen 7 6800u
GPU: Radeon 680M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220921.1733
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
yes
```

**Comment by theVakhovskeIsTaken** [comment]
Have you tried kernel 5.18?

**Comment by Gawah** [comment]
> Have you tried kernel 5.18?

yes.  It still has problems.

**Comment by theVakhovskeIsTaken** [comment]
> > Have you tried kernel 5.18?
> 
> yes.  It still has problems.

Just to confirm, does it work on bare Arch Linux?

**Comment by Gawah** [comment]
ok, I'll try it.  And another problem is that the orientation is 180 degrees upside down in gamescope. My product name is “AOKZOE A1 AR07”.

**Comment by danyi** [comment]
Yes.

I'm an AOKZOE A1 AR07 just like you

I have the same problem as you

I have the same problem with other Linux

I think we need an official driver for the handle

**Comment by danyi** [comment]
Driver info https://linux-hardware.org/?probe=7ac647f707

**Comment by danyi** [comment]
https://linux-hardware.org/?id=usb:045e-028e
The device is supported by kernel versions 2.6.26 and newer according to the LKDDb

**Comment by danyi** [comment]
The screen flips 180° in game mode on aokzoe has been resolved
https://github.com/theVakhovskeIsTaken/holoiso/issues/536
but gamepad drive problem I've tried a lot of third party drives it didn't work out
It seems the only hope is that officials will provide the drive
Because they customize the gamepad part

**Comment by ruineka** [comment]
> The screen flips 180° in game mode on aokzoe has been resolved
> https://github.com/theVakhovskeIsTaken/holoiso/issues/536
> but gamepad drive problem I've tried a lot of third party drives it didn't work out
> It seems the only hope is that officials will provide the drive
> Because they customize the gamepad part
> 

Did you still need a fix for this? I don't have an Aokzoe so I'd need your assistance with testing to sort out these sorts of issues, but my primary focus is to get handhelds like this better supported.

**Comment by danyi** [comment]
aokzoe has too many questions
aokzoe official attitude is also very bad
aokzoe went back on what she had officially promised
So I returned the machine
aokzoe's gamepad is still not working properly

**Comment by ruineka** [comment]
> aokzoe has too many questions
> aokzoe official attitude is also very bad
> aokzoe went back on what she had officially promised
> So I returned the machine
> aokzoe's gamepad is still not working properly

Darn, okay. I'm sorry to hear about the bad experience. :(

**Comment by Gawah** [comment]
Due to quality problems, I returned the aokzoe too.
 I have pre-ordered onexplayer mini pro. If it has the same issue, I will provide feedback.

**Comment by ruineka** [comment]
> Due to quality problems, I returned the aokzoe too.
>  I have pre-ordered onexplayer mini pro. If it has the same issue, I will provide feedback.

Sounds good. If you run into issues just report them and I'll likely see them.

**Comment by Gawah** [comment]
> > Due to quality problems, I returned the aokzoe too.
> > I have pre-ordered onexplayer mini pro. If it has the same issue, I will provide feedback.
> 
> Sounds good. If you run into issues just report them and I'll likely see them.

OK. I will.Thank you very much.
