### ISSUE TITLE
The screen flips 180° in game mode on aokzoe 

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#536]
The screen flips 180° in game mode on aokzoe 
CPU: Amd Ryzen 7 6800u
GPU: Radeon 680M
My product name is “AOKZOE A1 AR07”
![image](https://user-images.githubusercontent.com/1498746/194061135-e1060c32-0e41-4ec0-bdbe-bf83011c8f07.png)

**Comment by Gawah** [comment]
I found out how they repaired the rotation of oxp mini, which is also effective for aokzoe. opened usr/bin/gamescope-session with KWrite, and found line 186, add string": AOKZOE A1 AR07" at the end of OXP_LIST, or you can define an AOK_ LIST to fix it.

**Comment by danyi** [comment]
I found the
I changed the code directly

```
# Define orientation here
DEVICENAME=$(cat /sys/devices/virtual/dmi/id/product_name)
# OXP Devices
OXP_LIST="ONE XPLAYER:ONEXPLAYER 1 T08:ONEXPLAYER 1S A08:ONEXPLAYER 1S T08:ONEXPLAYER mini A07:ONEXPLAYER mini GA72:ONEXPLAYER mini GT72:ONEXPLAYER GUNDAM GA72:ONEXPLAYER 2 ARP23"
# AYANEO AIR Devices
AIR_LIST="AIR:AIR Pro"
# AOKZOE Devices
AOK_LIST="AOKZOE A1 AR07"

if [[ ":$OXP_LIST:" =~ ":$DEVICENAME:"  ]]; then
    DEVICEORIENTATION="--force-orientation left"
elif [[ ":$AIR_LIST:" =~ ":$DEVICENAME:"  ]]; then
    DEVICEORIENTATION="--force-orientation left"
elif [[ ":$AOK_LIST:" =~ ":$DEVICENAME:"  ]]; then
    DEVICEORIENTATION="--force-orientation left"
fi
```

I'm testing it now.

**Comment by danyi** [comment]
I have a new problem
![EE492468E1FD318B0143DE573683CEA9](https://user-images.githubusercontent.com/1498746/194081231-26a62dd8-1234-4312-b6d7-e7e65e787004.jpg)
Security cameras aren't where he's supposed to be

**Comment by Gawah** [comment]
> I have a new problem ![EE492468E1FD318B0143DE573683CEA9](https://user-images.githubusercontent.com/1498746/194081231-26a62dd8-1234-4312-b6d7-e7e65e787004.jpg) Security cameras aren't where he's supposed to be

You can try to play a game. It seems to be normal in the game

**Comment by Gawah** [comment]
![IMG_0518](https://user-images.githubusercontent.com/105637287/194101963-79b86033-88c1-4f8f-8300-5b265f193f00.PNG)

**Comment by danyi** [comment]
https://github.com/theVakhovskeIsTaken/holoiso_install_main/pull/5
https://github.com/theVakhovskeIsTaken/grub-holoiso-pkgbuild/pull/1
https://github.com/theVakhovskeIsTaken/gamescope-steamos-pkgbuild/pull/1

**Comment by Samsagax** [comment]
I think you should PR my gamescope-session git with the device quirk you found. Is cleaner that way. HoloISo can benefit from rebuilding the package then.

**Comment by danyi** [comment]
The problem has been submitted for solution
https://github.com/theVakhovskeIsTaken/holoiso_install_main/pull/5
https://github.com/theVakhovskeIsTaken/grub-holoiso-pkgbuild/pull/1
https://github.com/theVakhovskeIsTaken/gamescope-steamos-pkgbuild/pull/1

**Comment by ruineka** [comment]
@theVakhovskeIsTaken My changes for '--force-orientation' as well as the changes necessary for gamescope to use KMS panel props have been merged into gamescope-git. This should make things easier for everyone! :)

I also got a patch waiting to be merged to the upstream kernel adding alot of these handhelds to the quirk list..The Aokzoe included.
