### ISSUE TITLE
[Report] Desktop mode not working with multiple monitors

### ISSUE THREAD

**Issue by MichailIoannou** [holoiso-eol/holoiso#537]
When trying to enter desktop mode while having 3 monitors connected I get a black screen. Unplugging all but one fixes this, plugging them afterwards is fine and I can use all 3. Is there any permanent solution other than unplugging display cables with every boot?

I also edited `/etc/sddm.conf.d/autologin.conf` and changed one line to `Session = plasma.desktop` to launch straight into desktop but that also gives me a black screen.

CPU: R5 1600
GPU: RX460
snapshot20220921.1733
deckperience

**Comment by suboxide** [comment]
running in the same problem atm , with a docked steamdeck
