### ISSUE TITLE
How to update Linux kernel version?

### ISSUE THREAD

**Issue by huangsijun17** [holoiso-eol/holoiso#538]
I need to update the Linux kernel to get some hardware drivers. But the latest kernel version I see in pacman is 5.16. How can I upgrade to version 5.17 or higher?

**Comment by Grimish-ng** [comment]
![20221025193340_1](https://user-images.githubusercontent.com/10488887/197907356-5182a058-17c7-4ba6-bbe6-4bf6f2ae6377.jpg)
![20221025193346_1](https://user-images.githubusercontent.com/10488887/197907358-fa4396b5-a349-47f2-a295-46ef6bd795d4.jpg)
You can infact get the latest kernel. Be wary of bugs. For instance anything 6.0.0 and up right now have a change which prevents certain amdgpus from properly launching gamescope.

Can it work on any kernel? For sure but it depends on if and what the issues are and what you want to do to resolve them. Before this fantastici holoiso repo - I had just a butchered arch and valve packages and got it working with actually only a couple of packages from vavle - take that with a grain of salt as they will probably change more over time. Primarily xorg-wayland, those display backend thingies, yada yada.

Whats the solution -  Compile a kernel close to the ones mentioned and apply the functionality you specifically require the kernel to have through the patch process.

As for just an 'upgrade' through pacman... don't think you'll get what you are looking for anytime soon.

**Update: Without much playing around, I've compiled linux-5.15.74 up to linux-5.19.16 and both certainly do boot into the gamepadui with the configuration I used. There appears to be either a problem or too many changes in anything later, for instance kernel 6.0-stable and the 6.1rc1-mainline**

**Update 2: Per the gamescope repository - Any kernel 6.x and up has had a patch pushed that was affecting gamescope. It appears to have been resolved for upstream releases. Just waiting for mainline. https://gitlab.freedesktop.org/agd5f/linux/-/commit/93e28cf81406519622383ae51d6fd183b744ac46** 

**Update 3: Utilizing the associated patch from the above bug found [here](https://patchwork.kernel.org/project/dri-devel/patch/20221024030832.119039-1-samsagax@gmail.com/) I was able to launch gamescope on linux-6.0.3
Steam updates were recently applied lib32-vulkan-radeon-22.2.0_devel.156801.jupiter_22.3.2-2 &  vulkan-radeon-22.2.0_devel.156801.jupiter_22.3.2-2 immediately after booting up. I had to 'downgrade' back to vulkan-radeon-22.2.0_devel.156798.jupiter_22.3.1-1-x86_64.pkg & lib32-vulkan-radeon-22.2.0_devel.156798.jupiter_22.3.1-1-x86_64.pkg**

**Comment by jcfrosty** [comment]
The kernel patch has already made it into the 6.1-rc kernel https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.1-rc4&id=809734c110548dca410fb0cca52e6b1540319f5e

Since the 6.1 kernel is to be the new LTS, its best to aim for this kernel.

**Comment by jcfrosty** [comment]
My internet is really bad as of late so I apologize in advance for flaky connection.

https://wiki.darkremix.net/en/aokzoe/SteamOS-Guide

**Comment by Grimish-ng** [comment]
> My internet is really bad as of late so I apologize in advance for flaky connection.
> 
> https://wiki.darkremix.net/en/aokzoe/SteamOS-Guide

Nice guide!

**Comment by flawpiesammen** [comment]
> > My internet is really bad as of late so I apologize in advance for flaky connection.
> > https://wiki.darkremix.net/en/aokzoe/SteamOS-Guide
> 
> Nice guide!

Very nice guide. I was trying to reference it the other day and I was getting a 502 error. Any other places to find it?

**Comment by Labsdj** [comment]
https://github.com/mikeroyal/Steam-Deck-Guide get guide here
