### ISSUE TITLE
Wireplumber instead of pipewire-media-session

### ISSUE THREAD

**Issue by aleksasiriski** [holoiso-eol/holoiso#54]
I see that you install pipewire-media-session in holoinstall script

Please switch it out for [wireplumber](https://gitlab.freedesktop.org/pipewire/wireplumber)

**Comment by aleksasiriski** [comment]
I should also mention that both pipewire-media-session and wireplumber should have their corresponding system services enabled.

**Comment by theVakhovskeIsTaken** [comment]
Hm, yes i see. I forgot to keep it as wireplumber, probably overlooked when done taking a look at SD recovery image, thanks for heads up!!
[Screenshot_20220508_192743.jpg](https://user-images.githubusercontent.com/97450182/167305632-0026ac4f-979e-4d38-b8be-a9507824e527.jpg)

**Comment by aleksasiriski** [comment]
Also, pls change the first line of every script you use from `#!/bin/zsh` to `#!/bin/sh`

In addition, you could change `wget -q --spider http://google.com` to `wget -q --spider https://archlinux.org`
