### ISSUE TITLE
Black bars in gaming mode 

### ISSUE THREAD

**Issue by MaceKane** [holoiso-eol/holoiso#541]
Even when I set it to a native resolution black bars keep showing up on the right and left side of my screen. They also only show up when a game launches. 
My best guess is that it's being forced to display as 16:10. Any solutions?

![20221009_211939](https://user-images.githubusercontent.com/114621017/194788568-56c2acfb-72b8-478e-bcf1-3b713ffe3cd2.jpg)

**Comment by danyi** [comment]
You can try changing the resolution of 97 lines to match your screen
[gamescope-session](https://github.com/theVakhovskeIsTaken/gamescope-steamos-pkgbuild/blob/master/gamescope-session)
You can see the gamescope-session instructions here
https://github.com/Samsagax/gamescope-session
