### ISSUE TITLE
Free Space Selection while installing[Report]

### ISSUE THREAD

**Issue by KaanAlper** [holoiso-eol/holoiso#542]
## Your Issue: 
```
While i installing steam os, it wants to select install partition, i selected my SSD and it says Erase everything or install in Free Space
İ select free space ( İ make 50gb free space before install) and it's dedecting automatically but i dedecting wrong free space (1035 kb etc.)
```

## Your device's full specs
```
CPU: i5 10400f
GPU: MSI RX5500 XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type: 
```

```

## Have you updated your installation recently?
```
```

**Comment by Hexer-7** [comment]
You have to keep 50gb at least from end of the disk, if you are using laptop maybe there is recovery partitions in the end of disk.
