### ISSUE TITLE
Not Dedecting USB wifi adapter

### ISSUE THREAD

**Issue by Fazzuliyat** [holoiso-eol/holoiso#546]
## Your Issue:
i tired to use my wifi adapter to download the os but it did'nt dedect my USb adapter i tried using 3 different adapter but still no success so i tried to install the OS with ethernet on my laptop then i used that installed HOLOISO HDD on my main PC  '' thinking now the wifi will work '' but still so responce from any USB adapter. ANY solution?  AND yes i tried both HOLO-ISO and NEPTUNE-ISO and both didnt work with my USB wifi.

## Your device's full specs
```
CPU: intel i3 10100f
GPU: AMD RX 580 OC 

 
## Installation Type? 
STEAM OS HIGHER COMPATIBLITY
```

**Comment by lgcavalheiro** [comment]
What's your wifi adapter? How is it identified as in the system (using `sudo lsusb`)?
