### ISSUE TITLE
Is it possible to install holoiso on a partition and not the whole drive ?

### ISSUE THREAD

**Issue by Ta2b** [holoiso-eol/holoiso#55]
All is in the title, i don't know if this is the best place to ask it. (sorry if its not)
If its not possible right now, is it possible to add this function ?
(sorry for my bad english)

**Comment by lavilao** [comment]
this please

**Comment by aleksasiriski** [comment]
You can install holoiso on the whole drive then after install use GParted or something to resize the holoiso's partion and then use the left over space that you make however you like to use it.

So if you want to dual boot, install holoiso first then resize partition and install the second OS.

**Comment by JongAnYoo** [comment]
I implemented Windows 11 and SteamOS multiboot.

After installing Windows 11 first, partition the C drive.

Then, I opened the holoinstall file and changed the root partition information to the new partition path.

And after installing with holoinstall, copy the Microsoft efi file to the efi partition (backed up in advance) and add the Window 11 menu to the grub.cfg file.

https://youtube.com/shorts/OTIiWAY-Z54?feature=share

**Comment by Ta2b** [comment]
> You can install holoiso on the whole drive then after install use GParted or something to resize the holoiso's partion and then use the left over space that you make however you like to use it.
> 
> So if you want to dual boot, install holoiso first then resize partition and install the second OS.

okay but for that, i have to install holoiso first and i'll lose all my data. I want to keep my windows 10 dual boot with all my data... but thanks anyway

**Comment by Ta2b** [comment]
> I implemented Windows 11 and SteamOS multiboot.
> 
> After installing Windows 11 first, partition the C drive.
> 
> Then, I opened the holoinstall file and changed the root partition information to the new partition path.
> 
> And after installing with holoinstall, copy the Microsoft efi file to the efi partition (backed up in advance) and add the Window 11 menu to the grub.cfg file.
> 
> https://youtube.com/shorts/OTIiWAY-Z54?feature=share

Your answer seems interesting, but i didnt really understand. You said that you had windows 11 partition on drive (like me with windows 10) and you managed to dual boot with holoiso (without erasing all the drive) by "open the holoinstall file and change the root partition information to the new partition path". I didnt understand this part... sorry but can you explain more ?

**Comment by lavilao** [comment]
he basically edit the installer config file so that instead of installing on ej sda (hard drive) it installs on sda1 (a partition)... I think
