### ISSUE TITLE
How to change resolution in game mode?

### ISSUE THREAD

**Issue by ArcheyChen** [holoiso-eol/holoiso#550]
Steam Deck is a 720P device, and the game running in game mode will set the resolution at 720P.

But I'm running holoiso on a 1080p laptop, and 720p looks blurry.

My game for testing is TombRaider, and I can't change the resolution, it just fix in 720p.

any way to change resolution?

**Comment by MaceKane** [comment]
You go to the games properties menu and change the resolution from default to either native or 1080p. I hope that helps.

**Comment by ArcheyChen** [comment]
> You go to the games properties menu and change the resolution from default to either native or 1080p. I hope that helps.

Thanks, it works!
