### ISSUE TITLE
Stuttering and slow deck ui with install on NVIDIA 2080ti system

### ISSUE THREAD

**Issue by FoulSpud** [holoiso-eol/holoiso#552]
I am getting a ton of lagging and flickering of you elements when installing this os on my machine. Anyone else find a solution for this? I made sure to install the nvidia version of this os. I don't notice this when I'm desktop mode. 

The specs are. 

5950x
Gskill 32gb ram
evga 2080 ti
Samsung 970 pro ssd 1tb

**Comment by SaulGoodman1337** [comment]
same here with a 1080. i thinks its not ready for nvidia... :(

**Comment by ghost** [comment]
Also have this issue with a 3080ti, 4k 144hz display.

**Comment by Frostyman758** [comment]
Hi, this is both an Nvidia and valve issue.. Nvidia is still lacking certain Wayland elements that are required for the UI to function. In addition, Valve hasn't updated the UI to have proper GPU acceleration for Nvidia or for it to run without "disable layers" should that be fixed, it'll run perfectly.
