### ISSUE TITLE
[Report] Blank screen after booting (after install)

### ISSUE THREAD

**Issue by StupidRepo** [holoiso-eol/holoiso#553]
### Your Issue:
```
When I boot to the hard drive, it just shows a small white horizontal square (like the one you see in Terminal/Command Prompt)

That's it. No GRUB, nothing.
The installer didn't say anything bad had happened.

Ubuntu 22.10 runs fine on it. I ran the GUI installer twice to make sure it wasn't just the install but that didn't work either.
```

## Your device's full specs
```
CPU: Intel i5
GPU: AMD Radeon HD 6770M (512MB vRAM)
Device Model: Apple iMac Mid-2011
```

### Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Latest ISO as of post date.
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
...
```

### Your installation type:
```
deck-experience
```

## Have you updated your installation recently?
```
No
```

**Comment by theVakhovskeIsTaken** [comment]
I think you should read Readme part about specs once again.

**Comment by b1bradders** [comment]
I did but I wasn't sure if it was supported as it did show AMD. I had a feeling that it wasn't supported though. Oh well. Nothing ventured, nothing gained.
