### ISSUE TITLE
[SOLVED] Bluetooth headset no HSP/HPF profiles

### ISSUE THREAD

**Issue by augustoicaro** [holoiso-eol/holoiso#554]
Hello community,

Today I spent a few hours trying to fix my Bluetooth headset that I wasn't able to use the microphone. I tried many "solutions" and in the end, none of them worked. But in fact, wasn´t a problem with `bluez`, `pipewire`, or `wireplumber`, was just a default configuration that disable HSP/HPF profiles.

This configuration is located in `/usr/share/wireplumber/bluetooth.lua.d/60-bluez-disable-headset.lua`. The straightforward solution is to remove this file. But I think this file exists to avoid the headset using the wrong profile since you can't change it in gamescope. But you always can go to desktop mode and change your bluetooth profile.

For desktop users like me, you can remove the file and control the Bluetooth profiles with the package `pavucontrol` (PulseAldio Volume Control).

Now I can enjoy my video calls using my Bluetooth headset microphone :)

**Comment by danyi** [comment]
Let me try it after work. Thanks for sharing
