### ISSUE TITLE
A short list of apps that still don't work in HoloISO

### ISSUE THREAD

**Issue by jrcharney** [holoiso-eol/holoiso#556]
It's likely been said before, but it bears repeating, some apps that would work in Arch Linux will not work in HoloISO. And the Arch Linux community will not fix them because they consider HoloISO a derivative of Arch, like Manjaro.

* [ ] Slack - `slack-desktop` from `yay` and `snapd` are are literally unusable, stuck with old setting, some servers won't open.
* [x] FreeCAD - Old PGP signature that won't let the package `jxrlib` run, which is required for FreeCAD to work.

Any other apps that won't work?

**Comment by theVakhovskeIsTaken** [comment]
Cool. That means it doesn't work on Steam Deck _too_

Use flatpak version, if available :)

**Comment by jrcharney** [comment]
No luck. Tried installing `slack` with `flatpak` as root and as regular user and all the app did was do nothing. Unless there is something I need to remove from a previous install that is gumming up everything.

**Comment by jrcharney** [comment]
Some good news: FreeCAD installed with Flatpak.
