### ISSUE TITLE
[Report]No audio on fresh SteamDeck install

### ISSUE THREAD

**Issue by mindtheegab** [holoiso-eol/holoiso#557]
## Your Issue:
```
audio does not work on steamdeck
```

## Your device's full specs
```
steamdeck
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220921.1733

```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by taojishou** [comment]
sudo pacman -Rdd linux-firmware && sudo pacman -S linux-firmware-neptune && sudo mkinitcpio -P

**Comment by mindtheegab** [comment]
this works but i dont think it should be manually done by users especiall since the steamdeck is mentioned in the live usb boot one would expect everything to work

**Comment by stvweb02** [comment]
Is HoloISO still working for you on steam deck? I am getting a black screen after install. It used to work for me before the issues started with HoloISO
