### ISSUE TITLE
Deck UI showing on VR headset when it is plugged in

### ISSUE THREAD

**Issue by eduard-hdt** [holoiso-eol/holoiso#56]
Hi, do you have any recommendations on how to set a default display to avoid this issue? And is there a way to mirror the deck ui from my monitor to the tv?

using Boop snapshot2

And maybe it is relevant:
I am using RX 5700XT and Ryzen 5 3600

**Comment by theVakhovskeIsTaken** [comment]
Hey there!
DeckUI's docking feature is pretty much toggled on any first external monitor it sees, so no, its not possible to mirror it somewhere else unless Valve decides to do so :)
