### ISSUE TITLE
[Report] after install can't boot. 

### ISSUE THREAD

**Issue by Bchauncey0831** [holoiso-eol/holoiso#560]
## Your Issue: Unable to fully boot
```
*type your problem here*
```
Upon booting the laptop, I get the usual screen, I have tried normal booting into steam OS and EVERY advanced boot option, none will load, I get nothing but a black screen and that's IF it gets past the "loading initial Ramdisk.
## Your device's full specs
```
CPU: AMD A8 quad core 
GPU: AMD Radeon R5 
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`): latest release
```


## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
The installation updated itself when I loaded the live USB and started the install. 
```

**Comment by nagybal** [comment]
I am facing the same issue. Were You able to find a solution?

**Comment by prplwtf** [comment]
Currently having the same issue.
