### ISSUE TITLE
[Report] package yay missing.

### ISSUE THREAD

**Issue by oblende** [holoiso-eol/holoiso#565]
## Your Issue:
```
The package 'yay' appears to be missing from the repository. Error message reads as: warning: cannot resolve "yay", a dependency of "holoiso-main"
```

## Your device's full specs
```
System: Dell Precision T3600
CPU: Intel Xeon e5 1603 2.8 Ghz
GPU: Nvidia Quadro K2200
Memory: 4GB DDR 3 1333 Mhz
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Holoiso 3.4 Final
```

## Have you updated your installation recently?
```
N/A
```

**Comment by gsaker** [comment]
Having the same problem here. Let me know if I can help in any way. Maybe something's been removed from a repo?

**Comment by zLeqitEclipse** [comment]
Same here

**Comment by efrej** [comment]
I get the same error!

Hardware:
HP Elitedesk 800
CPU: Intel Core i5 8500 2.2 GHz (Gen 8)
Intel UHD 630
Memory: 8 GB

![yayerror](https://user-images.githubusercontent.com/37534634/198034400-1707097d-c761-4fc2-b13d-6f85e6632114.jpg)

**Comment by zLeqitEclipse** [comment]
Just tried it again but, still no luck.

**Comment by awe444** [comment]
Getting the same error shown in the above screenshot when attempting a fresh install of full-experience.

**Comment by zLeqitEclipse** [comment]
Okay, there's been an official statement on the Telegram Channel.
I'm going to close this issue since we apparently just need to wait.

**Comment by zLeqitEclipse** [comment]
There's just been a new post on the Telegram Channel. Looks like we just need to wait.

**Comment by efrej** [comment]
Ziyan from the Telegram Discussion suggested the following fix which worked for me!

run konsole in the installation,
type in konsole: sudo nano /etc/pacman.conf
add the following to the botton of the script and save it (CTRL + S)

[andontie-aur]
Server = https://aur.andontie.net/$arch
SigLevel = Never

then run the install again

**Comment by zLeqitEclipse** [comment]
> Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> 
> 
> run konsole in the installation,
> 
> type in konsole: sudo nano /etc/pacman.conf
> 
> add the following to the botton of the script and save it (CTRL + S)
> 
> 
> 
> [andontie-aur]
> 
> Server = https://aur.andontie.net/$arch
> 
> SigLevel = Never
> 
> 
> 
> then run the install again

Thx it worked for me too!

**Comment by sunhotblaze** [comment]
> Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> 
> [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> 
> then run the install again

Thank you. Very useful

**Comment by MrC1065** [comment]
> Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> 
> [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> 
> then run the install again

Doesn't work for me, I get a different error message very early in the installation process. Doesn't even make it to the part where you create usernames and passwords.

**Comment by zLeqitEclipse** [comment]
> > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> > 
> 
> > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> 
> > 
> 
> > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> 
> > 
> 
> > then run the install again
> 
> 
> 
> Doesn't work for me, I get a different error message very early in the installation process. Doesn't even make it to the part where you create usernames and passwords.

Maybe create a new issue and provide some details?

**Comment by MrC1065** [comment]
> > > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> > 
> > 
> > > 
> > 
> > 
> > > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> > 
> > 
> > > 
> > 
> > 
> > > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> > 
> > 
> > > 
> > 
> > 
> > > then run the install again
> > 
> > 
> > Doesn't work for me, I get a different error message very early in the installation process. Doesn't even make it to the part where you create usernames and passwords.
> 
> Maybe create a new issue and provide some details?

I'm just gonna wait until this gets resolved without needing a workaround. I'll just use Windows for now.

**Comment by nagybal** [comment]
> Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> 
> [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> 
> then run the install again

This does not work for me. SteamOS installs but when I try to boot from it, I make my choice at the boot menu and then just a black screen. System is not frozen. I can access the command line but seems to be the graphic driver did not install properly. I am unsing an AMD GPU? Does anyone know when the original server will be fixed?

**Comment by zLeqitEclipse** [comment]
> > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> 
> > 
> 
> > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> 
> > 
> 
> > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> 
> > 
> 
> > then run the install again
> 
> 
> 
> This does not work for me. SteamOS installs but when I try to boot from it, I make my choice at the boot menu and then just a black screen. System is not frozen. I can access the command line but seems to be the graphic driver did not install properly. I am unsing an AMD GPU? Does anyone know when the original server will be fixed?

I've had the same issue after I've fixed the yay-git bug.

I cloud try to explain a fix to you if I'm back home.

It btw has something to do with the latest Vulkan-Radeon.

**Comment by zLeqitEclipse** [comment]
> > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> > then run the install again
> 
> This does not work for me. SteamOS installs but when I try to boot from it, I make my choice at the boot menu and then just a black screen. System is not frozen. I can access the command line but seems to be the graphic driver did not install properly. I am unsing an AMD GPU? Does anyone know when the original server will be fixed?

Try this:

1. Boot up until you're at the black screen, then press ctrl+alt+F3 to get into tty and login.
2. Type in `wget https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/os/x86_64/vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
3. Type in `sudo pacman -U vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
4. Type in `reboot`

After the Reboot the SteamUI should come up, at least this was in my case. (Radeon Vega 8)

**Comment by nagybal** [comment]
> 

I can't believe I was able to type in the long address and package name on the first try :-)

It worked. Thank You! Now question: what will fix my repos? Which repo I need to update?

**Comment by nagybal** [comment]
> > > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> > > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> > > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> > > then run the install again
> > 
> > 
> > This does not work for me. SteamOS installs but when I try to boot from it, I make my choice at the boot menu and then just a black screen. System is not frozen. I can access the command line but seems to be the graphic driver did not install properly. I am unsing an AMD GPU? Does anyone know when the original server will be fixed?
> 
> Try this:
> 
> 1. Boot up until you're at the black screen, then press ctrl+alt+F3 to get into tty and login.
> 2. Type in `wget https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/os/x86_64/vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
> 3. Type in `sudo pacman -U vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
> 4. Type in `reboot`
> 
> After the Reboot the SteamUI should come up, at least this was in my case. (Radeon Vega 8)

I can't believe I was able to type in the long address and package name on the first try :-)

It worked. Thank You! Now question: what will fix my repos? Which repo I need to update?

**Comment by zLeqitEclipse** [comment]
> > > > Ziyan from the Telegram Discussion suggested the following fix which worked for me!
> > > > run konsole in the installation, type in konsole: sudo nano /etc/pacman.conf add the following to the botton of the script and save it (CTRL + S)
> > > > [andontie-aur] Server = https://aur.andontie.net/$arch SigLevel = Never
> > > > then run the install again
> > > 
> > > 
> > > This does not work for me. SteamOS installs but when I try to boot from it, I make my choice at the boot menu and then just a black screen. System is not frozen. I can access the command line but seems to be the graphic driver did not install properly. I am unsing an AMD GPU? Does anyone know when the original server will be fixed?
> > 
> > 
> > Try this:
> > 
> > 1. Boot up until you're at the black screen, then press ctrl+alt+F3 to get into tty and login.
> > 2. Type in `wget https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/os/x86_64/vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
> > 3. Type in `sudo pacman -U vulkan-radeon-22.2.0_devel.152974.jupiter_22.2.1.3-1-x86_64.pkg.tar.zst`
> > 4. Type in `reboot`
> > 
> > After the Reboot the SteamUI should come up, at least this was in my case. (Radeon Vega 8)
> 
> I can't believe I was able to type in the long address and package name on the first try :-)
> 
> It worked. Thank You! Now question: what will fix my repos? Which repo I need to update?

I'm also not sure about that one, but it also didn't bother me very much. As already said in the Telegram Channel, we are expecting a big update to the AL Base, so i think all left to do is just wait at this point.

**Comment by nagybal** [comment]
I was messing with my grub menu and I thought I get the black screen because I did something wrong... Valve can now expect some hundreads of GB unnecessary traffic on their servers, coming from game downloads. It's their own fault!

**Comment by sam0th** [comment]
i marked the vulkan-radeon pakage for not updateing in pacman.conf, but steam itself pushes the update and installs without asking. the pakage itself isnt a problem but it depends on llvm 14 and this dependecie cant be resolved. thats why vulkan support breaks with this update and gamescope not longer starts. for me it looks like we need some more spurces and dependecies on that holoiso image to work properly

**Comment by sam0th** [comment]
maybe, just a thought, steam uses it to break all those fake steamdecks, as they dont help th support for original steam deck. log files will get mixed up at steam and make no sense for them.. just a thought, maybe better label it not as steamOS 3.3 but steamOS 3.3 homebrew
