### ISSUE TITLE
[Report] Kernel Panic During Boot After Update

### ISSUE THREAD

**Issue by oblende** [holoiso-eol/holoiso#566]
## Your Issue:
```
After updating through the Steam UI and rebooting the system experiences a kernel panic during the boot sequence and halts.
```

## Your device's full specs
```
System: Dell 790
CPU: Xeon e3 1240 3.3 GHz
GPU: AMD RX 6400 4 GB
Memory: 16 GB DDR 3 1333 MHz
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
HoloISO 3.2
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Day of issue. It appears to be the problem.
```

**Comment by poperigby** [comment]
Are you getting an actual error message? I think I might be having the same issue, but it just freezes at "Verifying installation" for me.

**Comment by oblende** [comment]
It was the full kernel puking to the screen. I was using the console boot
option so I could see what was going on.

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/564#issuecomment-1293738936
