### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by MrC1065** [holoiso-eol/holoiso#567]
Your Issue:
So basically I'm just following the normal installation process for the full Deck experience. Right before I get to the part about graphics cards, however, I get a strange error message:
"warning: cannot resolve "yay", a dependency of "holoiso-main"

There are then several other errors, and eventually the installer simply says my internet connection is unstable and that the installation failed.

Specs:
Pentium G7400
RX 6400
16GB DDR4
ASUS Prime H610 ITX
Samsung 850 EVO 250GB (OS)
Silicon Power 500GB (boot)

Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
Not sure, I just grabbed the latest release and tried installing it.

(Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.

Your installation type:
deckperience

Have you updated your installation recently?
Never done this before.

**Comment by MrC1065** [comment]
![20221026_220435](https://user-images.githubusercontent.com/112527105/198174555-a451c4f0-a117-46d1-ba32-254787076106.jpg)

Here's the full error message. Sorry for the poor quality.

**Comment by EricFL1998** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/565

**Comment by imacmill** [comment]
Confirmed, exact same issue here.

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/564#issuecomment-1293738936

**Comment by ghost** [comment]
Same here. 
Using [efreg](https://github.com/theVakhovskeIsTaken/holoiso/issues/565#issuecomment-1292502332)'s advice solved the issue, which was adding this lines into `/etc/pacman.conf` with root privileges:

`sudo nano /etc/pacman.conf`

in the file, at it's bottom:

```[andontie-aur]
Server = https://aur.andontie.net/$arch
SigLevel = Never
```

and then running the installer again.

**Comment by imacmill** [comment]
> Same here. Using [efreg](https://github.com/theVakhovskeIsTaken/holoiso/issues/565#issuecomment-1292502332)'s advice solved the issue, which was adding this lines into `/etc/pacman.conf` with root privileges:
> 
> `sudo nano /etc/pacman.conf`
> 
> in the file, at it's bottom:
> 
> ```
> Server = https://aur.andontie.net/$arch
> SigLevel = Never
> ```
> 
> and then running the installer again.

The pacman.conf 'fix' worked for me in that it allowed the installer to complete successfully, but the OS completely hangs at startup. Fortunately for me, I had a backup image (Clonezilla) of a fully working HoloISO installation that I restored, and it works fine (just a bunch of junk on it that I had to manually remove...I was hoping to have a fresh install, but no-go, as above).

**Comment by ghost** [comment]
Same also, I get a black screen and keyboard doesn't work so I cannot get vt[1-7].
Do you use same hardware as you used with previous clonezilla image? If it is so, it smells like some misconfiguration on the iso.

> Fortunately for me, I had a backup image (Clonezilla) of a fully working HoloISO installation that I restored, and it works fine (just a bunch of junk on it that I had to manually remove...I was hoping to have a fresh install, but no-go, as above).

Lucky one :)

**Comment by imacmill** [comment]
> Same also, I get a black screen and keyboard doesn't work so I cannot get vt[1-7]. Do you use same hardware as you used with previous clonezilla image? If it is so, it smells like some misconfiguration on the iso.
> 
> > Fortunately for me, I had a backup image (Clonezilla) of a fully working HoloISO installation that I restored, and it works fine (just a bunch of junk on it that I had to manually remove...I was hoping to have a fresh install, but no-go, as above).
> 
> Lucky one :)

Yes, I used the exact same hardware for the image restoration...a Beelink GR9 mini PC.
