### ISSUE TITLE
I made a multi boot of Windows 11 and SteamOS on Ayaneo.

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#57]
I don't know much about Linux, so I spent about two days implementing Windows 11 and SteamOS multi-boot!

I learned a lot about Linux. haha

https://youtube.com/shorts/OTIiWAY-Z54?feature=share

**Comment by Ta2b** [comment]
Can you explain how did you manage to do that please ?

**Comment by theVakhovskeIsTaken** [comment]
PHENOMENAL! This is just beautiful!

**Comment by Ta2b** [comment]
> PHENOMENAL! This is just beautiful!
Shall you explain me please ?

**Comment by JongAnYoo** [comment]
When the time comes, I'll put it together and post it.

**Comment by slaminger** [comment]
i did this by installing steam os first, booting from an SD card using ubuntu, using gparted to split the drive in half, then installed windows to the 2nd

**Comment by FayeSpica** [comment]
Just follow step in this video：https://youtu.be/_6eHHr3b9Ck
note：replace steam os install to holoiso
