### ISSUE TITLE
[Report] jack2 and pipewire-jack in conflict

### ISSUE THREAD

**Issue by kyh96403** [holoiso-eol/holoiso#570]
## Your Issue:
```
First..
yay missing error..
So I try "https://github.com/theVakhovskeIsTaken/holoiso/issues/565"
And then...
jack2 and pipewire-jack in conflict
```

## Your device's full specs
```
CPU: AMD 6800U
GPU:  AMD 6800U
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Deprecated in SteamOS
https://github.com/theVakhovskeIsTaken/holoiso/actions/runs/3338008533
```

![SteamOS](https://user-images.githubusercontent.com/21171837/198559764-14e744dd-4ad8-426c-82a0-efee2fcacc77.jpg)

**Comment by jasonwitty** [comment]
reproduced this today as well building the iso from the latest and after running this fix. https://github.com/theVakhovskeIsTaken/holoiso/issues/565

**Comment by jasonwitty** [comment]
you can bypass this issue by editing line 3 of /usr/bin/holoinstall to

CMD_PACMAN_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --disable-download-timeout --ignore jack,jack2 --overwrite="*")

no promises that you will be able to complete your installation, i ran into issues after installing gpu driver.

**Comment by kyh96403** [comment]
@jasonwitty 
Thanks^^
