### ISSUE TITLE
[Critical Error] [Report] Installation with recent version fails 

### ISSUE THREAD

**Issue by Jason300** [holoiso-eol/holoiso#573]
## Your Issue:
```
i tried to reinstall SteamOS with HoloIso

on the desktop I click the icon to install SteamOS
console opens, does something and than asks me to run it again
when it opens again it asks me about erasing the disk
after that it stops :
"
error: database not found: core-main
error: database not found: core-main
==> ERROR: Failed to install packages to new root

Error: SOmething whent wrong when isntalling base package.
Please make sure you have a stable internet connection!

Press any key to exit .."

same with the SteamOS base version
```

## Your device's full specs
```
I7-7700K
RTX-3070 Ti
Samsung NVME
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
recent
```

## Your installation type:
```
deckperience (full)
```

## Have you updated your installation recently?
```
i tried updating my installed version of SteamOS, but it had dependency issues 
I was keeping it well updated and didnt change anything in those settings, which makes it strange that i got those issues in the first place
```

**Comment by Kreimeier** [comment]
So i got it running by doing the following steps:
First (and i don't know if this is optional, didn't tested it) i added this repo in /etc/pacman.conf:

```
[andontie-aur]
Server = https://aur.andontie.net/$arch
SigLevel = Never
```

This helps to install the necessary package yay, it could work without the repo, but if yay is missing, add this repo, then run the installier again.

Second, i started the installer once to be sure the holoinstall script is up-to-date. Then i modified /usr/bin/holoinstall, after it was updated and did the following changes:

```
Line 4:
CMD_PACMAN_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --disable-download-timeout --overwrite="*")
to
CMD_PACMAN_INSTALL=(/usr/bin/pacman -S --needed --disable-download-timeout --overwrite="*")
```
Just removed the --noconfirm, important in the deck-experience install. This is important for the file conflict between jack2 and pipewire-jack.

When the installer ask which of the packages jack2 or pipewire-jack should be installed, i choose the second option, pipewire-jack.

After that, my installation went successfully and i even got a login screen. Haven't tested it fully, i'm on it right now, but seems to work just fine.

**Comment by Ckk3** [comment]
Unfortunately, this don't work for me, I restart the installation and booted pendrive again and still getting the same error, I tried the full deck experience

**Comment by Kreimeier** [comment]
> Unfortunately, this don't work for me, I restart the installation and booted pendrive again and still getting the same error, I tried the full deck experience

Did you get the same error?

**Comment by Ckk3** [comment]
> > Unfortunately, this don't work for me, I restart the installation and booted pendrive again and still getting the same error, I tried the full deck experience
> 
> Did you get the same error?

Yes, the same error: 

```
error: database not found: core-main
error: database not found: core-main
```

**Comment by BeastRein** [comment]
i tried the fixes, but failed.
however, i got a semi-successful install after removing core-main packages from the holoinstall script
Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system.

**Comment by LinuxSwitch** [comment]
> i tried the fixes, but failed.
> 
> however, i got a semi-successful install after removing core-main packages from the holoinstall script
> 
> Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system. 

Can you explain in detail how did you do that?

**Comment by BeastRein** [comment]
> > i tried the fixes, but failed.
> > however, i got a semi-successful install after removing core-main packages from the holoinstall script
> > Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system.
> 
> Can you explain in detail how did you do that?


i ran
"sudo pacman -S glibc"
and
"sudo pacman -Sy"
then inside of holoinstall
find "pacstrap" and remove the parts separated by spaces that relate to core-main/[stuff]

sorry about the bad description i'm writing this down by memory.

**Comment by LinuxSwitch** [comment]
> > > i tried the fixes, but failed.
> 
> > > however, i got a semi-successful install after removing core-main packages from the holoinstall script
> 
> > > Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system.
> 
> > 
> 
> > Can you explain in detail how did you do that?
> 
> 
> 
> 
> 
> i ran
> 
> "sudo pacman -S glibc"
> 
> and
> 
> "sudo pacman -Sy"
> 
> then inside of holoinstall
> 
> find "pacstrap" and remove the parts separated by spaces that relate to core-main/[stuff]
> 
> 
> 
> sorry about the bad description i'm writing this down by memory.

Yeah I really didnt get it, but thx for the help.

**Comment by Ckk3** [comment]
I'm gonna test this solution later and see whats happen

**Comment by Ckk3** [comment]
> i ran "sudo pacman -S glibc" and "sudo pacman -Sy" then inside of holoinstall find "pacstrap" and remove the parts separated by spaces that relate to core-main/[stuff]
> 
> sorry about the bad description i'm writing this down by memory.


I'm gonna test this solution later and see whats happen

**Comment by LinuxSwitch** [comment]
> > > i tried the fixes, but failed.
> 
> > > however, i got a semi-successful install after removing core-main packages from the holoinstall script
> 
> > > Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system.
> 
> > 
> 
> > Can you explain in detail how did you do that?
> 
> 
> 
> 
> 
> i ran
> 
> "sudo pacman -S glibc"
> 
> and
> 
> "sudo pacman -Sy"
> 
> then inside of holoinstall
> 
> find "pacstrap" and remove the parts separated by spaces that relate to core-main/[stuff]
> 
> 
> 
> sorry about the bad description i'm writing this down by memory.

This worked around that error, The "pacstrap" part is Around line 257 on holoinstall.

But the deckexperience install gives out a error, the barebones manages to install sucefully but doesnt boot

**Comment by Ckk3** [comment]
> LinuxSwitch



> > > > i tried the fixes, but failed.
> > 
> > 
> > > > however, i got a semi-successful install after removing core-main packages from the holoinstall script
> > 
> > 
> > > > Edit: i don't recommend this as a permanent fix, because this is probably removing critical packages from the system.
> > 
> > 
> > > 
> > 
> > 
> > > Can you explain in detail how did you do that?
> > 
> > 
> > i ran
> > "sudo pacman -S glibc"
> > and
> > "sudo pacman -Sy"
> > then inside of holoinstall
> > find "pacstrap" and remove the parts separated by spaces that relate to core-main/[stuff]
> > sorry about the bad description i'm writing this down by memory.
> 
> This worked around that error, The "pacstrap" part is Around line 257 on holoinstall.
> 
> But the deckexperience install gives out a error, the barebones manages to install sucefully but doesnt boot

Well i think that we can only wait

**Comment by Jason300** [comment]
For how long has this error existed?
Or rather, why was it not fixed?

Could we get older versions and try it with those

**Comment by Jason300** [comment]
.

**Comment by Jason300** [comment]
.

**Comment by Jason300** [comment]
reopened (sorry, I have no experience with this)

**Comment by quintin-k** [comment]
Same error on my end as well. Am interested in helping resolve this problem, please let me know any way I can.

**Comment by Ckk3** [comment]
> For how long has this error existed? Or rather, why was it not fixed?
> 
> Could we get older versions and try it with those

yesterday i tried download old versions from github releases but they are all unavaliable, appears a 404 nginx message, i think that the link only works in new versions

**Comment by albertolg** [comment]
same error for me... tried all the suggested solutions but nothing worked

**Comment by isalgueiro** [comment]
Followed all instructions in this thread, but it still failed. So I edited /usr/bin/holoinstall and replaced `core-main`occurrences with `core` and it seems to work now.

BTW I **don´t** use arch, I don´t know what I'm doing here, just saw `core` references in the _Synchronizing databases_ step and tried this out.

**Comment by Kreimeier** [comment]
All my installations worked so far, but they booted normally only on my full AMD systems. I might have missed the information that i build my own image following the instructions of HOLOISO, i included the base-devel package in holoiso/packages.x86_64. Since the boot stick doesn't have enough space for the base-devel package, you might build your own image as well. Maybe give it a try.

**Comment by nagybal** [comment]
I thought the project is back to the "Steam Deck stable channel" and everything is going to be back to normal. I am trying to do a clean install using the HoloISO_Stable_GUI-20220902_1941-x86_64.iso I still get this `error: database not found: core-main
-> ERROR: Failed to install packages to new root` error.
Even if I add the **andontie-aur** repo.

Can someone tell what is happening? What is still the issue we are waiting to be fixed?

**Comment by Kreimeier** [comment]
What i assume is that the db files aren't written in the right location, are corrupt or not written at all. What i found out, is that if you boot the stick first time, no files are under /var/lib/pacman/sync. They are written into this directory when pacman -Sy finished successfully. I don't know for sure, when holoinstall writes the db files into /var/lib/pacman/sync or even if it does it correctly. So what i assume was that certain packages couldn't be installed because the db file wasn't under /var/lib/pacman/sync, it is corrupted or doesn't contain information about certain packages, please provide like more than one line, more like the last 20 or so, if the terminal does not auto closes.

One suggestion is to wait until a new release is available.

The second suggestion would be to copy the db files from stick to installation drive:
`cp /var/lib/pacman/sync/* /var/mnt//var/lib/pacman/sync/`
and then manually run the rest of the script, i assume that this portion of the script fails, so you need to run all of this (just put it in a file and run it, sh "file name"):
```
#!/bin/zsh
CMD_PACMAN_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --disable-download-timeout --overwrite="*")
CMD_PACMAN_UPDATE=(/usr/bin/pacman -Sy)
CPU_VENDOR=$(cat /proc/cpuinfo | grep 'vendor' | uniq | cut -c 13-)
SYSTEM_LOCALE="${SYSTEM_LOCALE:-en_US.UTF-8 UTF-8}"
HOLO_INSTALL_DIR="${HOLO_INSTALL_DIR:-/mnt}"
IS_WIN600=$(cat /sys/devices/virtual/dmi/id/product_name | grep Win600)

while true
        do
                echo "Please choose your current GPU:"
                #echo "1) AMD: Will install Gamescope with Mangohud and FSR support."
                #echo "2) Intel: Will install Gamescope without Mangohud and scaling methods support."
                #echo "3) NVIDIA (1xxx+ only): Will install proprietary drivers and Gamescope with Mangohud and NIR support."
                #read "?Enter your choice here: " HOLO_GPU_TYPE
                HOLO_GPU_TYPE=$(zenity --list --title="Choose your GPU Type" --column="Type" --column="Name" 1 "AMD (Will install Gamescope with Mangohud and FSR support)" \2 "Intel (Will install Gamescope with Mangohud and FSR or NIR support)" \3 "NVIDIA (Will install proprietary drivers and latest gamescope with NIR/FSR and mangohud support)" --width=778 --height=220)
                if [[ "${HOLO_GPU_TYPE}" == "1" ]]; then
                        echo "Installing gamescope for AMD GPUs..."
                        GAMESCOPE_INSTALL=(/usr/bin/pacman -S --needed --overwrite="*" vulkan-radeon lib32-vulkan-radeon holoiso/gamescope mesa lib32-mesa)
                        break
                elif [[ "${HOLO_GPU_TYPE}" == "2" ]]; then
                        echo "Installing gamescope for Intel GPUs..."
                        GAMESCOPE_INSTALL=(/usr/bin/pacman -S --needed --overwrite="*" holoiso/vulkan-intel holoiso/lib32-vulkan-intel mesa lib32-mesa holoiso/gamescope)
                        break
                elif [[ "${HOLO_GPU_TYPE}" == "3" ]]; then
                        echo "Installing gamescope for NVIDIA GPUs..."
                        GAMESCOPE_INSTALL=(/usr/bin/pacman --noconfirm -S --needed --overwrite="*" holoiso/nvidia-utils holoiso/lib32-nvidia-utils holoiso/nvidia-dkms holoiso/opencl-nvidia holoiso/gamescope)
                        break
                else
                        echo -e "You have made an invalid selection, please try again...\n"
                                sleep 2
                                clear
                fi
        done
sleep 1
arch-chroot ${HOLO_INSTALL_DIR} ${GAMESCOPE_INSTALL}
cp /etc/holoinstall/steamos-gamemode.desktop /mnt/home/${HOLOUSER}/Desktop/steamos-gamemode.desktop
arch-chroot ${HOLO_INSTALL_DIR} chmod +x /home/${HOLOUSER}/Desktop/steamos-gamemode.desktop
mkdir ${HOLO_INSTALL_DIR}/etc/sddm.conf.d
echo "[General]\nDisplayServer=wayland\n\n[Autologin]\nUser=${HOLOUSER}\nSession=gamescope-wayland.desktop" >> ${HOLO_INSTALL_DIR}/etc/sddm.conf.d/autologin.conf
mkdir /mnt/home/${HOLOUSER}/Desktop
arch-chroot ${HOLO_INSTALL_DIR} ln -s /usr/share/applications/steam.desktop /home/${HOLOUSER}/Desktop/steam.desktop
arch-chroot ${HOLO_INSTALL_DIR} chown -R ${HOLOUSER}:${HOLOUSER} /home/${HOLOUSER}/Desktop
arch-chroot ${HOLO_INSTALL_DIR} systemctl enable cups bluetooth sddm holoiso-reboot-tracker
arch-chroot ${HOLO_INSTALL_DIR} usermod -a -G rfkill ${HOLOUSER}
arch-chroot ${HOLO_INSTALL_DIR} usermod -a -G wheel ${HOLOUSER}
arch-chroot ${HOLO_INSTALL_DIR} sudo -u ${HOLOUSER} steam
arch-chroot ${HOLO_INSTALL_DIR} ${CMD_PACMAN_INSTALL} flatpak packagekit-qt5 rsync unzip vim
check_download $? "installing flatpak"
arch-chroot ${HOLO_INSTALL_DIR} flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
check_download $? "updating flatpak"
arch-chroot ${HOLO_INSTALL_DIR} echo "recoveryinit" > /root/.bashrc
sleep 1
echo "Installation finished! You may reboot now, or type arch-chroot /mnt to make further changes"
echo 'Press any key to exit...'; read -k1 -s
```

**Comment by Kreimeier** [comment]
Btw, the andontie repo is only necessary, if the installer fails to install yay, try without andontie repo, it should work by, at least i didn't need it.

**Comment by Kreimeier** [comment]
Forget about my script, it surely won't help. I just booted the image from theVakhovskeIsTaken and i ran into the database error early on. As it seems holoinstall tries to install the whole base-devel package and it fails. I got holoinstall running just fine by making my own image, you might need to make your own image as well, but it will take time and processing power. The steps are written on the github page, but here is the summary what i did, you maybe need an arch or Manjaro machine:
```
pacman -Sy archiso (if you are running arch)

yay archiso (if you are running Manjaro, i choose archiso-git)

(other Linux distros may not have the archiso package, Google helps)

git clone https://github.com/bhaiest/holoiso/

Then edit holoiso/packages.x86_64 and add "base-devel" either on the end of the file or over "#GUI"

sudo mkarchiso -v holoiso
```
The iso should be in "out" and try to run this iso. Good luck.

**Comment by theVakhovskeIsTaken** [comment]
Try the freshest "Actions" build

This is based on dry-stock stable Steam Deck repos

**Comment by Jason300** [comment]
Kleimeier, thank you for the huge effort to help us

**Comment by nagybal** [comment]
> Try the freshest "Actions" build
> 
> This is based on dry-stock stable Steam Deck repos

Using HoloISO_Stable_GUI-20221101_1321-x86_64.iso the issue is the same:
```
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
holotso-stable                7.6 KiB     35.7 KiB/s 00:00 [##################################] 100%
holostaging                1929.0   B     9.10 KiB/s 00:00 [##################################] 100%
jupiter                      79.1 KiB      719 KiB/s 00:00 [##################################] 100%
holo                         70.8 KiB      644 KiB/s 00:00 [##################################] 100%
core                        138.5 KiB     1184 KiB/s 00:00 [##################################] 100%
extra                      1555.6 KiB     5.18 MiB/s 00:00 [##################################] 100%
community                     6.0 MiB     4.62 MiB/s 00:01 [##################################] 100%
multilib                    148.9 KiB     1154 KiB/s 00:00 [##################################] 100%
:: There are 24 members in group base-devel:
:: Repository core
1) autoconf 2) automake 3) binutils 4) bison 5) fakeroot 6) file 7) findutils 8) flex 9) gawk 10) gcc 11) gettext 12) grep 13) groff 14) gzip 15) libtool 16) m4 17) make 18) pacman 19) patch 20) pkgconf 21) sed 22) sudo 23) texinfo 24) which

Enter a selection (default=all):
error: database not found: core-main
error: database not found: core-main
==> ERROR: Failed to install packages to new root

Error: Something went wrong when installing base package.
Please make sure you have a stable internet connection!

Press any key to exit...
```

**Comment by Drago245** [comment]
Having the same issue. I saw that someone had success building their own ISO. Is there documentation for doing this on an install that isn't Arch? I'm running Fedora and I don't know how to build an ISO here.

**Comment by Kreimeier** [comment]
> Having the same issue. I saw that someone had success building their own ISO. Is there documentation for doing this on an install that isn't Arch? I'm running Fedora and I don't know how to build an ISO here.

theVakhovskeIsTaken mentioned that you can build an iso using the freshest Actions build:
https://github.com/theVakhovskeIsTaken/holoiso/actions

But since the package archiso is required you need to google it on your own, if your distro does have support for this.

Otherwise just install Arch or Manjaro (or any other Arch derivates) in a VMware or Virtualbox VM.

**Comment by mikopolos** [comment]
Hi there, I've managed to install holoISO on desktop but after reboot I'm getting command line mode like in barebones mode, but I'm sure that I chose SD expirience because I did it twice. so it is starting to work but it is not instaling GUI
