### ISSUE TITLE
Installer stuck error

### ISSUE THREAD

**Issue by Suny4t4** [holoiso-eol/holoiso#578]
## Your Issue:
```
*type your problem here*
```
installer gets stuck after choosing nvidia gpu. Can anyone please assist in how to proceed. Im doing the full deck install and I overcome the core-main error by replacing core-main with core in /usr/bin/holoinstall
I have attached the output error from terminal view

I am using the latest  ISO Update 3.2

![Screenshot_20221101_150355](https://user-images.githubusercontent.com/117191684/199269327-0f7e1f59-ac44-4e83-b09c-20f684a4e89d.png)

## Your device's full specs

CPU I9 9820x 64GB DDR4 3000mhz NVIDIA RTX3090

**Comment by Suny4t4** [comment]
Additional, I have the output now also in text;


warning: database file for 'extra-main' does not exist (use '-Sy' to download)
warning: database file for 'community-main' does not exist (use '-Sy' to download)
warning: database file for 'multilib-main' does not exist (use '-Sy' to download)
warning: gamescope-3.11.48.100.snapshot20221029.1511-4 is up to date -- skipping
error: failed to prepare transaction (could not find database)
cp: cannot create regular file '/mnt/home/sunyata/Desktop/steamos-gamemode.desktop': No such file or directory
chmod: cannot access '/home/sunyata/Desktop/steamos-gamemode.desktop': No such file or directory
Created symlink /etc/systemd/system/printers.target.wants/cups.service → /usr/lib/systemd/system/cups.service.
Unit /usr/lib/systemd/system/cups.service is added as a dependency to a non-existent unit printers.target.
Created symlink /etc/systemd/system/multi-user.target.wants/cups.service → /usr/lib/systemd/system/cups.service.
Created symlink /etc/systemd/system/sockets.target.wants/cups.socket → /usr/lib/systemd/system/cups.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/cups.path → /usr/lib/systemd/system/cups.path.
Created symlink /etc/systemd/system/dbus-org.bluez.service → /usr/lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/bluetooth.target.wants/bluetooth.service → /usr/lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/display-manager.service → /usr/lib/systemd/system/sddm.service.
Created symlink /etc/systemd/system/multi-user.target.wants/holoiso-reboot-tracker.service → /usr/lib/systemd/system/holoiso-reboot-tracker.service.
sed: -e expression #1, char 39: unterminated `s' command
/usr/bin/steam: line 30: cd: /home/sunyata/.steam/root/package: No such file or directory
/usr/bin/steam: line 30: cd: /home/sunyata/.local/share/Steam/package: No such file or directory
bin_steam.sh[2]: Setting up Steam content in /home/sunyata/.local/share/Steam
steam.sh[2]: Running Steam on steamos rolling 64-bit
steam.sh[2]: STEAM_RUNTIME is enabled automatically
/usr/bin/zenity: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libgbm.so.1)
/usr/bin/zenity: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libgbm.so.1)
steam.sh[2]: Steam client's requirements are satisfied
[2022-11-01 16:26:28] Startup - updater built Jun 29 2022 07:46:36
[2022-11-01 16:26:28] Opted in to client beta 'steamdeck_stable' via beta file
You are in the 'steamdeck_stable' client beta.
Installing breakpad exception handler for appid(steam)/version(1656536422)
Authorization required, but no authorization protocol specified
src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
src/steamexe/updateui_xwin.cpp (339) : Could not open connection to X
Installing breakpad exception handler for appid(steam)/version(1656536422)
No minidump written, nothing to upload.
src/steamexe/main.cpp (1011) : failed to initialize update status ui, or create initial window
src/steamexe/main.cpp (1011) : failed to initialize update status ui, or create initial window
warning: database file for 'holo-main' does not exist (use '-Sy' to download)
warning: database file for 'core-main' does not exist (use '-Sy' to download)
warning: database file for 'extra-main' does not exist (use '-Sy' to download)
warning: database file for 'community-main' does not exist (use '-Sy' to download)
warning: database file for 'multilib-main' does not exist (use '-Sy' to download)
error: target not found: packagekit-qt5
error: target not found: rsync
error: target not found: unzip
error: target not found: vim

Error: Something went wrong when installing flatpak.
Please make sure you have a stable internet connection!

Press any key to exit...

**Comment by Kreimeier** [comment]
Issue is discussed more thorouhly here:
https://github.com/theVakhovskeIsTaken/holoiso/issues/573
