### ISSUE TITLE
GPD Win Max 2020 - Intel i5-1035G7 Intel Iris Plus Graphics - Can only access desktop mode, game mode shows black screen and goes back to login

### ISSUE THREAD

**Issue by Daxiongmao87** [holoiso-eol/holoiso#58]
I've taken the steps described in [the gist](https://gist.github.com/drraccoony/8a8d0a9e3dfde9fafd3e374e418d2935) as instructed by the README.md, but the issue still persists.  The gist didn't contain any info for GPD Win Max 2020 devices anyway, just GPD Win 1 and 2.

If there are logs I can provide I'd be more than happy to help!

**Comment by theVakhovskeIsTaken** [comment]
Run `sudo pacman -S lib32-vulkan-intel vulkan-intel` to see if this gives something.

Can you run `gamescope-session` under terminal?

**Comment by ruineka** [comment]
This is an ANV driver bug issue. downgrade mesa/gamescope in order to use Intel. I believe it was the global FSR build of gamescope that causes the issue.

Downgrade Gamescope & install Intel Mesa:

    This requires internet. Connect to a network or use a dongle for ethernet.
    sudo pacman -S extra/mesa extra/vulkan-intel multilib/lib32-mesa multilib/lib32-vulkan-intel holo/gamescope

**Comment by mijosch** [comment]
Might it be the same with my problem? #80
but here its amdgpu as driver

**Comment by Daxiongmao87** [comment]
@theVakhovskeIsTaken 
> Run sudo pacman -S lib32-vulkan-intel vulkan-intel to see if this gives something.

> Can you run gamescope-session under terminal?

I've ran the pacman install command, seemed to work fine.  However, running gamescope-session (without root) returns this:


```
$ gamescope-session
/usr/bin/gamescope-session: line 28: /usr/bin/ev2fixaudio.sh: No such file or directory
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vulkan: selecting physical device 'Intel(R) Iris(R) Plus Graphics (ICL GT2)'
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: [backend/noop/backend.c:59] Creating noop backend
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/noop/backend.c:16] Starting noop backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:84] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:737] New wlr_surface 0x55bb6388e990 (res 0x55bb63a06de0)
wlserver: [xwayland/server.c:242] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 79
steam.sh[2453]: Running Steam on steamos rolling 64-bit
steam.sh[2453]: STEAM_RUNTIME is enabled automatically
setup.sh[2529]: Steam runtime environment up-to-date!
steam.sh[2453]: Steam client's requirements are satisfied
gamescope: received kill signal, terminating!
(EE) failed to read Wayland events: Broken pipe
xwm: Lost connection to the X11 server
gamescope: received kill signal, terminating!
gamescope-session: unexpected background pid 2452 at teardown: 
    PID TTY          TIME CMD
   2452 pts/1    00:00:00 gamescope-sessi
/usr/bin/gamescope-session: line 133:  2452 Killed                  ( while true; do
    ${POWER_BUTTON_HANDLER};
done )
/usr/bin/gamescope-session: line 134:  2574 Killed                  sleep 5

```
@mijosch
I do see that same error as well, but it's accompanied by another error that I could not catch.

**Comment by memmam** [comment]
@Daxiongmao87 Hello fellow GPD Win Max user!

Do you have any input on the issues I'm having? #154

**Comment by theVakhovskeIsTaken** [comment]
> @theVakhovskeIsTaken 
> > Run sudo pacman -S lib32-vulkan-intel vulkan-intel to see if this gives something.
> 
> > Can you run gamescope-session under terminal?
> 
> I've ran the pacman install command, seemed to work fine.  However, running gamescope-session (without root) returns this:
> 
> 
> ```
> $ gamescope-session
> /usr/bin/gamescope-session: line 28: /usr/bin/ev2fixaudio.sh: No such file or directory
> Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
> MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
> 
> vulkan: selecting physical device 'Intel(R) Iris(R) Plus Graphics (ICL GT2)'
> vulkan: physical device supports DRM format modifiers
> vulkan: supported DRM formats for sampling usage:
> vulkan:   0x34325241
> vulkan:   0x34325258
> vulkan:   0x3231564E
> wlserver: [backend/noop/backend.c:59] Creating noop backend
> wlserver: Running compositor on wayland display 'gamescope-0'
> wlserver: [backend/noop/backend.c:16] Starting noop backend
> wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
> wlserver: [xwayland/server.c:84] Starting Xwayland on :1
> wlserver: [types/wlr_surface.c:737] New wlr_surface 0x55bb6388e990 (res 0x55bb63a06de0)
> wlserver: [xwayland/server.c:242] Xserver is ready
> pipewire: stream state changed: connecting
> pipewire: stream state changed: paused
> pipewire: stream available on node ID: 79
> steam.sh[2453]: Running Steam on steamos rolling 64-bit
> steam.sh[2453]: STEAM_RUNTIME is enabled automatically
> setup.sh[2529]: Steam runtime environment up-to-date!
> steam.sh[2453]: Steam client's requirements are satisfied
> gamescope: received kill signal, terminating!
> (EE) failed to read Wayland events: Broken pipe
> xwm: Lost connection to the X11 server
> gamescope: received kill signal, terminating!
> gamescope-session: unexpected background pid 2452 at teardown: 
>     PID TTY          TIME CMD
>    2452 pts/1    00:00:00 gamescope-sessi
> /usr/bin/gamescope-session: line 133:  2452 Killed                  ( while true; do
>     ${POWER_BUTTON_HANDLER};
> done )
> /usr/bin/gamescope-session: line 134:  2574 Killed                  sleep 5
> 
> ```
> @mijosch
> I do see that same error as well, but it's accompanied by another error that I could not catch.

This looks fine now, try to switch back to Gamemode

**Comment by Daxiongmao87** [comment]
@theVakhovskeIsTaken fine now, as in it's fixed in the newer ISO? Should I reinstall with the newest iso?

**Comment by JulyIghor** [comment]
I confirm, it is still not fixed

**Comment by JulyIghor** [comment]
Any progress on it?
Any testers needed?

**Comment by Daxiongmao87** [comment]
I'm also eagerly waiting/watching.  I'm also willing to help test if needed.

**Comment by JulyIghor** [comment]
I waited so long, but no bugs fixed.

Anyway I'm not going to support this project anymore.
The main dev is publicly advertising his position that he is supporting the War against Ukraine by displaying Rashism symbols in his social profiles.
So if you are donating to this project, it is maybe re-donated to support russian army.

![2022-11-14 23 28 41](https://user-images.githubusercontent.com/3390357/201856314-bde27a53-68f0-4f2b-bfe3-d3485522b276.jpg)
![image](https://user-images.githubusercontent.com/3390357/202029982-b546a020-5db0-40a8-b210-6a0123eeaa77.png)
![2022-11-14 23 28 38](https://user-images.githubusercontent.com/3390357/201856324-9a475259-414f-4ae7-9a91-667547b58a7c.jpg)
https://web.archive.org/web/20221115075000/https://t.me/theVakhovske
