### ISSUE TITLE
The refresh rate slider is not displayed in the game mode

### ISSUE THREAD

**Issue by Gawah** [holoiso-eol/holoiso#581]
desktop mode：
![IMG_1752](https://user-images.githubusercontent.com/105637287/199710401-94f76028-7169-4ac3-ba24-291ddf91d7fd.JPG)

game mode
![IMG_1750](https://user-images.githubusercontent.com/105637287/199710737-3cf4e540-15b0-48f2-b50d-5a79b3ae08f7.JPG)

**Comment by Gawah** [comment]
My device only supports 60hz. I think this may be the reason why the refresh rate slider is not displayed.But I found that when running "gamescope-session" on the terminal, the refresh rate slider will not be hidden, and the settings are also effective. Although my device only supports 60hz, it still works at 50hz, so I hope I can adjust it in the range of 50hz-60hz in the game mode.
  I found a configuration parameter in "gamescope session" and changed it to "export STEAM_DISPLAY_REFRESH_LIMITS=50,60" It takes effect in  the desktop mode, but the slider is still hidden in the game mode, which makes it impossible for me to change the refresh rate in the game mode. 
  Although there is only a 10 hz gap, it is much easier to stabilize 50 hz on the handheld than 60 hz. Is there any way to display the refresh rate slider?

**Comment by theVakhovskeIsTaken** [comment]
> desktop mode：
> ![IMG_1752](https://user-images.githubusercontent.com/105637287/199710401-94f76028-7169-4ac3-ba24-291ddf91d7fd.JPG)
> 
> game mode
> ![IMG_1750](https://user-images.githubusercontent.com/105637287/199710737-3cf4e540-15b0-48f2-b50d-5a79b3ae08f7.JPG)
> 

Developer Settings ->  Allow external display refresh rate control

Steam Client treats any non-16:10 target as an external display

**Comment by Gawah** [comment]
The refresh rate slider appears, but no matter how you drag it, it will not take effect.
 The value set in desktop mode can take effect in game mode.

**Comment by Gawah** [comment]
And the "STEAM_DISPLAY_REFRESH_LIMITS=50,60" I set does not work in the game mode. The range is still 40hz-60hz in the game mode.

**Comment by Gawah** [comment]
The settings take effect after updating the gamescope.
