### ISSUE TITLE
Stuck installing on Hyper V

### ISSUE THREAD

**Issue by kgreel** [holoiso-eol/holoiso#582]
![SteamOS](https://user-images.githubusercontent.com/82187920/199847282-183f29a6-9e71-4494-8310-9e583e770549.jpg)

Is it due to the Hyper V hard drive SCSI controller?

Thanks

**Comment by Felzow47** [comment]
No VM support.

_Originally posted by @theVakhovskeIsTaken in https://github.com/theVakhovskeIsTaken/holoiso/issues/356#issuecomment-1247300680_

[No VM Support ](https://github.com/theVakhovskeIsTaken/holoiso/issues/356#issuecomment-1247300680)
