### ISSUE TITLE
[Report] unable to satisfy dependency libopus.so=0-64

### ISSUE THREAD

**Issue by KingProNoob2** [holoiso-eol/holoiso#583]
## Your Issue:
unable to satisfy dependency libopus.so=0-64
*type your problem here*
In the middle of the install pacman can't resolve dependencies libopus.so=0-64 and pipewire-audio

## Your device's full specs
```
CPU: Core i-5 8th gen
GPU: Intel Integrated graphics
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220716.2021
```

## Your installation type:
```
Deck-experience
```

**Comment by hermlon** [comment]
I also encountered this problem and captured a full log, in case this is helpful: https://0x0.st/oEKu.log

**Comment by KingProNoob2** [comment]
I now actually know the cause, because a dependency of pipewire has 2 repos, the Holo iso repo and the arch repo, and the arch repo is the default, but i think there is a different version. (In the Holo iso repo)

**Comment by NuiceT** [comment]
found any workaround for this?

**Comment by KingProNoob2** [comment]
I guess install the bare-bones steam os, then chroot into it and install the rest of the packages manually (look in the git repo which to install)

**Comment by NuiceT** [comment]
Found the issue: pipewire-audio requires **libopus.so=0-64** (included in **opus-1.3.1-3**) but the steamos repo (https://steamdeck-packages.steamos.cloud/archlinux-mirror/extra/os/x86_64/) only contains **opus-1.3.1-2** (which provides libopus.so=0-32).

**Comment by NuiceT** [comment]
The reason for that is, that pipewire-audio was updated yesterday. As I said, the steamos mirror doesn't include opus-1.3.1-3.

**Comment by NuiceT** [comment]
I think you can close the thread, it's actually working with the newest ISO Build directly [from GitHub](https://github.com/theVakhovskeIsTaken/holoiso/actions)

**Comment by Scriptiq** [comment]
@NuiceT I'm encountering the same issue and it seems like you resolved it by getting the latest ISO Build. Do you have the manually build it? If so, not sure how to do it.

**Comment by KingProNoob2** [comment]
ok
