### ISSUE TITLE
Holoiso 3.3 Installation give some USB errors starting with Ventoy

### ISSUE THREAD

**Issue by TuberViejuner** [holoiso-eol/holoiso#585]
## Your Issue:
Holoiso 3.3 Installation give an USB error starting with Ventoy
I burn ventoy into a pendrive, then I copy holoiso iso too, then I start the pc and I try to start holoiso 3.3 , installation starts but gives me some usb errors and can't do anything, ( see the attachent)

## Your device's full specs
Mini pc MinisForum UM580
CPU: AMD Ryzen™ 7 5800H
GPU: AMD Radeon™ Graphics
RAM: 16 GB

## Your installation type:
deckperience
![photo1667766434](https://user-images.githubusercontent.com/36773104/200198400-43ec9025-d0ba-4854-b461-1733ceb1b557.jpeg)

**Comment by Angheloss** [comment]
For me it worked just fine wierd

**Comment by Jakemate977** [comment]
The readme explicitly states that flashing the ISO with other tools not listed might cause issues

**Comment by TuberViejuner** [comment]
> The readme explicitly states that flashing the ISO with other tools not listed might cause issues

The first thing I tried was balena etcher and... nothing happens, the machine can't start with holoiso 3.3

**Comment by Jakemate977** [comment]
Weird, did you checksum the iso?
Maybe redownloading it could help

**Comment by t-MURO** [comment]
I tried with ventoy as well before completely reading the docs. Did not work. Then I used BalenaEtcher as suggested in the readme but got stuck while installing. The last try was with Rufus in DD mode and still no success though I came even further than with BalenaEtcher variant...
