### ISSUE TITLE
install 3.3 with gui installer(not offline installer iso)

### ISSUE THREAD

**Issue by cubehead** [holoiso-eol/holoiso#587]
after install finished, it stop at verifying installation screen. can not go into login screen.

intell 1165g with 16G ram

**Comment by GuardianZX9** [comment]
Also having this issue, only after steam os update.

**Comment by szlukisz** [comment]
it's the same with me

intel 11400F nvidia 1060

**Comment by PadTrick** [comment]
same here, was trying it out on my i7(7th gen), gtx 1060 asus laptop. installation was normal like ever. after reboot and selecting country & network. it tries to update, reboots and starts with country & network selection and trying to update again.

btw. i was trying the offline installer

got it somehow working by unplugin and plugin ethernet cable on offline installer. took several attempts and 3 reinstalls
