### ISSUE TITLE
Can't boot into SteamOS on Mac Mini 2010 (Loading internal ramdisk..)

### ISSUE THREAD

**Issue by prplwtf** [holoiso-eol/holoiso#589]
## Your Issue:
```
Both Barebones and Full stay at "Loading internal ramdisk.." when booted. Recovery mode doesn't work and hangs at "[  OK  ] Started Load/Save RF Kill Switch Status."
```

## Your device's full specs
```
CPU: Intel Core 2 Duo
GPU: NVIDIA GeForce 320M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

**Comment by duffyjp** [comment]
Your system is _way_ too old unfortunately.  For nvidia only 9xx (really 10xx) and newer will work.  Even if you somehow got it installed it's going to be awful.
