### ISSUE TITLE
Can't login in gamescope session 

### ISSUE THREAD

**Issue by BlueBerrySans365** [holoiso-eol/holoiso#59]
For some reason i successfully installed steamos, but now at start it's shows me this:
```
Starting version 250.3-1-arch
[FAILED] Failed to start Jupiter BIOS Update Service
```

**Comment by BlueBerrySans365** [comment]
Started with simple linux (not linux-neptune) and it's worked. Idk why, rlly.

**Comment by BlueBerrySans365** [comment]
Now it's problem to start steamos. Entered password, 4-5 seconds of black screen and returned back to login window.

**Comment by theVakhovskeIsTaken** [comment]
What is your GPU? Are you able to run `gamescope-session` in terminal?

**Comment by BlueBerrySans365** [comment]
Still, idk why linux-neptune not working. SteamOS (gamescope) (Wayland) is not working. At least Plasma (x11) is working.

**Comment by BlueBerrySans365** [comment]
> What is your GPU? Are you able to run `gamescope-session` in terminal?

Nvidia GTX 1650
Result of `gamescope-session`: ```Failed to initialize Vulkan```

**Comment by theVakhovskeIsTaken** [comment]
![image](https://user-images.githubusercontent.com/97450182/167315034-1cd64621-fb89-409d-ab3a-64e96d85b1b3.jpg)

**Comment by VolyFnap** [comment]
> What is your GPU? Are you able to run `gamescope-session` in terminal?

Какая это команда? Я весь вечер пытаюсь найти команду по запуску сессии(

**Comment by BlueBerrySans365** [comment]
> > What is your GPU? Are you able to run `gamescope-session` in terminal?
> 
> Какая это команда? Я весь вечер пытаюсь найти команду по запуску сессии(

`gamescope-session`
