### ISSUE TITLE
[not a bug report] HoloISO Running on Vmware Workstation

### ISSUE THREAD

**Issue by Felzow47** [holoiso-eol/holoiso#591]
HoloISO Boot with no problem on vmware using a usb key with Medicat (Ventoy) 
@theVakhovskeIsTaken do you want the VMDK of the Virtual Machine for everyone ask for HoloIso on VirtualMachine ? 

- [x] Test install Edit : Install work but Black screen
- [x] Vmware Guest Tool
- [ ] ~~Test Gpu PassThrought (can't Make Gpu PassThrought On VmwareWorkstation.....)~~

![image](https://user-images.githubusercontent.com/49567056/200976765-b6867040-3bf3-4941-987a-94fbf2628461.png)

**Comment by AKASGaming** [comment]
Does it boot to the actual Steam Deck interface?

**Comment by Felzow47** [comment]
> Does it boot to the actual Steam Deck interface?

i don't know for the moment i have a bug when installing "Steam OS" 
apparently  there would be a connection problem during the installation so I will try the offline version and I tell you
![image](https://user-images.githubusercontent.com/49567056/200992167-b41b1a90-2d87-44c8-970a-fa53eb653c83.png)

**Comment by Felzow47** [comment]
Install is working perfectly and boot BUT black screen after ```Select Operating System```

![image](https://user-images.githubusercontent.com/49567056/200996065-65bcb7b7-8a5c-4254-928a-5febcf69592e.png)

so i saw in this [issue](https://github.com/theVakhovskeIsTaken/holoiso/issues/548) i can show the SteamOS Terminal and login to my user account with no problem or error
but when i launch ``` gamescope-session``` i have a lot of error ! 

![image](https://user-images.githubusercontent.com/49567056/200996498-5dc37cd5-f844-4278-8b87-2a664e21b125.png)
i think is beacause i don't connect a gpu to this VM and also in fault of the touch command who fails


i look for why the touch command fail but.... there is no config folder in /home/felzow47/.steam/root/~~config/~~

im dumb.... vulkan is the AMD technology but i have Nvidia card BUT i find [this driver](https://developer.nvidia.com/vulkan-driver) i don't know if this work with HoloISO

sooo i installed vmware tools ! i used [this tutorial](https://medium.com/@ribomo42/install-official-vmware-tools-on-arch-linux-15afd5b848ed) bc i never used arch linux.... 
And it's working !!! 
![image](https://user-images.githubusercontent.com/49567056/201007814-72043d29-7733-412f-9cc3-07fdb758796d.png)

**Comment by jxshuaa** [comment]
Hey, could I get the VMDK? Or could you just walk me through the steps maybe in Discord? (if you have it). My username is ``jxshua``. Thanks!

**Comment by CoolGames101** [comment]
How to install? wid link or comment.

**Comment by Felzow47** [comment]
> How to install? wid link or comment.

i totaly forgot how sorry
