### ISSUE TITLE
[Holoiso mirrors] how can I make a local mirror of the holoiso 

### ISSUE THREAD

**Issue by ArcheyChen** [holoiso-eol/holoiso#592]
Hello, I'm in China, and the network to holoiso sourse is really slow.

And I'm thinking of building a mirror using rsync  
Like:
https://wiki.archlinux.org/title/DeveloperWiki:NewMirrors

but these servers don't have a rsync support.

Server = http://dlcdn2.thevakhovske.pw/$repo/os/$arch
Server = http://dl.thevakhovske.pw/$repo/os/$arch
Server = http://holoiso.itsvixano.me/$repo/os/$arch

how should I make a mirror or something like that?

**Comment by theVakhovskeIsTaken** [comment]
Second mirror "dl.thevakhovke.pw" is located in Hong Kong/CN

But I don't know how to setup rsync server, but would be glad to set it up

**Comment by ArcheyChen** [comment]
I hadn't do it before, but I think you can refer to  arch wiki:

It shows how to start a rsync daemon, and manage what files to share
 
https://wiki.archlinux.org/title/Rsync
