### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by Evil2056** [holoiso-eol/holoiso#593]
## Your Issue:
the install says not enough space
![20221110_024421](https://user-images.githubusercontent.com/115745235/201046747-20141805-9906-475e-8ae2-6948ea16e0ed.jpg)

**Comment by nisel11** [comment]
I have the same problem, someone wrote a telegram channel that you need 8 GB of RAM or more.

**Comment by Evil2056** [comment]
damn, my device only has three GB. I know linux can run on this device, so steamos should be capable of running, but idk why size is a requirement.

**Comment by nisel11** [comment]
The extracted file system of the image weighs about 7.5 gigabytes and all this should be written to RAM but I have 6 gigabytes free, you have 3 and it just gives an error, the only solution is to delete the offline installation from the image (I think so, after the message says that he wants to extract the file system squashfs(sfs) in RAM and therefore needs 7.5 GB of free RAM)

**Comment by nisel11** [comment]
The image with 3.2 in unpacked form weighs 4.5 GB of RAM, but I somehow ran it on a virtual machine with 4 GB of RAM, I unfortunately can not explain it

**Comment by Evil2056** [comment]
What I want to know is why it goes to ram at all. Why not use the usb drive

**Comment by nisel11** [comment]
Unfortunately, I can't answer this question because I don't know.
