### ISSUE TITLE
[bug] The icon that returns to game mode disappears

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#595]
I used the latest offline image for the installation
When I feel good about everything
The icon that returns to game mode disappears
I copied one from the previous version to the desktop
But when you go into game mode and go back to desktop mode
He would still disappear
The other programs I installed are fine
How can I fix this

![image](https://user-images.githubusercontent.com/1498746/201125625-8d0d8993-e3f4-45bc-b05f-f34abe69ec32.png)

**Comment by cstruck** [comment]
you could make the steamos-gamemode.desktop file immutable.

```
sudo chattr +i ~/Desktop/steamos-gamemode.desktop
```

but this might be a bad Idea since it cannot get updated until you remove the immutable flag.
