### ISSUE TITLE
Greeted with Arch log in rather than Steam Deck OOBE setup

### ISSUE THREAD

**Issue by ByteSz** [holoiso-eol/holoiso#6]
As the title says, I installed this today using BalenaEtcher, then holoinstall on nvme01n1. But rather than booting up to the Deck OOBE, I'm greeted with an Arch log in instead.

Any info on the default user name and password?

**Comment by theVakhovskeIsTaken** [comment]
Sure. What is your hardware? Do you run AMD GPU?

**Comment by ByteSz** [comment]
Yup! Sorry, forgot to include that but I'm running on a 5700g. After restarting, now I'm being greeted with "[FAILED] Failed to start Light Display Manager"

**Comment by theVakhovskeIsTaken** [comment]
Mhm. Looks like you are using older version of my ISO. Mind trying out the "Beta One" release? https://github.com/bhaiest/holoiso/releases/tag/beta1

**Comment by ByteSz** [comment]
OH, my bad lol. Will do, saw it was the version from yesterday when I got here from the Reddit post. Thanks!

**Comment by theVakhovskeIsTaken** [comment]
> OH, my bad lol. Will do, saw it was the version from yesterday when I got here from the Reddit post. Thanks!

No problem, have a gd :>
