### ISSUE TITLE
Cannot go into gamescope mode - Vulkan problem

### ISSUE THREAD

**Issue by Lolo280374** [holoiso-eol/holoiso#60]
On the first startup, i was greeted with a Arch login screen, weirdly enough.
I selected to login to the gamescope session, but it just kicked me back on the login screen.
However, by selecting KDE mode, it logins without any problems, and i was able to try and install the drivers for Vulkan, ect.
Still no success, after installing "vulkan-icd-loader,vulkan-radeon, and amdvlk". (I also installed their 32 bit version)
Do you have any idea how could i get gamecope to work, or Vulkan to work?

(On startup, theses lines appears:
Starting version 250.3-1-arch
[FAILED] Failed to start **Jupiter BIOS Update Service**.
[FAILED] Failed to start **Jupiter Controller Firmware Update Service**.

When typing "gamecope" in the KDE terminal, this appears:
vulkan: failed to find physical device
Failed to initialize Vulkan

Also, my CPU is a AMD E1-6010 APU with the AMD Radeon R2 graphics, which says on the AMD website it is supported)

**Comment by theVakhovskeIsTaken** [comment]
Those A* era GPUs afaik are not having vulkan, let alone separate DRMFB, so your hardware is incompatible.
