### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Likx16** [holoiso-eol/holoiso#601]
##您的问题：```*Hello Steamosui is very stuck when using nvdia graphics card. How to solve this problem?*```## 您设备的完整规格```CPU：12490FGPU：nvdia 3070```## 您的操作系统版本（`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`）：```snapshot19700101_1011-beta2a```##（仅适用于SteamOS会话加载问题）您是否尝试过从终端启动“gamescope-session”？如果是，请提供日志。```是的，pubg crash bhai```## 您的安装类型：```甲板上```## 你最近更新了安装吗？```纳日```

**Comment by KrisCris** [comment]
check known issues in the readme.
