### ISSUE TITLE
[Report] Fails to boot - Steam Deck

### ISSUE THREAD

**Issue by KickAssDave** [holoiso-eol/holoiso#603]
## Your Issue:
```
Stuck on ramdisk (kernel doesn't seem to start properly?)
```

## Your device's full specs
```
Steam Deck

Disabled quiet boot, seen message regarding sd-mount.. so removed both the USB drive and micro SD.

Tried again.
Boot stops on ....
System Time Set

```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Latest ISO release
```

## Your installation type:
```
deckexperience
```

## Have you updated your installation recently?
```
This is a clean install.
```

**Comment by bkdfkup** [comment]
As supporting information, and starting with a fully working install of HoloISO, I performed the update process via desktop-mode terminal, and upon reboot was met with the same error. I then proceeded to download the latest iso, performed a clean reinstall, and was met with the same issue.

Of note is that this is an intel GPU, and the latest full install did NOT ask what GPU i was running, where the previous full install did.

**Comment by SnackaJax** [comment]
@KickAssDave this is not meant to be installed on a Steamdeck, it's for PC's. If you want to install SteamOS on your steamdeck you can [go to this page](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3) and follow the instructions from Valve.

**Comment by KickAssDave** [comment]
> @KickAssDave this is not meant to be installed on a Steamdeck, it's for PC's. If you want to install SteamOS on your steamdeck you can [go to this page](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3) and follow the instructions from Valve.

I'm well aware of the SteamOS image.
I don't want a locked down system (or at least... My changes overwritten).

Manjaro/Ubuntu/Debian etc were all not meant for the Deck, but they work just fine other than the known issues with audio.

**Comment by Artem45** [comment]
Hi, I've got the same, stuck on screen with initialize ramdisk, it happened after reboot and change my BIOS settings -> Set Enabled Intel 12th (iGPU) with AMD RX570 (dGPU) , but when I install OS  -> iGPU was disabled and system nothing know about, after instalation of OS -> AMD RX 570 work fine whithout any issues. 
But for my happines holo-iso option in Advance boot works, maybe some one know how can I recover default neptune booting without full reinstall OS and setup all settings and apps again ? is it possible ? why holo-iso boot with all setting and apps that I have on normal boot - I thought it's just copy of iso installation image, but it's seems work as my usual system with all maded changes and installed apps.

P.S: sorry for my English

**Comment by Artem45** [comment]
Oh, thank you for attention I've solved my problem, just boot at neptune recovery mod and press Ctrl+D, and it's work for now.
