### ISSUE TITLE
[need help] AOKZOE A1 AR07 and ONEXPLAYER Mini Pro The sound was suddenly shrill

### ISSUE THREAD

**Issue by danyi** [holoiso-eol/holoiso#604]
These two pieces of equipment are produced by the same manufacturer
The motherboard is exactly the same
Presumably many people have all kinds of problems with it
Question about the voice
The sound was suddenly shrill
In windows, change the format of the sound to
Changing the format from 24-bit 48000 Hz to 16-bit 48000 Hz solves this problem
But in archlinux I changed it and couldn't solve it
Here's how I changed it
```
sudo vim /etc/pulse/client.conf
default-sample-format = s16le
default-sample-rate = 48000
```
Did I change something wrong
I need your help

**Comment by uplush** [comment]
I had the issue, too.

**Comment by prosolis** [comment]
Also experiencing this same issue on AOKZOE A1.

**Comment by NikhilSaini38** [comment]
> These two pieces of equipment are produced by the same manufacturer The motherboard is exactly the same Presumably many people have all kinds of problems with it Question about the voice The sound was suddenly shrill In windows, change the format of the sound to Changing the format from 24-bit 48000 Hz to 16-bit 48000 Hz solves this problem But in archlinux I changed it and couldn't solve it Here's how I changed it
> 
> ```
> sudo vim /etc/pulse/client.conf
> default-sample-format = s16le
> default-sample-rate = 48000
> ```
> 
> Did I change something wrong I need your help

it needs to be in wireplumber configuration, since wireplumber manages pipewire and alsa configuration, the issue is with ALSA not being set to correct sample rate and format for the onboard sound device. You can do this by setting `alsa_monitor.properties` to
```
alsa_monitor.properties = {
  ["audio.format"] = "S16LE",
  ["audio.rate"] = 48000
}
```

in `/usr/share/wireplumber/main.lua.d/30-alsa-monitor.lua` or equivalent. 
try this, reboot you device and see if that resolves the issue.

this changes the default audio format which is 32bit for alsa to 16bit, and audio rate which i think is 48000 but get maybe gets overriden elsewhere is defaults are not overriden.

**Comment by danyi** [comment]
> > These two pieces of equipment are produced by the same manufacturer The motherboard is exactly the same Presumably many people have all kinds of problems with it Question about the voice The sound was suddenly shrill In windows, change the format of the sound to Changing the format from 24-bit 48000 Hz to 16-bit 48000 Hz solves this problem But in archlinux I changed it and couldn't solve it Here's how I changed it
> > ```
> > sudo vim /etc/pulse/client.conf
> > default-sample-format = s16le
> > default-sample-rate = 48000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did I change something wrong I need your help
> 
> it needs to be in wireplumber configuration, since wireplumber manages pipewire and alsa configuration, the issue is with ALSA not being set to correct sample rate and format for the onboard sound device. You can do this by setting `alsa_monitor.properties` to
> 
> ```
> alsa_monitor.properties = {
>   ["audio.format"] = "S16LE",
>   ["audio.rate"] = 48000
> }
> ```
> 
> in `/usr/share/wireplumber/main.lua.d/30-alsa-monitor.lua` or equivalent. try this, reboot you device and see if that resolves the issue.
> 
> this changes the default audio format which is 32bit for alsa to 16bit, and audio rate which i think is 48000 but get maybe gets overriden elsewhere is defaults are not overriden.

I changed this file myself yesterday
/usr/share/wireplumber/main.lua.d/50-alsa-config.lua

`audio-format = s16le`
`audio-rate = 48000`

After the restart, run the command
`pactl list sinks|grep -B3 Sample`
You can see that the changes have taken effect
I have no further problems at the moment
I'll use it for a while to make sure it's resolved

**Comment by NikhilSaini38** [comment]
I tried this, problem is still there, maybe lets try 192000 as it is suggested by someone in discord? I am wondering if this is a userspace issue at all.

**Comment by prosolis** [comment]
Unfortunately, none of the suggestions here resulted in a change in the format or sample rate reported by Pipewire (pactl list sinks).. at least on my device. When I edited the file mentioned by @danyi: 50-alsa-config.lua  under the apply.properties section, I uncommented and edited the following lines:
```
apply_properties = {
      ["audio.format"]           = "S16LE",
      ["audio.rate"]             = 48000,
      ["audio.allowed-rates"]    = "32000,44100, 48000",
    },
```
Pipewire reported the desired results after saving these changes and a reboot. I have not had a chance to keep it powered up during a game to see if the issue persists however.

**Comment by NikhilSaini38** [comment]
> Unfortunately, none of the suggestions here resulted in a change in the format or sample rate reported by Pipewire (pactl list sinks).. at least on my device. When I edited the file mentioned by @danyi: 50-alsa-config.lua under the apply.properties section, I uncommented and edited the following lines:
> 
> ```
> apply_properties = {
>       ["audio.format"]           = "S16LE",
>       ["audio.rate"]             = 48000,
>       ["audio.allowed-rates"]    = "32000,44100, 48000",
>     },
> ```
> 
> Pipewire reported the desired results after saving these changes and a reboot. I have not had a chance to keep it powered up during a game to see if the issue persists however.

worked for me

**Comment by jcfrosty** [comment]
The wireplumber config change fixes this, but I have a feeling this may be related to a kernel config issue. While building and configuring my own kernel (6.1-rc6) I noticed the Rembrandt audio co-processor module isn’t enabled as a module (M). I need to test this now that I’ve built the module for the audio co-processor.

update: no adding the audio coprocessor driver doesn’t fix it.

**Comment by danyi** [comment]
I tested for a long time and confirmed that the problem does not reoccur, so I will close this question

**Comment by danyi** [comment]
We made a script, and it can be repaired by running it directly. I hope it can help everyone
`#!/bin/sh`
`alsaconfigPath="/usr/share/wireplumber/main.lua.d/50-alsa-config.lua"`
`format_line=$(echo $(grep -rn "audio.format" $alsaconfigPath)|cut -d " " -f 1|cut -d ":" -f 1|xargs)`
`rate_line=$(echo $(grep -rn "audio.rate" $alsaconfigPath)|cut -d " " -f 1|cut -d ":" -f 1|xargs)`
`format_string="                  [\"audio.format\"]           = \"S16LE\","`
`rate_string="                    [\"audio.rate\"]           = \"48000\","`
`sudo sed -i "${format_line}""c ""${format_string}" $alsaconfigPath`
`sudo sed -i "${rate_line}""c ""${rate_string}" $alsaconfigPath`
`echo $(cat $alsaconfigPath|grep "audio.format")`
`echo $(cat $alsaconfigPath|grep "audio.rate")`
`echo "Press any key to exit"`
`read -n 1`
