### ISSUE TITLE
Won’t boot USB

### ISSUE THREAD

**Issue by F0R3V3R50F7** [holoiso-eol/holoiso#605]
![image](https://user-images.githubusercontent.com/30199830/202718898-0d48729a-1629-4b2f-ae91-db946372c0eb.jpg)

Tried running on several compatible machines, flashed 2 different usb drives, tried all USB ports and it keeps giving me this. Flashed from Etcher Mac OS Monterey.

**Comment by theVakhovskeIsTaken** [comment]
> ![image](https://user-images.githubusercontent.com/30199830/202718898-0d48729a-1629-4b2f-ae91-db946372c0eb.jpg)
> 
> Tried running on several compatible machines, flashed 2 different usb drives, tried all USB ports and it keeps giving me this. 

How much RAM does your system have?

Before booting, try to press "E" on boot choices and replace cow_spacesize=20G to 10G

**Comment by TTR-IND** [comment]
I’m reflashing with dd currently but will try this next. One system has 4gb, the others have 8.

**Comment by TTR-IND** [comment]
Re downloaded and reflashed using dd, attempted to run on the 4gb ram system but same issue.

**Comment by TTR-IND** [comment]
Also tried on 8gb ram system with Radeon 6xxx series and same error again

**Comment by k1yrix** [comment]
I may be aware that a 4 GB memory machine may not work as according to KDE's system monitor, it took at least 6 GB (more or less) of that whole SFS image in that drive to the memory on an 8 GB memory config, which is over 4 GB of memory. Therefore, there could be that insufficient memory = unable to boot on that configuration. And not all of the AMD cards would support the OS.

Related issue regarding to insufficient memory: #593

**Comment by kirbix12** [comment]
#593

**Comment by TTR-IND** [comment]
As I’ve said, I’ve tested everything on an 8gb machine aswell.

**Comment by TTR-IND** [comment]
Upon finding a ram issue with the machine I was testing on and upgrading the first machine to 8gb, I can confirm that at least 8gb ram is required for holoiso.
