### ISSUE TITLE
QUESTION (FEATURE REQUEST?):  Kiosk/Child mode?

### ISSUE THREAD

**Issue by johnodon** [holoiso-eol/holoiso#607]
I love this project and want to use it in the worst way as a frontend from my steam games and EmulationStation-DE (retro) on my familyroom TV but my family is not to be trusted with having access to settings, etc.  Even button-mashing can get them into trouble.

Is there any chance that a 'Kiosk' mode could/would ever be implemented?  I know that this this getting away from the true intent of the project but figured it didn't hurt to ask.

TIA!

John

**Comment by k1yrix** [comment]
That would be up to Valve to do that such thing on their OS as the general point is to attempt to have SteamOS 3 available on a non-Steam Deck, not forking it + also be aware that the we as the majority are not Valve ourselves nor affiliated with Valve
