### ISSUE TITLE
Password set for liveuser?

### ISSUE THREAD

**Issue by Hayden-Fluff** [holoiso-eol/holoiso#608]
## Your Issue:
```
I went to the Partition Manager when running live, and it asked for a password for authentication, but any of the common LiveUser passwords (including nothing) didn't work, is there an arbitrary password set for the LiveUser?
I also couldn't elevate to superuser in the terminal, as it gives me the same thing.
```

## Your device's full specs
```
CPU: Intel Core i5-3210M
GPU: Intel HD 4000
*2012 MacBook Pro 13 inch*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
ISO release 3.3
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/A
```

## Your installation type:
```
N/A, Live session
```

## Have you updated your installation recently?
```
Yes
```

**Comment by picobng** [comment]
Same.

Fix:
  Enter these commands in terminal : 
    sudo su -
    sudo passwd liveuser
    sudo passwd root
