### ISSUE TITLE
Login wont show user

### ISSUE THREAD

**Issue by gmodn** [holoiso-eol/holoiso#61]
I have no idea why this is happening and I'm not the best with linux. Did I fuck things up? Looks like [this ](https://cdn.discordapp.com/attachments/892146295827996674/972939072727289938/unknown.png)when I boot it up.

**Comment by theVakhovskeIsTaken** [comment]
What is your GPU?

**Comment by theVakhovskeIsTaken** [comment]
Looks like you didn't set up user during installation. Run the installation process again.

**Comment by gmodn** [comment]
got it! thought I had but it's fine. thanks!

**Comment by theVakhovskeIsTaken** [comment]
Mhm. Let me know when you finish.

**Comment by gmodn** [comment]
Ah, it works now. Thanks for the help!

**Comment by theVakhovskeIsTaken** [comment]
> Ah, it works now. Thanks for the help!

No probs :D enjoy using it
