### ISSUE TITLE
Intel Arc not working 

### ISSUE THREAD

**Issue by remy-luisant** [holoiso-eol/holoiso#610]
## Your Issue:
```
No graphics on Intel Arc A770 during the installation. Text mode works fine.
System still running, but output stops right after the line about entering the graphics mode. 
You can still change text mode displays, but no graphics mode does show up.  
```

## Your device's full specs
```
CPU: Intel 13900KF
GPU: Intel Arc A770
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
N/A, Failed to install
```

**Comment by theVakhovskeIsTaken** [comment]
Already known, you can fix it by building mesa and lib32-mesa from source in master branch as of now

**Comment by atoulmin** [comment]
I have the same issue. However I’m not knowledgeable enough to do the fix. Is there a guide of some kind?

**Comment by renne** [comment]
@theVakhovskeIsTaken
It would be great to have the one and only GPU vendor providing open-source drivers supported in HoloISO

**Comment by Casuallynoted** [comment]
Am also curious as to how to get this working. I've tired using the beta isos from Actions, but they don't boot.
