### ISSUE TITLE
Error: Something went wrong when installing full SteamOS 3.

### ISSUE THREAD

**Issue by lordkramgb** [holoiso-eol/holoiso#611]
Having some trouble with getting this to install giving me the above error in title
Trying to install on a Lenovo Thinkcentre M710Q (i5 6400T, ‎Intel HD Graphics 530, 8GB Ram)
Manage to get past the bit where you have to enter a hostname/username etc but then fails after trying to install the full steam os3
Also added the line: [andontie-aur]

Server = https://aur.andontie.net/$arch

SigLevel = Never

I've attatched a full error log as a text file, hopefully someone might be able to help?

[error.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/10047815/error.txt)

**Comment by ErickHatesBMC** [comment]
also having this exact issue

**Comment by demon86rm** [comment]
Same issue here, it seems some kind of pacman repo configuration inside the installer. 

I've tried also to configure a local repository (hosted on a container in a server reachable from the installer) but even though the repo worked like a charm from the cmdline, when I launch the holoinstall still does not work for other reasons that, for the moment, I do not have any clue nor the will to investigate furtherly about.

**Comment by gharringto** [comment]
Same here. Internet is connected via LAN but reading through the error text it looks like selections are not being made by the installer to satisfy dependencies.
