### ISSUE TITLE
holoiso won't start or freezes after a few seconds

### ISSUE THREAD

**Issue by nisel11** [holoiso-eol/holoiso#615]
## Your Issue:
```
holoiso won't start or freezes after a few seconds, 
no applications open, nothing on the desktop,
3.3 image only without copytoram, 
because I don't have free 8 GB of RAM on my laptop
Now the system won't start at all, but I can log in to 
the terminal, but I don't know the liveuser password. 
In VirtualBox, everything works except that
no video card drivers for Xorg, as far as I 
understood from what was in the logs. . 
```

## Your device's full specs
```
CPU: Ryzen 5 3550H
GPU: Vega 8
GPU: RX 560X
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
nothing
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
nothing
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
3.3 
```

**Comment by nisel11** [comment]
I repeat that I don’t have access to the commands in the terminal, you need to enter the password from liveuser or root, as far as I understand they don’t exist, but then what to do, without entering the password it says that the login is incorrect

**Comment by nisel11** [comment]
In rescue mode without entering a password, it says that the login is incorrect, despite the fact that I did not even enter it

**Comment by JesseKoldewijn** [comment]
Are you running the image as a VM or bare-metal? (asking because you mentioned VirtualBox)

**Comment by nisel11** [comment]
VM

**Comment by JesseKoldewijn** [comment]
Aight so, the default users's password is not set by default on steamOS and I believe it is the same way on holo. So my main question is, do you have a way of getting into the system via deck mode?

**Comment by JesseKoldewijn** [comment]
As for video card drivers. If I remember correctly the amd drivers are included in the kernel (not much experience with amd gpu's where I actually needed a driver for it).

If there seems to be a missing driver or weird low performance for the hardware you virtually provided to your vm you could try to google for amd driver arch linux or something. This would mean that you need to be able to login to the system tho.

**Comment by JesseKoldewijn** [comment]
In case you're able to get to the desktop of the system you could try to follow the following guide: https://christitus.com/unlock-steam-deck 

Should do the trick on holo as well eventhough Chris wrote this focussed on the steamdeck itself.

**Comment by jcfrosty** [comment]
There are a couple known issues I've found dealing with HoloISO/arch

1. It seems some QT updates can cause breakage https://bugs.archlinux.org/task/75851. Simple fix is to just reinstall packages that are broken:

$ sudo pacman -Su qt5-base qt5-xcb-private-headers qt5-wayland xdg-desktop-portal xdg-desktop-portal-kde

2. You cannot even access TTY2 via CTRL+ALT+F2 . The reason for this is a deprecated udev service is still used in HoloISO/SteamOS for some reason.This udev service forces your machine to wait 2-3 minutes to make sure all hardware is fully loaded up which isn't necessary. Lets just remove this old service.

$ sudo rm -rf /use/lib/systemd/system/systemd-udev-settle.service

**Comment by nisel11** [comment]
I build an image with offline_inst branch with some changes to access root, if you remove the service you are talking about, the screen will start flashing constantly, without deleting it will just freeze at some point and I also want to add that the screen will freeze at an early moment, in the first time it hung after loading the logo, the second time somewhere in the middle
Sorry for the long answer, I live in Ukraine and here they turn off the lights, maybe even for a week

**Comment by nisel11** [comment]
I will close this, because I realized that before the official release, which will take place, I will almost never be able to install holoiso for myself, I even tried to run the installation script in the live-cd image of arcolinuxd, but it came to downloading flatpak vim packages, etc. and hung

**Comment by theVakhovskeIsTaken** [comment]
> ## Your Issue:
> ```
> holoiso won't start or freezes after a few seconds, 
> no applications open, nothing on the desktop,
> 3.3 image only without copytoram, 
> because I don't have free 8 GB of RAM on my laptop
> Now the system won't start at all, but I can log in to 
> the terminal, but I don't know the liveuser password. 
> In VirtualBox, everything works except that
> no video card drivers for Xorg, as far as I 
> understood from what was in the logs. . 
> ```
> 
> ## Your device's full specs
> ```
> CPU: Ryzen 5 3550H
> GPU: Vega 8
> GPU: RX 560X
> ```
> 
> ## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
> ```
> nothing
> ```
> 
> ## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
> ```
> nothing
> ```
> 
> ## Your installation type:
> ```
> deckperience
> ```
> 
> ## Have you updated your installation recently?
> ```
> 3.3 
> ```
> 

It doesn't really work in VM.........It just doesn't.

You need a physical GPU.

Sorry for not clarifying that explicitly

**Comment by nisel11** [comment]
This was not originally the question, and holoiso I have already installed using the script in the livecd image another arch-based distro, the only thing left is that you can not press the button to enter the menu in the game, but I think this can only solve the Valve
