### ISSUE TITLE
Raspberry Pi 4?

### ISSUE THREAD

**Issue by JavaCoder5542884** [holoiso-eol/holoiso#617]
Can I install HuluISO on an Raspberry PI 4B 4gb RAM

**Comment by cstruck** [comment]
no you cannot since Steam is only build for the amd64 or even i386 architecture, but the raspberry pi is an ARM64 architecture. Even if you can install archlinux on a raspberry PI you could only get steam to run through qemu.

**Comment by JavaCoder5542884** [comment]
Ok thank you

**Comment by SirObby** [comment]
@cstruck Wait really? Steam supports i386?

**Comment by cstruck** [comment]
the steam binary is i386

```bash
$ file ~/.steam/steam/ubuntu12_32/steam
~/.steam/steam/ubuntu12_32/steam: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=f47803f40f25bd185db28e8a8dc9dcb2063b4d86, not stripped
```

**Comment by cstruck** [comment]
there is actually a shell script wrapped around it which does the whole library path things for it to work. that's also one reason why steam ships its own runtime. the other one is so that all games compiled for linux can be linked against their runtime and work on almost every linux distro
