### ISSUE TITLE
When I try to launch in gamescope it crashes and boots me to the login screen.

### ISSUE THREAD

**Issue by gmodn** [holoiso-eol/holoiso#62]
Tried to update it but didn't fix it. Could this possibly be a hardware issue? The computer I have it on is pretty old so I wouldn't be surprised if it was a hardware issue.

**Comment by theVakhovskeIsTaken** [comment]
What's your specs?

**Comment by gmodn** [comment]
https://cdn.discordapp.com/attachments/892146295827996674/972978568579649606/unknown.png again pretty old laptop

**Comment by theVakhovskeIsTaken** [comment]
Alright, let's see..... Can you do me a favour and run `sudo pacman -S lib32-vulkan-intel vulkan-intel` and then run `gamescope-session` in terminal?

**Comment by gmodn** [comment]
https://cdn.discordapp.com/attachments/892146295827996674/972979618699153408/IMG_1581.jpg does this when running the second command you gave me.

**Comment by gmodn** [comment]
Hey, any updates? Still stuck with this.

**Comment by theVakhovskeIsTaken** [comment]
> Hey, any updates? Still stuck with this.

I'm kinda trying to figure out how to force enable DRI3.

You can add this to /etc/X11/xorg.conf tho:

Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "SwapBuffersWait" "0"
   Option      "DRI" "3"
EndSection

**Comment by JoshDoesStuff** [comment]
> > Hey, any updates? Still stuck with this.
> 
> I'm kinda trying to figure out how to force enable DRI3.
> 
> You can add this to /etc/X11/xorg.conf tho:
> 
> Section "Device" Identifier "Intel Graphics" Driver "intel" Option "SwapBuffersWait" "0" Option "DRI" "3" EndSection

Heya, another person here. adding that command just keeps the display at starting arch-250, and 2 failed messages. Attached is a screenshot. Ran in VM to grab screenshot, but same issue shows up on my actual laptop, a Lenovo 300e
![Steam OS 3-2022-05-10-09-58-23](https://user-images.githubusercontent.com/52802454/167682703-bbc3441e-ecb8-4462-b7aa-0ac793b685cd.png)

**Comment by JoshDoesStuff** [comment]
Changing the loglevel to 7 gives some more info. It hangs after Load/Save Random seed for 3 minutes, then spits out the red block of text. 3 more minutes, then the blue block of text, then after 1 final minute, spits out the green block, and then hangs there with no more output. Sorry for crude markings.

![Steam OS 3-2022-05-10-10-07-45](https://user-images.githubusercontent.com/52802454/167684728-4d257ab5-f511-4d2e-9555-3e1e21396e98.png)

**Comment by gmodn** [comment]
> 

I don't have that file.

**Comment by theVakhovskeIsTaken** [comment]
> > > Hey, any updates? Still stuck with this.
> > 
> > I'm kinda trying to figure out how to force enable DRI3.
> > 
> > You can add this to /etc/X11/xorg.conf tho:
> > 
> > Section "Device" Identifier "Intel Graphics" Driver "intel" Option "SwapBuffersWait" "0" Option "DRI" "3" EndSection
> 
> Heya, another person here. adding that command just keeps the display at starting arch-250, and 2 failed messages. Attached is a screenshot. Ran in VM to grab screenshot, but same issue shows up on my actual laptop, a Lenovo 300e
> ![Steam OS 3-2022-05-10-09-58-23](https://user-images.githubusercontent.com/52802454/167682703-bbc3441e-ecb8-4462-b7aa-0ac793b685cd.png)
> 
> 
> 
> 

Those aren't issues in any way sincs those are just userspace system-unrelated services that are only usable on deck

**Comment by Mario-119** [comment]
Getting the same "Failed to start Jupiter Controller Firmware Update Service error" as shown above. Afterwards it kicks me back to the login screen, and this happens whenever I try to boot into Gamescope. The X11 desktop works fine, though.

**Comment by bsmntoid** [comment]
This same issue. Ryzen 7 5700G, 32 GB ram, rx6600? Any solution? Might it have to do with me installing it on an external hard drive
