### ISSUE TITLE
[offline installer] a start job is running for User Login Management (forever)

### ISSUE THREAD

**Issue by prog-amateur2** [holoiso-eol/holoiso#620]
**Specs :** 

Hello, thank you for your wonderful OS. Please find my device specs : 
_GPD Win 3, CPU : Intel Core i7 1195G7, RAM : 16GB_

**History :** 
When I try online installers, only the version `HoloISO_Stable_GUI-20220903_1502-x86_64.iso` works but I have hundreds of unable to satisfy dependency errors one step after giving the ID & password. 

When I try the Offline installers, it never enters in GUI and show `a start job is running for User Login Management`  with a timer which never end, and a line saying something like `kauditd_printk_skb: 1 callback suppressed [...] msg='unit=systemd-logind comm="systemd" exe="/usr/lib/systemd" hostname=? addr=? terminal=? res=failed`. This is more or less repeated in a loop. 

Any Offline installer, even the version `HoloISO_Stable_OfflineInstaller-20221124_0911-x86_64.iso` gives the same above result. For your information, I see on the changelog that : 

> Intel systems might not boot into gamemode, behavior excepted due to reverted MESA changes on repository merges

But I am not sure if it is related and how to solve this issue. 

**Question :** 
Please, could you reproduce this issue, and what can I do to solve it ? Thank you very much for your kind help.

**Comment by NikhilSaini38** [comment]
I faced this issue too, this happens due to udev_settle service not finishing. I was able to resolve this issue by entirely removing the said service because it's reportedly been deprecated for a couple of errors.
