### ISSUE TITLE
[Report] Forza Horizon 5 Black Screen

### ISSUE THREAD

**Issue by max676** [holoiso-eol/holoiso#623]
## Your Issue:
```
Forza Horizon 5 Black Screen but Sound -> only in GameScope, Desktop Mode is runninf Forza Horizon 5 fine. The problem is described here: https://www.reddit.com/r/linux_gaming/comments/xf0ez6/forza_horizon_5_with_gamescope/ (game launches 2 windows, one of them black screen, GameScope focuses on the wrong window)
The problem doesnt occure on the SteamDeck with latest Updates installed.
```

## Your device's full specs
```
CPU: Ryzen 5 5600U
GPU: RX6400
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221127.1305
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
yes, with steamos-update check && steamos-update now
```

**Comment by max676** [comment]
Update - changed to Beta Channel in GameScope Settings, no change :(

**Comment by cyn1c** [comment]
https://github.com/ValveSoftware/SteamOS/issues/931#issue-1479469056
Know issue. Either you start the game via desktop mode or you map gamepadkeys to ALT + ENTER and you press it as soon as you hear the gamesound.
