### ISSUE TITLE
[Report] Latest ISO download 404s

### ISSUE THREAD

**Issue by Plaer1** [holoiso-eol/holoiso#624]
## Your Issue:
```
*Latest ISO link 404s*
```

## Have you updated your installation recently?
```
I was just trying to install for the first time actually.
```

**Comment by Plaer1** [comment]
![image](https://user-images.githubusercontent.com/3485414/204575112-19324f1d-b7a0-4f3c-83b5-535381cf81f6.png)

**Comment by max676** [comment]
No problems here, all release links are working

**Comment by usama32h1** [comment]
same man :(

**Comment by Plaer1** [comment]
I had an arch install up already so I just made the ISO myself if anybody see's this here's a D.W.T.F.Y.W. link:

[Here u go, have fun.](https://drive.google.com/file/d/1lWrPTGnxd0MQGlE5ZMZ9BpBBWzea9or-/view?usp=share_link)

**DISCLAIMER:** I am not one of the devs, download provided as-is, please do not bother me or the actual devs for support (I may have made a mistake that they don't need to debug, and I can't debug any mistakes _at all_). In addition if you're reading this, you should assume this ISO is out-of-date.

**Comment by SmugZombie** [comment]
You can find the builds here, just look at the date:
http://dl.thevakhovske.pw/index.php?b=isodl
