### ISSUE TITLE
NUC with Vega GPU

### ISSUE THREAD

**Issue by krak3nnn** [holoiso-eol/holoiso#63]
Just ran through an install and everything seems to be working well. UI scaling of the box didn't not work properly and just required disabling OpenGL Composer in the dev menu. 

I just started Elden Ring and realized I don't have access to the performance (fps cap) menu. How do you access that menu on a device without the battery icon?

**Comment by theVakhovskeIsTaken** [comment]
ig you'll need a gamepad with "Options" key

**Comment by krak3nnn** [comment]
Ah, I completely missed it in the shortcut menu. 

To access the power menu with xbox and ps controllers, you just need to hit the guide button + A.
