### ISSUE TITLE
[Report] battery level is low

### ISSUE THREAD

**Issue by dimi1game** [holoiso-eol/holoiso#631]
## Your Issue:
```
*type your problem here*
```
I have the problem with a fresh installation that the error message comes up before the installation is complete
That the battery level is low ..And then the computer turns off 
## Your device's full specs
```
CPU: Ryzen 5700g
GPU: RX 5700 xt
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
ISO Update 3.3 (Bootstrap based on snapshot20221101.1327
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
cant

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
cant

```

**Comment by Griffen8280** [comment]
Fixed this on my install.  Just reboot into the HoloIso installer and use the new CHROOT feature added in the latest version.  Once you are in the chroot environment just run:
`systemctl disable upower.service`
Once I did that the service wasn't reporting that my desktop had a "low battery" and shutting down immediately.
