### ISSUE TITLE
404 download link

### ISSUE THREAD

**Issue by spe201** [holoiso-eol/holoiso#632]
the download is giving me a 404

**Comment by oman2124** [comment]
I get this too ![image](https://user-images.githubusercontent.com/91768553/206510847-08258bbb-6088-449c-86b3-8bc89b4eed5e.jpeg)

**Comment by tgienger** [comment]
So is this even possible to download?

**Comment by oman2124** [comment]
I don't think so

**Comment by kramlat** [comment]
simply disable the Russian mirror and it works.
