### ISSUE TITLE
Wsl2 support

### ISSUE THREAD

**Issue by niceEli** [holoiso-eol/holoiso#636]
when will there be wsl2 support (or if there is can you tell me how to install with wsldl)

**Comment by sanchezzjf** [comment]
why do you want wls2 support if you are already on a linux system

**Comment by niceEli** [comment]
i currently use windows and would like to use holoiso in wsl2 (preferably
decksperience) to test it out before switching to holoiso full time

**Comment by k1yrix** [comment]
Holo is based out of Arch, but since Arch does not have a WSL, Holo must not have WSL as well

**Comment by RyanHakurei** [comment]
Actually, Arch does have a WSL image albeit unofficial. You can load any rootfs tarball into WSL really.
