### ISSUE TITLE
ISO Update 4.0 download "file missing"

### ISSUE THREAD

**Issue by f3bandit** [holoiso-eol/holoiso#637]
the link for ISO Update 4.0 from this link shows "404 Not Found nginx/1.22.1"
http://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

Just a heads up

the google drive one is working tho
https://drive.google.com/file/d/1tAJQbqrg8t6hzymeynNIXp-pAzqLbYb3/view

The previous versions link were borken the same way "404 Not Found nginx/1.22.1"
the file name listed in the links for the previous versions linked to a file name that was 
not in the directory @ http://dl.thevakhovske.pw/index.php?b=isodl

![2022-12-11 (1)](https://user-images.githubusercontent.com/4943324/206928646-e667a6ab-87e2-4910-ac10-e777cb12eeb3.png)

Like I said just a heads up as the google link was working, just the self hosted ones are missing the file stated in the download link.

**Comment by bob448** [comment]
Not for me

**Comment by f3bandit** [comment]
that's very odd, well I was just giving a heads up. as I was able to download it thru the google drive link.

**Comment by ItsVixano** [comment]
> the link for ISO Update 4.0 from this link shows "404 Not Found nginx/1.22.1" http://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso
> 
> Just a heads up
> 
> the google drive one is working tho https://drive.google.com/file/d/1tAJQbqrg8t6hzymeynNIXp-pAzqLbYb3/view
> 
> The previous versions link were borken the same way "404 Not Found nginx/1.22.1" the file name listed in the links for the previous versions linked to a file name that was not in the directory @ http://dl.thevakhovske.pw/index.php?b=isodl
> 
> ![2022-12-11 (1)](https://user-images.githubusercontent.com/4943324/206928646-e667a6ab-87e2-4910-ac10-e777cb12eeb3.png)
> 
> Like I said just a heads up as the google link was working, just the self hosted ones are missing the file stated in the download link.

Can you check if the link is working now ? Should be fine now

**Comment by f3bandit** [comment]
Just this
![2022-12-12](https://user-images.githubusercontent.com/4943324/206981453-f03c8be4-9c64-410b-af86-3ba256c4237d.png)

**Comment by ItsVixano** [comment]
> Just this ![2022-12-12](https://user-images.githubusercontent.com/4943324/206981453-f03c8be4-9c64-410b-af86-3ba256c4237d.png)

Check again, is strange that nginx redirects you somewhere else

**Comment by f3bandit** [comment]
404 again

**Comment by ItsVixano** [comment]
> 404 again

Increased the timeout connection time, see again :/

**Comment by f3bandit** [comment]
nope

**Comment by ItsVixano** [comment]
> nope

Try again :(

**Comment by Thelvaen** [comment]
can confirm I just tried, I have a 404 as well.

**Comment by ItsVixano** [comment]
> can confirm I just tried, I have a 404 as well.

Mind trying it again ?? Go on  http://holoiso.itsvixano.me and tell me the result

**Comment by xmstspider** [comment]
> > can confirm I just tried, I have a 404 as well.
> 
> Mind trying it again ?? Go on http://holoiso.itsvixano.me and tell me the result

404 there as well.

And it looks like Gdrive is overloaded, throwing Quota exceeded.

**Comment by Thelvaen** [comment]
I can see the page `Index of /` now, and the download link seems to be working (can't really download it on my work computer atm, but I'm prompted to download an iso file.

**Comment by ItsVixano** [comment]
> > > can confirm I just tried, I have a 404 as well.
> > 
> > 
> > Mind trying it again ?? Go on http://holoiso.itsvixano.me and tell me the result
> 
> 404 there as well.
> 
> And it looks like Gdrive is overloaded, throwing Quota exceeded.

Well the log is clear now, try again, should be fine now

**Comment by xmstspider** [comment]
> Well the log is clear now, try again, should be fine now

Hmm both [https://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso](https://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso) and [https://holoiso.itsvixano.me](https://holoiso.itsvixano.me) are still throwing 404. Tested with 2 different browsers.

**Comment by Thelvaen** [comment]
same here, back to 404.

**Comment by f3bandit** [comment]
404

**Comment by ItsVixano** [comment]
Hi everyone, sorry for the inconvenience, i've just managed to trigger the issue at my school computers

from now on, i've registered the ssl keys and migrated to https protocol instead

It "should" works fine now

Let me know if anything is broken :D 

https://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

**Comment by xmstspider** [comment]
> Hi everyone, sorry for the inconvenience, i've just managed to trigger the issue at my school computers
> 
> from now on, i've registered the ssl keys and migrated to https protocol instead
> 
> It "should" works fine now
> 
> Let me know if anything is broken :D
> 
> https://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

Thanks, both links are working now

**Comment by ItsVixano** [comment]
> > Hi everyone, sorry for the inconvenience, i've just managed to trigger the issue at my school computers
> > from now on, i've registered the ssl keys and migrated to https protocol instead
> > It "should" works fine now
> > Let me know if anything is broken :D
> > https://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso
> 
> Thanks, both links are working now

Nais
