### ISSUE TITLE
Image Tearing Launching Gamescope [Report]

### ISSUE THREAD

**Issue by bkdfkup** [holoiso-eol/holoiso#638]
## Your Issue:
```
Graphical issues in recent releases when booting into gamescope mode, where process stops at Verifying Installation, and image is "torn".  Desktop works fine. Image attached as example of issue.

Have attempted all kernal options in grub. All producing the same issue.

I have had a successful installation a few months back, but recent releases have failed.

```

## Your device's full specs
```
CPU: Intel I7
GPU: iGPU
Device: Microsoft Surface Laptop 4
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
http://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
Nil
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Yes 
```

**Comment by bkdfkup** [comment]
![PXL_20221213_025227036 MP](https://user-images.githubusercontent.com/74683396/207216386-c7985169-17e8-45d8-be43-48d2afbe34c8.jpg)

**Comment by Pempoii** [comment]
I'm having the exact same problem with a surface pro 4 tablet.
Connecting an external monitor doesn't help.
I am able to get into the desktop by using the terminal with crtl alt f4 and running
steamos-session-select plasma
sudo reboot

Have tried different resolutions by editing gamescope session file, and disabling composition in destktop setting no success

**Comment by fuzzysb** [comment]
I have this same issue on a OneXPlayer 1S Intel I7 and XE Graphics, just installed the 4.0 offline iso

**Comment by InstantComet** [comment]
same issue here

**Comment by InstantComet** [comment]
Tried manually installing mesa 22.3.1, some progress, now stuck at Update complete. launching steam

**Comment by InstantComet** [comment]
log here
[Text File.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/10315917/Text.File.txt)

**Comment by InstantComet** [comment]
After plugging in an external display I did get to the opening animation, but it stuck at boot loop.
