### ISSUE TITLE
[Report] Unable to install SteamOS using the install script

### ISSUE THREAD

**Issue by IvoDeK** [holoiso-eol/holoiso#639]
## Your Issue:
```
It throws me an error after I create the passwords I get the following:

----
mount: /mnt/home: can't find in /ect/fstab.
Error: Something went wrong when mounting home partition. Please try again!
----

Repeating this will cause the same error to occur. I guess some issue with the script?
I also don't know why, but I can't select another installer. When I press a button the 15s wait time goes away and then never responds to any key input again.
```

## Your device's full specs
```
CPU: Intel i9-9880H
GPU: AMD ATI Radeon RX 5500M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426 (Using latest 4.0 Live ISO)
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
No
```

**Comment by IvoDeK** [comment]
Fixed by zero wiping my free space

**Comment by ValfarDeveloper** [comment]
> Fixed by zero wiping my free space

how did you did that? just facing this problem right now in my device, and I just tried to compile zerofree utility but it doesn't recognize the disk. Yet isn't completelly clear to me, should I wipe the disk with the empty space? or the partitions created by holoiso?
Right now I'm trying to install holoiso in a ssd this to have a dual boot machine.

Also I think that the feature of wiping the disk/partition should be included in the holo installation script.
