### ISSUE TITLE
Not seeing Kernel 6.x

### ISSUE THREAD

**Issue by maddox** [holoiso-eol/holoiso#641]
After numerous attempts at trying to upgrade an install I did last October, I finally just did a fresh install, and I'm still not seeing it being on the 6.x kernel. Is there something we have to do special for this?

Does it even matter? I'm not exactly sure which version numbers we should be paying attention to in the System panel while running Holoiso.

**Comment by S1ngl3-x** [comment]
Can I ask you how you got kernel 6.x working in holoiso (hopefully without too much hassle)?
