### ISSUE TITLE
[Issue] Multiple Errors (Likely Intel Caused)

### ISSUE THREAD

**Issue by AceSardonyx** [holoiso-eol/holoiso#643]
There are multiple errors but I will just describe the major 2 and are the most common error I get.
After installing the system, booting normally does not work.
I have to go in to recovery and disable sessions so that it will boot properly.
Sometimes, it does fix the main boot selection and sometimes it does not. It's a game of chance with each installation.
Second major issue is that SteamOS does not work, but the desktop does after I implement the fixes for the first one.
Sometimes, I will get to hear the sounds for it every installation or two along with the cursor with some white static artifacts.

![image](https://user-images.githubusercontent.com/77860646/207994644-777ffe7e-5ec3-40de-9a5b-e4b8ef385a1f.png)

I tried with all from 3.0 to 4.0 although I do not want to use some of the olders ones that have worked better in fear of incompatibility.
The latest version as of today (Dec 16) has the same isues

```
This new offline installer does not allow me to select the installation type for some reason?
I believe it defaults to barebones even though the whole deck is enabled after installing so that is very weird.
```
Also, is it ok to use ventoy to install? I was afraid I was not allowed so I tried it without it too.

**Comment by C7YPT0N1C** [comment]
A slightly long winded fix that worked for me (lastest 4.0 iso):

> Install without ventoy (write iso to usb or ssd)

>Install without WiFi. Do not update any packages in installer.

>Once installation is done, reboot.

>Upon first boot, boot into recovery image and run "holoiso-disable-sessions" to disable sessions. Type "exit". You should boot into the desktop experience.

>(This method seems to skip the OOBE set up screen, so change system language / time zone in settings here)

>Steam should open. Close it.
>Connect to internet (you're on your own for this one, I can't really help here)
>Reopen steam. It should update. Sign into steam.
>Once you've signed into steam, close it.

>Open terminal and check if polkit is installed:
>"sudo pacman -S polkit" to check if installed
>"sudo pacman -Sy polkit" to install if not already

>Update system packages just in case  (if there is a package called "*something*-hw-support", don't update it, as it will cause the update to fail").

>If everything install / updates without issue, reboot back into recovery image and enable sessions ("holoiso-enable-sessions") and exit.

>After this, test install by going into desktop experience and running command "gamescope-session" in terminal, or returning to deck mode.

**Comment by AceSardonyx** [comment]
> A slightly long winded fix that worked for me (lastest 4.0 iso):
> 
> > Install without ventoy (write iso to usb or ssd)
> 
> > Install without WiFi. Do not update any packages in installer.
> 
> > Once installation is done, reboot.
> 
> > Upon first boot, boot into recovery image and run "holoiso-disable-sessions" to disable sessions. Type "exit". You should boot into the desktop experience.
> 
> > (This method seems to skip the OOBE set up screen, so change system language / time zone in settings here)
> 
> > Steam should open. Close it.
> > Connect to internet (you're on your own for this one, I can't really help here)
> > Reopen steam. It should update. Sign into steam.
> > Once you've signed into steam, close it.
> 
> > Open terminal and check if polkit is installed:
> > "sudo pacman -S polkit" to check if installed
> > "sudo pacman -Sy polkit" to install if not already
> 
> > Update system packages just in case  (if there is a package called "_something_-hw-support", don't update it, as it will cause the update to fail").
> 
> > If everything install / updates without issue, reboot back into recovery image and enable sessions ("holoiso-enable-sessions") and exit.
> 
> > After this, test install by going into desktop experience and running command "gamescope-session" in terminal, or returning to deck mode.

One liiittttllee issue. Everything else works accept the first step because not using ventoy boots to the efi shell screen and not holo iso in any way. I will update if this worked though. I really don't think ventoy makes any issues though.

**Comment by k1yrix** [comment]
I see you have a Celeron. Yes...those I believe are underpowered to at least get good performance with SteamOS we are at right now. You might as well have a machine with a Core or a Ryzen or else I believe you are on your own...

**Comment by AceSardonyx** [comment]
> I see you have a Celeron. Yes...those I believe are underpowered to at least get good performance with SteamOS we are at right now. You might as well have a machine with a Core or a Ryzen or else I believe you are on your own...

It's a garbage cpu, but it runs very well despite my expectations. For some reason, it runs better than on windows but Iwant this to work, not perform good. I will be using amd in the future though.

**Comment by C7YPT0N1C** [comment]
> > A slightly long winded fix that worked for me (lastest 4.0 iso):
> > 
> > > Install without ventoy (write iso to usb or ssd)
> > 
> > > Install without WiFi. Do not update any packages in installer.
> > 
> > > Once installation is done, reboot.
> > 
> > > Upon first boot, boot into recovery image and run "holoiso-disable-sessions" to disable sessions. Type "exit". You should boot into the desktop experience.
> > 
> > > (This method seems to skip the OOBE set up screen, so change system language / time zone in settings here)
> > 
> > > Steam should open. Close it.
> > > Connect to internet (you're on your own for this one, I can't really help here)
> > > Reopen steam. It should update. Sign into steam.
> > > Once you've signed into steam, close it.
> > 
> > > Open terminal and check if polkit is installed:
> > > "sudo pacman -S polkit" to check if installed
> > > "sudo pacman -Sy polkit" to install if not already
> > 
> > > Update system packages just in case  (if there is a package called "_something_-hw-support", don't update it, as it will cause the update to fail").
> > 
> > > If everything install / updates without issue, reboot back into recovery image and enable sessions ("holoiso-enable-sessions") and exit.
> > 
> > > After this, test install by going into desktop experience and running command "gamescope-session" in terminal, or returning to deck mode.
> 
> One liiittttllee issue. Everything else works accept the first step because not using ventoy boots to the efi shell screen and not holo iso in any way. I will update if this worked though. I really don't think ventoy makes any issues though.

Very sorry for the late reply, but HoloISO DOES NOT play nice with ventoy 💀

It's honestly a hassle, but you'll have to write it to a usb, which is a pain cuz I'm using the 3.0, 4.0 and 4.1 ISOs to attempt bug fixes

**Comment by AceSardonyx** [comment]
@C7YPT0N1C It is for me because I am so used to being able to throw the iso onto ventoy and having it work.
I have not flashed a usb in a while and I have to move stuff off of one now 😭
Thank you very much though. I will retry it for sure.

**Comment by C7YPT0N1C** [comment]
I feel you man 😭

I bought a 64gb usb stick and use it for ventoy, expecting everything to work.

Then there's that ONE iso that forces me to flash it to another usb lmfao

Good luck!
