### ISSUE TITLE
[Report] power-button-handler.py problem while launching gamescope-session

### ISSUE THREAD

**Issue by myr1299vfx** [holoiso-eol/holoiso#644]
## Your Issue:
Cannot boot into gamescope UI (at least Desktop mode still works perfectly), trying to execute gamescope-session shows several power-button-handler.py lines, disabling compositor (Alt + Shift + F12) ended up with endless power-button-handler.py lines. My early thoughts goes to partial Vulkan support for pre-Skylake iGPU's, but after saw power-button-handler.py problem i don't know what the actual problem is. 

## Your device's full specs
```
CPU: Intel Core i5-4310M
GPU: Intel HD Graphics 4600
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221212.1224
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
(myr-12@holoiso ~)$ gamescope-session
rm: cannot remove '/home/myr-12/.config/gamescope/modes.cfg': No such file or directory
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
wlserver: [backend/headless/backend.c:82] Creating headless backend
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
vulkan: selecting physical device 'Intel(R) HD Graphics 4600 (HSW GT2)': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [xwayland/server.c:92] Starting Xwayland on :2
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55b8eebfd0a0 (res 0x55b8eebf5e50)
wlserver: [xwayland/server.c:250] Xserver is ready
wlserver: [types/wlr_surface.c:741] New wlr_surface 0x55b8eebf85d0 (res 0x55b8eebe3d60)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 65
pipewire: renegotiating stream params (size: 1280x720)
gamescope-session: detected broken Steam, bootstrapping from OS copy...
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
```

## Your installation type:
```
deckperience (full installation from v4.0 live ISO)
```

## Have you updated your installation recently?
```
yes 
```

**Comment by nisehime** [comment]
I have Intel HD 4400 and I also can't boot into gamescope. Fresh install from latest ISO

**Comment by C7YPT0N1C** [comment]
A fix that seemed to work for me:

Boot into recovery image and run "holoiso-disable-sessions" to disable sessions. Type "exit". You should boot into the desktop experience.

Open terminal and check if polkit is installed:
- "sudo pacman -S polkit" to check if installed 
- "sudo pacman -Sy polkit" to install if not already

Update system packages just in case  (if there is a package called "*something*-hw-support", don't update it, as it will cause the update to fail").

If everything install / updates without issue, reboot back into recovery image and enable sessions ("holoiso-enable-sessions") and exit.

After this, gamescope should work. Test by going into desktop experience and running command "gamescope-session" in terminal, or returning to deck mode.

**Comment by nisehime** [comment]
Didn't work for me. I think the issue is that Intel HD 4000 simply not supported, although readme says that Intel iGPUs up to 11th gen Iris Xe should work. I remember earlier it was written that you need to downgrade Mesa for Intel but it's gone now for some reason.
