### ISSUE TITLE
Holoiso installer gets stuck on welcome to steamos

### ISSUE THREAD

**Issue by Copenhagen432** [holoiso-eol/holoiso#649]
## Your Issue:
```

Booting from offline usb installer hangs on Welcome to SteamOS!

```

## Your device's full specs
```
CPU: 5900hx
GPU: RX 6800m
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Latest release: version 4
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
No, unsure how to access terminal
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
Yes
```

**Comment by alou-S** [comment]
Same issue with my. Similar specs:

CPU : 5800H
GPU : 6600M

**Comment by apalazzi** [comment]
Same issue here, my specs are:
CPU: 5800X
GPU: RX 6700 XT
Running on a QEMU virtual machine.

**Comment by onykster** [comment]
I am having same issue for my HP Victus laptop (AMD Ryzen 7 5800H / GPUAMD RX 5500M

**Comment by onykster** [comment]
I am having same issue for my HP Victus laptop (AMD Ryzen 7 5800H / GPUAMD RX 5500M

**Comment by onykster** [comment]
I am having same issue for my HP Victus laptop with (Processor - Ryzen 7 5800H / GPU - AMD RX 5500M)
