### ISSUE TITLE
issue with graphics intel 11gen

### ISSUE THREAD

**Issue by serj-47** [holoiso-eol/holoiso#650]
## Your Issue:
```
I downloaded the latest iso v4.0. And it seems the installation was successful. After that, I pulled out the bootable flash drive, the perk loaded, but the os itself does not boot. The OS startup sound at was played normally
```

## Your device's full specs
```
Laptop MSI Modern 15 B11M with core i3-1115g4 with Intel UHD Graphics Xe G4 48EUs
```

**Comment by serj-47** [comment]
![IMG20221218171037](https://user-images.githubusercontent.com/3147011/208303482-011a4af2-c432-41ce-a051-c6a985c44ecc.jpg)

**Comment by xis666** [comment]
ctrl alt f2
type your user and password

type: steamos-session-select plasma
type: reboot

**Comment by bkdfkup** [comment]
Thanks for the advice, i have used this previously. My  issue is with gamescope, not the desktop GUI.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by serj-47** [comment]
Yes, it helped, the desktop is now displayed normally. But when I press shortcut Return to Gaming mode, the system restarts, but still a black screen with the sound of the system starting.

**Comment by InstantComet** [comment]
> Yes, it helped, the desktop is now displayed normally. But when I press shortcut Return to Gaming mode, the system restarts, but still a black screen with the sound of the system starting.

Same here

**Comment by kzieres61** [comment]
> ## Your Issue:
> ```
> I downloaded the latest iso v4.0. And it seems the installation was successful. After that, I pulled out the bootable flash drive, the perk loaded, but the os itself does not boot. The OS startup sound at was played normally
> ```
> 
> ## Your device's full specs
> ```
> Laptop MSI Modern 15 B11M with core i3-1115g4 with Intel UHD Graphics Xe G4 48EUs
> ```

Same issue fresh install on 2 separate Intel based builds. but gen 7 and gen 8 intel chips. onboard intel graphics, no external vid card.

**Comment by ChandlerHooley** [comment]
[See this thread, we were able to fix the issue.](https://github.com/theVakhovskeIsTaken/holoiso/issues/672)
