### ISSUE TITLE
[Report] Pacman Doesnt Update

### ISSUE THREAD

**Issue by Worldgate** [holoiso-eol/holoiso#657]
## Your Issue:
```
When I try to update or install anything via pacman I receive.

[root@holoiso ~]# pacman -Syu
:: Synchronizing package databases...
 holoiso-stable is up to date
 holostaging is up to date
 jupiter.db failed to download
 holo.db failed to download
 core.db failed to download
 extra.db failed to download
 community.db failed to download
error: failed retrieving file 'jupiter.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'holo.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'core.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: too many errors from steamdeck-packages.steamos.cloud, skipping for the remainder of this transaction
error: failed retrieving file 'extra.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'community.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)

```

## Your device's full specs
```
CPU: Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
GPU: Radeon RX 6800/6800 XT / 6900 XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426
```

## Your installation type:
```
deckperience
```

**Comment by cirolaferrara** [comment]
Same here. Try:
# wget https://raw.githubusercontent.com/theVakhovskeIsTaken/holoiso/stable/airootfs/etc/pacman.conf -o /etc/pacman.conf
# pacman -Syu

**Comment by Worldgate** [comment]
Found this on reddit.

[Rafinesque](https://www.reddit.com/user/Rafinesque/)
·
[1 day ago](https://www.reddit.com/r/SteamDeck/comments/zrc2ep/comment/j14iysa/?utm_source=reddit&utm_medium=web2x&context=3)
·
edited 23 hr. ago
512GB
This worked but your instructions aren't very clear for people not used to being in these config files. Here's an example of what he's talking about changing - the section headings:

[jupiter-3.3]
[holo-3.3.3]
[core-3.3]
[extra-3.3]
[community-3.3]
[multilib-3.3]

You may have to change these back whenever the issue with the repositories is fixed.

Edit: SteamOS 3.4 just dropped in the beta channel. That might be why the repositories were offline, and the new version might break this fix. I haven’t had a chance to test it yet.

**Comment by Worldgate** [comment]
It ended up saying conflicting packages.

**Comment by Worldgate** [comment]
The most recent iso that you were asking for someone to test, does seem to work now.  It's now pulling updates and rebooting so looks like its good to go.  Thanks. :)
