### ISSUE TITLE
GPU power managemenr

### ISSUE THREAD

**Issue by 420247paul** [holoiso-eol/holoiso#66]
My gpu is being power limited  to 45 watts is there a work around besides just closing the github issue.

**Comment by massatt212** [comment]
what GPU u have, cause i have the same problem with a RX 470, once -steamos3 enable gpu power drops by almost 70%

**Comment by 420247paul** [comment]
5600xt i have tried a few things installing the arch mesa and lib32 mesa pacage nothing works so far on vanilla arch i can hit 150 fps now just 30

**Comment by krak3nnn** [comment]
Having a similar issue with the RX Vega M GH. The chip is getting only about 15w and clocks only reach ~400Mhz.

**Comment by massatt212** [comment]
i think -steamos3 is made only for steam deck, prob have a limiter in the software so the apu wont overheat.

**Comment by krak3nnn** [comment]
where is the -steamos3 flag set? grub boot?

**Comment by massatt212** [comment]
/usr/bin/gamescope-session, if u replace steamos3 with steamos u loose almost all the benefits only the ui works and install sudo pacman -S nano so u can sudo nano /usr/bin/gamescope-session and re-enable steamos3 cause you will loose the ability to swap to desktop.

**Comment by rbrugnolli** [comment]
So I was the one who opened the problem topic, imagine how unhappy I was when they closed the topic.
There must be some setting that removes this limiter, as ChimeraOS has it they use the gamescope-session and it doesn't limit it.

**Comment by massatt212** [comment]
chimeraos prob using -steamos and not -steamos3 so u dont get the full benefits

**Comment by rbrugnolli** [comment]
I must have Chimera installed on a test HD at home, as soon as it arrives I can see how it is there.

**Comment by rbrugnolli** [comment]
Looking at Chimera here, it doesn't really put steam3, it has two different methods in it, I just don't know what it would be

1st steam -tenfoot -steamos -pipewire-dmabuf

2nd steam -gamepadui -steamos

**Comment by massatt212** [comment]
best to wait on valves release, or an update, prob doesnt work on all GPU, valve may release update when nvidia gets their act together.

**Comment by 420247paul** [comment]
dude figured it out guys if yall still need a fix

**Comment by krak3nnn** [comment]
Did you try the fix from this ticket?
#94

**Comment by 420247paul** [comment]
yes it works for me

**Comment by massatt212** [comment]
2TB of games down the drain again, why did I waste my time, their isn't any tdp file to edit
