### ISSUE TITLE
[Report] Install boots to sound and black screen

### ISSUE THREAD

**Issue by GormAuslander** [holoiso-eol/holoiso#664]
## Your Issue:
```
Selecting any boot option, inlcuding recovery mode, results in a flashing black screen, an eventual startup sound, and then a frozen black screen with a hyphen displayed in the top left corner.
```

## Your device's full specs
```
CPU: Intel Pentium Gold 4425Y
GPU: Intel HD Graphics 610
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
ISO Update 4
```

**Comment by OrionMelaeno** [comment]
Had the same issue, and I made the bad decision to clear drive, so now I'm stuck...

**Comment by shrshnka** [comment]
Seems to be common issue to intel hd

**Comment by worldofgeese** [comment]
Is there a workaround for Intel users? XPS 13 9380 here.

**Comment by cookiejar5081** [comment]
Same issue.
