### ISSUE TITLE
HoloISO installer cannot boot from USB device

### ISSUE THREAD

**Issue by TGSAN** [holoiso-eol/holoiso#666]
## Your Issue:
```
HoloISO installer cannot boot from USB device.
1. Use a USB 2.0 disk (has flash HoloISO 4.0 ISO file).
2. Boot and select HoloISO Installer.
3. Print error: hub 4-0:1.0: config failed, hub doesn't have any ports! (err -19).
```

## Your device's full specs
```
CPU: AMD Zhongshan CPU (Base Zen 1st-Gen)
GPU: AMD Fenghuang GPU (Base AMD Vega)
```

## LOG
```
hub 4-0:1.0: config failed, hub doesn't have any ports! (err -19)
```

## Your installation type:
```
HoloISO 4.0
```

## Have you updated your installation recently?
```
first to install.
```

**Comment by Christ0phH** [comment]
'+ 1 on this issue using a external SSD as mass storage.

Case: NZXT H1 [2022]  
CPU (Prozessor): AMD Ryzen 7 7700X \| 8x 4,5GHz, 32MB L3 
Mainboard: ASUS ROG Strix B650E-I \| AMD B650 
Graphics: AMD Radeon RX 7900 XT \| Sapphire MBA |
RAM: 32GB Corsair Vengeance DDR5-5600 \| 2x 16GB 
SSD  (M.2 / PCIe): 1TB Western Digital Black SN850X PCIe 4.0 {target drive}
Sound: HD-Audio Onboard

**Comment by rzippo** [comment]
> * 1 on this issue using a external SSD as mass storage.
> 
> Case: NZXT H1 [2022]   CPU (Prozessor): AMD Ryzen 7 7700X | 8x 4,5GHz, 32MB L3 Mainboard: ASUS ROG Strix B650E-I | AMD B650 Graphics: AMD Radeon RX 7900 XT | Sapphire MBA | RAM: 32GB Corsair Vengeance DDR5-5600 | 2x 16GB SSD (M.2 / PCIe): 1TB Western Digital Black SN850X PCIe 4.0 {target drive} Sound: HD-Audio Onboard

I have the same issue on a similar build.
Same case and motherboard, Ryzen 7600, no dedicated GPU.

The installer seems stuck after the message above.

**Comment by Christ0phH** [comment]
> > * 1 on this issue using a external SSD as mass storage.
> > 
> > Case: NZXT H1 [2022]   CPU (Prozessor): AMD Ryzen 7 7700X | 8x 4,5GHz, 32MB L3 Mainboard: ASUS ROG Strix B650E-I | AMD B650 Graphics: AMD Radeon RX 7900 XT | Sapphire MBA | RAM: 32GB Corsair Vengeance DDR5-5600 | 2x 16GB SSD (M.2 / PCIe): 1TB Western Digital Black SN850X PCIe 4.0 {target drive} Sound: HD-Audio Onboard
> 
> I have the same issue on a similar build. Same case and motherboard, Ryzen 7600, no dedicated GPU.
> 
> The installer seems stuck after the message above.

For me the following things DID NOT FIX the issue:
- updating Bios to newest version
- Using a different flash software (both belena and rufus resulted in the same error)
- using a different built: Offline ISO installer image build-date 2023-03-24 
 (https://github.com/HoloISO/holoiso/issues/743) 
- using different usb-ports on the mainboard or case
- using different mass storages besides usb-c SSD ( tried sticks with usb2/3/c)

**Comment by rzippo** [comment]
I tried using the latest build of Chimera OS, and I could spot the same error message displayed - however the installer continued booting, and I was able to install and then boot the OS.

**Comment by Christ0phH** [comment]
> I tried using the latest build of Chimera OS, and I could spot the same error message displayed - however the installer continued booting, and I was able to install and then boot the OS.

so chimera now is your workaround until our holo issue is fixed? Will look into it, thanks for the hint !

**Comment by TGSAN** [comment]
I tried Chimera OS and it does continue to install after showing the same error message.

**Comment by pimboli** [comment]
Same here. 
I tried beta versions 4.2 and 4.5 which do not hang at this error, but there I have other issues.

**Comment by pimboli** [comment]
> 

I also tried booting via SSD (image) and not having anything in USB ports, but same problem

Also I found out its not related to the 7900xt, because with onboard GPU I have the same problem

**Comment by pimboli** [comment]
> I tried Chimera OS and it does continue to install after showing the same error message.

where you able to have AMD drivers in Chimera? I only have mesa with horrible FPS's

**Comment by Christ0phH** [comment]
> 

Im playing Elden Ring with Chimera now. Generally works but sometimes the Proton-GE has some hickups. Deleting the files and using a fresh version works most of the time. When that's the case i can play the game with max settings online with good fps.

**Comment by Christ0phH** [comment]
> > I tried Chimera OS and it does continue to install after showing the same error message.
> 
> where you able to have AMD drivers in Chimera? I only have mesa with horrible FPS's

Im playing Elden Ring with Chimera now. Generally works but sometimes the Proton-GE has some hickups. Deleting the files and using a fresh version works most of the time. When that's the case i can play the game with max settings online with good fps.
