### ISSUE TITLE
Black screen after installation with AMD Radeon R9 M275X

### ISSUE THREAD

**Issue by elkuchmanuel** [holoiso-eol/holoiso#669]
I had an old Gigabyte AMD gaming PC and tried to install holoiso. Installation no problem, booting menu also good.
After leaving the booting menu I get a black screen and it seeems to stuck.

The PC ist this one: https://www.gigabyte.com/Mini-PcBarebone/GB-BXA8G-8890-rev-10#ov
In the installation description it says a GPU supporting RADV Drivers instead of Radeon is needed. Could this be the problem?

**Comment by elkuchmanuel** [comment]
in the logs i saw this
radeon 0000:01:00:0  vram limit (0) must be power a of 2

**Comment by elkuchmanuel** [comment]
when I boot with the USB drive an I open the steam client from the desktop app I get following error after installing a game:  failed to initialize grapics. make shure Direktx is installed....

**Comment by TRINCETT** [comment]
Where do you find the log file? I am having an issue with the boot too.

**Comment by rfrayer420** [comment]
Same issue here with R7
