### ISSUE TITLE
Errors when installing on SD Card

### ISSUE THREAD

**Issue by Mario-119** [holoiso-eol/holoiso#67]
Opening another issue because mine was closed for some reason that wasn't stated. Whenever I try to install HoloISO onto an SD Card, multiple errors are thrown and the flashed SD Card doesn't boot properly (either boots into TTYL or a broken Arch login screen). I've tried two different brands of 128gb SD Cards, but the same thing happens. It also seems to lock the SD Cards in a read only state so when I attempt to wipe them nothing really happens, the holo-root partition stays intact. Below are some of the errors the installer threw for reference.
![20220508_034945](https://user-images.githubusercontent.com/15970874/167323966-e7fa6008-3e50-420b-acd4-0f91c7b0fbe6.jpg)

**Comment by theVakhovskeIsTaken** [comment]
Apparently, BTRFS and SDCard doesn't go well.

Modify the script while inside the ISO, so that it formats the card to ext4

**Comment by Mario-119** [comment]
I'll give it a try, thanks
