### ISSUE TITLE
weird ui crashing after installing

### ISSUE THREAD

**Issue by retrocountry** [holoiso-eol/holoiso#671]
## Your Issue:
it looks verry glitchy and i can read barelly read "veryfying installation"
```

## Your device's full specs
```
CPU: Intel core i5
GPU: Nvidia GeForce RTX 3050 Laptop Graphics Card
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```HOLOISO IDIOTS
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```idk
yeah pubg crash bhai
```

## Your installation type:
```laptop
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by bob448** [comment]
Did you read the description? It says no NVIDIA gpu are supported.

**Comment by retrocountry** [comment]
well can i install steamos a different way?
