### ISSUE TITLE
[Feature Request]Pls add steam++ support.

### ISSUE THREAD

**Issue by greatliu** [holoiso-eol/holoiso#673]
Dear author,
I am very glad to use holoiso. But I can not visit steam directly, in windows I need the tool steam++.
Can you add steam++ in holoiso? I found it support arch, but we do not know how to install it.
Thanks.

**Comment by winzkh** [comment]
```bash
cd
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -Sy watt-toolkit-bin # or install watt-toolkit-git
```

**Comment by winzkh** [comment]
You can use yay to install steam++
Now, steam++ has been renamed Watt Toolkit

**Comment by greatliu** [comment]
When I send this issus I used AMD rx460, but today I do not have that card, I just tried AMD firepro m5100(GCN) and can not show the steam desktop.
Thanks for your reply, next time when I get a proper card I will have a try.
