### ISSUE TITLE
How to install games on another hdd?

### ISSUE THREAD

**Issue by greatliu** [holoiso-eol/holoiso#674]
Dear author.
Sorry to open a new issue.
How to install game on another hdd? I installed holoiso on hdd1, and want to install games on hdd2.
The ui just shows "format SD", but the color is gray and can not click.
Thanks.

**Comment by winzkh** [comment]
First of all, you must mount your hard disk (the hard disk must be mounted with executable permissions)
Then, follow the https://help.steampowered.com/en/faqs/view/4578-18A7-C819-8620 Tips in Add Steam Library

**Comment by sojab0on** [comment]
Its not that hard, 
if you go back to the desktop mode in start there is an partition manager 
format the drive to btrfs or ext4 and give it a mount point. be shure that users can mount and unmount it

after that start steam on the desktop and go to settings --> downloads and click steam library folders there click the + and it should auto select the drive. 

If not the trick is to make the folder the drive is mounted to (example /mnt/drive1) had the group users with rwx rights 

to do that open konqurer (terminal) and type the following 

sudo su beware you gain root rights with this.

then type 
chown (your normal username) /mnt/drive1 hit enter now your normal users has ownership rights 

kill the terminal 

open file browser (dolphin) 
go to holoiso-root and click mnt  in the mnt folder right click on drive1 and click properties
then go to the tab premisions 
and advanced premisions 

and select group and click add then go trough the drop down and select the group users.
give them rwx and click okay 
after that steam desktop mode should auto detect the drive mounted on /mnt/drive1 as usable storage

**Comment by greatliu** [comment]
When I send this issus I used AMD rx460, but today I do not have that card, I just tried AMD firepro m5100(GCN) and can not show the steam desktop.
Thanks for your reply, next time when I get a proper card I will have a try.

**Comment by mrbwhitby** [comment]
@sojab0on 
Thank you so much!
It was driving me craze that I couldn't get this to work, but following your instructions got everything perfect.

I will have to admit to not following your instructions to the letter, at first.
I missed the part where you said:

>  start steam on the desktop 

I simply mounted, gave myself permission to the drive and went back into the SteamOS gui
NOT Steam on the DESKTOP.

That was the integral part I missed. Doing that fixed it.

Thanks so much!
