### ISSUE TITLE
Can't update and GLIBC isn't preinstalled (got a question too)

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [holoiso-eol/holoiso#675]
## Your Issue:
When I try to update these three things in discover, I get this:
![image](https://user-images.githubusercontent.com/88291316/210489541-75912582-f82c-424d-9994-c00d2414bcdc.png)
When I try to update per terminal per pacman I get this :( :
![image](https://user-images.githubusercontent.com/88291316/210489610-215a8859-c955-4178-be43-670f4a4e0e00.png)
I also got a question, how do I enable AUR? I didn't find it in the settings or discover. Some help :)?

*Type your problem here*
I don't know how I can fix this, I had it since I installed holoiso. I tried to fix it by restarting and updating in DeckUI nothing worked though.
Can't really install GLIBC because AUR is so hard to install.

## Your device's full specs
```
CPU: AMD Ryzen 5 3600 (12) @ 4.200GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT / 6800M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
4.0 propably installed it 3 days ago
Not really sure maybe this screenshot will help :/
![image](https://user-images.githubusercontent.com/88291316/210490104-6296720e-0e98-4035-8da6-92ab5860d50d.png)
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
i have no idea what you want from me here
```

## Your installation type:
```
deckperience propably (i boot into deckui)
```

## Have you updated your installation recently?
```
cant :( looks broke
```

**Comment by sojab0on** [comment]
same here , i tried to isntall holo iso 4 and even 3 booth during installation give the same database errors 
If after install i run pacman -sY then it also give database file errors on all but the basic arch ones 

root@steamos michel]# pacman -Sy
:: Synchronizing package databases...
 holoiso-stable                                5.6 KiB  12.3 KiB/s 00:00 [########################################] 100% holostaging                                1933.0   B  4.17 KiB/s 00:00 [########################################] 100% jupiter.db failed to download
 holo.db failed to download
 core.db failed to download
 extra.db failed to download
 community.db failed to download
error: failed retrieving file 'holoiso-stable.db' from dlcdn2.thevakhovske.pw : Failed to connect to dlcdn2.thevakhovske.pw port 80 after 19 ms: Connection refused
error: failed retrieving file 'holostaging.db' from dlcdn2.thevakhovske.pw : Failed to connect to dlcdn2.thevakhovske.pw port 80 after 19 ms: Connection refused <-- fixed (/etc/pacman.d/holo_mirrorlist) nao and # out the lines not for my geo region 
error: failed retrieving file 'holoiso-stable.db' from dl.thevakhovske.pw : Failed to connect to dl.thevakhovske.pw port 80 after 8 ms: Connection refused <-- fixed (/etc/pacman.d/holo_mirrorlist) nao and # out the lines not for my geo region 
error: failed retrieving file 'holostaging.db' from dl.thevakhovske.pw : Failed to connect to dl.thevakhovske.pw port 80 after 8 ms: Connection refused<-- fixed (/etc/pacman.d/holo_mirrorlist) nao and # out the lines not for my geo region  
error: failed retrieving file 'core.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'community.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
warning: too many errors from steamdeck-packages.steamos.cloud, skipping for the remainder of this transaction
error: failed retrieving file 'jupiter.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed retrieving file 'holo.db' from steamdeck-packages.steamos.cloud : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
How do i setup the right db paths for the steamdeck package repos? 

is what pacman trows on 3.3 iso and 4.0 iso after install it wont boot to gui on my device 

AMD ryzen 5 3400g interngpu 
16GB ddr4 ram and a 256GB m.2 ssd

Also tested a weaker system with apu ryzen embeded 1765g with vega 8 igp also same errors during install and after

**Comment by ACCESS-DENIIED** [comment]
I'm on 3.3 with Nvidia + Intel, managed to get all the repos up and running again last night but i'm a complete noob at linux so at some point my pc was unresponsive. I'm unsure what it was that caused the issue but I can confirm that there is a way to download the other repos.
Grabbed this from another post:

edit /etc/pacman.conf
go to
# REPOSITORIES
and change them to:
[jupiter-rel]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[holo-rel]
Include = /etc/pacman.d/mirrorlist
SigLevel = Never

[core-rel]
Include = /etc/pacman.d/mirrorlist

[extra-rel]
Include = /etc/pacman.d/mirrorlist

[community-rel]
Include = /etc/pacman.d/mirrorlist

[multilib-rel]
Include = /etc/pacman.d/mirrorlist

just add -rel after each jupiter holo core extra community and lultilib
then
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syu

Again though, I'm a noob at linux so while this did work I cannot confirm whether this was what broke my linux install or whether it was when i tried to install missing dependencies for mangohud afterwards. When I made the edits above, the repos did successfully download and the discovery store showed around 750+ updates, I didn't update anything but some point after this I had to reinstall the OS.

**Comment by matthewh626** [comment]
im getting this issue aswell, it looks like its comming from a comflict of /etc/pacman.conf being in both pacman and holoiso-main
![Screenshot_20230106_223404](https://user-images.githubusercontent.com/16733399/211115563-b6514481-2f95-44c8-b495-51ac97fb9ab3.png)

**Comment by matthewh626** [comment]
i think i fixed it,
 step huan;

sudo nano /etc/pacman.conf
then just delete the whole thing and replace it with the contents of the most up to date pacman.conf
(yes this is an incredibly noob thing to do im even more noob than the last guy)

step two;
sudo pacman-key --init 
sudo pacman-key --populate archlinux
(no idea if this is necessary i have no idea what im doing)

the new step;
sudo pacman -Syyu --overwrite "*"
found this after some googling

4. ???????

finally;
profit

everything updates and now there are no stuck updates in discover.

**Comment by AdGir** [comment]
Hi everyone,

Same issue here and happy to see some fix here.
@matthewh626 can you explain what you mean by "delete the whole thing and replace it with the contents of the most up to date pacman.conf" where do I get the most up to date pacman.conf?
See?! Even more newbe than you :)

Thank you

**Comment by ACCESS-DENIIED** [comment]
> 

I followed his instructions myself after his post. What I noticed was that the pacman.conf that was on my OS post-installation was actually not the same one that was provided with the holoIso installer. For some reason or another the installation removes the mirrors in the pacman.conf.

What I did to follow his instructions was: Go to the "Releases" section here and then go to the one you've installed (In my case it was version 3.3. Then go to the "assets" at the bottom of the page. Download the "source" zip file. Open the zip with ark. You'll see pacman.conf right away. Open that file and copy all of the text. You can then paste the contents of the file into the one on your system.
