### ISSUE TITLE
[Report] black screen after initializing ramdisk

### ISSUE THREAD

**Issue by Retro12** [holoiso-eol/holoiso#677]
Black screen after initializing ramdisk
CPU: Intel i7 4790
GPU: AMD R9 390

**Comment by SkyN6T86** [comment]
https://www.reddit.com/r/SteamOS/comments/uy53l7/holoiso_stuck_on_loading_initial_ramdisk/
When you boot up your Holoiso drive, select Advanced options for SteamOS. Then boot in to recovery.

You'll then need to type in the root password you set up for your hostname. Once you're done, type in holoiso-disable-sessions

This will turn off session switching and disable the autologin, which will take you to the KDE desktop login. Make sure you have Plasma (X11) selected as the session in the top right.

As an FYI, when installing you need to make sure your hostname and username don't contains capitals, or you won't see a user to log into here.

This will get you into KDE desktop and you can use Steam! Big Picture works, but this won't fix Game Mode.

**Comment by paegan69** [comment]
> This will get you into KDE desktop and you can use Steam! Big Picture works, but this won't fix Game Mode.

Thank you for this! I have 2 broken laptops that I've been trying to get to work with HoloISO for ages that both have similar generation AMD GPUs (HD8520 or thereabouts) and this solution has actually given me some progress towards usability. In fact the solution was a lot shorter on my end, when i got my black screen after boot I hit Ctrl+Alt+F2 on my keyboard and got a login prompt. I then just logged into the account I created during setup and at the terminal prompt i entered "sudo holoiso-disable-sessions" and instantly got the KDE Desktop login. 
Now ifwe can just fix GameMode from here we'll be golden...

EDIT/UPDATE: after messing about with a few things that broke the OS (window manager go bye bye) I settled on a basic workaround of updating the client to the beta stream and getting the new SteamOS interface that way. Nice alternative but unfortunately missing most if not all of the system setting controls. To access it go to Steam->Settings->Account->Beta Participation. Literally the 1st thing u see under the setting window.

**Comment by l0gar1thm** [comment]
> but this won't fix Game Mode.

Is there any way to fix gamemode?

**Comment by l0gar1thm** [comment]
> To access it go to Steam->Settings->Account->Beta Participation.

Does this fix game mode?

**Comment by xSeaGull** [comment]
？？？？ some solution？

**Comment by xSeaGull** [comment]
@Adam Jafarov
