### ISSUE TITLE
[Report]black screen on startup

### ISSUE THREAD

**Issue by Alloinkil** [holoiso-eol/holoiso#678]
black screen on startup

CPU: intell xeon e5 2696
GPU: and firepro s7000

black screen on startup, log error

![210965748-6dfe1bbc-89ba-4bcc-a985-5ba926f99321](https://user-images.githubusercontent.com/122085811/211154343-22e2c9b8-1212-49d7-a865-ece3cbdc057e.png)

**Comment by advert665** [comment]
I think I potentially have a similar issue, this is what mine looks like after boot: 
<img width="1054" alt="Screenshot 2023-01-06 at 21 44 50" src="https://user-images.githubusercontent.com/77785968/211105209-5a960c77-6cb5-4388-92b9-d1dba69b291d.png">

**Comment by Alloinkil** [comment]
its normal?
![Screenshot_20230107_134740](https://user-images.githubusercontent.com/122085811/211154055-ae4cd9c1-6356-4ed7-8c95-c5fee3d34dd7.png)

**Comment by Alloinkil** [comment]
the problem is that users from Ukraine do not have access to the update servers, the next question is how to install a VPN on this livecd, I'm not very strong in linux
