### ISSUE TITLE
Unsupported hardware

### ISSUE THREAD

**Issue by Decbuan** [holoiso-eol/holoiso#684]
I install holoios4.1 
ayaneo2

Status bar display
![BAE9A821-5AA3-4952-8978-4C0FAD00BFE4](https://user-images.githubusercontent.com/59784379/212274254-7a1b872a-f9d5-4555-ba2d-7a0cd37d57e2.png)

please fix

**Comment by CUD** [comment]
Any luck with this? I was considering trying this on my AYANEO 2 also. Are you able to get past this screen?

**Comment by S1nPur1ty** [comment]
I just installed HoloISO 4.0 and it works flawlessly @CUD. There are some minor issues that can be manually resolved, but everything works so far.

@Decbuan Try creating a new bootable USB with this ISO: https://drive.google.com/file/d/1tAJQbqrg8t6hzymeynNIXp-pAzqLbYb3/view

**Comment by CUD** [comment]
> I just installed HoloISO 4.0 and it works flawlessly @CUD. There are some minor issues that can be manually resolved, but everything works so far.

I actually gave it a go also. I played around with it for a bit but I think I needed some plugins to get the controller working properly. The bigger issue for me would be the lack of fan control. So I might stick to Windows at this point.

**Comment by S1nPur1ty** [comment]
@CUD It seems that crankshack isn't working anymore, so I have no way to control the TDP. I will have to switch back to Windows as well unfortunately. I was a bit too fast with my judgment, hehe..
