### ISSUE TITLE
Why aren't the ISO files hosted on github?

### ISSUE THREAD

**Issue by b-** [holoiso-eol/holoiso#686]
Github's releases allow you to host ISOs for free, at a much higher speed than any of your current links, without bandwidth limits or anything. (I know Google Drive sometimes takes things down due to bandwidth "abuse", and the other link was painfully slow).

Can I ask you to upload new releases to Github, please? You could probably even make a github action to build and release these regularly for you...

**Comment by winzkh** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/actions

**Comment by b-** [comment]
> https://github.com/theVakhovskeIsTaken/holoiso/actions

Huh, I feel silly!

I also forked this to try and run it myself with a release action, and GitHub rejected the upload because they have a max size of 2 GB that I overlooked. So please forgive my ignorance!

I feel like there really has to be better free hosting for Linux distros than Google Drive, though…

**Comment by VaiN474** [comment]
even a torrent would be better than being capped at a 9hr download

**Comment by b-** [comment]
@theVakhovskeIsTaken one potential lead for better (free) ISO and pacman mirror hosting: https://mirror.clarkson.edu/projects bottom of the page

**Comment by kramlat** [comment]
you can also lease a vps at 1and1 ionos for dirt cheap and set that up for isos and pacman as I did and can even host a site there if you want to. You can even set up a tor hidden service for no additional cost if you know what you are doing and they don't even care as long as you don't actually break the law.
