### ISSUE TITLE
External controllers not detected in edge/chrome for xcloud Geforecenow

### ISSUE THREAD

**Issue by sojab0on** [holoiso-eol/holoiso#690]
## Your Issue:
Holo iso detects xbox controller wired and trough bleutooth, but edge/chrome do not detect it
*type your problem here*
When i connect my xbox one x controller trough usb cable or bleutooth doesnt matter , system detects it but browsers like edge do not.
I followed the instructions from nvidia and microsoft to add Geforcenow and xcloud to steam and set the gapad with mousand trackpad layout ran teh flatpack command to give it more rights still no go. 

## Your device's full specs
```
CPU: AMD Ryzen 5 3400G
GPU: AMD vega 11 Intergrated gpu 
16GB DDR4 Ram
256GB M.2 ssd boot drive 
120GB SSD for biger more intesive games
1TB hdd for bulk storage 
Xbox one x controller 

```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
"snapshot20221211.1426"
```

is it posible to get teh command for priviladges to get edge/crome detect the controller

**Comment by kramlat** [comment]
you can use sudo and usermod together to do that.
