### ISSUE TITLE
[Report] No more mirrors error

### ISSUE THREAD

**Issue by eyeonus** [holoiso-eol/holoiso#699]
## Your Issue:
```
When attempting Discovery update after brand new install, an error message is received
This problem is not due to internet access, as Firefox is downloading when error occurs.
```
![image](https://user-images.githubusercontent.com/1733600/217038589-15ef927a-6ce1-4b7c-9527-997a3062e8a1.png)
![image](https://user-images.githubusercontent.com/1733600/217038782-c2cf592a-7ec8-4d25-baa9-cea857df420b.png)

## Your device's full specs
```
VirtualBox installation on Win10, 16GB memory, 6 processors, 64MB VMSVGA
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426
```

## Your installation type:
```
There are different types?
```

## Have you updated your installation recently?
```
brand new installation
```

**Comment by maconforti** [comment]
I am experiencing the same issue with a new install.

It is a clean install on an HP 455 G7
Operating System: SteamOS 3.4
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.3-1-neptune (64-bit)
Graphics Platform: X11
Processors: 6 × AMD Ryzen 5 4500U with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: AMD RENOIR (512MB dedicated to video RAM)

No updates will install in desktop mode.

No updates will install in game mode.

No games will run in game mode. The attempt to start then abruptly quit with no error and return to the home screen.
