### ISSUE TITLE
Failed to Install Because dl.thevakhovske.cf is Down

### ISSUE THREAD

**Issue by wynn1212** [holoiso-eol/holoiso#70]
Failed to install SteamOS 3 from holoiso because of `Could not resolve host: dl.thevakhovske.cf`
![failed](https://user-images.githubusercontent.com/10562889/167382030-150e47c2-5b24-40ba-932f-eb39bf9978bf.png)

**Comment by smb1982** [comment]
> Failed to install SteamOS 3 from holoiso because of `Could not resolve host: dl.thevakhovske.cf` ![failed]

Having the same issue.  Checked with isitdown and it seems to be down atm.

**Comment by theVakhovskeIsTaken** [comment]
Yeah, my domain just went fully down.

Sorry about that.

**Comment by smb1982** [comment]
> Yeah, my domain just went fully down.
> 
> Sorry about that.

Nothing to be sorry about, it happens and i'm sure its because HoloISO is so popular ;)

**Comment by Mar0xy** [comment]
also depending on where you got the .cf domain(I assume freenom) then it's pretty common for the domain to just be taken away from you by freenom as they are known to take away high traffic domains to then resell them for profit.

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/commit/c499e02f69fd4edd06591d81062c20d58c291725

Apparently, my domain was marked as fraud (for some interesting reason)

**Comment by Mar0xy** [comment]
> [c499e02](https://github.com/theVakhovskeIsTaken/holoiso/commit/c499e02f69fd4edd06591d81062c20d58c291725)
> 
> Apparently, my domain was marked as fraud (for some interesting reason)

Yeah this is normal for freenom this is their way of telling you thanks for your high traffic domain.
https://www.trustpilot.com/review/freenom.com
