### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by sh0ra1t** [holoiso-eol/holoiso#707]
## Your Issue: Bluetooth reconnection
```
*After pairing and playing, when I try to reconnect the computer to the Bluetooth between the gamepad and the holo os it just don't connect.*
```

## Your device's full specs
```
UM690 Minisforum
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
Last version
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
Normal
```

## Have you updated your installation recently?
```
Yes
```

**Comment by sh0ra1t** [comment]
Any information about this?
It's so boring to pair the gamepad everytime that I want to play..

**Comment by nlflint** [comment]
You might try new bluetooth kernel module. This worked for my bluetooth problem with was different than yours. These are my personal steps formulated from a bunch of googling and testing on my machine. You'll need to open a shell to do it:

## Upgrade USB drivers (if not able to pair)

Clone the driver repo and compile.
```bash
cd ~
git clone https://github.com/jeremyb31/bluetooth-5.13.git
cd bluetooth-5.13
make
```

Rename (backup) old compressed kernel bluetooth module file:
``` bash
sudo mv /lib/modules/$(uname -r)/kernel/drivers/bluetooth/btusb.ko.xz /lib/modules/$(uname -r)/kernel/drivers/bluetooth/btusb.ko.xz.bak
```

Copy new compiled driver, reload kernel modules, and reboot:
```bash
sudo cp btusb.ko /lib/modules/$(uname -r)/kernel/drivers/bluetooth/
sudo depmod -a
sudo reboot
```

No guarantees, proceed at your own risk!
