### ISSUE TITLE
error：404 to jupiter.db &holo.db

### ISSUE THREAD

**Issue by xdnfufufufu** [holoiso-eol/holoiso#709]
## Your Issue:
```
error：404 to jupiter.db &holo.db
*type your problem here*
```
when use pacman -Sy
  error with the request Url returned error :404 获取文件 'jupiter.db'

## Your device's full specs
```
CPU: intel xeon E5-1575m v5
GPU: nvidia quadro P4000 mobile
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```yes
nawww
```

**Comment by kramlat** [comment]
change jupiter to jupiter-rel and holo to holo-rel and also disable signature checking because it is broken.

**Comment by AkitoItashi** [comment]
C7YPT0N1C made a hotfix, that seems to work...
I had the same issue and just tried it in my VMWare VM....
It took a while cause there were many updates, but it worked :3

[C7YPT0N1C/HoloISOHotfix](https://github.com/C7YPT0N1C/HoloISOHotfix)

**Comment by slaminger** [comment]
Having the issue currently as well. Used the offline installer.  Trying the fix above. 


Line 139:  syntax error near token else

Seemed to get far enough in I can use the normal Pacman now however.
