### ISSUE TITLE
[Question] Suport for AMD RX 7000 series

### ISSUE THREAD

**Issue by S1ngl3-x** [holoiso-eol/holoiso#710]
Are there any plans to add support for these new graphics cards? 

I tried installing mesa git along with the new LLVM which worked. I did not however manage to easily upgrade the kernel to at least 6.1+ version (ended up with black screen).

I am not talking about out of the box support but at least a newer kernel included in grub menu would be great.

Thank you for your work, it's great.

btw : it was once discussed in this [thread](https://steamdeck.community/threads/holoiso-rdna3.322/#post-1830)  already.

**Comment by PennyFranklin** [comment]
I'm wondering if 7900xtx is supported now

**Comment by S1ngl3-x** [comment]
> I'm wondering if 7900xtx is supported now

check HoloIso kernel and mesa version. For me it did not get updated for a long time so I switched to ChimeraOs.

**Comment by PennyFranklin** [comment]
okay thanks
