### ISSUE TITLE
[Report] Stuck on loading initial ramdisk

### ISSUE THREAD

**Issue by estrogencat** [holoiso-eol/holoiso#717]
## Your Issue:
```
Stuck on “Loading initial ramdisk …” but works in recovery mode, kinda.
```
![image](https://user-images.githubusercontent.com/121733739/220211284-461f87e2-7a3c-4873-9853-b14f0f924c9a.jpg)

## Your device's full specs
```
PC: Dell OptiPlex 3070 Small Factor
CPU: Intel® Core™ i3-9100T (4 Cores/6MB/4T/3.1GHz to 3.7GHz/35W); supports Windows 10/Linux
GPU: Intel UHD 630 Graphics [with 8th Generation Core i3/i5/i7 CPU-GPU combo]

Full specifications: https://www.dell.com/support/manuals/en-uk/optiplex-3070-desktop/opti3070_micro_setiup_specs/system-specifications
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
no output
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
```

## Your installation type:
```
```

## Have you updated your installation recently?
```
no
```

**Comment by Azoozgg171** [comment]
I have the same problem if you find a solution tell me thanks

**Comment by slygathor** [comment]
Having the same issue here, I've tried on 2 different Intel Nuc's and in VirtualBox, and won't get passed the loading RAM disk.

**Comment by Azoozgg171** [comment]
https://www.reddit.com/r/SteamOS/comments/uy53l7/holoiso_stuck_on_loading_initial_ramdisk/
When you boot up your Holoiso drive, select Advanced options for SteamOS. Then boot in to recovery.

You'll then need to type in the root password you set up for your hostname. Once you're done, type in holoiso-disable-sessions

This will turn off session switching and disable the autologin, which will take you to the KDE desktop login. Make sure you have Plasma (X11) selected as the session in the top right.

As an FYI, when installing you need to make sure your hostname and username don't contains capitals, or you won't see a user to log into here.

This will get you into KDE desktop and you can use Steam! Big Picture works, but this won't fix Game Mode

**Comment by x0rgo** [comment]
> https://www.reddit.com/r/SteamOS/comments/uy53l7/holoiso_stuck_on_loading_initial_ramdisk/ When you boot up your Holoiso drive, select Advanced options for SteamOS. Then boot in to recovery.
> 
> You'll then need to type in the root password you set up for your hostname. Once you're done, type in holoiso-disable-sessions
> 
> This will turn off session switching and disable the autologin, which will take you to the KDE desktop login. Make sure you have Plasma (X11) selected as the session in the top right.
> 
> As an FYI, when installing you need to make sure your hostname and username don't contains capitals, or you won't see a user to log into here.
> 
> This will get you into KDE desktop and you can use Steam! Big Picture works, but this won't fix Game Mode

Tried this, after got login same error

**Comment by cookiejar5081** [comment]
I have the same issue even after applying the fix listed above.

**Comment by x0rgo** [comment]
> I have the same issue even after applying the fix listed above.

I was actually able to do it applying the steps, i needed to click the SteamOs on the top left corner and change it. Try that, it worked for me.

**Comment by AxFrancois** [comment]
Hi folks, I am also having this issue on another Dell OptiPlex 3070 SFF with a i5-6500 using Intel HD Graphics 530. Following the recommendations listed above I managed to log in to the desktop environment but I failed to start the Game Mode (exact same screen than above). Any clues/updates regarding this issue?

**Comment by balapradeep** [comment]
Same here stuck at ramdisk. Tried it in recovery mode by holoiso-disable-sessions, Plasma is working but not the gamescope.
Any workaround that needs to be done? 
Specs:
Intel® Core™ i7-10610U CPU @ 1.80GHz × 8 
Mesa Intel® UHD Graphics (CML GT2)

**Comment by pfeifferworks** [comment]
Hi folks,

I have the same issue on a Dell Optiplex 3070 SFF with a i5-6500 using Intel HD Graphics 530. Workaround to get in Desktop-Mode works fine, and I can start Steam in BigPicture Mode. But I can't switch to GamingMode and start it directly after reboot.

Any more hints?

**Comment by theVakhovskeIsTaken** [comment]
@ben21684 Is it that hard to read readme and finding out that Intel GPUs are NOT supported?

**Comment by jumofogit** [comment]
Iris Xe is working, tho.
