### ISSUE TITLE
Hang on triggering uevents

### ISSUE THREAD

**Issue by NorgePlayz** [holoiso-eol/holoiso#719]
I was trying to instal HoloISO but it's stuck at triggering uevents. I also trying to use balenaetcher, but it dosen't work without UEFI mode. I using Rufus with DD and nothing works for me. Any know how to solve this?

**Comment by Mario-119** [comment]
Seconding this, just hangs and eventually reboots

**Comment by PadTrick** [comment]
Also have this problem with the new iso. something is broken.
Error appears on a Ryzen 3500u(APU) Laptop, I7-7700HQ+GTX1060 Laptop, Ryzen3600+GTX1070Ti Desktop and Ryzen3400G(APU) Desktop

Previous HoloIso and all other Distros (Arch,Nobora,Mint,Manjaro) are booting fine

**Comment by peterkle9** [comment]
you do nomodeset or and nouveau.modeset=0 but I just get stuck at live sessions, e to edit launch options in the rescue menu

**Comment by Flexusma** [comment]
bump, having the same issue

**Comment by PennyFranklin** [comment]
I run into the same error

**Comment by JHoltavac** [comment]
Ditto 😥

**Comment by alteredtech** [comment]
running into issue on Ryzen 5 7600X. Waiting on my GPU which will be here next week, 7900XTX. 
Some lines before it.
```
ACPI BIOS Error (bug): Failure creating named object [\_SB.PCIO.GPPO._PRW], AE_ALREADY_EXISTS (20210331/dswload2-326)
repeats twice.

ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20210331/psobject-220)

running early hook [udev]
starting version 250.3-1-arch
running early hook [archiso_pce_nbd]
running hook [udev]
triggering uevents
```

**Comment by niandralades** [comment]
Press E and add 

nouveau.modeset=0

at the end of the line in bootmode

I am using 1070.

**Comment by alteredtech** [comment]
Yeah that did nothing. Thanks though. I should have also included that I am using the integrated graphics until the gpu gets here. Guess I can just wait to install until that shows up and see if that fixes it. I was hoping it would just install since I thought iGPU was same architecture as the steam deck.
