### ISSUE TITLE
SteamOS updates keep appearing

### ISSUE THREAD

**Issue by JongAnYoo** [holoiso-eol/holoiso#72]
Software update is still showing in the SteamOS system menu. The May 3rd update keeps popping up.
Hit 'Apply' and reboot, it still appears.

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/issues/70#issuecomment-1120906984

Run this as sudo

**Comment by JongAnYoo** [comment]
Run sudo pacman -Sy --overwrite="*" holoiso-updateclient or download "holoiso-updateclient" here, and run sudo pacman -U --overwrite="*" holoiso-updateclient-rel.20220508.1222-1-x86_64.pkg.tar.zst before running steamos-update

Can't use this method
And the current Steam OS version is snapshot2.

**Comment by sharicov** [comment]
same here, getting holoiso.db error:

$steamos-update
HoloISO Updater Beta 1
Current version: Boop (snapshot2)
snapshot20220508.1224
Checking for updates...
error: failed retrieving file 'holoiso.db' from dl.thevakhovske.cf : Could not resolve host: dl.thevakhovske.cf
warning: too many errors from dl.thevakhovske.cf, skipping for the remainder of this transaction
error: failed to synchronize all databases (unexpected error)
Update complete to version Boop (snapshot2)
snapshot20220508.1224. Please restart your device to apply changes.

solved with 
sudo curl https://raw.githubusercontent.com/theVakhovskeIsTaken/holoiso/3.0/airootfs/etc/pacman.conf -o /etc/pacman.conf
