### ISSUE TITLE
PC doesn't boot the USB Drive

### ISSUE THREAD

**Issue by jajadannn** [holoiso-eol/holoiso#720]
I have the Problem that my PC doesn't boot every time I boot I get into the Bios flash utility

What I tried to do:
check other USB Port
Plug the USB in other Computer 
Reset the Bios

Specs:
AMD FX 6300 Six-Core Processor
8GB of Ram
Asus ROG Strix Radeon RX570 8GB
400W Power Supply
4TB of SSD

**Comment by ItsRogueRen** [comment]
Bumping this as I'm having the same issue, attempting to install on my actual Steam Deck.

Boot to the UEFI BIOS screen, boot manager, USB device, and then I get an error screen saying the USB couldn't boot

**Comment by jurassicjordan** [comment]
Also bumping. Does not even boot in virtual machines. Qemu couldn’t recognize the boot medium. How does that happen?

**Comment by evanstos** [comment]
me too .. motherboard gigabyte x99-ud4 + gtx 750 ti
