### ISSUE TITLE
Hyper-V or QEMU support?

### ISSUE THREAD

**Issue by JustinKJChen** [holoiso-eol/holoiso#724]
By now, steam OS holo support Hyper-V or QEMU? 

The screen is black after install, is it expectation?

**Comment by ju6ge** [comment]
well that is happening for me as well, but it is running. If you switch to a different tty you are greeted with a login prompt and can login to the system. So it seams the ui just not shown. Need to dig deeper to find out what is going on

**Comment by HikariKnight** [comment]
for qemu use the virtio graphics card, that works for me but only desktop mode will work so you need to enable the login screen

still good for testing internals and look at how things are laid out

**Comment by jaimeiniesta** [comment]
A guide for installing on QEMU would be really welcome :)

**Comment by theVakhovskeIsTaken** [comment]
no.

**Comment by ju6ge** [comment]
I ended up going a different route to get a steam deck like experience in a virtual machine ;) … Dropping this here for people interested https://forum.level1techs.com/t/steamos-3-0-vfio-guide/177341/19?u=felixrichter
