### ISSUE TITLE
[Report] Stuck on "Loading initial ramdisk..." on Intel NUC

### ISSUE THREAD

**Issue by WifiRouterYT** [holoiso-eol/holoiso#725]
## Your Issue:
Hello! I recently installed HoloISO 4.0 on my Intel NUC (unsure which model, definitely an older one) but I can't get past the Loading initial ramdisk part. Recovery boots fine and through recovery mode I was successful with getting into a desktop OS using "holoiso-disable-sessions" (or similar), but it would be nice to actually use the steam desk ui to it's full potential, as this will be sitting on my TV with just a controller. I've tried using HoloISO 3.3 but the same issue.

## Your device's full specs
```
CPU: i3-5010U
GPU: Intel HD Graphics 5500 (or similar, integrated gpu)
RAM: 8GB DDR3
Storage: 128GB SSD + 2TB external HDD (formatted with ext4)
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
latest provided in the 4.0 offiline installer
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
Making Gamescope Mode Save file at "/home/wifirouter/.config/gamescope/modes.cfg"
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
wlserver: [backend/headless/backend.c:82] Creating headless backend
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
vulkan: selecting physical device 'Intel(R) HD Graphics 5500 (BDW GT2)': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
vulkan: physical device queue doesn't support presenting on our surface
vulkan_make_output failed
/usr/bin/gamescope-session: line 246: kill: (3170) - No such process
```

## Your installation type:
```
deck-experience
```

## Have you updated your installation recently?
```
no
```

**Comment by Jason300** [comment]
same

**Comment by lyte0ne** [comment]
me too only that my CPU is i7-5500u but same gpu. I guess is a gpu issue but...

**Comment by TheGithubJoshua** [comment]
Same issue on MacBook Pro. If you won't fix it close it as Won't fix instead of Resolved, should fix it though as it seems to be a major issue.
