### ISSUE TITLE
Stuck reached target graphical interface

### ISSUE THREAD

**Issue by ACRZeuss** [holoiso-eol/holoiso#726]
When trying to install from scratch it gets stuck here and won't continue

My specs:
AMD Ryzen 5900X
RTX 3060
32 GB RAM
250 GB SSD

**Comment by pimboli** [comment]
Hi, seems I have the same problem. Did you find a solution?

Thanks

**Comment by ACRZeuss** [comment]
> Hi, seems I have the same problem. Did you find a solution?
> 
> Thanks

Unfortunately i couldn't find it

**Comment by pimboli** [comment]
I found this: https://github.com/HoloISO/holoiso/issues/670

not sure if it makes sense...

**Comment by pimboli** [comment]
and do you also see this error at the beginning of the boot process?
![IMG_20230525_233740](https://github.com/HoloISO/holoiso/assets/5020679/c84149d5-bc7b-404d-91d6-677cdc7fcb8a)

Maybe as soon as it should load graphical interface it stucks because no AMD gpu support is working
