### ISSUE TITLE
[Report] Bluetooth not working

### ISSUE THREAD

**Issue by Burgersim** [holoiso-eol/holoiso#727]
## Your Issue:
```
Bluetooth isn't able to be enabled either Desktop or Gaming mode
```
## Your device's full specs
```
CPU: AMD Ryzen 7 6800U
GPU: Radeon Graphics

Device: AyaNeo GEEK
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
yes, but it wasn't working at first so I used different settings for pacman.conf that I found in the issues here (bluetooth wasn't working before the update either though)
```

**Comment by Albusaidi30** [comment]
same issue, update from Desktop also not working. it get unexpected error. 
update from deck ui also not working , every boot its get same update.

**Comment by rosostolato** [comment]
In my case, the problem was the Neptune kernel, I changed to holoiso kernel and uninstalled the other.

-- edit --

If I change the kernel, vulkan stops working 😞

**Comment by rosostolato** [comment]
I found a better solution! Install the version 6 of Neptune kernel:

`sudo pacman -S linux-neptune-60 linux-neptune-headers-60`

Then rebuild grub config:

`sudo grub-mkconfig -o /boot/grub/grub.cfg`

Fully working now, Bluetooth + vulkan.
