### ISSUE TITLE
screen stuck on distorted logo

### ISSUE THREAD

**Issue by mmkoss** [holoiso-eol/holoiso#728]
## Your Issue:

*type your problem here*
when I reboot after installation the screen is stuck on a screen as shown on attached screen. Funny enough the sound is still there.

## Your device's full specs
```
CPU: Intel i5 8th gen
GPU: iGPU
Hp Elitebook 840 G6

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
latest ISO downloaded yesterday 12 March


## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
I cannot access terminal


## Your installation type:
full install on local SSD


## Have you updated your installation recently?
nope, no need
![viber_image_2023-03-13_10-48-22-799](https://user-images.githubusercontent.com/111077576/224667482-5dfd3d74-bb5f-4e3b-90fa-805d66e59bdb.jpg)

**Comment by PorChaGT** [comment]
Same problem here

**Comment by Flame1211** [comment]
Same issue for me aswell, I’ve tried deleting that one config file but that hasn’t fixed it. I can boot into plasma but normal launch has said above issue

**Comment by yureng** [comment]
I'm having the same problem,  the same distorted screen

CPU:  Intel i5 8th gen
GPU:  iGPU
