### ISSUE TITLE
https://dl.thevakhovske.cf/6:/holoiso/os/x86_64/ is Down

### ISSUE THREAD

**Issue by gelson-zord** [holoiso-eol/holoiso#73]
Without this HoloISO can't apply updates though...

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/holoiso#major-note-for-now-before-installing-please-run-curl-httpsrawgithubusercontentcomthevakhovskeistakenholoiso30airootfsetcpacmanconf--o-etcpacmanconf-because-my-main-domain-is-dead
