### ISSUE TITLE
Games not starting?

### ISSUE THREAD

**Issue by Dakumee** [holoiso-eol/holoiso#730]
Not sure what im doing wrong..
i downloaded holoISO, put it on a massive sized USB stick, installed it flawlessly on my machine
specs of the machine are:
Intel i5 10600kf (no integrated GPU)
8GB of 3000mhz TridentZ ram
Sapphire Radeon RX590 nitro+ special edition GPU
i run 1 M.2 for the installation and a separate (extra) 1TB Sata SSD for all games.

My intention for this machine is focused on gaming with a little bit of discord and maybe youtube on the side..

The issue:
Whenever i try to launch a game from steam e.g. whether it be in game mode or in desktop mode, it tries to 'Synch' with i assume the steam cloud. which is fine, and thats it. not a single game launches at this point and i don't know how to fix it.

This is my issue.

on the side i downloaded a 3rd party 'Epic games' launcher called "Heroic Games Launcher" to play my Epic library games and this for some reason works flawlessly..? so.. i have a system based on steam that can't run any steam game, but CAN run epic games..

any help is appreciated and any question you might have for me will get answered.
Keep in mind im a beginner at Linux/Ubuntu/Debian ect.

i do know how to open the konsole/terminal and how to move about but thats about it.
anyways, thanks for your time!

**Comment by JesseKoldewijn** [comment]
Since you got Heroic Games Launcher installed I imagine you do know how to get to the desktop environment right?

If so, open steam from the desktop, navigate to settings and enable proton (if not enabled) and background vk shader caching and it should start working for ya. It could also be possible that some of the games you try to run either dont work on linux (and so on steamdeck) or require launch args to get working. Maybe check the entries of the games you want to play on ProtonDB to see if they run on linux 😄

**Comment by SpecterOoze** [comment]
If no games will launch, increase the xwayland-count above 1:

Try adding the argument "--x-wayland-count 2" to your gamescope-session.conf in home/YOURUSERNAME/.config/environment.d/

Assume this works, what happened was a single gamescope window was used to launch the steam client and no other sessions were created to launch games. Not sure if this a bug or intended behavior. 

This also works for chimeraos implementation of gamescope-session and most likely others. The location I listed is where it is on chimeraos gamescope-session. I assume its the same for holoiso, but please correct me if I'm wrong. 

I see this issue posted online alot with no solution. Can this be added to a wiki/readme ?
