### ISSUE TITLE
question: can holoiso  update steam deck firmware?

### ISSUE THREAD

**Issue by logan001** [holoiso-eol/holoiso#733]
im curious if holoiso offers steam deck firmware updates?
i'm more incline to install holoiso due to space requirements than official steam deck os but i also want to have the latest firmware available for steam deck

i know this is not a forum but i think here is the best place to ask this

**Comment by JesseKoldewijn** [comment]
What do you mean by firmware? both holoiso and steamdeck os are operating systems. This means they by definition dont have anything in that sense to do with the firmware of your device. If by firmware you mean kernel, they both are based on arch meaning you get the bleeding edge most recent kernel versions depending on what mirror your connected to (in case some would not be up-to-date)

**Comment by logan001** [comment]
steam os that comes with the deck updates the firmware for the deck too (and dock too)

**Comment by JesseKoldewijn** [comment]
That's a firmware level hook to their proprietary side of the os I believe. But what you can try is the following in a terminal window:
```
steamos-update check
```

**Comment by JesseKoldewijn** [comment]
I know there was some form of the firmware hook implemented into holoiso but since you can install it on basically anything I would be surprised if it would be able to call a firmware update.

**Comment by JesseKoldewijn** [comment]
As far as the firmware updates go. Check the readme and you'll see the following:
```md
Working stuff on Steam Deck compared to other distributions:

Dock Firmware updater (additionally installable in desktop by running sudo pacman -S jupiter-dock-updater-bin)
Steam Deck BIOS, Controller firmware, OS firmware updater
New fan curve control
TDP/Clock control
```

I've personally only ran holoiso on devices other than the steamdeck itself so no clue how the steamdeck bios and firmware updates would work.

**Comment by logan001** [comment]
thank you  for info.  that's great
