### ISSUE TITLE
[Report] Onexplayer Mini Pro - AMD 6800U - Screen Orientation

### ISSUE THREAD

**Issue by BluesBrothers7** [holoiso-eol/holoiso#735]
## Your Issue:
``Screen orientation on Onexplayer Mini Pro AMD 6800u is upside down (gamescope mode). The screen orientation in desktop mode is in the right direction`

## Your device's full specs
```
CPU: Ryzen™ 7 6800U​
GPU: Radeon™ 680M 2200 Mhz
```

## Your OS version
```
(https://gdrivecdn.thevakhovske.pw/3:/daily_ci/HoloISO_4.2_6.1-test-20230317_2043_5bea3ab8e6-preview-x86_64.iso?a=view)
```

## Your installation type:
Offline

deckperience
```

## Have you updated your installation recently?
no

**Comment by BluesBrothers7** [comment]
Screen is still upside down  HoloIso 4.5 RC1 beta: https://gdrivecdn.thevakhovske.pw/3:/daily_ci/HoloISO_4.5-rc1_beta-candidate-20230324_d1cc6e5738_intel_mesa_changes-1-x86_64.iso?a=view

**Comment by theVakhovskeIsTaken** [comment]
This is a known issue, and is subject to be updated

**Comment by BluesBrothers7** [comment]
Thanks for this info. 

I just want to kindly report that this issue still exists in the latest RC 4.5.01-rc1 beta.

https://gdrivecdn.thevakhovske.pw/3:/daily_ci/HoloISO_4.5.01-rc1_beta-uprev_with_gpu_changes-20230325_42bdfc6a6f_misc_fixes-1-x86_64.iso?a=view

Thank you for your great work! Very much appreciated!

**Comment by parth-menon** [comment]
@BluesBrothers7  Hey man, I have the OneXPlayer2 Pro with 7840u and I think my fix might work for you too.

1. Switch to Desktop Mode
2. Open Konsole
3. kwrite /usr/bin/gamescope-session
4. Scroll down until you see "gamescope \ --generate-drm" etc
5. After the "-w 1280 -h 800\" add a new line with "--force-orientation left \"
6. Save the file. It might ask for root access
7. Now switch back to Gaming mode and it should be in the correct orientation

Let me know if this works for you.
