### ISSUE TITLE
Cant switch to desktop mode after update

### ISSUE THREAD

**Issue by lbroschart** [holoiso-eol/holoiso#737]
## Your Issue:
```
After manually updating it is not possible for me to switch to desktop mode from gamemode.
The Overlay saying 'Switching to Desktop Mode' appears but nothing happens. It is not possible to abort the overlay. Weirdly I can use the gamemode while the Overlay is still visible but everything is blurred because of the modal.

Also I have lost performance after the update (games started to stutter)
```

## Your device's full specs
```
CPU: AMD Ryzen 5 3600XT 6-Core @ 12x 3.8GHz
GPU: AMD Radeon RX 5700 XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221222.1749
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
yes, via 'steamos-update now'
```

**Comment by crlink271986** [comment]
odd i havent updated and face the same issue (after second reboot) first time I got into desktop mode) on my steam deck

**Comment by lbroschart** [comment]
I managed to boot to desktop mode by edit /etc/sddm.conf.d/autologin.conf and set:
Session=plasma.desktop
But from there i cant switch to gamemode via the shortcut on the desktop

**Comment by SpecterOoze** [comment]
Had this issue. If you are missing lots of options in your settings as well its probably not launching in deck mode.

Try launching with this command from a terminal in desktop mode:
" gamescope -e -f -- steam -steamos3 -steamdeck -steampal -gamepadui "

If it works from a terminal, then you are missing some combination of "-steamos3 -steamdeck -steampal -gamepadui" from steam launch options in the
gamescope-session.conf file. Add missing options and save the file, restart and it should work.

**Comment by SpecterOoze** [comment]
I suspect this is an issue with either steam client or a config from steam's repos. I suspect this because I did not have this issue when I switched to a gamescope-session (from chimeraos) on top of Fedora 37. 

When I did a clean install of Fedora 38 I got the issue again. Seems to transcend distros.
