### ISSUE TITLE
How to change installation type?

### ISSUE THREAD

**Issue by icofs223** [holoiso-eol/holoiso#738]
I want to change my installation type from bare-bones to deck-experience.

**Comment by Bryan199234** [comment]
Good luck getting support. You're almost better off just starting the project and working through the issues. I've been on here for about a month, with no prior Linux experience, and was able to get my deck project completed just using web search and using the group to search for what others have done.

Am I correct in assuming you want to start a new bootable partition for holoiso and are just looking for how to get started and what is needed?

**Comment by logan001** [comment]
i think he wants to keep the current installation and upgrade to deck-experience. i don't know how to do that. you need to install the rest of packages. i don't know where to find the corresponding scripts to compare them and install the rest of packages + settings

**Comment by icofs223** [comment]
> Good luck getting support. You're almost better off just starting the project and working through the issues. I've been on here for about a month, with no prior Linux experience, and was able to get my deck project completed just using web search and using the group to search for what others have done.
> 
> Am I correct in assuming you want to start a new bootable partition for holoiso and are just looking for how to get started and what is needed?

Yes.
