### ISSUE TITLE
HoloISO: Summertime (snapshot1) improperly mounts root to /var/mnt

### ISSUE THREAD

**Issue by acleiker2** [holoiso-eol/holoiso#74]
When running holoinstall on this latest release, the installation fails, with a lot of ERROR: failed to setup chroot /mnt.
The results of lsblk afterwards points shows my nvme0n1p2 is mounted to /var/mnt.

**Comment by theVakhovskeIsTaken** [comment]
Huh? This sounds strange.
Given that it mounted fine, it might be an issue with network. Can you cap me a video with what's happening?

**Comment by acleiker2** [comment]
I can do that. Will update with a video link

**Comment by acleiker2** [comment]
https://youtu.be/AFUrhmapAjc is a video capture of the latest install attempt.

**Comment by theVakhovskeIsTaken** [comment]
> When running holoinstall on this latest release, the installation fails, with a lot of ERROR: failed to setup chroot /mnt.
> The results of lsblk afterwards points shows my nvme0n1p2 is mounted to /var/mnt.
> 

Ouch.... looks like i made a small mistake

Can you run nano /usr/local/bin/holoinstall, get to part with "pacstrap --noconfrim" and replace it with "pacstrap -i"

**Comment by Super-6-1** [comment]
I'm at the same issue, also present in the stable release. Aya neo pro 2021 
![20220509_120521](https://user-images.githubusercontent.com/26772591/167462994-8a3e330b-d5a5-4119-ac02-7e2de176640c.jpg)
![20220509_131208](https://user-images.githubusercontent.com/26772591/167463024-835a11e9-651a-412f-8cb3-8d2b1fe1369f.jpg)
![20220509_131234](https://user-images.githubusercontent.com/26772591/167463056-c311a978-292b-4c14-ac24-786760e9573f.jpg)
![20220509_131236](https://user-images.githubusercontent.com/26772591/167463095-e7d8736b-3812-48a4-9f2c-01c7966a8cb1.jpg)
![20220509_131303](https://user-images.githubusercontent.com/26772591/167463119-b70abb02-f466-4260-a634-651c11151748.jpg)
![Uploading 20220509_131306.jpg…]()
![Uploading 20220509_131309.jpg…]()

**Comment by acleiker2** [comment]
https://youtu.be/rKhhRKs_l68 for the output of nano

**Comment by Super-6-1** [comment]
> > When running holoinstall on this latest release, the installation fails, with a lot of ERROR: failed to setup chroot /mnt.
> > The results of lsblk afterwards points shows my nvme0n1p2 is mounted to /var/mnt.
> 
> Ouch.... looks like i made a small mistake
> 
> Can you run nano /usr/local/bin/holoinstall, get to part with "pacstrap --noconfrim" and replace it with "pacstrap -i"

This worked

**Comment by Super-6-1** [comment]
I'm still getting issues after the download 
![Uploading 20220509_132754.jpg…]()

**Comment by acleiker2** [comment]
I can confirm that changing the pacstrap --noconfirm to -i does indeed solve the problem. Thank you.

**Comment by acleiker2** [comment]
Upon rebooting after what appeared to be a successful install, it did not actually create a EFI boot entry. Output of efibootmgr only shows the UEFI: Samsung drive that I installed from.

**Comment by Super-6-1** [comment]
> Upon rebooting after what appeared to be a successful install, it did not actually create a EFI boot entry. Output of efibootmgr only shows the UEFI: Samsung drive that I installed from.

I can conclude the same efi doesn't show a boot drive.

**Comment by acleiker2** [comment]
Was able to bypass by manually mounting the partitions and running grub-install --efi-directory=/efi instead of /boot/efi while in arch-chroot.

**Comment by Super-6-1** [comment]
> Was able to bypass by manually mounting the partitions and running grub-install --efi-directory=/efi instead of /boot/efi

Got the commands?

**Comment by acleiker2** [comment]
In my case. I'll be using nvme0n1
mount /dev/nvme0n1p2 /mnt
mount /dev/nvme0n1p1 /mnt/efi
arch-chroot /mnt
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=holo --removable
exit
reboot

**Comment by Super-6-1** [comment]
> 

Confirmed working

**Comment by mijosch** [comment]
> In my case. I'll be using nvme0n1 mount /dev/nvme0n1p2 /mnt mount /dev/nvme0n1p1 /mnt/efi arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=holo --removable exit reboot

Does work
