### ISSUE TITLE
[Info] Offline ISO installer image build-date 2023-03-24

### ISSUE THREAD

**Issue by nt74** [holoiso-eol/holoiso#743]
If You would like to upload the latest offline ISO file please feel free to use mine. I created this one on 24th of March 2023.
Also included is the SHA256 checksum file. Many thanks for a great project!

Link to the ISO:
https://drive.google.com/file/d/1MG8mXY4krDdGAkZ4BdMeteIb2KRU2uom/view?usp=sharing

Link to SHA256 checksum:
https://drive.google.com/file/d/1tMHf3UvSosOSbW3zADkuhmZtj0WmPtNV/view?usp=sharing

**Comment by megapro17** [comment]
Free Download (1MB/s)
are you kidding me? Can't you find better cloud?

**Comment by nt74** [comment]
New links with hopefully better download speeds. It would however be better if the maintainers could upload these files for people to access through the upstream releases.

**Comment by clemens98** [comment]
file download limit exieded

**Comment by Nulled-Out** [comment]
Can't wait to try it! :D
