### ISSUE TITLE
Is it ok or something is off?

### ISSUE THREAD

**Issue by mkikets99** [holoiso-eol/holoiso#746]
![VideoCapture_20230407-194932.jpg](https://user-images.githubusercontent.com/22869811/230646698-02acb95a-c6ce-432b-8ee0-ddd70bae4f45.jpg)

Having those at the beginning...
Do I need to be worried?

System starts normally, btw...
Just curious because those messages apearing everytime at boot.

**Comment by theVakhovskeIsTaken** [comment]
> ![VideoCapture_20230407-194932.jpg](https://user-images.githubusercontent.com/22869811/230646698-02acb95a-c6ce-432b-8ee0-ddd70bae4f45.jpg)
> 
> Having those at the beginning...
> Do I need to be worried?

Nope, excepted behavior, of course it won't allow sda1 to mount because that's your system drive

**Comment by mkikets99** [comment]
What about first 2? About Jupiter...

**Comment by theVakhovskeIsTaken** [comment]
> What about first 2? About Jupiter...

Yeah well those are really working on the actual deck (Jupiter) only
