### ISSUE TITLE
[Feature Request] To allow non-read-only system with updates

### ISSUE THREAD

**Issue by Nulled-Out** [holoiso-eol/holoiso#747]
## Your Issue: 

Feature Request To have an option to install whilst removing the 'read-only' system 
(_Currently done via terminal and Dev mode_) 
but without the clean format that occurs with every update on normal steamdeck. 
 
I mean if its possible to keep changes by relocking file system when done then surely it's possible to just make the OS act as if the changed filesystem is set as locked before an update?

**Comment by theVakhovskeIsTaken** [comment]
i think you clearly didn't try this one :D
