### ISSUE TITLE
Failed to run commands on install for Bootloader, locale, steam deck ui

### ISSUE THREAD

**Issue by Super-6-1** [holoiso-eol/holoiso#75]
![20220509_132754](https://user-images.githubusercontent.com/26772591/167464979-6233b286-6e9e-4e49-81c9-b2cd6b1e5ea4.jpg)

No idea what the issue is. Aya neo pro 2021

**Comment by theVakhovskeIsTaken** [comment]
Looks like your internet got hard a bit for a moment, try downloading again
