### ISSUE TITLE
forced to use wifi

### ISSUE THREAD

**Issue by mijosch** [holoiso-eol/holoiso#76]
Even if connected via LAN it says no internet and want me to connect via wifi

**Comment by theVakhovskeIsTaken** [comment]
> Even if connected via LAN it says no internet and want me to connect via wifi
> 

It just checks whether it can ping google.com or not. Looks like your network doesn't really work well

**Comment by mijosch** [comment]
Sure i used ping with google which worked but running holoinstall fails because of no internet

**Comment by mijosch** [comment]
I deleted the check from the holoinstall script and it works, so something is wrong with the check
