### ISSUE TITLE
[Report] No longer booting up … black screen

### ISSUE THREAD

**Issue by SomaticIllusions** [holoiso-eol/holoiso#763]
## Your Issue:
```
[Failed] Failed to start Jupiter fan control. 

Won’t boot up into gamescope anymore. I installed several updates and restarted from desktop mode and am unable to get back into game scope. 
```
HX99G
```
CPU: AMD
GPU: AMD
```

## version 4.2 newest beta

```

## Your installation type:
```
Holoiso 4.0
```

## Have you updated your installation recently?
```
Yes
```

**Comment by SomaticIllusions** [comment]
![Uploading 0A3F1CA6-F48F-4503-9356-4D837E446E70.jpeg…]()

**Comment by SomaticIllusions** [comment]
![image](https://user-images.githubusercontent.com/39324662/236368111-2af87777-af94-4b23-ba61-035287024aa8.jpeg)

**Comment by Kidswiss** [comment]
Can confirm, same issue with `HoloISO_4.2_ux_changes-20230414_a192ee2182_installation_reuse-fixes1-1-x86_64.iso` from the telegram channel. Freshly installed.

After installing some updates in desktop mode it refuses to boot with the same systemd errors SomaticIllusions.

**Comment by SomaticIllusions** [comment]
Well, it wasn’t Proton 7.0 but all the other updates. I reinstalled last
night and making sure not to upgrade. Lol

**Comment by F1ReB4LL** [comment]
gamescope update (3.11.52.beta6-4 => 3.12.0.beta3-3 atm) causes this

**Comment by SomaticIllusions** [comment]
Nice. So just wait until a new version comes out ? Thanks.

**Comment by sinistarZ** [comment]
same here any eta

**Comment by gertz22** [comment]
Hello, also stuck on black screen, any one find workaround for gamescope issue?

**Comment by gertz22** [comment]
Looks like 4.5 is fixed
