### ISSUE TITLE
Cant boot to steam os (haloiso)

### ISSUE THREAD

**Issue by SilverBlade5050** [holoiso-eol/holoiso#764]
I installed halo iso using ventoy and it installed correctly but when i boot it gives me a blank screen. I saw the boot screen of this  os but not booting

**Comment by SilverBlade5050** [comment]
> I installed halo iso using ventoy and it installed correctly but when i boot it gives me a blank screen. I saw the boot screen of this  os but not booting

My laptop specs:
Lenovo thinkpad e550 with 500gb ssd and 16gb of ram

**Comment by gertz22** [comment]
I have same issue looks like installer mounting  for /dev/disks/by-label/HoloOS_XXXXXX... but in ../by-label isnt such a thing only: ventoy
