### ISSUE TITLE
[Report] Boot problems

### ISSUE THREAD

**Issue by ErickA2000** [holoiso-eol/holoiso#767]
## My issue:

After selecting the steamOS system, the screen goes black and no matter how much time passes, it doesn't boot. An update was applied yesterday (May 10, 2023).

## Installed version:
```
HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64
```

## My device
```
CPU: AMD Ryzen 5 3550H
GPU: AMD Radeon Vega 8
```

**Comment by grimlokason** [comment]
try to do some ctrl+alt+f1/f2/... after some minutes

**Comment by ErickA2000** [comment]
didn't work

**Comment by grimlokason** [comment]
edit the grub entry directly and remove everything that concern the video and splash

**Comment by ErickA2000** [comment]
edit the file that is in /boot/grub/ the grub.cfg?

**Comment by grimlokason** [comment]
No, At boot time, you can edit the grub entry on live.  ( with "e" )Le 12 mai 2023 20:13, RickMirai ***@***.***> a écrit :
edit the file that is in /boot/grub/ the grub.cfg?

**Comment by ErickA2000** [comment]
I couldn't get it to work like this so I reinstalled the OS without losing data from the home partition.
Thanks for you help

**Comment by SomeDetarame** [comment]
>  I reinstalled the OS without losing data from the home partition.


how did you do that? HoloISO stop reinstalling with no losing data with error like "sector .../sda5 doesn't exist", but with full formatting it installs, but i don't want to ruin my new SSD by installing my games again.
