### ISSUE TITLE
GRUB Error 17

### ISSUE THREAD

**Issue by reboun** [holoiso-eol/holoiso#769]
Can't install.

`tGRUB Loating stage1.5.`

`GRUB loading, please wait...`
`Error 17`
`_`

![WhatsApp Image 2023-05-20 at 12 25 34](https://github.com/HoloISO/holoiso/assets/124934245/ed71226f-0581-48a4-8790-cc1d716fdfeb)

**Comment by reboun** [comment]
Now error 22

**Comment by miaadev** [comment]
not fixed
