### ISSUE TITLE
Can't download the ISO

### ISSUE THREAD

**Issue by komasio71** [holoiso-eol/holoiso#770]
Hi, whenever I try to download the ISO from the releases page it fails/stops at 2.09 or 1 Gb on download.
I tried to use download managers, use chrome to download none works, I even used another network and I used both, Google Drive and the normal download link.
Can we just get a torrent file or something? I really want to download that ISO and I'm tired cause it never downloads.

**Comment by FuadFox** [comment]
same here

**Comment by FuadFox** [comment]
@komasio71 
try this link found it in the tags 
http://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

**Comment by komasio71** [comment]
Worry not, I already downloaded it and installed it on my PC.
And it was the worst mistake of my life.

**Comment by komasio71** [comment]
Worry not, I already downloaded it and installed it on my PC.
And it was the worst mistake of my life.

**Comment by FuadFox** [comment]
@komasio71 can you please tell me why ?
