### ISSUE TITLE
Boot: amdgpu: Fatal error during GPU init

### ISSUE THREAD

**Issue by pimboli** [holoiso-eol/holoiso#772]
## Your Issue:
```
When trying to installing with an ISO 4.1+ I receive the following error at the beginning of boot process:
"amdgpu: Fatal error during GPU init```

## Your device's full specs
```
![IMG_20230525_233740](https://github.com/HoloISO/holoiso/assets/5020679/59ef6905-0075-4490-b0cc-04a9e6f1090b)

CPU: AMD ryzen 7 7700X
GPU: integrated gfx
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
4.1, 4.2, 4.5```

**Comment by PennyFranklin** [comment]
how long are you waiting when code ' triggering uevents ' shows? I use the 7900xtx gpu and always stuck at this moment

**Comment by pimboli** [comment]
I waited once hours 😅.

Switched now to chimeraos, seems Kernel on holoiso is too old.

**Comment by PennyFranklin** [comment]
That is quite..... wired : (

**Comment by smoebody** [comment]
Sorry, but this is still an issue. I have a Radeon RX 7800 XT
