### ISSUE TITLE
[Gaming Mode]: HoloISO Gaming mode not working.

### ISSUE THREAD

**Issue by Naymmmm** [holoiso-eol/holoiso#777]
## Your Issue:
```
Gaming mode not working, Linux host. VMWare Workstation Pro 17
```

## Your device's full specs
```
CPU: Intel Core i7-4710mq @ 2.493Ghz
GPU: Nvidia GeForce GTX 960m / VMWare Virtual GPU thing idk / Intel Integrated Graphics
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
3.4
snapshot20221211.1426
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
no Intel GPU, skipping color compression disabling
Making Gamescope Mode Save file at "/home/nay/.config/Gamescope/modes.cfg
Claimed global Gamescope stats session at "/run/user/1000/Gamescope-stats
wlserver: [backend/headless/backend.c:82]
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment
vulkan: failed to find physical device
Failed to initialize Vulkan
/usr/bin/gamescope-session: line 246: kill: (83976) - No such process
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by Naymmmm** [comment]
**[UPDATE]** Still not working, got VMWare tools installed, 3D Graphics acceleration, still broken.

**Comment by MisterSheeple** [comment]
According to the readme, NVIDIA GPUs are not supported, due to gamepadui breaking compatibility with them at some point.
