### ISSUE TITLE
Do we have target disk choice at installation?

### ISSUE THREAD

**Issue by Metafalica** [holoiso-eol/holoiso#780]
The installation process does not cover that question, but it's very important. Who knows what that "Follow on-screen instructions" would be? I don't want it to wipe my existing disk while testing what that "on-screen instructions" offer me... I want to choose another disk, not my main disk with Windows 10. For example, native SteamOS installer installs it only on internal drive without any questions.

**Comment by zweiler2** [comment]
Yes. You can choose a whole seperate drive without affecting your windows disk at all or install alongside windows on that disk;  
Meaning you leave 50GB+ of unformatted space at the end of the disk and install HoloISO there.  
The Installer will ask you where you want to install to.
