### ISSUE TITLE
Resolution not compatible

### ISSUE THREAD

**Issue by Galaxy-Chan** [holoiso-eol/holoiso#782]
I am trying out the iso on a desktop with only a vga hookup so i think it can only do about 1280x720 or about that. every time i try to boot to the desktop to fully install it says on my tv that the screen resolution isnt compatible. i tried on another tv with vga and it didnt work as well. i cant access the main screen to do a full install to the os because i was gonna dual boot on my laptop for a future project im working on.

**Comment by Galaxy-Chan** [comment]
![4B34774D-3E2E-4C86-BA80-0C9F7388A6C2](https://github.com/HoloISO/holoiso/assets/137472219/6a67700c-aa1c-44eb-80f2-ca4c99529d44)
heres what it says everytime it goes past the boot into os screen

**Comment by Galaxy-Chan** [comment]
update: i got it working on my other laptop and it has to be due to screen limitations of course

**Comment by Galaxy-Chan** [comment]
follow up question: can you dual boot with a windows 10 pc? if so how

**Comment by Martan404** [comment]
To dual boot Linux and Windows just Google it or watch a video on YouTube.

You should check out ZorinOS. I currently use it on my desktop until HoloISO becomes more stable or ValvE releases the official ISO

**Comment by Galaxy-Chan** [comment]
> To dual boot Linux and Windows just Google it or watch a video on YouTube.
> 
> You should check out ZorinOS. I currently use it on my desktop until HoloISO becomes more stable or ValvE releases the official ISO

alright thanks appreciate it

**Comment by Galaxy-Chan** [comment]
> To dual boot Linux and Windows just Google it or watch a video on YouTube.
> 
> You should check out ZorinOS. I currently use it on my desktop until HoloISO becomes more stable or ValvE releases the official ISO

i checked out that os but im more interested in the steamos for now
