### ISSUE TITLE
[ADD HD 630+I5 7500 PLEASE]

### ISSUE THREAD

**Issue by GT115** [holoiso-eol/holoiso#785]
## ADD INTEL 630 HD:
```
* 🙏 Please add intel hd 630 graphics 🙏 *
```
CPU: intel core i5 7500
GPU:HD 630.

Thanks for understanding 😊

**Comment by GT115** [comment]
Add uhd 630

**Comment by Jubscleisson** [comment]
@GT115 but i5 7500 uses HD630 instead of UHD630 iirc

**Comment by GT115** [comment]
> 

Thanks

**Comment by theVakhovskeIsTaken** [comment]
@GT115

**Comment by GT115** [comment]
> @GT115

Yes

**Comment by GT115** [comment]
@theVakhovskeIsTaken yes
