### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by dbhasin96** [holoiso-eol/holoiso#786]
## Your Issue: how do I uninstall HoloISO and reinstall windows on the laptop. I am using a Lenovo ideated. 
```
*type your problem here*
```

## Your device's full specs
```
CPU: Apple A15 Bionic
GPU: Apple Lighting 2nd gen
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by GT115** [comment]
Need windows installation on usb

**Comment by GT115** [comment]
Type diskpart on cmd

**Comment by GT115** [comment]
Type
Select disk 0
Clean
