### ISSUE TITLE
ASUS Prime Z390-A with Core i5-9400 (scrambled video)

### ISSUE THREAD

**Issue by bearhntr** [holoiso-eol/holoiso#787]
## Your Issue:
```
Fresh install on this machine's Samsung EVO 970+ NMVe 512GB SSD; no matter which option I choose after I get the "Installation is complete - reboot" message, I get nothing but scrambled video.  I was not prompted (as so many videos I have seen) to choose INTEL video.  I have GPU installed as I wanted to see if the integrated Intel UHD Graphics 630 core would get me some use. 
```

## Your device's full specs
```
CPU:  Intel i5-9400
RAM:  48GB  (Video set to use 1024MB)
GPU:  Integrated Intel UHD Graphics 630 core
HDD:  Samsung EVO 970+ NMVe SSD
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
I get Syntax error when using the command above from GRUB command line.
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
I cannot get that far. See images below as to what I am getting.
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
I just downloaded this version 3 days ago (HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso)
```
![PXL_20230710_001459999](https://github.com/HoloISO/holoiso/assets/100164602/8e2d80e6-197c-4f2e-b9b2-0e47633959b2)
![PXL_20230710_001638055](https://github.com/HoloISO/holoiso/assets/100164602/a6dcf8e0-ecfe-40d9-ad69-44ca703e74bc)

**Comment by bearhntr** [comment]
I was able to get the other image:

![PXL_20230710_005745301](https://github.com/HoloISO/holoiso/assets/100164602/200dfc7b-f92e-4ee0-bf32-d637d8ad9407)

**Comment by umbrella369** [comment]
You are able to use rEFInd to solve the problem.

**Comment by umbrella369** [comment]
> You are able to use rEFInd to solve the problem.

I solve this by the boot tool

**Comment by bearhntr** [comment]
> > You are able to use rEFInd to solve the problem.
> 
> I solve this by the boot tool

I have no idea what rEFInd is that you mention.  I gave up trying, as I was not getting anywhere.  Nothing I did would make it work.  If you have suggestions, please share.

**Comment by umbrella369** [comment]
> > > You are able to use rEFInd to solve the problem.
> > 
> > 
> > I solve this by the boot tool
> 
> I have no idea what rEFInd is that you mention. I gave up trying, as I was not getting anywhere. Nothing I did would make it work. If you have suggestions, please share.

I’m sorry that the problem can’t be solved by my solution, because I read your problem as grub’s error, but your problem is about Intel graphics.
