### ISSUE TITLE
Improper UI Scaling

### ISSUE THREAD

**Issue by Apt-get-CupRamen** [holoiso-eol/holoiso#79]
I know this is more of a Steam Deck issue as well, but even when I force the resolution to 1280 by 800 the Home UI goes wonky and the overlay is slightly off from the top. 

Device being used is an Elitedesk 705 G4, AMD Ryzen 5

**Comment by sharicov** [comment]
Same with ultrawide monitor (2560x1080) store and menus are moving to right half-screen.

**Comment by theVakhovskeIsTaken** [comment]
Disable OpenGL scaling in developer settings.
