### ISSUE TITLE
is it available on RTX 4090?

### ISSUE THREAD

**Issue by ZongXR** [holoiso-eol/holoiso#792]
I have a RTX 4090 machine, which CPU is i9. Is this image available on my machine ?

**Comment by k1yrix** [comment]
Let me remind you that support for NVIDIA GPUs are unsupported at the moment, as stated in the repo's readme.md

![Screenshot 2023-07-18 16 06 38](https://github.com/HoloISO/holoiso/assets/80133246/52afbe6c-8945-48a2-90b1-c6992589db90)

**Comment by CorruptName** [comment]
While i can't vouch for haloiso, chimeraos will work on systems with 4090 if they also have integrated graphics. Just plug your monitor into the onboard port and use "export-gpu" from terminal from desktop mode and select your integrated graphics. 4090 will still be used for rendering but image will be passed through igpu. I cannot try similar on haloiso because i cannot boot it due to "hub doesn't have any ports!" error.

**Comment by Bryan199234** [comment]
> I have a RTX 4090 machine, which CPU is i9. Is this image available on my machine ?

You could try an older version: v3.3 or v3.5, I believe? I, too, am also running a Nvidia build and have been running that version of the OS due to it being the last support image. I honestly haven't had any issues with it and get all Proton updates.

**Comment by GoogleLLP** [comment]
> 

Could you please tell me about the image download link? I searched  in this repository but no one is available. Thank you very much!

**Comment by ZongXR** [comment]
> > I have a RTX 4090 machine, which CPU is i9. Is this image available on my machine ?
> 
> You could try an older version: v3.3 or v3.5, I believe? I, too, am also running a Nvidia build and have been running that version of the OS due to it being the last support image. I honestly haven't had any issues with it and get all Proton updates.

Could you please tell me about the image download link? I searched in this repository but no one is available. Thank you very much!

**Comment by ZongXR** [comment]
> While i can't vouch for haloiso, chimeraos will work on systems with 4090 if they also have integrated graphics. Just plug your monitor into the onboard port and use "export-gpu" from terminal from desktop mode and select your integrated graphics. 4090 will still be used for rendering but image will be passed through igpu. I cannot try similar on haloiso because i cannot boot it due to "hub doesn't have any ports!" error.

Unfortunately, there's no integrated graphics on my board. Do you have another solution?

**Comment by k1yrix** [comment]
> > > I have a RTX 4090 machine, which CPU is i9. Is this image available on my machine ?
> > 
> > You could try an older version: v3.3 or v3.5, I believe? I, too, am also running a Nvidia build and have been running that version of the OS due to it being the last support image. I honestly haven't had any issues with it and get all Proton updates.
> 
> Could you please tell me about the image download link? I searched in this repository but no one is available. Thank you very much!

There is a v3.3 build available, which is basically right here: https://github.com/HoloISO/holoiso/releases/tag/off_1 (I cannot verify if this is still downloadable or not, but I can only assume so)

**Comment by ZongXR** [comment]
> > > > I have a RTX 4090 machine, which CPU is i9. Is this image available on my machine ?
> > > 
> > > 
> > > You could try an older version: v3.3 or v3.5, I believe? I, too, am also running a Nvidia build and have been running that version of the OS due to it being the last support image. I honestly haven't had any issues with it and get all Proton updates.
> > 
> > 
> > Could you please tell me about the image download link? I searched in this repository but no one is available. Thank you very much!
> 
> There is a v3.3 build available, which is basically right here: https://github.com/HoloISO/holoiso/releases/tag/off_1 (I cannot verify if this is still downloadable or not, but I can only assume so)

I've noticed this. But it's not downloadable now by no reasons. So I'm search for other alternatives. Thanks a lot.

**Comment by theVakhovskeIsTaken** [comment]
Try to use latest NVIDIA drivers from extra-main and multilib-main
