### ISSUE TITLE
Unusable on Asus Zenbook S13 OLED

### ISSUE THREAD

**Issue by Gpinchon** [holoiso-eol/holoiso#799]
## Your Issue:
```
I'm trying to install HoloISO on an Asus S13 OLED and the installer doesn't seem to recognize the laptop's keyboard.
I successfully launched the installation process by running in "copy-to-ram" mode and replacing the USB key with a physical keyboard.
Once past installation, the Wi-Fi doesn't work, keyboard is still not recognized and the screen is very dark.
```

## Your device's full specs:
```
Asus Zenbook S13 OLED
CPU: AMD Ryzen™ 7 6800U
GPU: AMD Radeon™ Graphics RDNA 2
```

## Your OS version:
```
release-4.0
```

## Your installation type:
```
I don't understand the question.
```

## Have you updated your installation recently?
```
I cannot even install.
```

**Comment by Grimish-ng** [comment]
I'm going to say this really fast - holoiso uses a kernel that is pretty much that on part with the deck itself. So its a little far behind even for your Asus Zenbook. I would say unless you are somewhat proficient with linux you may want to hold back a little. If you want to try to get a newer kernel on there (basically replacing what holoiso ships with) that would probably resolve your issues.

This is all just speculation. I don't know alot about your hardware but it seems a little newer.

**Comment by Gpinchon** [comment]
Thanks for your answer, I'm quite proficient with linux, but the person using this laptop isn't. So after tinkering around I decided she would be better off with a good ol' Debian with Steam installed, and SteamTinkerLaunch or Lutris.
And apart from the lack of shiny convenient Steam interface it works very well, even giving far superior performances on The Sims 4 than on Windows where it stuttered and froze all over the place.
Overall I think I'll just wait for either Valve to release Steam OS, or the forks to get more mature.

**Comment by Grimish-ng** [comment]
I think thats a good choice. I had the choice of doing this on my desktop and its sopmething I decided against after all I've gone through. Compiling the kernel, switching packages (wireplumber and pipewire) among other things that holoiso has already straightened out. Compiling mesa, getting my nvidia driver working. I'm on the latest kernel and its great I admit but not something I want to maintain on another machine even if its all amd.

I went with a default install of arch linux with steam, got a threadripper 3960X and a 6900XT. Using kwin as the compositor, no gamescope at all - and I have to say WOW linux has certain come a long way with gaming and of course proton and valve. Just a little tidbit that you may already know, corectl is pretty damn good for any amdgpu.

**Comment by Gpinchon** [comment]
> Just a little tidbit that you may already know, corectl is pretty damn good for any amdgpu.

Oh thank you for this advice, I did not know this utility, installing it right away ! 👌

I understand this feeling you're talking about, that's why I backpedaled early in order to avoid the sunk loss bias, especially when there are easier and more maintainable solutions 😅

**Comment by winstonma** [comment]
@Gpinchon Actaully this is Linux Kernel related problem. You have to use You can check [um5302ta](https://github.com/latin-1/um5302ta) repo for more detail. Actually I have keyboard problem on Ubuntu 22.04 which comes with Linux Kernel 5.15. After installing Ubuntu with external keyboard then I updated the kernel to 5.19, then all are good.

But if you want everything working you need to install Linux Kernel 6.1+.

**Comment by LightLegendXR** [comment]
@winstonma cock balls asuck
