### ISSUE TITLE
GPU problems

### ISSUE THREAD

**Issue by massatt212** [holoiso-eol/holoiso#8]
GPU At 100% with 36 watts maxed used<RX 470 8GB
I5 4th Gen

**Comment by theVakhovskeIsTaken** [comment]
Is this in perfomance overlay inside Steam Deck's UI? If yes, ignore the "100%" mark, that's a bug that comes directly from Valve, because `mangoapp` isn't optimized for different GPUs

**Comment by massatt212** [comment]
But I'm getting , 23 to 30 fps also, if I put it on -steamos without 3 it works fine, bit no steamos3 benefits.

**Comment by theVakhovskeIsTaken** [comment]
Have you installed Steam client update? If not, do it now. Since OOBE version of client isn't really smooth.

**Comment by massatt212** [comment]
Yes everything updated, some reason it won't use my gpu properly, I even tried Amdvlk.
