### ISSUE TITLE
Wayland session (handheld mode) does not start

### ISSUE THREAD

**Issue by mijosch** [holoiso-eol/holoiso#80]
It just does not start gives an error:
failed to start Jupiter controller firmware update service

I am running a I3-4160 and a R7 370 -> x11 runs with amdgpu

**Comment by theVakhovskeIsTaken** [comment]
Your GPU probably isn't supported by RADV.

Can you run `gamescope-session` while being in desktop mode?

**Comment by Super-6-1** [comment]
I saw this issue also and I'm running amd but it will eventually start up. Problem is now I'm getting random lockups, visual tearing on the screen and more. 

From my aya neo pro 2021
