### ISSUE TITLE
[Report] No audio through built in speakers

### ISSUE THREAD

**Issue by parth-menon** [holoiso-eol/holoiso#806]
## Your Issue:
```
No audio through speakers on OneXPlayer 2 Pro
3.5 mm jack is working
```

## Your device's full specs
```
CPU: Ryzen 7840u
GPU: Ryzen 780M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230820.1658-1
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
- I tried a lot of ArchLinux fixes like pulseaudiio, alsa, amixer etc. None of it worked
```

## Have you updated your installation recently?
```
Yes
```

**Comment by zongren** [comment]
any update

**Comment by parth-menon** [comment]
> any update

No support from HoloISO.
Use chimeraOS, atleast developers respond there.

**Comment by zongren** [comment]
> > any update
> 
> No support from HoloISO. Use chimeraOS, atleast developers respond there.

ok, give it a try on my gpd mini

**Comment by parth-menon** [comment]
> > > any update
> > 
> > 
> > No support from HoloISO. Use chimeraOS, atleast developers respond there.
> 
> ok, give it a try on my gpd mini

GPD audio should work! This issue is only for OneXPlayer2, OneXPlayer2 Pro and OneXFly
