### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by Elcapone86** [holoiso-eol/holoiso#807]
## Your Issue:

Onexplayer 2 

Power overlay in the middle of the screen 
Different languages in desktop Steam and GameMode UI for 2 games.

*type your problem here*

1. 

My performance overlay is in the middle of the display, I guess because the GameUI resolution is 1280x800 and my Oxp uses a 2k resolution.

Is there any way to adjust the GameMode Ui resolution? 

2.

I have the problem with Diablo 2 Ressurrected and Red Dead Redemption 2 that both games run in desktop Steam in German (which is desired) and in GameMode Ui in English. 

Can I change this somehow? 

## Your device's full specs
```
CPU: Ryzon 6800
GPU: Radeon 680m 
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
4
snapshot20230820.1825

**Comment by theVakhovskeIsTaken** [comment]
@Elcapone86 sudo genquirks --gamescope_resolution 2560x1600

**Comment by Elcapone86** [comment]
@theVakhovskeIsTaken Unfortunately this did not work
