### ISSUE TITLE
Power button not working for sleep on 5.0.x using Steam Deck [Report]

### ISSUE THREAD

**Issue by payaso13th** [holoiso-eol/holoiso#808]
## Your Issue:
```
Power button not working for sleep using Steam Deck in Game Mode. (However in Desktop Mode I can set power button to sleep and it's working)

```

## Your device's full specs
```
CPU: AMD APU CPU: Zen 2 4c/8t, 2.4-3.5GHz
GPU: 8 RDNA 2 CUs, 1.0-1.6GHz
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
image snapshot20230823.1454
```

## Have you updated your installation recently?
```
Yes
```

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th Does ps aux | grep "power" return something with "powerbuttond"?

**Comment by payaso13th** [comment]
(holoiso@holoiso ~)$ ps aux | grep "power"
root        2953  0.0  0.0 313788 11192 ?        Ssl  Aug23   0:00 /usr/lib/upowerd
holoiso     6214  0.1  0.3 563084 46336 ?        Ssl  03:43   0:00 /usr/lib/org_kde_powerdevil
holoiso     8029  0.0  0.0   6580  2432 pts/1    S+   03:45   0:00 grep --color=auto power

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th Could you run that inside gamescope mode, and run the same command under ssh?

**Comment by payaso13th** [comment]
Added Konsole as non-steam game and got this.

(holoiso@holoiso Steam)$ ps aux | grep "power"
ERROR: ld.so: object '/home/holoiso/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/holoiso/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
root        2953  0.0  0.0 313788 11196 ?        Ssl  Aug23   0:00 /usr/lib/upowerd
holoiso    14297  0.1  0.1  28784 19692 ?        S    04:39   0:00 /usr/bin/python /usr/lib/holoiso-hwsupport/power-button-handler.py
holoiso    15817  0.0  0.1  29160 23936 pts/0    S+   04:41   0:00 grep --color=auto power
pid 15818 != 15403, skipping destruction (fork without exec?)

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th Are you sure your device is identified as Steam Deck?

Please run cat /sys/devices/virtual/dmi/id/product_name and see if it outputs Jupiter 1

**Comment by payaso13th** [comment]
Desktop Mode:
(126)(holoiso@holoiso ~)$ cat /sys/devices/virtual/dmi/id/product_name
Jupiter

**Comment by payaso13th** [comment]
Gaming Mode:
(holoiso@holoiso Steam)$ cat /sys/devices/virtual/dmi/id/product_name
ERROR: ld.so: object '/home/holoiso/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Jupiter
pid 5927 != 5468, skipping destruction (fork without exec?)

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th Understood. Will fix shortly later

**Comment by payaso13th** [comment]
@theVakhovskeIsTaken Thank you, will it be fix thru update?

**Comment by payaso13th** [comment]
@theVakhovskeIsTaken  Thank you, will it be fix thru update? Or I have to full reinstall again? Did a reinstall multiple times now and it's tiring setting everything up again.

(Power button was working properly on 4.1) 😔

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th No! You would need to just update and that's it!

**Comment by payaso13th** [comment]
@theVakhovskeIsTaken thank you so much, will wait for it later. 😔

**Comment by theVakhovskeIsTaken** [comment]
@payaso13th https://t.me/c/1516578859/22274 You may try now!

**Comment by payaso13th** [comment]
Working now!  Thank you so much, you're the best! @theVakhovskeIsTaken
