### ISSUE TITLE
[Bug] No Audio out through Internal Speakers for OneXPlayer2 Pro

### ISSUE THREAD

**Issue by parth-menon** [holoiso-eol/holoiso#811]
## Your Issue:
```
There is no audio coming out of OneXPlayer 2 Pro built-in speakers. 
Headphone jack and Bluetooth works.
```

## Your device's full specs
```
CPU: Ryzen 7840u
GPU: 780M
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230820.1658-1
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
I reported this to ChimeraOS as well. They are working on a fix too.
I have a bunch of logs for this.

Alsa info: http://alsa-project.org/db/?f=280c56830a60868346995b41309f663c5fe7510b
[oxp2pro-dmesg.log](https://github.com/HoloISO/holoiso/files/12448876/oxp2pro-dmesg.log)
[RtHDDump.txt](https://github.com/HoloISO/holoiso/files/12448877/RtHDDump.txt)

This is a fix patch they tried to send me but i couldn't get thr kernel to install properly.
[oxp2-pro-audio-patch-test-patch.txt](https://github.com/HoloISO/holoiso/files/12448878/oxp2-pro-audio-patch-test-patch.txt)

Please help
```

## Have you updated your installation recently?
```
*Yes*
```

**Comment by parth-menon** [comment]
Hey team,
Is there anything i can do to help fix this issue?

**Comment by rpheuts** [comment]
I tried a multitude of Linux distros and kernels on my OneXPlayer 2 and audio through the speakers does not work anywhere. This seems to be an issue with Linux at large…

**Comment by parth-menon** [comment]
> I tried a multitude of Linux distros and kernels on my OneXPlayer 2 and audio through the speakers does not work anywhere. This seems to be an issue with Linux at large…

We actually had a discussion with ChimeraOS devs about it.
Here is the issue i created
https://github.com/ChimeraOS/chimeraos/issues/742

**Comment by NightHammer1000** [comment]
At this Point we are pretty sure its just an Issue with the AMPs not turning on.

Any Input on how we could manage that is Welcome.

Things that did not help:

Setting Pins and COEF like the Windows Driver.
Toggling the GPIO Pins
