### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by umbrella369** [holoiso-eol/holoiso#812]
## Your Issue:
Sleep mode in my machine doesn't work well. I can't wake it up after it falls into sleep mode. I think this is about acpi devices,because my PC report "acpi error" when I start the Steam Os. 

## Your device's full specs
CPU: Ryzen 5600
GPU: RX6600

## Your OS version:
snapshot20230824.1429

## Have you updated your installation  recently
no

**Comment by theVakhovskeIsTaken** [comment]
@umbrella369 is your motherboard by a(n/s)us?

**Comment by umbrella369** [comment]
> @umbrella369 is your motherboard by a(n/s)us?

no,the motherboard was b550itx by Sapphire. Maybe you haven't heard.
