### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by fogsaturate** [holoiso-eol/holoiso#814]
## Your Issue:
```
Random errors flash up, and it hangs on the steam deck starting logo. One of them mentions the fact that SGX is disabled by BIOS, but I have AHCI enabled, and TPM is also enabled. There is no option for SGX in my bios. I am on an Acer Nitro 5. I do not know what to do, and it wont get past the steam deck logo on startup.
```

## Your device's full specs
```
Laptop Specs (Integrated Graphics and GPU)
CPU: Intel i5-8300H (8) @ 4.000GHz
iGPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
i can not check this if i cant get past the steam deck logo
```

## Have you updated your installation recently?
```
yes, latest build in the debug telegram channel, and the same issue persists on the latest stable build.
```
![IMG_7944](https://github.com/HoloISO/holoiso/assets/57604850/be46a89e-2789-4be1-80ca-c51ea0ff69a3)
![IMG_7945](https://github.com/HoloISO/holoiso/assets/57604850/6dc91d82-bc2f-454e-8f3d-addacfc26534)

**Comment by theVakhovskeIsTaken** [comment]
@fogsaturate NVIDIA and Intel GPUs are *not* supported.

**Comment by fogsaturate** [comment]
> 

Thank you. This was really confusing since it used to work about a year ago when I installed it on the same laptop, but it confused me it didn't work again.

**Comment by Diceyreal** [comment]
I had the same issue
but with a AMD laptop with a gpu error

**Comment by nisel11** [comment]
> I had the same issue but with a AMD laptop with a gpu error

Do you have usb 2.0 or 3.0?
My 2.0 flash drive has this problem, my 3.0 doesn't.
