### ISSUE TITLE
[Dual-GPU, Gamescope] Getting garbled graphics when loading up holo iso.

### ISSUE THREAD

**Issue by PrateekDas97** [holoiso-eol/holoiso#817]
![IMG-20230903-WA0005](https://github.com/HoloISO/holoiso/assets/103494593/99690fd8-6631-40ff-aba7-0468057f38d2)
Greetings,

I installed the OS  as specified in the installation instructions (dual boot. Tried having win10 and holo iso on the same drive and on separate drives.)

After installation, when I restarted I got the steam logo and then the display started to glitch out. Lines and squares of various sizes and colours.

Please help!

Specs:
Asus Tuf fx505dy

CPU:
Ryzen 5 3550h

Ram:
16gb ram 2400mhz

Graphics card:
Rx560x 4gb (Dedicated); 
Amd Radeon(TM) Vega 8 (Internal)

**Comment by PrateekDas97** [comment]
I also tried to open plasma by going into the terminal, typing in my ID and password, and using "steamos-session-select plasma".
It got stuck on the splash screen. Kindly Help.

**Comment by nisel11** [comment]
I'm writing late, but I solved this by installing vulkan-mesa-layers and lib32-vulkan-mesa-layers

**Comment by PrateekDas97** [comment]
Hi,

Thanks for your reply. I am starting out with linux.

Could you please help me with he steps to do so.

Regards,
Prateek Das

**Comment by nisel11** [comment]
Burn the HoloISO image to a flash drive, boot from it and before installation go to konsole and enter there:
`sudo pacman -Sy lib32-vulkan-mesa-layers`
and then you can start the installation.

**Comment by PrateekDas97** [comment]
Thanks a lot!!!!!!
It works now. Now to figure out how to let it know the path to the games😁
