### ISSUE TITLE
[Report] sudo steamos-readyonly disable results in "error command not found"

### ISSUE THREAD

**Issue by ThePfhor** [holoiso-eol/holoiso#821]
## Your Issue:
steamos-readyonly disable results in "error command not found"
*type your problem here*
Essentially title, I cannot unlock the filesystem. I want to do this so I can access my drive when I am booted into Windows 11 on my second SSD to move games back and forth as I see fit.

## Your device's full specs
```
CPU: AMD 7840U
GPU: 780M integrated graphics
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230823.1454
```

## Have you updated your installation recently?
```
*No, I did a clean install from 5.0.1 and did not update either within Game Mode or in Desktop mode.*
```

**Comment by MadSynth** [comment]
You may have a misspelling in your code:
`steamos-readyonly`

It is actually supposed to be written as follows:
`steamos-readonly`

Hope that helps!

-MadSynth

**Comment by ThePfhor** [comment]
Ah, yes, that was a typo on GitHub, not on my HoloISO CLI.
The error still persists, I just tried again.
Thanks though!

**Comment by theVakhovskeIsTaken** [comment]
You will be surprised when you run 'sudo touch /test’....
