### ISSUE TITLE
Proxmox VM 6700XT not running at 100%[Report]

### ISSUE THREAD

**Issue by MDevellis** [holoiso-eol/holoiso#823]
## Your Issue:

The GPU is not running at full speed. It's only using about half it's max power(~100w out of it's ~180w) after using most of the community work arounds to get rid of the TDP limits built in for the Steam Deck. The FPS is not even close to what a 6700XT should be getting. Even at the lowest settings in Spiderman Remastered at 1080p with FSR 2.1 ON I can't even get a steady 60FPS and it regularly dips and stays around 30-40FPS. 

1. I've tried editing /usr/bin/steamos-polkit-helpers/steamos-priv-write as suggested by https://github.com/HoloISO/holoiso/issues/294#issuecomment-1164047278

2. I've also tried editing ~/.steam/steam/config/config.vdf as suggested by https://github.com/HoloISO/holoiso/issues/94#issuecomment-1124460628
Only I changed FPS Limit/V2 to 144 because of my monitor and my TDP to 250

3. I tried step 2. again only this time I edited .local/share/Steam/config/config.vdf file instead as suggested by the pdf posted here: https://github.com/HoloISO/holoiso/issues/94#issuecomment-1125727811

The GPU runs at 100w and will hover around 60-80w sometimes which is not normal for my card. I have only tried Spiderman so far but will try more titles for testing soon. 

And a side note, the audio is crackling and very delayed within the VM.

"lspci -v" output within the VM:
```
02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] (rev c5) (prog-if 00 [VGA controller])
        Subsystem: Tul Corporation / PowerColor Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
        Physical Slot: 0-2
        Flags: bus master, fast devsel, latency 0, IRQ 29
        Memory at 800000000 (64-bit, prefetchable) [size=16G]
        Memory at c00000000 (64-bit, prefetchable) [size=2M]
        I/O ports at c000 [size=256]
        Memory at c0e00000 (32-bit, non-prefetchable) [size=1M]
        Expansion ROM at c0f20000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

02:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21/23 HDMI/DP Audio Controller
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21/23 HDMI/DP Audio Controller
        Physical Slot: 0-2
        Flags: bus master, fast devsel, latency 0, IRQ 71
        Memory at c0f00000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel 
```

Update:
Just tested Halo TMCC, same problem. Gonna try creating a new VM with an identical config only in Ubuntu 22.04 Desktop instead. Will update soon.

Update 2:
The audio is fixed in Ubuntu but the GPU utilization/power consumption is the same. Tried a Windows 10 VM too and I'm getting code 43 with and without Resizable BAR enabled.

Update 3
I just booted the exact config from bare metal(No VM) and HoloISO is mostly working fine now, no audio issues now, the GPU is being fully utilized EXCEPT there is a 72FPS cap on my games now and I don't know how to fix that but I now know there is a problem with the Proxmox VM config whether it's user error or not.

Update 4
Got the Windows VM working and everything is working perfectly now. I'd ideally like to still use HoloISO as it's way more controller friendly so I'm going to keep this open for now. I'm going to retest Ubuntu and few other distros as well and update this as I go.

## Your device's full specs

HoloISO is running in a Proxmox VM(Debian 11 based hypervisor). I've passed 8 of the CPU's cores(which are actually threads in this case), 16GB of ram out of the 48GB DDR4 available, the GPU's driver is blacklisted on the host and both the NVMe drive and GPU are fully passed to the VM. 
```
CPU: Ryzen 7 5700x
GPU: RX 6700XT
SSD: Corsair MP510 PCIe 3.0 960GB
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230824.1429
```

## (Only for SteamOS Session loading issues) Have you tried launching 
`gamescope-session` from terminal? If yes, provide a log.
Ignore the CPU temp sensor error, afaik it's because it's running in a VM and I don't know or really care to fix that as I monitor it's temp from the Proxmox host (70c under load fyi).

```
Making Gamescope Mode Save file at "/home/devellis/.config/gamescope/modes.cfg"
Making Gamescope patched edid at "/home/devellis/.config/gamescope/edid.bin"
Claimed global gamescope stats session at "/run/user/1000/gamescope-stats"
Skipping any device quirks, as device-specific quirks weren't set.
wlserver: [backend/headless/backend.c:68] Creating headless backend
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 6700 XT (RADV NAVI22)': queue family 1
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :1
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x557a9688d240 (res 0x557a968a0490)
wlserver: [xwayland/server.c:273] Xserver is ready
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x557a96717ee0 (res 0x557a968a3330)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 52
wlserver: Updating mode for xwayland server #0: 1280x720@60
pipewire: renegotiating stream params (size: 1280x720)
Error : /etc/xbindkeysrc not found or reading not allowed.
please, create one with 'xbindkeys --defaults > /etc/xbindkeysrc'.
or, if you want scheme configuration style,
with 'xbindkeys --defaults-guile > /home/devellis/.xbindkeysrc.scm'.
/usr/bin/gamescope-session: line 250: /usr/bin/ibus-daemon: No such file or directory
/usr/bin/gamescope-session: line 269: /tmp/steamos-short-session-tracker: No such file or directory
power-button-handler.py: Can't find device for power button!
+ systemctl reload --no-block --state=active 'steamos-automount@*'
Failed to acquire service name: File exists
Is a notification daemon already running?
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x557a96632200 (res 0x557a96807cd0)
[2023-09-09 20:24:42.046] [info] [config.cpp:123] parsing config: '/tmp/mangohud.FeLGg7eC'
[2023-09-09 20:24:42.066] [error] [cpu.cpp:461] Could not find cpu temp sensor location
[2023-09-09 20:24:42.067] [info] [overlay.cpp:815] Uploading is disabled (permit_upload = 0)
power-button-handler.py: Can't find device for power button!
xwm: Rejecting WM_CHANGE_STATE to ICONIC for window 0x400007
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
steam.sh[45322]: Running Steam on steamos rolling 64-bit
steam.sh[45322]: STEAM_RUNTIME is enabled automatically
setup.sh[45440]: Steam runtime environment up-to-date!
power-button-handler.py: Can't find device for power button!
power-button-handler.py: Can't find device for power button!
steam.sh[45322]: Steam client's requirements are satisfied
gamescope: received kill signal, terminating!
power-button-handler.py: Can't find device for power button!
(EE) failed to read Wayland events: Broken pipe
(EE) failed to read Wayland events: Broken pipe
gamescope-session: unexpected background pid 45307 at teardown: 
    PID TTY          TIME CMD
  45307 pts/1    00:00:00 gamescope-sessi
gamescope-session: unexpected background pid 45321 at teardown: 
    PID TTY          TIME CMD
  45321 pts/1    00:00:00 mangoapp
/usr/bin/gamescope-session: line 323: 45307 Killed                  ( while true; do
    /usr/lib/holoiso-hwsupport/power-button-handler.py;
done )
/usr/bin/gamescope-session: line 337: 45321 Killed                  mangoapp
/usr/bin/gamescope-session: line 337: 45482 Killed                  sleep 5
(devellis@holoiso ~)$ power-button-handler.py: Can't find device for power button!
```

## Have you updated your installation recently?
```
Yes
```

**Comment by johannboth** [comment]
I am having the same issue. 

CPU: Ryzen 7 5800x
GPU: RX 6750XT

Exact same OS version.

**Comment by theVakhovskeIsTaken** [comment]
Alright. Try to use the TDP slider and/or GPU freq in QS menu and see if that changes any issues.
This is strange since i not only fixed it, but also mitigated any OS-dependant condition where DPM states would change

**Comment by MDevellis** [comment]
> Alright. Try to use the TDP slider and/or GPU freq in QS menu and see if that changes any issues. This is strange since i not only fixed it, but also mitigated any OS-dependant condition where DPM states would change

I've gotten the GPU to run at it's full clock speed before and this definitely is an easy way to make it do that but the GPU usage is still sitting at 30% and the wattage is less than half of what it should be just like before. I'm still getting like 1/3 the FPS of what a 6700XT should be getting.

**Comment by johannboth** [comment]
> Alright. Try to use the TDP slider and/or GPU freq in QS menu and see if that changes any issues. This is strange since i not only fixed it, but also mitigated any OS-dependant condition where DPM states would change

For me the GPU issue is gone, and is running at 100% at 200W again. I did play with the sliders as you recommended and I also used the "reset to default" button.

**Comment by MDevellis** [comment]
> > Alright. Try to use the TDP slider and/or GPU freq in QS menu and see if that changes any issues. This is strange since i not only fixed it, but also mitigated any OS-dependant condition where DPM states would change
> 
> For me the GPU issue is gone, and is running at 100% at 200W again. I did play with the sliders as you recommended and I also used the "reset to default" button.

Are you on a 6700XT and in a Proxmox VM?
