### ISSUE TITLE
[Report] Mirrors unreachable. Domain pending deletion.

### ISSUE THREAD

**Issue by KS-HTK** [holoiso-eol/holoiso#827]
## Your Issue:

[holo_mirrorlist](/HoloISO/holoiso/blob/stable/airootfs/etc/pacman.d/holo_mirrorlist) contains three mirror links of which two point to `thevakhovske.pw`.
This domain is no longer reachable. So I did a little digging and it seems they most likely will not work in the future either. The [WhoIs Server for .pw](https://whois.nic.pw/) gives the information that the domain registration ran out 10 Days ago as of today and the Domain Status is `pendingDelete` without any additional status of `redemptionPeriod` or `pendingRestore`. Aside from these status codes there is a more worrying one: `serverTransferProhibited`. ICANN expalins the status code with "This status code prevents your domain from being transferred from your current registrar to another. It is an uncommon status that is usually enacted during legal or other disputes, at your request, or when a redemptionPeriod status is in place." [source](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en#serverTransferProhibited)

My best guess is that the domain will run out in a bit more than 20 Days and is up for grabs beyond then. So it should probably be removed from the mirrorlist prior to that.

## Your OS version:
```
snapshot20221222.1749
```
but the issue is present in almost all branches of this repo.

**Comment by theVakhovskeIsTaken** [comment]
@KS-HTK sudo steamos-update regen

**Comment by KS-HTK** [comment]
> @KS-HTK sudo steamos-update regen

Well that leads to some error about a steamos-updatepersistent-sentinel file missing or along those lines. `steamos-update check` returns that I am up to date.

But that misses the Point of this Issue

> […] the issue is present in almost all branches of this repo.

The Domain is currently not in any DNS so it points to nowhere and should thus be updated to one that does point to the desired location.

**Comment by theVakhovskeIsTaken** [comment]
That domain is not being used/nor owned anymore. You might wanna update your mirrorlists and pacman configuration to latest current files
