### ISSUE TITLE
[Steam Deck] weird night color behavior in gaming mode

### ISSUE THREAD

**Issue by albert-softie** [holoiso-eol/holoiso#830]
## Your Issue:

this is possibly related to #829
as stated in the above issue, manually toggling night mode from gamepadui doesn't work. however, i have noticed that sometimes, but not always, there will be a dim but noticable night color filter over the menus. the filter disables itself when a game is running, but exiting the game, opening the steam/quick access menus, and/or enabling performance overlay will re-enable it (temporarily in the case of the latter 2 scenarios)

## Your device's full specs
```
CPU: AMD Custom APU 0405 (8) @ 2.800GHz
GPU: AMD ATI AMD Custom GPU 0405
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230918.0956
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```

## Have you updated your installation recently?
```
if a first time fresh install counts as an update then yeah i guess
```

**Comment by theVakhovskeIsTaken** [comment]
@albert-softie https://www.reddit.com/r/SteamDeck/comments/146zsj4/upgraded_to_35_nightmode_now_completely_broken/
