### ISSUE TITLE
Two local IP addresses on fresh installations

### ISSUE THREAD

**Issue by F2FG** [holoiso-eol/holoiso#833]
## Your Issue:
```
I get two local IP addresses via wired connection on fresh installations
```

## Your device's full specs
```
CPU: *AMD 7735HS*
GPU: *Integrated*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230823.1454
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/A
```

## Have you updated your installation recently?
```
Fresh installation
```

![20230930_002834](https://github.com/HoloISO/holoiso/assets/50996306/f358a937-e50c-451e-8776-90ae1f761bd0)

**Comment by F2FG** [comment]
I just tested on wifi and I have the same issue.

**Comment by F2FG** [comment]
I think there's a double network configuration, one via systemd and one via networkmanager.

I commented out all the lines in these 3 files:

/etc/systemd/networking/20-ethernet.network
/etc/systemd/networking/20-wlan.network
/etc/systemd/networking/20-wwan.network

and now I have only one IP that I can configure via KDE network manager.

**Comment by minecraft3719** [comment]
Hello, did you resolved this issue and was it affect your browsing experience ?

**Comment by F2FG** [comment]
I solved the issue by commenting the lines as explained above. No, it didn't affect my browsing experience.

**Comment by minecraft3719** [comment]
what was the status of "ip a" or steamOS setting after that, was it only have one ip ?

**Comment by F2FG** [comment]
I had only one IP after that, as it should be. I'm not using HoloISO anymore so I can't do other tests.

**Comment by minecraft3719** [comment]
Ok, thank you for your answer, i just installed Holoiso and having some network issue and require reconnect every time, i saw your post and though having 2 ip for the same 2 interface might be the causes

**Comment by F2FG** [comment]
You're welcome! I think it is a misconfiguration in the installer so everybody's getting a double configuration until it gets solved. I can tell you that I didn't need to reconnect, I just needed a static local IP setup and having a double network configuration was annoying.

This is a long shot, but are you having network issues after you wake up your system from suspend?

**Comment by minecraft3719** [comment]
I do have some issue during the first day install, after that i simply disable suspend and there seems no issue occur. When i woke the laptop from suspend, the OS already reboot and clear my ongoing session, there even some cases i cannot boot the OS when woke up.

**Comment by F2FG** [comment]
Your situation is different from what I had in mind, I can't help you.

**Comment by minecraft3719** [comment]
No problem, thank you for asking anyway, hope your info about double ip could help resolve my issue.
