### ISSUE TITLE
Holoiso boot issues

### ISSUE THREAD

**Issue by tomdelahaba** [holoiso-eol/holoiso#834]
I have been trying to google answer, but without any luck to this particular issue i have. I had ubuntu on my Dell Latitude E6440. Downloaded HoloIso and i used ventoy to create the installation usb. Botting went fine. I selected installing the steam and went through the terminal / konzole installation. At the end it wanted me to reboot the system. I did. Now, when it reboot (or when i atart the pc), immediately after the dell logo appears, i get a selection what i want to do. I have an options of launching steamos, advanced options for steam os or uefi firmware settings. Selecting the steamos seems to try to launch steamos, as the "loading linux-zen, ...." appears and later for a while the holoiso logo appears. But immediately after that, dell logo appears again and nothing is happening. It seems like booting is broken 🤷‍♂️ and it seems like that instead of booting the holo system (or steamos), notebook tries to reboot 🤷‍♂️ any advice?

Edit:
Pressing ctrl+alt+f2 when the logo (dell) is visible displayes me "login" terminal view for a while but it dissapears quickly.

I am able to boot from the installation usb without an issue and the chroot shows it found valid installation...

**Comment by viirin** [comment]
Just wanted to comment that I am experiencing this same issue on a Lenovo Legion 5 Pro.

**Comment by cookiejar5081** [comment]
Same issue on an Acer Aspire.

**Comment by ghost** [comment]
Same issue on Dell Optiplex 9020.

**Comment by theVakhovskeIsTaken** [comment]
have you tried checking readme first? Closing.
