### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by Grimish-ng** [holoiso-eol/holoiso#835]
## Your Issue:
My issue is that, NVIDIA sucks. It blows monkey shit splattering all over their GPU's on linux. For real. They really suck.
*type your problem here*
My problem here is i'm venting. I'm venting because they suck so bad. gamescope has not worked properly since uhh 3.12.0-beta-3-3. I'm effed around with it so much and it really sucks. If anyone is better than I am at trying to get it to work on anything more recent. I'm all ears.

## Your device's full specs
My device is fine. A little dated but fine. 2021 era.
CPU: Ryzen - love it.
GPU: N-Vid-iya-Shit-on-ya!
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
6.6rc4
snapshotxxxxxxxxxxx_xxxx
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
Not when I compile/change/modify anything later.

*Please put anything here if you tried to launch session separately*
Yeah sure - gamescope log shows the same bullshit drm crap.

## Have you updated your installation recently?
yeah everyday.

Not exactly looking for help here. I know we all hate nvidia's crap here. Maybe just some pointers.

**Comment by bluedinosaur139** [comment]
no, you are right, but venting wont help, just sell that ngreedia trash and buy an amd gpu for plug and play linux experience lmao

**Comment by bluedinosaur139** [comment]
also try googling, how do i install nvidia drivers on arch linux.................. then vent at yourself for being too stupid to google lmao
