### ISSUE TITLE
Failed to boot from VirtualBox virtual machine

### ISSUE THREAD

**Issue by Henry7611913083** [holoiso-eol/holoiso#838]
## Your Issue:
Failed to boot from VirtualBox virtual machine
*type your problem here*
Failed to boot from VirtualBox virtual machine

## Your device's full specs
VirtualBox Machine
CPU: *Host: Intel(R) Core(TM) i7-6700K CPU 4GHz, Virtual Machine: 3/4 of Host*
GPU: *Host: NVIDIA GeForce RTX 2070 SUPER(16GB), Virtual Machine: Video RAM 128MB(1/128 of Host)*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
5.0.1
snapshotxxxxxxxxxxx_xxxx
None

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
What's gamescope-session
*Please put anything here if you tried to launch session separately*
2 Times

## Have you updated your installation recently?
NO
*yes or no*

**Comment by theVakhovskeIsTaken** [comment]
@LunaFlies https://music.youtube.com/watch?v=EYqSORnrsWY&si=l9C1_lFLJsz6RTG2

**Comment by Henry7611913083** [comment]
Rufus에서 이미징 했어요 지금은 잘돼요, 하지만 가상머신을 키면 로고 잘 뜨는데 그 후에 검은 화면만 뜨고 아무것도 안 나와요

**Comment by Henry7611913083** [comment]
실제 usb를 가상머신에 연결 했어요
