### ISSUE TITLE
Installer broken 

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#84]
On the latest installer iso, I can install but can't load into the os once the installation is complete. Laptop acts like the drive is completely gone. This wasn't an issue on the last iso I tried before the rolling release. Installing other distros works completely fine.

**Comment by 420247paul** [comment]
you have to build the iso the fixes have been pushed to the git so either build it or wait till a new release

**Comment by Frostyman758** [comment]
Thanks for letting me know! Is there any way I could build it through windows?
 Thanks~

**Comment by pondwater** [comment]
i dont have a arch machine to build with what would it be for ubuntu/debain

**Comment by 420247paul** [comment]
i can see if i can figure out how to share it from my google drive, ill hit you up

**Comment by 420247paul** [comment]
I dont know if this is allowed but here is a link to my google drive with the iso https://drive.google.com/file/d/1RlT8mE7WMkJX2tHl9Gbdw6B8naPJpyNW/view?usp=sharing

**Comment by pondwater** [comment]
thanks man

**Comment by 420247paul** [comment]
no problem

**Comment by pondwater** [comment]
hopefully the auto update works from now on,
but i did have the old one with a nvidia gpu working, but steam needs to just realse the official version

**Comment by 420247paul** [comment]
my gpu is power limited to 40 watts and i cant figure out why yeah gamescope dont work with nvidia gpus under wayland it should work under x11 the standalone gamescope does

**Comment by theVakhovskeIsTaken** [comment]
Fixed as of a8829508ccb02c8cf67978aa97806265167eee1f. Will publish ISO later
