### ISSUE TITLE
Unable to complete update

### ISSUE THREAD

**Issue by DimitriyPS** [holoiso-eol/holoiso#840]
Holo ISO 3
Ambernic WIN 600

The system shows that a new update is available, but cannot install it due to missing dependencies.
![Screenshot_20231018_200702](https://github.com/HoloISO/holoiso/assets/11189223/bd253eff-dcf5-4185-b94a-fd20d3a8520c)
![Screenshot_20231018_200742](https://github.com/HoloISO/holoiso/assets/11189223/6766b687-b425-43f4-a268-c415d931db57)

**Comment by theVakhovskeIsTaken** [comment]
@DimitriyPS there is a clear warning to not update using Discover

**Comment by DimitriyPS** [comment]
I have now read all that is on the page https://github.com/HoloISO
Is there any more source information?

What can I do now to solve this problem?

**Comment by DimitriyPS** [comment]
> @DimitriyPS there is a clear warning to not update using Discover

I have now read all that is on the page https://github.com/HoloISO
Is there any more source information?

What can I do now to solve this problem?

**Comment by nagybal** [comment]
> > @DimitriyPS there is a clear warning to not update using Discover
> 
> I have now read all that is on the page https://github.com/HoloISO Is there any more source information?
> 
> What can I do now to solve this problem?

I did read all the manual as well. I have missed this info too. Is there a way to disable holoiso updates in Discover?

I was using discover and if I try to update I get  
```
 (bigb@holoiso ~)$ sudo steamos-update check && steamos-update now
[sudo] password for bigb: 
Update available
 HoloISO OS Image version 4 (snapshot20230918.0956)
:: Starting full system upgrade...
resolving dependencies...
warning: ignoring package jupiter-hw-support-20231005.2-1
warning: cannot resolve "jupiter-hw-support", a dependency of "steamos-systemreport"
:: The following package cannot be upgraded due to unresolvable dependencies:
      steamos-systemreport

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
 there is nothing to do
yes: standard output: Broken pipe
Cleaning up...
Update complete. Restart your device to finish.
```
Please consider fixing this. The consistency has probably broken down. How can I help?

**Comment by DimitriyPS** [comment]
I tried to do:

`sudo steamos-update check && steamos-update now`

But that didn't change anything, this update reappeared both in desktop mode and in game console mode.

I went into game console mode and went into settings, the system section and switched the update to "Early Build", the system rebooted and it installed. When it downloaded and checked the update appeared again. I either switched the update system to "Stable" again, the system rebooted again and it installed...  I ran the checks that are on the same settings page... then I checked again and tried to install the update, the system rebooted and the update disappeared.

I switched to desktop mode and the update was no longer detected. I think my problem is solved. I was already preparing to reinstall the OS on the device...

Preventing updates in desktop mode is very non-native. Especially for Linux users. If possible, it would be great to fix this. Otherwise, users must be informed of this.

**Comment by nagybal** [comment]
> game console mode, "Stable" update, system rebooted 

This is strange, I did all this. I updated using the console mode first, system restarted. Then I went to desktop and updates in Discover again. Does it suppose to update only the rest?

**Comment by DimitriyPS** [comment]
> Does it suppose to update only the rest?

I don't quite understand what you have in mind.

For me, the update of one package could not be completed (like the screenshot in the first post).

What I described in the previous post, I did out of desperation... it was desperation at the thought of reinstalling the game console.

**Comment by DimitriyPS** [comment]
I want to say thank you very much for this distro! I really wanted to put SteamOS on my console and it lived up to my expectations.

On the Steam site, it is not possible to download SteamOS for third-party platforms, so HoloISO became my salvation. I hope you continue to develop and support Holo ISO.

**Comment by nagybal** [comment]
> What I described in the previous post, I did out of desperation... it was desperation at the thought of reinstalling the game console.

But what were the steps again?

Steps:
1. Switch to beta
2. Install update
3. Switch to stable again

or

1. Beta
2. Stable
3. Update

?

**Comment by F1ReB4LL** [comment]
> I went into game console mode and went into settings, the system section and switched the update to "Early Build", the system rebooted and it installed. When it downloaded and checked the update appeared again. I either switched the update system to "Stable" again, the system rebooted again and it installed... I ran the checks that are on the same settings page... then I checked again and tried to install the update, the system rebooted and the update disappeared.

Check the build date in the "System" section. If it still says 20230820, it wasn't updated. I can confirm the core update routine is broken (had the 20230918 build installed earlier, reinstalled from ISO, tried to update - same error, stucked on 20230820).

**Comment by xrishox** [comment]
What is the way that we are supposed to update? I'm stuck in a loop where no matter how many times I update it keeps telling me to download and apply the same one from inside of steam's big screen mode.

**Comment by nagybal** [comment]
Which update is it? What is the date on it?On 2023. Nov 11., at 3:18, xrishox ***@***.***> wrote:﻿
What is the way that we are supposed to update? I'm stuck in a loop where no matter how many times I update it keeps telling me to download and apply the same one from inside of steam's big screen mode.

**Comment by Mohandevir** [comment]
It might not be recommended, but I removed the steamos-systemreport and steamos-hardware-support packages. Updates resumed normally; it seems to mimick my Steam Deck updates and its been over a month. No crashes, no issues. I was willing to take the risk. I like too much holoiso over other options.

To use at your own risk?

*Fingers crossed*
