### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by mhdeiiking** [holoiso-eol/holoiso#841]
## Your Issue:
```
developer is sucks
```

## Your device's full specs
```
CPU: 69
GPU: 69
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshotx696969696969
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yea
```

## Have you updated your installation recently?
```
yea
```

**Comment by mhdeiiking** [comment]
aggree

**Comment by mhdeiiking** [comment]
lol that crazy i can talk in telegram too

**Comment by mhdeiiking** [comment]
sukaa

**Comment by mhdeiiking** [comment]
![h](https://github.com/HoloISO/holoiso/assets/69827418/0d9c5f6e-9281-4629-b155-3391240c9ab6)
aunti

**Comment by mhdeiiking** [comment]
suka

**Comment by bluedinosaur139** [comment]
this is why retarded children should not be allowed to comment online
