### ISSUE TITLE
Unable to connect bluetooth controllers.

### ISSUE THREAD

**Issue by CasperTheEpic** [holoiso-eol/holoiso#845]
## Your Issue:
```
*type your problem here*
```
I've been trying to connect something other than my Steam controller to play games with, I've tried a brand new xbox controller, and a PS5 controller, all of which I know are working and can pair to my normal desktop and their respective consoles. 
The xbox controllers don't even show up as options when trying to add a bluetooth device, the PS5 ones show up, but once you try and connect them they instantly get disconnected after pairing and it will never let them connect. 

## Your device's full specs
```
CPU: Intel i9-9900K
GPU: 5500XT
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
CARIANT_ID="snapshot20230918.0956
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```

## Have you updated your installation recently?
```
yes
```

**Comment by yjgbg** [comment]
It works on https://github.com/HoloISO/holoiso/releases/tag/v4.0

**Comment by yjgbg** [comment]
`sudo systemctl enable --now handycon`

It works for me.
