### ISSUE TITLE
Stuck in boot loop

### ISSUE THREAD

**Issue by thanone2** [holoiso-eol/holoiso#846]
## Your Issue: can't install Holoiso properly
```
I have a Lenovo ThinkPad W520 and when I try to boot Holoiso it gets stuck in a boot loop. I was wondering if this was a GPU driver problem, or I'm doing something wrong.
```

## Your device's full specs
```
CPU: Intel i7 vPro 2920XM
GPU: Nvidia Quadro 2000M
```

Holoiso 4.0
```

```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```

## Have you updated your installation recently?
```
can't
```

**Comment by theVakhovskeIsTaken** [comment]
@thanone2 Have you not f-ing seen the readme💀

**Comment by thanone2** [comment]
I did and wondered if older versions would work.
P.S. I followed the instructions and they didn't work.

**Comment by eltrevii** [comment]
@thanone2 ofc old versions wont work bruh

**Comment by thanone2** [comment]
ok thx🙂
