### ISSUE TITLE
[Report]An error occurred during installation.

### ISSUE THREAD

**Issue by ZGQ-inc** [holoiso-eol/holoiso#852]
## Your Issue:

My PC is GPD Win Max 2. I used Ventoy as the installation media, but I was prompted with `ACPI BIOS Error` when booting. I confirmed that my BIOS was the latest version, but there was no ACPI option in the BIOS and I could not debug. Since I didn't have an extra USB flash drive (a new one is on the way), I didn't try BalenaEtcher. By the way, the version given on the GPD official website is v3.3/v4.0 and there is no problem. I guess v5.0.1 has some compatibility issues.

## Your device's full specs
```
CPU: AMD Ryzen™ 5 7640U
GPU: AMD Radeon™ 760M
```

**Comment by benjaminfenech** [comment]
I get these errors when using Ventoy on my GPD Win 4, only works with a direct write to USB. I'd definitely hold out and try the write methods when you get that new drive.

**Comment by ZGQ-inc** [comment]
> I get these errors when using Ventoy on my GPD Win 4, only works with a direct write to USB. I'd definitely hold out and try the write methods when you get that new drive.

The new one hasn't arrived yet, but I dug out an idle one and used BalenaEtcher to burn it. No errors were reported and I successfully entered the system.
