### ISSUE TITLE
Disable NVIDIA gpu

### ISSUE THREAD

**Issue by MaxweIlCatDEV** [holoiso-eol/holoiso#853]
When I start the system I get a black screen after the logo. I think it's because of my GTX1650. But i also have amd vega 10 installed in my laptop. If this is causing the problem, can I disable NVIDIA gpu before booting the system?

**Comment by Bandito11** [comment]
I don't know what brand of laptop you have, but can do that on the BIOS. Most of the time is under ***Chipset Config***.
