### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by minecraft3719** [holoiso-eol/holoiso#854]
## Your Issue:
```
Browsing internet stop working after some time, require wifi to be disconnected and reconnect to continue browsing. Ping 8.8.8.8 works fine, but google.com will not work once disconnected.
```

## Your device's full specs
```
CPU: AMD Ryzen 5 4500U with Radeon Graphics - using Radeon RX vega 6 
RAM: 12Gb
lspci | grep -Ei 'network|ethernet'
01:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20231120.1038
```

## Have you updated your installation recently?
```
I just installed the OS freshly so most of the stuff fairly updated
```

**Comment by minecraft3719** [comment]
i checked for ip a output which return 2 ip address, is this the normal behavior of the OS and does it cause router to block internet connection ?

**Comment by theVakhovskeIsTaken** [comment]
@minecraft3719 E/WONTFIX: highest quality qualcomm waste of silicon

**Comment by minecraft3719** [comment]
Hello, was it due to the qualcomm card ?
