### ISSUE TITLE
Does not work with Steam Deck OLED

### ISSUE THREAD

**Issue by Tank-Missile** [holoiso-eol/holoiso#855]
Currently, the installer checks if the product name is Jupiter. This is for the LCD model of Steam Decks. The OLED model is Galileo. When switching out the model name in the script, the installation succeeds and the deck is able to boot. However, there is no wifi, bluetooth, or audio when reaching the first time setup screen. I imagine this is because the installer is using the jupiter repository.

**Comment by gelbphoenix** [comment]
Question: Why do you want to use HoloISO when you already have an SteamDeck and could use the Valve provided recovery image?

**Comment by Tank-Missile** [comment]
I'm having an issue with KDE Plasma on SteamOS where it does not seem to enable both of my monitors. I was hoping to try out Plasma 6 just to see if it was an issue with the desktop environment, or if I needed to do further investigation.

**Comment by gelbphoenix** [comment]
Which Dock are you using for trying to connect to your monitor(s)?
Can you please decribe your problem and setup in more detail?

**Comment by Tank-Missile** [comment]
I'm using the official dock with two LG 24QP500-B monitors. The monitors come with their own hdmi and displayport cables. I think I remember both monitors working before I performed a SteamOS and dock firmware update when I first bought my deck. It could have been those updates that broke my setup, but I'm not sure. Sometimes enabling one monitor causes both of them to turn on, but the display is duplicated as if they are one monitor. I think a better option at this point is to try the KDE Neon unstable ISO, which uses Plasma 6. HoloISO would also come in handy later if I want to make system modifications that remain after updates. For instance, if Plasma 6 does end up fixing my monitor issue, I want to install a distro that I could install Plasma 6 with and have full or nearly full compatibility with the deck.

**Comment by gelbphoenix** [comment]
Have you tried to reinstall SteamOS with the recovery image? Sometimes there is a small error/bug in a Linux system that could be solved with an reinstall.

Also you could try to test other HDMI and DP cables before an reinstall.
