### ISSUE TITLE
Can this work under Virtual Box?  VBox just says VM failed to boot.  

### ISSUE THREAD

**Issue by hspindel** [holoiso-eol/holoiso#856]
## Your Issue:

VBox just says VM failed to boot.  Might be caused by missing OS.  Tried remounting and still doesn't work.

Configured VBox for Bookworm Debian 64 bit.  Also tried Jessie Debian.  4096MB system memory, 32GB disk, 2 processors.

Also tried Debian Jessie 32bit just in case.

**Comment by hspindel** [comment]
Made progress by enabling EFI.

Stuck after holoinstall select desired drive node for installation.  No matter what I type in it says cannot stat drive node.  Finally figured out it wants /dev/sda.

After reboot, VBox won't boot from the hard disk.

**Comment by Vanguard2023** [comment]
Can I get HOLOiso To work with proxmox erro 404
