### ISSUE TITLE
Intel graphics help

### ISSUE THREAD

**Issue by realSkyfr** [holoiso-eol/holoiso#857]
I installed holo on my 2014 mac mini, but i get a black screen with some text after install. Uses intel iris 5000 graphics

![image](https://github.com/HoloISO/holoiso/assets/82292336/eb3a5a71-d49c-4b26-80a8-a84c30205c52)

**Comment by eltrevii** [comment]
intel and nvidia are not fully supported (not all models work yet), only amd

**Comment by realSkyfr** [comment]
thanks, in the meantime im running ubuntu with bigscreen mode. very laggy. hope for intel support soon!

**Comment by eltrevii** [comment]
id recommend you pop os or linux mint, i dont use ubuntu anymore

**Comment by realSkyfr** [comment]
ok! thank you! ill try pop as i have heard good things about it
