### ISSUE TITLE
HEEELLLPPP MEEEE PLSSSSS

### ISSUE THREAD

**Issue by OliverBgamer965** [holoiso-eol/holoiso#863]
I installed Steam OS to a USB and tried to boot off it but it just shows the Lenovo logo for a few seconds then the Steam OS logo and then it gets stuck on the Lenovo logo again. (I just installed it then it told me to reboot then this happened).

**Comment by lipe993** [comment]
It happened to me too with an Avell notebook.
Can anyone help?

**Comment by theVakhovskeIsTaken** [comment]
Closed. Be more mature and informative next time.
