### ISSUE TITLE
[Report] USB Booting throws me back to BIOS

### ISSUE THREAD

**Issue by landerrrrrr** [holoiso-eol/holoiso#865]
## Your Issue:
```
*When booting from USB, it throws me back to bios, no error messages.*
```

## Your device's full specs
```
CPU: * Intel Core i7-7600U*
GPU: *Intel HD Graphics 620*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
HoloISO_5.0_stable-20230821_1bc0b307c6_release-1-x86_64
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
* I cant *
```

## Have you updated your installation recently?
```
*I also cant do that..*
```

**Comment by theVakhovskeIsTaken** [comment]
@landerrrrrr > sees intel
> thinks of telling them to read readme
> nvm leave this to them to figure out

**Comment by landerrrrrr** [comment]
Listen, ive installed this iso with intel before and it worked, now it wont work.

**Comment by theVakhovskeIsTaken** [comment]
@landerrrrrr clo-seeeeed. Next

**Comment by landerrrrrr** [comment]
To-xiiiiiic, you son of a bitch. add intel support you russian suppporter.

**Comment by theVakhovskeIsTaken** [comment]
@landerrrrrr

**Comment by theVakhovskeIsTaken** [comment]
> To-xiiiiiic, you son of a bitch. add intel support you russian suppporter.

https://github.com/HoloISO/holoiso/assets/97450182/4db7f2ee-bfe5-4b8f-b601-c68d38c11e83

**Comment by landerrrrrr** [comment]
your a russian supporter and your already exposed, and you have bad support, get a job. you worthless war fan.

**Comment by theVakhovskeIsTaken** [comment]
> your a russian supporter and your already exposed, and you have bad support, get a job. you worthless war fan.

okaaaaaaay
https://github.com/HoloISO/holoiso/assets/97450182/d8b1a1cf-22a9-4914-999d-1a70703c2b07

**Comment by LeddaZ** [comment]
> To-xiiiiiic, you son of a bitch. add intel support you russian suppporter.

You dumb as hell mate, how can he add Intel support if Valve itself doesn't do it
Just because it sometimes works doesn't mean it will always work, if not officially supported, racist
