### ISSUE TITLE
The ability to install normal arch packages or AUR packages.

### ISSUE THREAD

**Issue by 1525561** [holoiso-eol/holoiso#866]
I've been trying to figure out how to get normal packages to run on Holo ISO through the thermal. any normal arch-based commands wouldn't work and so I would check the mirror list and I didn't see anything wrong with it But it seems to be getting it in a different repository. It's obviously designed this way, but if there's a way to install packages outside of the flathub store. I also try to unlock the file system similar to how you would do in vanilla Steam OS but it seems that it's different here because that command does not work so if you have an answer that would be appreciated or if there's no way through this because it's designed this way then further clarification would be helpful. Again, this may not exactly be an issue and just by design but clarification would be nice. Thank you!

**Comment by theVakhovskeIsTaken** [comment]
@1525561 this is the reason i went immutable 👍

**Comment by 1525561** [comment]
Most likely for security reasons, correct so this is not reversible?
