### ISSUE TITLE
Auto Mounting second drive

### ISSUE THREAD

**Issue by crazyembereks** [holoiso-eol/holoiso#867]
Hello,
In the previous install I was able to follow this guide to auto mount my drives 
https://github.com/HoloISO/holoiso/issues/468

by adding this line to fstab
# my secondary drive
UUID=DRIVE_UUID   DRIVE_MOUNTPOINT   ext4   defaults,nofail   0 0

However this no longer seems to work with the latest immutable holoiso.

Can anyone help in how to do it now?

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks Hello! Thanks for reporting this bug. Immutable project is kind of WIP rn, and editing real root filesystem with such thing as postcopy fstab additions are in TO-DO list.

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks Just to point out your issue: the /etc/fstab you're editing is in /var/overlays/etc/upper, not touching the real filesystem. A custom hook will be implemented later to add your changes to real filesystem.

**Comment by crazyembereks** [comment]
ok got it, so just have to wait until update?

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks exactly!

**Comment by crazyembereks** [comment]
@theVakhovskeIsTaken 
Hello! I saw the new update should allow fstab edits. I'm guessing that should fix this problem. Would you be able to help me in how I would go about auto mounting a secondary drive now? I tried editing the fstab in root but it did not allow me to.

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks You don't need to! You can just edit your overlaid fstab and it'll load fine

**Comment by crazyembereks** [comment]
@theVakhovskeIsTaken
So I got an SD card to mount this way, but my internal ssd wont mount automatically and still asks for password. I've attached my fstab here. I've tried the internal ssd with both the rw,relatime and the defaults, nofail. Is there something I'm doing wrong here?
![mount](https://github.com/HoloISO/holoiso/assets/94838821/c0db6a63-bc6b-4400-b6d1-650e95203f31)

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks Have you tried using a physical node instead of label? It looks to obscure for me

**Comment by crazyembereks** [comment]
@theVakhovskeIsTaken Is the physical node the UUID?

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks Either UUID or /dev/nvmeblabla

**Comment by crazyembereks** [comment]
@theVakhovskeIsTaken Tried with both but end up getting an error (attached)
![error](https://github.com/HoloISO/holoiso/assets/94838821/441dbcc8-43fe-4544-8969-cb71f371c987)
![uuid](https://github.com/HoloISO/holoiso/assets/94838821/58c3bd40-ae7c-4921-9bea-8a1c88ca1275)

**Comment by theVakhovskeIsTaken** [comment]
@crazyembereks Probably because /run isn't populated on boot, try other mountpoint to see if it mounts

**Comment by crazyembereks** [comment]
@theVakhovskeIsTaken Do you have a recommended mountpoint? Tried also on /var/mnt and got the same error
