### ISSUE TITLE
Add support for nvidia GPUs

### ISSUE THREAD

**Issue by selderium** [holoiso-eol/holoiso#869]
## Your Issue:
add support for nvidia GPUs Please
*type your problem here*
I have lags because i have enabled AMD Vega

## Your device's full specs
```
CPU: *AMD Ryzen 5 5600H*
GPU: *3060 RTX for Laptop*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshotxxxxxxxxxxx_xxxx sorry i dont know how to check snapshot..
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```
n/a
## Have you updated your installation recently?
yes
*yes or no*
```

**Comment by muhammad23012009** [comment]
@S1owjan nvidia GPUs wont be supported until Valve decides to support them
