### ISSUE TITLE
HoloISO is not showing up in UEFI Bios Boot Option

### ISSUE THREAD

**Issue by mirashif** [holoiso-eol/holoiso#87]
I have installed HoloISO successfully on my PC. But it's not showing up in boot option. So, I cannot boot into it. I have Windows10, and HoloISO installed on two separate drives.

**Comment by wynn1212** [comment]
Refer #85 
Please wait the new ISO releases

You can try this first
https://github.com/theVakhovskeIsTaken/holoiso/issues/85#issuecomment-1122051055
