### ISSUE TITLE
[Report] Installer Broken?

### ISSUE THREAD

**Issue by methanoid** [holoiso-eol/holoiso#870]
## Your Issue:
```
Installer does nothing at all when selecting Install Alongside....  It seems to start but then craps out and no partition created etc.  Can we not just have a normal GUI installer like Calamares where we can select partitions etc ourselves?  I mean kudos that this has an "alongside" option compared to ChimeraOS which is wipe the whole disk and nothing else but, a proper installer needed really IMHO

```

## Your device's full specs
```
CPU: R9 5950x
GPU: RX 6800
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
HoloISO latest
```

## Have you updated your installation recently?
```
n/a
```

**Comment by theVakhovskeIsTaken** [comment]
@methanoid The main difference between HoloISO/ChimeraOS and other distributions is that we have "sealed" containers that are completely robust and integrity-keeping from any external mishaps or actions, meaning that we can't bootstrap it in classical "calamares" or "anaconda" way

**Comment by methanoid** [comment]
Ah yes, I recall that from last time I tried it...    Maybe remove the "install alongside" option then if it isnt going to work?

**Comment by ghost** [comment]
If there is some way of getting it working that would be great. I would like holoiso and windows dual booting but I can't install holoiso and then windows. I need to install holoiso after windows. Is there anything that can be done?

**Comment by ghost** [comment]
I saw a post on reddit that explains that you need at least 50 GB of unpartitioned space at the end of your disk. The problem can be you need a bit more storage or you may have a partition at the end of your disk (eg. recovery partition). You can look through gparted and see if you have any of these problems. I could be 100% wrong though and the problem is something else.
