### ISSUE TITLE
Get Logo, then nothing (sort of)

### ISSUE THREAD

**Issue by Komak57** [holoiso-eol/holoiso#871]
## Your Issue:
```
Installer runs fine. CHROOT valid. Reboot. Grub launches, Deck logo shows, ASUS logo shows, and stays there. ALT+F2-7 gives me access to the command line, but resets every roughly 3 seconds. Even if I can get my login credentials in that time frame, as soon as the screen wipe happens, it needs me to enter them again. Can't SSH, can't diagnose with CHROOT, same happens in safe mode.
```

## Your device's full specs
```
ASUS TUF FX504GD-RS51
CPU: i5 8300H
GPU: Intel UHD 630 iGPU + GTX 1050
RAM: 8GB
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230823.1454
```

## Have you updated your installation recently?
```
Fresh Installation
```

**Comment by JesseDeLoore** [comment]
I have the same experience.
Is there any way to be able to just get to the CLI so we can see what is causing the issue at a system level?

**Comment by theVakhovskeIsTaken** [comment]
`GPU: Intel UHD 630 iGPU + GTX 1050
`

Will it be obvious why i closed this issue?

**Comment by Komak57** [comment]
I'm not looking for a solution to the incompatibility. I'm looking for a solution to gain access to the terminal so I can narrow down and identify the problems myself. Which is, to the best of my knowledge, the purpose of an open-source project. The live-cd installer operates fine, which means I should be able to get the installation to work before making performance modifications. But, I can't do that if some service is constantly crashing the terminal, preventing me from diagnosing said issue. Any idea which services are running at boot I can temporarily disable to gain access?
