### ISSUE TITLE
URL to latest release ISO is broken, returns 404

### ISSUE THREAD

**Issue by snipem** [holoiso-eol/holoiso#872]
## Your Issue:
Using the latest release from here: https://github.com/HoloISO/holoiso/releases
```
$ curl https://cd2.holoiso.ru.eu.org/HoloISO_5.0.1_stable-20230823_f3bbb0d973_release-1-x86_64.iso
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.25.0</center>
</body>
</html>
```

## Your device's full specs
intentionally left blank

## Your OS version
intentionally left blank

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
intentionally left blank

## Have you updated your installation recently?
intentionally left blank

**Comment by theVakhovskeIsTaken** [comment]
@snipem ....that's what the "legacy-installer" folder is for

**Comment by snipem** [comment]
If there is a legacy installer is there also a new installer? I did not find anything in the README

**Comment by theVakhovskeIsTaken** [comment]
@snipem new installer is the one that will be the true new holoiso experience, aka the immutable one.

it's not documented on GitHub yet

**Comment by Minepool9** [comment]
its been 6 hours what the hell i literally was about to download the iso  like 5 hours ago

**Comment by yjgbg** [comment]
https://github.com/HoloISO/holoiso/issues/864

**Comment by develperbayman** [comment]
is still broken why dont you just upload to github?

**Comment by develperbayman** [comment]
i too was about to test it and use it as i have a 7 days to die addiction
