### ISSUE TITLE
[Report]

### ISSUE THREAD

**Issue by orhankaradal6868** [holoiso-eol/holoiso#873]
## Your Issue:
*type your problem here*
Stopping Session 89 of User liveuse

CPU: *intel i5 4590*
GPU: *gtx 950*
snapshot
![Uploading IMG_20240124_232440.jpg…]()

**Comment by theVakhovskeIsTaken** [comment]
@orhankaradal6868 CPU: intel i5 4590 
GPU: gtx 950 

here's your issue

**Comment by orhankaradal6868** [comment]
I don't understand what you mean
