### ISSUE TITLE
Getting gamepadui to work 

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#88]
Under Manjaro Linux, I can run the gamepadui and get it to load. I believe this is because I have Nvidia/Intel setup on my device. Would it be possible to do this in holoiso too?

Thanks!

**Comment by theVakhovskeIsTaken** [comment]
Standalone gamepadui works, separate Deck session doesn't

**Comment by Frostyman758** [comment]
I can't get standalone gamepadui to work either, the window opens but is white or blank
