### ISSUE TITLE
Will updates nuke hardware specific patches?

### ISSUE THREAD

**Issue by cpuccino** [holoiso-eol/holoiso#89]
There’s a couple patches that needs to be ran to make aya neo work properly.
https://github.com/ShadowBlip/aya-neo-fixes

Obviously most of them happen on the root level, does that mean they need to be reapplied every time there’s an update?

**Comment by theVakhovskeIsTaken** [comment]
No. If you are talking about incremental snapshot updates, then no. However, the ISO reinstalls speak for itself.
