### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [holoiso-eol/holoiso#9]
So far, so good. The ISO boots and installs, which is a good thing.
However, i plan few interesting things to do:
- Maybe ship minimal gamescope-only install option? (no KDE plasma and rest of the bloat, only Steam Deck UI)
- Ship bloated ISO with calamares (distro installer), since valve's repositories have calamares with their configuration:
![image](https://user-images.githubusercontent.com/97450182/166465797-87477a3b-a65c-4cf1-ac1d-54b5f0b8c821.png)
- CPU/GPU detection to install less bloat?
- Updates? Like, genuinely working updates?

**Comment by byzocker** [comment]
If a Intel iGPU gets detected install an older version of gamescope with mesa? or some kind of gpu driver selector where you select which gpu driver you want to use (maybe nvidia when it gets supported too)

**Comment by Mar0xy** [comment]
"Ship bloated ISO with calamares (distro installer)"
this would actually be a neat addition for the first stable release to get working so more users could enjoy this easily especially since valve having it in their repo kinda points out their plan on using calamares for their iso release.

**Comment by massatt212** [comment]
should add gnome-disk-utility
https://archlinux.org/packages/extra/x86_64/gnome-disk-utility/
that will make it easier for people with external hdd

**Comment by cyrneko** [comment]
> should add gnome-disk-utility
> https://archlinux.org/packages/extra/x86_64/gnome-disk-utility/
> that will make it easier for people with external hdd

Calamares already has it's own disk partitioning utility built-in.

**Comment by razzeee** [comment]
what's going to happen, if valve start shipping steamOS 3? Will this still be maintained?

**Comment by moocow1452** [comment]
Crazy white whale of an idea would be to try and make a Raspberry Pi build of SteamOS with Box86/64 and other ARM native libraries, but that's probably way out of scope for this particular project.
