### ISSUE TITLE
User permission can't write to desktop or system files? 

### ISSUE THREAD

**Issue by Super-6-1** [holoiso-eol/holoiso#90]
Seems to be a issue with user not able to write to the desktop or allow apps to edit system files. Is this a known issue or intentional?

**Comment by theVakhovskeIsTaken** [comment]
Looks like folder gets chowned as root:root while creating shortcuts on installation. Just run sudo chown youruser:youruser Desktop

**Comment by Super-6-1** [comment]
> Looks like folder gets chowned as root:root while creating shortcuts on installation. Just run sudo chown youruser:youruser Desktop

Worked thank you
