### ISSUE TITLE
Forced update of Intel drivers 

### ISSUE THREAD

**Issue by Frostyman758** [holoiso-eol/holoiso#91]
I finally got my laptop (Intel + Nvidia) to run with proper driver support and acceleration in steamdeckUI I had to run the command to downgrade mesa, Intel, and gamescpoe to do this. Everything is mostly working now except for a few problems -

-1 I need to rerun the downgrade command after every reboot and then reboot again in order for the UHD drivers to load
-2 the gamepadui interface lacks any audio, in game audio still works
-3 attempting to run steam-compositor-plus freezes the entire computer after showing the big picture mouse for a second, rebooting causes Intel-UHD to be broken again.

~~Would love to know what can be done to fix these issues~~

**Comment by Frostyman758** [comment]
As a follow -up, I've discovered that those drivers can be uninstalled in the background during use, causing me to have to reinstall them whilst my desktop is already loaded. I can determine this through kde.

**Comment by Lolo280374** [comment]
You can add blacklisted packages that pacman will not update.
For that, go to your root directory, then /ect/pacman.conf and on the IgnorePkg line, add the packages of your drivers
(i.g for me: IgnorePkg   = mesa vulkan-intel lib32-vulkan-intel gamescope)

Hope that helps!
