### ISSUE TITLE
steam os using the IGPU instead of dedicated

### ISSUE THREAD

**Issue by bbgoose92** [holoiso-eol/holoiso#93]
for some reason its using the renior graphics included in the ryzen 7 5800h instead of the dedicated rx 6600m, is there any way to specify what GPU the game mode uses?

**Comment by bowes332frank** [comment]
What is your laptop brand? ASUS?

**Comment by bbgoose92** [comment]
> What is your laptop brand? ASUS?

HP, it's an omen 16
R7 5800h
Rx 6600m

**Comment by ewagner12** [comment]
Have you tried adding the launch option:
DRI_PRIME=1 %command%

**Comment by bbgoose92** [comment]
> Have you tried adding the launch option: DRI_PRIME=1 %command%
Doesn't look like that's worked, gamescope doesn't show names, but my vram usage is still way low measuring .03gb when my GPU has 6gb of vram. And I'm running elden ring so I know it needs more than 0.3
Additionally in the system info tab it only shows the IGPU in steam deck game mode

**Comment by 420247paul** [comment]
i dont think you can do it on a per game basis you have to start steam with that command try putting DRI_PRIME=1 steam in the terminal and see if steam starts up using the gpu you wantr  it too. close steam first it is always open by you clipboard in the lower right right click exit it run that command and see if it works for you from what i can see thats an x11 thing though this beast runs wayland

**Comment by bowes332frank** [comment]
Try edit /usr/bin/gamescope-session
Search "-steamos3" than you should add your prefix in it.
