### ISSUE TITLE
Fix for touch screen aya neo next , need update?

### ISSUE THREAD

**Issue by mva94** [holoiso-eol/holoiso#95]
Here is how I made the touchscreen work temporarily on my aya neo next thanks to Steve, a guy I met who does linux development. 
Can you try to include it in the next build ?
https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver

**Comment by theVakhovskeIsTaken** [comment]
> Here is how I made the touchscreen work temporarily on my aya neo next thanks to Steve, a guy I met who does linux development. 
> Can you try to include it in the next build ?
> https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver

:O I might integrate this into kernel later, looks neat

**Comment by mva94** [comment]
@theVakhovskeIsTaken let me know if you want me to try a beta version,  you can always contact me on discord

**Comment by theVakhovskeIsTaken** [comment]
https://github.com/theVakhovskeIsTaken/valve_linux_neptune/commit/669eee4352bb0e50e0b3529e5a30bf59a6a8274c

I'm rebuilding kernel with this now, will drop into `holostaging` later.

**Comment by mva94** [comment]
@theVakhovskeIsTaken so you'll drop an iso ?

**Comment by theVakhovskeIsTaken** [comment]
> @theVakhovskeIsTaken so you'll drop an iso ?

Run `sudo pacman -Sy linux-neptune-dri` and check if it works. Don't forget to unload your custom module before installing.

**Comment by mva94** [comment]
@theVakhovskeIsTaken that doesn't work :/

**Comment by theVakhovskeIsTaken** [comment]
> @theVakhovskeIsTaken that doesn't work :/ 

Can you run `sudo modprobe goodix`?

**Comment by mva94** [comment]
Didn't do anything

**Comment by theVakhovskeIsTaken** [comment]
This is weird. Then i'll just ship it as DKMS later

**Comment by mva94** [comment]
@theVakhovskeIsTaken so now doing clean install + sudo modprobe is working !!! 
Clean install helped and also adding manually the driver here 
![Uploading 16522945837417131382677511356970.jpg…]()

**Comment by mva94** [comment]
@theVakhovskeIsTaken after restarting its gone again :(

**Comment by pastaq** [comment]
Some insight on this issue that you may come across. I don't know if you are using the [goodix-gpdwin3-dkms](https://aur.archlinux.org/packages/goodix-gpdwin3-dkms) package in your ISO or not, but there will be a conflict in all kernels before 5.17.1 between the Aya Neo and the GPD Win 3. The patch that this DKMS module installs is incorporated into the 5,17.1+ kernels without issue, but installing this package will break the Aya Neo's support as it blacklists its working drivers. Working Aya Neo drivers should exist in vanilla kernels 5.14.15 and above.

**Comment by pastaq** [comment]
for reference: 
https://github.com/torvalds/linux/commits/master/drivers/input/touchscreen/goodix.c

**Comment by mva94** [comment]
Hey Adam

Audrey is my friend from one netbook , she would like to discuss some business with you .

Thank you,
MvA

⁣Télécharger BlueMail pour Android ​

Le 11 mai 2022, 19:48, à 19:48, Adam Jafarov ***@***.***> a écrit:
>This is weird. Then i'll just ship it as DKMS later
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/theVakhovskeIsTaken/holoiso/issues/95#issuecomment-1124081304
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by theVakhovskeIsTaken** [comment]
> Hey Adam
> 
> Audrey is my friend from one netbook , she would like to discuss some business with you .
> 
> Thank you,
> MvA
> 
> ⁣Télécharger BlueMail pour Android ​
> 
> Le 11 mai 2022, 19:48, à 19:48, Adam Jafarov ***@***.***> a écrit:
> >This is weird. Then i'll just ship it as DKMS later
> >
> >-- 
> >Reply to this email directly or view it on GitHub:
> >https://github.com/theVakhovskeIsTaken/holoiso/issues/95#issuecomment-1124081304
> >You are receiving this because you authored the thread.
> >
> >Message ID:
> ***@***.***>
> 

I'm not open for any business inquiries, but you/they can message me at t.me/thevakhovske anytime :D

**Comment by mva94** [comment]
Thank you Melvin ：)


Hi Adam,

This is Audrey from One—Netbook （Onexplayer）, nice to meet you.

We wonna invite you to explore some issues about our models. Can you send
us a big hand？thanks.




Cheers,
Audrey Chen
One–Network Team



在 2022年5月13日星期五，MVA ***@***.***> 写道：

**Comment by slaminger** [comment]
> Here is how I made the touchscreen work temporarily on my aya neo next thanks to Steve, a guy I met who does linux development. Can you try to include it in the next build ? https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver

I am Steve :) Still working on this as well, need the mediatek/amd wifi drivers now

**Comment by slaminger** [comment]
> > Here is how I made the touchscreen work temporarily on my aya neo next thanks to Steve, a guy I met who does linux development.
> > Can you try to include it in the next build ?
> > https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver
> 
> :O I might integrate this into kernel later, looks neat

I can provide you with the necessary drivers for the amd/mediatek wifi/bt module as well. I am the main dev behind Ubuntu Linux on AYA devices and would love to see this fully functional. I opened a new issue about gyro/bt/wifi

**Comment by pastaq** [comment]
Including that driver patch by default is probably not a good idea and will end up breaking many devices that use GOODIX touchscreens. (I.E. GPD Win 3, some OneXPlayer, 2021 and previous Aya Neo, various laptops, etc) 

I installed HoloISO with the Linux-Neptune config and touch worked OOTB for me on my Aya Neo 2021 Pro Retro Power. Does the NEXT use a different hardware revision of this device? Here is the truncated output of  ```cat /proc/bus/input/devices```

```
I: Bus=0018 Vendor=0416 Product=038f Version=1060
N: Name="Goodix Capacitive TouchScreen"
P: Phys=input/ts
S: Sysfs=/devices/platform/AMDI0010:00/i2c-0/i2c-GDIX1002:00/input/input17
U: Uniq=
H: Handlers=kbd event7 mouse1 
B: PROP=2
B: EV=b
B: KEY=400 0 0 0 2000000000000000 0
B: ABS=265800000000003

I: Bus=0018 Vendor=0416 Product=038f Version=1060
N: Name="Goodix Active Stylus Pen"
P: Phys=input/pen
S: Sysfs=/devices/platform/AMDI0010:00/i2c-0/i2c-GDIX1002:00/input/input18
U: Uniq=
H: Handlers=kbd event8 mouse2 
B: PROP=2
B: EV=b
B: KEY=1c00 0 0 0 2000000000000000 0
B: ABS=6e5800001000003
```
```
$ lsmod | grep goodix
goodix                 28672  0
```
```
$ lsusb
Bus 004 Device 004: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 004 Device 003: ID 1058:25a1 Western Digital Technologies, Inc. Elements / My Passport
Bus 004 Device 002: ID 1d5c:5500 Fresco Logic USB3.0 Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 0e8d:0608 MediaTek Inc. Wireless_Device
Bus 003 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 005: ID 1d5c:7102 Fresco Logic Generic Billboard Device
Bus 003 Device 002: ID 1d5c:5510 Fresco Logic USB2.0 Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 045e:028e Microsoft Corp. Xbox360 Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
```
$ lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 7
01:00.0 Network controller: MEDIATEK Corp. Device 0608
02:00.0 Non-Volatile memory controller: Sandisk Corp WD Blue SN550 NVMe SSD (rev 01)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c1)
03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
03:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
03:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
03:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
03:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
```

**Comment by pastaq** [comment]
> > > Here is how I made the touchscreen work temporarily on my aya neo next thanks to Steve, a guy I met who does linux development.
> > > Can you try to include it in the next build ?
> > > https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver
> > 
> > 
> > :O I might integrate this into kernel later, looks neat
> 
> I can provide you with the necessary drivers for the amd/mediatek wifi/bt module as well. I am the main dev behind Ubuntu Linux on AYA devices and would love to see this fully functional. I opened a new issue about gyro/bt/wifi

Have you seen [this thread](https://lore.kernel.org/linux-iio/CACAwPwYQHRcrabw9=0tvenPzAcwwW1pTaR6a+AEWBF9Hqf_wXQ@mail.gmail.com/T/) on the gyro? Its on my todo list to make a DKMS module to incorporate the kernel patch posted there.
