### ISSUE TITLE
Shortcut request

### ISSUE THREAD

**Issue by mva94** [holoiso-eol/holoiso#96]
Would it be possible to create a shortcut to bring the quick access menu in game? 
Like pressing two inputs rb+lb ?

**Comment by theVakhovskeIsTaken** [comment]
> Would it be possible to create a shortcut to bring the quick access menu in game? 
> Like pressing two inputs rb+lb ?

Sadly no.
But shortcuts are predefined. It's Home+A/cross or CTRL+1

**Comment by mva94** [comment]
@theVakhovskeIsTaken on aya neo there is no home button :/

**Comment by mva94** [comment]
Is it possible to create a home button shortcut then ?

**Comment by Super-6-1** [comment]
See if this works for you. Did for me 

https://www.reddit.com/r/ayaneo/comments/uku3uh/guide_to_installing_holoiso_unofficial_steamos_30/i854qbx?utm_medium=android_app&utm_source=share&context=3

**Comment by mva94** [comment]
@Super-6-1 so you now have a home button? Or how does it work ?

**Comment by Super-6-1** [comment]
> @Super-6-1 so you now have a home button? Or how does it work ?

Yeah mine works as the steam home button.

**Comment by mva94** [comment]
@Super-6-1 which aya neo next do you have ? The silver next?

**Comment by Super-6-1** [comment]
No I'm using the pro 2021

**Comment by theVakhovskeIsTaken** [comment]
I suppose the issue is somewhat resolved.
