### ISSUE TITLE
disable auto-update of gamescope

### ISSUE THREAD

**Issue by Lolo280374** [holoiso-eol/holoiso#97]
I've got SteamOS to work on my Intel laptop, and Deck UI works too.
The problem is that almost each restart/shutdown, deckUI is then doing a black screen.
The fix is to re-execute the downgrade of gamescope.
Any way to disable gamescope auto updating, so that no need for me to downgrade everytime?

**Comment by piaccarino** [comment]
You could edit `/etc/pacman.conf` and uncomment `IgnorePkg` and add gamescope.

**Comment by SelfRef** [comment]
Also Intel drivers need to be ignored:
```sh
IgnorePkg = mesa vulkan-intel lib32-vulkan-intel gamescope
```

**Comment by Lolo280374** [comment]
Thank you, that indeed worked!
