### ISSUE TITLE
Ventoy

### ISSUE THREAD

**Issue by Martinligabue** [holoiso-eol/holoiso#98]
Ventoy does work, just tested it, I think it might be added to the readme

**Comment by maade93791** [comment]
see https://github.com/theVakhovskeIsTaken/holoiso/issues/2

**Comment by carmona** [comment]
I just tried it and got an error after passing the first screen, says it can't find the drive.
Using the same ISO on the same drive through conventional methods (etcher) works, though.

**Comment by palxex** [comment]
Cannot reproduce too, both 20220510/20220522 reports mount problem.
