### ISSUE TITLE
use partition not disk !

### ISSUE THREAD

**Issue by firashacker** [holoiso-eol/holoiso#99]
i got 200 gb of data on my 500 gb ssd and the os cant be installed into partition theres no way i'm gone try it

**Comment by theVakhovskeIsTaken** [comment]
ok and

**Comment by GuavaEater** [comment]
Get a spare disk.... It's not good practice to "test" software on your main disk :-) Even a sufficiently large USB drive would work well!

**Comment by PibePlayer** [comment]
> Get a spare disk.... It's not good practice to "test" software on your main disk :-) Even a sufficiently large USB drive would work well!

I have a 2nd disk, a 14TB one, I did free 3TB to install /home into it, and 6GB on my SSD for /boot, efi and etc...
It's not like I can just delete the whole drive for Steam OS :v

**Comment by GuavaEater** [comment]
> > Get a spare disk.... It's not good practice to "test" software on your main disk :-) Even a sufficiently large USB drive would work well!
> 
> I have a 2nd disk, a 14TB one, I did free 3TB to install /home into it, and 6GB on my SSD for /boot, efi and etc... It's not like I can just delete the whole drive for Steam OS :v

If you're already using the disk then it isn't spare... It's not just an App you're installing it's a full blown OS. On top of that it should be considered "Experimental". If you choose to do it the way you suggest that's fine, it's your perogative but you could add a lot of complexity to your setup and ultimately you could lose data if something goes wrong. The risk is yours to take, I just want you to be aware of it and accept it. If you don't want to accept it then I suggest holding off until Valve release an official ISO for use by 3rd party system builders and is certified for use in setups such as yours.

You seem like you know what you're doing so it's up to you to decide, just bear in mind that your use case is somewhat unique and not what is recommended. :-)

**Comment by firashacker** [comment]
what i mean is just i want to be able to manually partition and format drive (chose the main system partition) i can deal with fixing grub and like so...... you know what i'll talk a look at the install script and do it my way.

**Comment by GuavaEater** [comment]
> what i mean is just i want to be able to manually partition and format drive (chose the main system partition) i can deal with fixing grub and like so...... you know what i'll talk a look at the install script and do it my way.

Ah yeah, that sounds like it could be a useful addition for power users, though I suspect many casual users wouldn't even know where to begin with that. So perhaps add it as an optional advanced setup step?

**Comment by methanoid** [comment]
Almost every linux I have installed allows manual partition or selection of existing partitions  :-(
